### ISSUE TITLE
[Feature Request] KBD67RGB mkii v2 ansi 68 key layout

### ISSUE THREAD

**Issue by itsmacca97** [qmk/qmk_firmware#10093]
Could you please add in a 68 key ansi layout with three 1u keys to the left of the arrow keys (alt, MO1, Ctrl) for the KBD Fans KBD67 mkii v2 RGB

## Feature Request Type
![68 key layout](https://user-images.githubusercontent.com/69898691/90627350-2fcdac00-e25f-11ea-82cf-4544c27c657a.jpg)

- [ y] Core functionality
- [n ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [n ] Alteration (enhancement/optimization) of existing feature(s)
- [n ] New behavior

## Description

Could you please add in a 68 key ansi layout with three 1u keys to the left of the arrow keys (alt, MO1, Ctrl) for the KBD Fans KBD67 mkii/' v2 RGB

**Comment by mrsendyyk** [comment]
Did you mean added to [QMK Configurator](https://config.qmk.fm/#/kbdfans/kbd67/mkiirgb/v2/LAYOUT_65_ansi_blocker)?

**Comment by itsmacca97** [comment]
I would like the above layout added to the kbd fans kbd67 mkii RGB V2 on QMK Configurator yes please. I accidentally flashed the wrong board and can only reflash with the template on there and lose functionality of one of my key. 
Thanks 😊😊

**Comment by mrsendyyk** [comment]
Ok, maybe i can help you after fixed my Issues [#794](https://github.com/qmk/qmk_configurator/issues/794) on  [qmk/qmk_configurator](https://github.com/qmk/qmk_configurator).

**Comment by itsmacca97** [comment]
> Hi @itsmacca97, i think KBD67 v2 MKII RGB PCB not support `LAYOUT_65_ansi`. Based on picture from [KBDfans](https://kbdfans.com/products/kbd67-mkii-pcb), that pcb only support `LAYOUT_65_ansi_blocker`.
> 
> ![KBD67 v2 MKII RGB PCB](https://camo.githubusercontent.com/0396c3c707e4443071537c1f37cdfe42077f3e5b/68747470733a2f2f63646e2e73686f706966792e636f6d2f732f66696c65732f312f313437332f333930322f70726f64756374732f315f36363663333431632d666361392d343032662d383865622d6336396338613966373965635f3138303078313830302e6a70673f763d31353834343337303230)
> 
> ![KBD67 v2 MKII RGB PCB](https://camo.githubusercontent.com/96b085fff43f1f29e8bb6b7500444da685555c16/68747470733a2f2f63646e2e73686f706966792e636f6d2f732f66696c65732f312f313437332f333930322f66696c65732f315f62366136303863302d393861302d343232362d623739352d3465346239396530393232652e6a70673f763d31353638383939343235)
> 
> @mechmerlin & @moyi4681 as [KBD67 Maintainer](https://github.com/qmk/qmk_firmware/tree/master/keyboards/kbdfans/kbd67), is that correct?
> 
> Also @fauxpark, can you help me again? Sorry...

I'm an idiot. I just realised that I got the DZ65 and got confused not seeing it there and thinking I had the kbd67 smh

**Comment by mrsendyyk** [comment]
> 
> 
> > Hi @itsmacca97, i think KBD67 v2 MKII RGB PCB not support `LAYOUT_65_ansi`. Based on picture from [KBDfans](https://kbdfans.com/products/kbd67-mkii-pcb), that pcb only support `LAYOUT_65_ansi_blocker`.
> > ![KBD67 v2 MKII RGB PCB](https://camo.githubusercontent.com/0396c3c707e4443071537c1f37cdfe42077f3e5b/68747470733a2f2f63646e2e73686f706966792e636f6d2f732f66696c65732f312f313437332f333930322f70726f64756374732f315f36363663333431632d666361392d343032662d383865622d6336396338613966373965635f3138303078313830302e6a70673f763d31353834343337303230)
> > ![KBD67 v2 MKII RGB PCB](https://camo.githubusercontent.com/96b085fff43f1f29e8bb6b7500444da685555c16/68747470733a2f2f63646e2e73686f706966792e636f6d2f732f66696c65732f312f313437332f333930322f66696c65732f315f62366136303863302d393861302d343232362d623739352d3465346239396530393232652e6a70673f763d31353638383939343235)
> > @mechmerlin & @moyi4681 as [KBD67 Maintainer](https://github.com/qmk/qmk_firmware/tree/master/keyboards/kbdfans/kbd67), is that correct?
> > Also @fauxpark, can you help me again? Sorry...
> 
> I'm an idiot. I just realised that I got the DZ65 and got confused not seeing it there and thinking I had the kbd67 smh

[QMK Configurator](https://config.qmk.fm/#/dztech/dz65rgb/v2/LAYOUT_65_ansi)

**Comment by itsmacca97** [comment]
> > > Hi @itsmacca97, i think KBD67 v2 MKII RGB PCB not support `LAYOUT_65_ansi`. Based on picture from [KBDfans](https://kbdfans.com/products/kbd67-mkii-pcb), that pcb only support `LAYOUT_65_ansi_blocker`.
> > > ![KBD67 v2 MKII RGB PCB](https://camo.githubusercontent.com/0396c3c707e4443071537c1f37cdfe42077f3e5b/68747470733a2f2f63646e2e73686f706966792e636f6d2f732f66696c65732f312f313437332f333930322f70726f64756374732f315f36363663333431632d666361392d343032662d383865622d6336396338613966373965635f3138303078313830302e6a70673f763d31353834343337303230)
> > > ![KBD67 v2 MKII RGB PCB](https://camo.githubusercontent.com/96b085fff43f1f29e8bb6b7500444da685555c16/68747470733a2f2f63646e2e73686f706966792e636f6d2f732f66696c65732f312f313437332f333930322f66696c65732f315f62366136303863302d393861302d343232362d623739352d3465346239396530393232652e6a70673f763d31353638383939343235)
> > > @mechmerlin & @moyi4681 as [KBD67 Maintainer](https://github.com/qmk/qmk_firmware/tree/master/keyboards/kbdfans/kbd67), is that correct?
> > > Also @fauxpark, can you help me again? Sorry...
> > 
> > 
> > I'm an idiot. I just realised that I got the DZ65 and got confused not seeing it there and thinking I had the kbd67 smh
> 
> [QMK Configurator](https://config.qmk.fm/#/dztech/dz65rgb/v2/LAYOUT_65_ansi)

As you can very much tell I am a complete NOOB when it comes to this stuff. So much research in a short period had my mind all over the place. Thanks for dealing with my incompetence. Much appreciated (:

**Comment by robotesque** [comment]
Hey,
I'm actually having the exact issue the OP described. I do have a KDB67RGB mkii v2 and the only option for it I see in QMK Configurator is the 67 key layout, but I need a 68 key layout like this:

![image](https://user-images.githubusercontent.com/74321055/98850621-a7ecdd80-241a-11eb-87c9-07e2102bc6a0.png)

I'm currently using the kbdfans/kbd67/mkiirgb/v2 template in the configurator and everything works but I'm missing 1 key. The kbdfans/kbd67/rev2 has the correct layout I need but it doesn't work properly with my pcb.

![image](https://user-images.githubusercontent.com/74321055/98850995-3a8d7c80-241b-11eb-83a9-e57a0529a4be.png)

Thank you for the support!
