### ISSUE TITLE
[Bug] crkbd kidbrazil layout doesn't compile

### ISSUE THREAD

**Issue by Zeioth** [qmk/qmk_firmware#10121]
## Describe the Bug

The layout fail to compile, likely, some qmk update made it deprecated.

**command:**
`sudo make CFLAGS="-Wno-error=format-truncation" crkbd:kidbrazil:flash  `

**Output:**
```
drivers/oled/oled_driver.c:146:6: error: conflicting types for 'oled_init'
 bool oled_init(uint8_t rotation) {
      ^~~~~~~~~
In file included from drivers/oled/oled_driver.c:18:
drivers/oled/oled_driver.h:163:6: note: previous declaration of 'oled_init' was here
 bool oled_init(oled_rotation_t rotation);
      ^~~~~~~~~
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [tmk_core/rules.mk:386: .build/obj_crkbd_rev1_kidbrazil/oled_driver.o] Error 1
Make finished with errors
make: *** [Makefile:584: crkbd:kidbrazil:flash] Error 1
```
Note: I compile with CFLAGS="-Wno-error=format-truncation" because otherwise, warnings are treated as errors.

## System Information

 - Keyboard:  crkbd
   - Revision (if applicable):  1
 - Operating system: Manjaro i3
 - AVR GCC version: 8.3.0
 - ARM GCC version: 10.2.0
 - QMK Firmware version: 0.9.54
 - Any keyboard related software installed? no

## Additional Context

I can correctly compile and use crkbd/default

**Comment by mtei** [comment]
The following command has been compiled correctly.

```shell
make crkbd:kidbrazil
```

The Makefiles in qmk_firmware are not very commonly configured, so your addition of CFLAGS will not produce the results you are hoping for.

**Comment by FilipParyz** [comment]
Confirmed, no errors/warnings for command: `make crkbd:kidbrazil`
