### ISSUE TITLE
Optimizing oled_write_pixel()

### ISSUE THREAD

**Issue by TNKSoftware** [qmk/qmk_firmware#10149]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

"oled_write_pixel" function sets "oled_dirty" flag always, so the frequency of OLED updates will be high when we use this funcion.

What about a way of not processing if there are no changes in pixels?

```
void oled_write_pixel(uint8_t x, uint8_t y, bool on) {
    if (x >= OLED_DISPLAY_WIDTH || y >= OLED_DISPLAY_HEIGHT) {
        return;
    }

    uint16_t index = x + (y / 8) * OLED_DISPLAY_WIDTH;
    bool old_on = (oled_buffer[index] >> (y % 8)) & 0x01;
    if(old_on != on) {
        if (on) {
            oled_buffer[index] |= (1 << (y % 8));
        } else {
            oled_buffer[index] &= ~(1 << (y % 8));
        }
        oled_dirty |= (1 << (index / OLED_BLOCK_SIZE));
    }
}
```

**Comment by tzarc** [comment]
Sounds fair enough, feel free to make a PR?
