### ISSUE TITLE
Quantum keycode RESET throwing error

### ISSUE THREAD

**Issue by CrisHale** [qmk/qmk_firmware#10165]
I thought I'd try a leader sequence for resetting the keyboard, but when it came to compiling I got the error "unsigned conversion from 'int' to 'uint_8t'.
I used the line "register_code(RESET);"
Is there something specific that needs to be done to use these quantum keycodes, and if that is the issue, could that be added to the documentation page?

Thanks,
Cris

**Comment by zvecr** [comment]
You cannot use the keycodes like that, use `reset_keyboard()` directly instead.

**Comment by CrisHale** [comment]
Great, thank you. Perhaps a reference to that function could be included on the quantum keycodes page to help people like myself who learn about it from that page?
