### ISSUE TITLE
Can't use alternative layout feature going by documentation

### ISSUE THREAD

**Issue by CrisHale** [qmk/qmk_firmware#10198]
The [reference keymap extras](https://docs.qmk.fm/#/reference_keymap_extras?id=sendstring-support) page says that including
`#include "sendstring_keymap_uk.h"`
will allow the SENDSTRING function to send strings as with the UK layout, but it says no such file or directory is found. Is the documentation out of date?

Thanks,
Cris

**Comment by fauxpark** [comment]
> If you are using a different layout, you can also #include "sendstring_*.h" (as above) in your keymap to override the lookup tables used for mapping ASCII characters to keycodes.

It's `sendstring_uk.h`.

**Comment by CrisHale** [comment]
Thanks. So the documentation if wrong? Is there someone I should inform?

**Comment by fauxpark** [comment]
The documentation is correct. The `*` here stands in for the language suffixes, not the whole thing. You have `keymap_uk.h` and `sendstring_uk.h`.

**Comment by CrisHale** [comment]
Well it doesn't specify that - or even imply it - in the wording on the page. I've got my answer, so I'm sorted. If you want to make it difficult for others in the future I'm not going to stop you.
