### ISSUE TITLE
Redox (wired) - Flashing the keyboard with a recently compiled firmware leaves the replica side unresponsive

### ISSUE THREAD

**Issue by CTocha** [qmk/qmk_firmware#10230]
## Describe the Bug

Flashing the keyboard with a recently compiled firmware (default layout) leaves the replica side unresponsive. If using saved layouts (both the default and custom ones) from a month ago, it works without problems.

Seems to be something about the compiling itself:
I saved a .json of the working configuration prior to compiling the .hex file I use to successfully flash the board, I imported this .json into the QMK configurator and compiled it, When flashing the board with this file, the replica side stops working. (I attached all the mentioned files in the ZIP archive.)

## System Information

 - Keyboard:  Redox
   - Revision (if applicable):  
 - Operating system: Windows
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version: 

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

[Example_files.zip](https://github.com/qmk/qmk_firmware/files/5174451/Example_files.zip)

**Comment by piscue** [comment]
did you tried to compile locally on your machine? does the resulting files differ?

**Comment by CTocha** [comment]
I don't know how to compile it locally. The new file I compiled online differs from the old one, though, although the keyboard layout is the same.

**Comment by fauxpark** [comment]
Are you flashing both sides?

**Comment by CTocha** [comment]
Not sure if I understand the question. I didn't need to flash them separately in the past, as they're always connected and set up accordingly.

**Comment by fauxpark** [comment]
As I understand it, the Redox uses two Pro Micros, one on each side - but flashing one does not flash the other, so when changes to the split protocol occur, you must flash both sides (we try to keep these changes to a minimum, for this exact reason).

**Comment by CTocha** [comment]
Thanks a lot, that did worked perfectly!
