### ISSUE TITLE
The config.qmk.org no longer populates layer 1 for the k_type

### ISSUE THREAD

**Issue by dmgm** [qmk/qmk_firmware#10279]
I've used the qmk web-based configurator a couple of times. It seems not to be working as it did in the past. If I select my k_type board, then the tkl layout, I get a default configuration of layer0, but layer1 is clear. Previously it included volume control and alternative keys.

Possibly related, I do not seem to be able to import the jason file from my last use, but I do not know that the jason files is good, as I did not import last time.

I wanted to compile a new image as I think there has been some recent work on the k_type code. This might also explain why something has changed.

**Comment by fauxpark** [comment]
@dmgm whoops, I completely forgot to update the Configurator keymap after the K-Type refactor. I've filed a PR to fix it above. You'll need to change the layout name in your .json file from `KEYMAP` to `LAYOUT_tkl_ansi` to import it again after that's merged.
