### ISSUE TITLE
[Bug] "Features" link on doc homepage is broken

### ISSUE THREAD

**Issue by jaredrhine** [qmk/qmk_firmware#10293]
The "features" link under "Make It Yours" section on https://docs.qmk.fm/#/ is a 404

I'd consider submitting a PR (if the web site is in public git), but I'm not sure where it's intended to go as the sidebar has both a software features and hardware features section (maybe that split is when the link broke).

**Comment by pwlandoll** [comment]
It looks like whatever was in `docs/features.md` was split up and moved to the sidebar. I don't think there's much use for that link now that it's in the sidebar.

**Comment by arcturus140** [comment]
duplicate of #9329
