### ISSUE TITLE
[Bug]  https://docs.qmk.fm/#/cli_commands

### ISSUE THREAD

**Issue by mtei** [qmk/qmk_firmware#10300]
## Describe the Bug

Clicking the table of contents of 'https://docs.qmk.fm/#/cli_commands' does not work.

## System Information

 - Operating system:
    macOS safari

**Comment by FilipParyz** [comment]
I have the same problem, I tried to fix it but couldn't.
I'm on Windows and using Firefox.

**Comment by zvecr** [comment]
Fixed by https://github.com/qmk/qmk_firmware/pull/15169
