### ISSUE TITLE
Drop.com Preonic rev3: RGB LEDs

### ISSUE THREAD

**Issue by RomainGehrig** [qmk/qmk_firmware#10324]
My brand new Preonic from Drop arrived today and I saw it had 8 (?) RGB LEDs on the PCB. I flashed it with my own keymap (see #7067) only to see that the LEDs where set to red. I hoped to find the handling of these LEDs in the `default` keymap but nothing there. 

Is there a keymap I can get inspiration from to use those LEDs ?

**Comment by nblyumberg** [comment]
@RomainGehrig if I am not mistaken that's the default (Red) color for RGB in the QMK firmware. What you can do is add [RGB_TOG, RGB_MOD, RGB_RMOD, etc](https://beta.docs.qmk.fm/using-qmk/hardware-features/lighting/feature_rgblight#keycodes) to your keymap so you can make necessary adjustments.
