### ISSUE TITLE
[Feature Request] Support higher resolution joystick analog values

### ISSUE THREAD

**Issue by Leesam** [qmk/qmk_firmware#10330]
The recently added HID joystick interface maps analog read values to an 8bit range. To use this in custom simulator gimbals/throttles/collectives a higher resolution would be preferable.

## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

[This pull request](https://github.com/qmk/qmk_firmware/pull/4226) implemented basic joystick functionality. The [documentation](https://docs.qmk.fm#/feature_joystick) shows the analog value is mapped to a signed 8-bit value. For something like a gamepad thumbstick, this may precise enough but would be noticeably less precise with physically larger simulator controls.

**Comment by fauxpark** [comment]
@Leesam I believe the above linked PR has resolved this?
