### ISSUE TITLE
[Feature Request] LAYOUT_alice addition 

### ISSUE THREAD

**Issue by stanrc85** [qmk/qmk_firmware#10435]
There are a lot of Alice style PCB floating around now that all share a very similar layout. It might be nice to add a LAYOUT_alice so that community layouts can be used for these boards. 

## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

**Comment by MudkipMao** [comment]
I already have one made, so I can take this up pretty easily

**Comment by stanrc85** [comment]
> I already have one made, so I can take this up pretty easily

I can help as well, I just didn't want to do the work first since I think it would involve updating a lot of peoples keymaps.

**Comment by MudkipMao** [comment]
I don't think you're required to updated any other people keymaps, you only need to create the layout and put it in the layouts/default/ folder as an option for people to use in the future
