### ISSUE TITLE
Undefined reference to `ucis_symbol_table`

### ISSUE THREAD

**Issue by Swoy** [qmk/qmk_firmware#1044]
Hello, 
Thank you for an awesome firmware! Much appreciated!

However, i've stumbled over a few issues:
OS: Windows 10
Compiler: Bash for Windows beta gcc (the anniversary update one)
Setup: Just ran the install_deps.sh file and it did it's thing.
PCB: Satan GH60 (with the small metal reset button underneath)

I've now made a new keymap using `UCIS_ENABLE`, but when I try to compile I recieve the error `undefined reference to ucis_symbol_table` and the compiler is pointing to process_unicode.c on line 272 and 275. 
It might as well just be that I have misunderstood the documentation. I've attached the [keymap.c](https://github.com/qmk/qmk_firmware/files/737051/keymap.c.txt) file, [Makefile](https://github.com/qmk/qmk_firmware/files/737052/Makefile.txt) and [config.h](https://github.com/qmk/qmk_firmware/files/737050/config.h.txt) file for you to see. I've also tried to add `#define UC_NAME UC(0xXXXX)` to the process_unicode.h file (from looking at keymap_unicode_cyrillic.h as an example)

The compiler is running OK untill building the *.elf file (from what I can see in the log)

What am I doing wrong? Any ideas?

**Comment by algernon** [comment]
You also need to create a symbol table for UCIS (that's the missing `ucis_symbol_table` thing), otherwise it does not know how to turn a symbol name into a Unicode codepoint.

Check [this part](https://github.com/qmk/qmk_firmware/blob/07e266bbc6df2745e0f1c611ec2faaa1fa9376bb/keyboards/ergodox/keymaps/algernon/keymap.c#L1031-L1044) of my keymap for an example.

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @Swoy please reopen this or open a new issue.
