### ISSUE TITLE
[Bug] LBR KC_LBRC results in @

### ISSUE THREAD

**Issue by jpuerto96** [qmk/qmk_firmware#10456]
When using the QMK Configurator, it appears that the KC_LBRC is being interpreted by the machine as @. 

## System Information

 - Keyboard:  Lily58
   - Revision (if applicable):  Rev1
 - Operating system: Mac OSx 10.15.6
 - AVR GCC version: 8.4.0
 - ARM GCC version: 8.3.1
 - QMK Firmware version: 0.10.10
 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by elfmimi** [comment]
QMK Configurator is maintained in another repository. So this issue should go there instead.

The following one should be related to your request.
https://github.com/qmk/qmk_configurator/issues/229

For now, you have to manually map these keycodes shown below.
https://github.com/qmk/qmk_firmware/blob/2013f6313430b977e557e482d30daa279a46e75d/quantum/keymap_extras/keymap_jp.h#L55-L56
https://github.com/qmk/qmk_firmware/blob/2013f6313430b977e557e482d30daa279a46e75d/quantum/keymap_extras/keymap_jp.h#L68-L69
https://github.com/qmk/qmk_firmware/blob/2013f6313430b977e557e482d30daa279a46e75d/quantum/keymap_extras/keymap_jp.h#L82-L83
https://github.com/qmk/qmk_firmware/blob/2013f6313430b977e557e482d30daa279a46e75d/quantum/keymap_extras/keymap_jp.h#L95

https://github.com/qmk/qmk_firmware/blob/2013f6313430b977e557e482d30daa279a46e75d/tmk_core/common/keycode.h#L141-L146
