### ISSUE TITLE
[Bug] qmk_firmware is too old or not set up correctly

### ISSUE THREAD

**Issue by quantum-booty** [qmk/qmk_firmware#10602]
I cloned the repository using `git clone git@github.com:qmk/qmk_firmware.git`
But when I do `qmk setup`, it returns the following error:
```
Error: /home/henryw/qmk_firmware is too old or not set up correctly!
Please update it or remove it completely before continuing.
```

**Comment by Shadowtrance** [comment]
Yep I'm getting this too.
Just updated my local (already set up) copy because i was a fair bit behind and now I'm just getting this when I try compile or setup or anything really. :(

**Comment by fauxpark** [comment]
This is probably due to https://github.com/qmk/qmk_firmware/pull/8817.

Run `python3 -m pip install pygments` and you should be good.

**Comment by Shadowtrance** [comment]
That did the trick!

**Comment by TheWeirdDodo** [comment]
> This is probably due to #8817.
> 
> Run `python3 -m pip install pygments` and you should be good.

Tried this, didn't work for me

**Comment by chris-ryu** [comment]
Even after "brew reinstall qmk" the problem is not gone.

**Comment by gwillad** [comment]
> 
> 
> > This is probably due to #8817.
> > Run `python3 -m pip install pygments` and you should be good.
> 
> Tried this, didn't work for me

didn't work for me either

**Comment by fauxpark** [comment]
@TheWeirdDodo @chris-ryu @gwillad I've updated my comment, try it now.

**Comment by gwillad** [comment]
I used `util/install_qmk.sh` and that fixed it

**Comment by chris-ryu** [comment]
In my case, brew android-sdk location was the problem.
sudo ln -s /usr/local/Caskroom/android-sdk /usr/local/share/android-sdk
after this linking, the problem was resolved

**Comment by fauxpark** [comment]
The android SDK has nothing to do with QMK.
