### ISSUE TITLE
[Bug] qmk compile/flash leaves ortho48 unresponsive with current `BOOTLOADER` selection

### ISSUE THREAD

**Issue by scnewma** [qmk/qmk_firmware#10645]
## Describe the Bug

Compiling and flashing any ortho48 layout (including the default) leaves the board in an unresponsive state. The board is no longer recognized and no keys are sent.

## System Information

 - Keyboard:  ortho48
 - Operating system: macOS (tried on Windows as well)
 - AVR GCC version: `avr-gcc (Homebrew AVR GCC 8.4.0) 8.4.0`
 - ARM GCC version: `arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 8-2019-q3-update) 8.3.1 20190703 (release) [gcc-8-branch revision 273027]`
 - QMK Firmware version: `0.10.34`
 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

This seems to be related to the `BOOTLOADER` setting in `keyboards/cannonkeys/ortho48/rules.mk`. Commit d46b8ef67c91f1794c35a1a91ff9fc7dcba6b009 added `BOOTLOADER = stm32duino` replacing the following:

```
# GENERIC STM32F103C8T6 board - stm32duino bootloader
MCU_LDSCRIPT = STM32F103x8_stm32duino_bootloader
BOARD = STM32_F103_STM32DUINO

DFU_ARGS = -d 1eaf:0003 -a2 -R
DFU_SUFFIX_ARGS = -v 1eaf -p 0003
```

Reverting that change (by defining these parameters explicitly and removing the BOOTLOADER setting) fixed my problem. I'm not sure exactly what the problem is though.

BTW, I had the same problem when compiling firmware through QMK Configurator for the ortho48.

**Comment by fauxpark** [comment]
Sorry about that!

The above PR should hopefully fix this.
