### ISSUE TITLE
[Bug] Warning when running qmk setup

### ISSUE THREAD

**Issue by drtweety** [qmk/qmk_firmware#10692]
I keep getting this error when trying to run qmk setup:

```
⚠ Missing udev rules for 'massdrop' boards. See https://docs.qmk.fm/#/faq_build?id=linux-udev-rules for more details.
⚠ Detected ModemManager without the necessary udev rules. Please either disable it or set the appropriate udev rules if you are using a Pro Micro.
```

I have followed the instructions in the URL but the warnings persist. 

## System Information

 - Keyboard: Hand wired Pro Micro
 - Operating system: Ubuntu 20.04 LTS

**Comment by fauxpark** [comment]
#10691
