### ISSUE TITLE
Typo in RS Readme

### ISSUE THREAD

**Issue by pseudobacon** [qmk/qmk_firmware#10725]
Very small typo on [this](https://github.com/qmk/qmk_firmware/blob/master/users/rs/readme.md) page
![image](https://user-images.githubusercontent.com/12183854/96886410-472f4c80-14cf-11eb-86e3-eb4af7326018.png)

Should be Crkbd not Crkdb

**Comment by precondition** [comment]
@rs

**Comment by precondition** [comment]
This tiny issue is still valid.
