### ISSUE TITLE
USB2USB AT90USB1286 SPI Pins

### ISSUE THREAD

**Issue by duoshock** [qmk/qmk_firmware#10757]
Hi,

I'm trying to make a usb2usb with at90usb1268 so that it will have enough eeprom for VIA.
I've looked at the original hasu u2u schematic for the pin connections, and the SPI port pins matched the at90usb1286 port pins. Pins are : SCK = B1, MOSI = B2, MISO = B3, SS = B6, INT = B5

So I copied the schematic and swapped the MCU to at90usb1286 (of cause adjusted all the C and R to fit).

PCB arrived pre-assembled, flashed it with u2u firmware (with 'MCU=at90use1286' and define 'CORE_TEENSY'). It recognised as a keyboard, but when I plug a keyboard to the u2u, it did nothing. No key output at all.
I tested with other PCB, but it's the same. Also flashed other keyboard firmware with at90usb1286 and it works as expected, so it's not faulty chips of or the wiring.

Now it makes me think the SIP pins may have changed in the firmware when I change the MCU to 'at90use1276' and added "define 'CORE_TEENSY'". I've done some digging in 'tmk_core\protocol\usb_hid\USB_Host_Shield_2.0' I can see some pins setting for various dev boards, but I'm lost, this is way out of my depth.

So my question is - Is there a way to define SPI pins in keyboard in config.h rather than modifying tmk_core? If not, any pointers where I can set the SPI pins? Or some other things I've missed?

Any clues and tips would be appreciated.

**Comment by fauxpark** [comment]
This line:
https://github.com/fauxpark/qmk_firmware/blob/master/tmk_core/protocol/usb_hid/USB_Host_Shield_2.0/usbhost.h#L89
seems to say the SS pin should be on B0 (and this in fact matches up with the AT90USB1286 datasheet).

However, this line apparently claims the SS pin is E1, with INT on E0:
https://github.com/fauxpark/qmk_firmware/blob/master/tmk_core/protocol/usb_hid/USB_Host_Shield_2.0/UsbCore.h#L34
(see avrpins.h for the mapping between this notation and the "actual" pin name in the datasheet)
