### ISSUE TITLE
Travis CI build fails when keyboard name contains numbers

### ISSUE THREAD

**Issue by dungdung** [qmk/qmk_firmware#1075]
Came across this after submitting #1074 which only contains changes for the KC60

This seems to be due to `travis_build.sh` grepping for `[a-zA-Z_]+` instead of `[0-9a-zA-Z_]+`.

```MKB=$(git diff --name-only -n 1 ${TRAVIS_COMMIT_RANGE} | grep -oP '(?<=keyboards\/)([a-zA-Z_]+)' | sort -u)```

Will submit a fix for this.

**Comment by jackhumbert** [comment]
Just fixed - thanks :)
