### ISSUE TITLE
Is there interest in adding support for boards using GON NerD PCBs?

### ISSUE THREAD

**Issue by Mauin** [qmk/qmk_firmware#1081]
Over the last week I've worked on getting QMK running on my GON NerD based board. There is support for the nerd in TMK in the "orphan" directory as well as some forks which I've taken as a base to get QMK running on my board.

Due to the complicated nature of getting TMK/QMK to run on the NerD, having to manually flash the bootloader of the chip, is there any interest in adding support for it in this repo?

If that's the case. I'd clean up my very minimal configuration that I've used to run QMK on my keyboard and create a PR.

**Comment by jackhumbert** [comment]
Yeah! That'd be awesome :)

**Comment by Mauin** [comment]
Cool, I'll try to clean up my files over the weekend and then create a PR. Implementation is pretty minimal so far, I guess. Especially since the NerD supports multiple layouts and I only have my one layout to test it on.
