### ISSUE TITLE
[Bug] Travis CI is failing, PR's are timed out randomly

### ISSUE THREAD

**Issue by Anton3** [qmk/qmk_firmware#10849]
Travis CI limits the duration of one job (not the whole build) to 50 minutes. QMK is right at that limit at the moment.

After a couple of weeks, no PR will be able to merge, unless we throw away a cluster of random keyboards.

To solve the issue, build each keyboard in a separate Travis job.

**Comment by zvecr** [comment]
Travis :skull:
