### ISSUE TITLE
There are no default keymap in QMK configurator

### ISSUE THREAD

**Issue by XBowsTech** [qmk/qmk_firmware#10983]
After opening this link:https://config.qmk.fm/#/xbows/nature/LAYOUT

When I click LOAD DEFAULT,The browser prompts me:Sorry there is no default for the xbows/nature keyboard... yet!

Why is that?What should I do to get it to have the default keymap?

**Comment by fauxpark** [comment]
The Configurator does not use the `default` keymap.

https://docs.qmk.fm/#/configurator_default_keymaps

**Comment by XBowsTech** [comment]
> The Configurator does not use the `default` keymap.
> 
> https://docs.qmk.fm/#/configurator_default_keymaps

What can I do about it?

**Comment by XBowsTech** [comment]
Let xbows/nature Configurator have the default keymap.

**Comment by fauxpark** [comment]
Read the docs page I posted.

**Comment by noroadsleft** [comment]
I'm actually planning on working on this today.

**Comment by XBowsTech** [comment]
> I'm actually planning on working on this today. I already have a branch in the works.

That's great! thank you!

**Comment by noroadsleft** [comment]
This should be working now.

https://config.qmk.fm/#/xbows/nature/LAYOUT
