### ISSUE TITLE
STM32F401 A9 cannot be used as MATRIX_COL_PINS

### ISSUE THREAD

**Issue by tinggua** [qmk/qmk_firmware#11099]
A9 on output mode can be set to low and high, but after `setPinInputHigh(A9)` it only 1V and even if A9 is not connect the result of  `readPin(A9)` is low. Sothat pin_state of A9 is alway low, it makes all the keys on A9 column triggering.
https://github.com/qmk/qmk_firmware/blob/eaa8c18174405c4e8891b9350f87bfa3ee3da8b6/quantum/matrix.c#L99-L104
https://github.com/qmk/qmk_firmware/blob/eaa8c18174405c4e8891b9350f87bfa3ee3da8b6/quantum/matrix.c#L115-L121

**Comment by zvecr** [comment]
Duplicate of #7855.
