### ISSUE TITLE
[Feature Request] Adding support for lighting control on two pins

### ISSUE THREAD

**Issue by jessenlogin** [qmk/qmk_firmware#11143]
## Feature Request Type

- [x] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

I'm requesting for an feature to expand the rgb lighting capabilities for two separate pins. For example per key rgb lighting on one pin with A-RGB leds such as SK6812mini-e and underglow rgb leds on another pin. For example a simple 68 key keyboard with 68 SK6812mini-e rgb leds and about 10 rgb leds on underglow (such as WS2812). Able to sign different animation effects and colors separately. Including all the control modes on/off, layer specific etc.

**Comment by drashna** [comment]
The simple method would be to implement a custom driver for one or the other features.
