### ISSUE TITLE
[Feature Request] Adding support for use RGBLIGHT and RGB Matrix using WS2812 at the same time

### ISSUE THREAD

**Issue by oren-git** [qmk/qmk_firmware#11145]
## Feature Request Type

- [x] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

Yes, I want RGBLIGHT and RGB Matrix using WS2812 at the same time, but RGBLIGHT and RGB Matrix using different data buffer, Rgblight and RGB matrix will interfere with each other, I think merging two buffers is a solution, And I've solved this problem, So I want to submit a pull request

**Comment by drashna** [comment]
Right now, that's simply not possible.  The WS2812 driver has some preprocessor stuff in it, which prevents it from being changed.  Changing the code ... doesn't work for that.

The ... best (and yet, not good) option is to use a custom driver.... or something like: 

```c
#undef RGB_DI_PIN
#define RGB_DI_PIN (new_pin)
#include "ws2812.c"

void rgblight_call_driver(LED_TYPE *led, uint8_t led_num) {
    ws2812_setleds(led, led_num);
}
```

That or set up a custom driver for the rgb matrix, that ... well essentially does the same thing. 

It's super hacky, but should work.
