### ISSUE TITLE
[Bug]  error while install WSL_INSTALL.SH

### ISSUE THREAD

**Issue by szuruburru** [qmk/qmk_firmware#11222]
Hi,

I install all requirement things from instructions from [https://github.com/TaranVH/2nd-keyboard/blob/f76f566fdfc058c0ab171967f9884662208e8dc9/HASU_USB/readme.md](url) 

But the finally i've got a error and i can't go on... The WSL_Install command cannot found.

I've installed WSL in //WSL$ directory.

![image](https://user-images.githubusercontent.com/76078095/102288335-8e204800-3f3c-11eb-8cf7-031289ec3ce3.png)

Could anyone help me?... I'm new, but i really need use and learn a lot about a programmable keyboard.

Greetings from Poland
Szuruburru

**Comment by fauxpark** [comment]
The install process has changed since that guide was written. That script no longer exists as the WSL install is treated like any other Linux install. Instead you should follow the official QMK docs to set up the environment: https://docs.qmk.fm/#/newbs_getting_started?id=linux
