### ISSUE TITLE
Is there interest in adding support for TheVan Keyboards Roadkit Macropad?

### ISSUE THREAD

**Issue by jmdaly** [qmk/qmk_firmware#1123]
I just received a Roadkit from TheVan keyboards earlier this week. This board runs TMK by default, but I worked to get a QMK build running on it. So far, things look like they're working. If you're interested in having Roadkit support in QMK, I'd gladly submit a pull request.

**Comment by jackhumbert** [comment]
Totally! :)

**Comment by jmdaly** [comment]
Great! I'll clean the code up, add some documentation, and submit a PR in the next couple of days.
