### ISSUE TITLE
[Feature Request] Future support for keychron k6?

### ISSUE THREAD

**Issue by OhItsTom** [qmk/qmk_firmware#11279]
- [x] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

A keychron k6 addition would be awesome as it ships with no software for rgb or per key lighting ect Or even simple macro stuff

**Comment by fauxpark** [comment]
See https://github.com/qmk/qmk_firmware/issues/7370
