### ISSUE TITLE
How to reset my EEPROM on Ergodox EZ?

### ISSUE THREAD

**Issue by jaydpage** [qmk/qmk_firmware#1133]
In the past I had successfully flashed the EEPROM on my Ergodox EZ with hex files generated both from this QMK repo and from the massdrop configurator (https://www.massdrop.com/configurator/ergodox).

Recently out of the blue my keypresses stopped registering whilst having the QMK generated layout loaded. I tried re-flashing with the same layout only to have the same result. I then tried flashing with a layout generated by the massdrop configurator and it worked.

I would much rather use my QMK generated layout because I was able to achieve more with my customization. 

1) Is there a possible explanation for my QMK layout to not work?
2) Is there a way to perhaps reset the EEPROM by adding something to the boot loop?

**Comment by ezuk** [comment]
Tweaked the reset firmware and sent you the compiled hex over email - should be good now I believe, let's see how it goes.
