### ISSUE TITLE
Brightness level of leds

### ISSUE THREAD

**Issue by mystcreater** [qmk/qmk_firmware#1136]
Hi,

Like in the default keymap of my Ergodox EZ keyboard, I have in my keymap a function that provides the ability to bring lights on or off depending on the layer where I am. Is there any way to set the level of brightness of these leds?

**Comment by h-youhei** [comment]
```
void matrix_init_user(void) {
    ergodox_led_all_set( brigntness_level );
};
```
You can set brightness_level 15(LED_BRIGHTNESS_LO) to 255(LED_BRIGHTNESS_HI).

Reference
- keyboards/ergodox/ez/config.h
- keyboards/ergodox/ez/ez.h

**Comment by mystcreater** [comment]
Thank you very much.
