### ISSUE TITLE
Using uGFX/SPI-driven TFT

### ISSUE THREAD

**Issue by Gr1mR3aver** [qmk/qmk_firmware#11396]
I am in the process of designing a board that I would like to include an SPI-driven TFT on.  The QMK docs reference the [uGFX](https://beta.docs.qmk.fm/developing-qmk/c-development/hardware_drivers#ugfx) driver, but I can't find any information on how to enable/use it - are there any docs or examples you can point me to?

**Comment by tzarc** [comment]
It's intentionally not promoted because we're in the process of deprecating and removing uGFX due to licensing constraints.
#10174 is in progress in order to replace it.
