### ISSUE TITLE
Id tagging of titles on layers docs is rendered as it is

### ISSUE THREAD

**Issue by danielo515** [qmk/qmk_firmware#11410]
Here is the thing I'm talking about: https://github.com/qmk/qmk_firmware/blame/master/docs/feature_layers.md

Those are rendered like normal text on the documentation page, so maybe the format is incorrect, or the feature is not supported?

![image](https://user-images.githubusercontent.com/2270425/103466479-eda49300-4d45-11eb-8223-129626c1151e.png)

**Comment by zvecr** [comment]
This is used for docsify, specifically to give consistent urls between translations. While there is a potential plan to move to a different documentation setup, the intent would still be that it has to display correctly on <docs.qmk.fm> and anything that happens to correctly render on GitHub to be a bonus.

**Comment by danielo515** [comment]
Thanks for the explanation
