### ISSUE TITLE
[Feature Request] Support for SSD1306 OLED fade register (23h)

### ISSUE THREAD

**Issue by Barabas5532** [qmk/qmk_firmware#11433]
## Feature Request Type

- [ ] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

According to [this](https://www.olimex.com/Products/Modules/LCD/MOD-OLED-128x64/resources/SSD1306.pdf) datasheet, the SSD1306 OLED has a register that can be used for fade out. This is missing from earlier revisions of the datasheet, but it did work on the OLEDs I have (only a single pair from the same source). It would be nice if this could be used instead of the DISPLAY_OFF when the OLED times out. 

I have created [a branch](https://github.com/Barabas5532/qmk_firmware/tree/oled_fade_rebase) with a prototype implementation. I've just replaced the DISPLAY_OFF and DISPLAY_ON commands with the equivalent using the fade register.

This register also supports a blink mode, but that is not so relevant for me.

**Comment by drashna** [comment]
Looks nice, actually. 

Though, `OLED_DRIVER_DISPLAY_FADE` for enabling it, and `OLED_DRIVER_DISPLAY_FADE_INTERVAL` would probably be better names. 

Feel free to open up a PR, though.
