### ISSUE TITLE
[Feature Request] A "layer modifier" for the QMK configurator

### ISSUE THREAD

**Issue by bad1080** [qmk/qmk_firmware#11566]
Dear QMK community,
for me as a newcomer switching between multiple layers is a daunting process, setting them up even more so. 
Because of this I wanna propose the idea of a "layer modifier", let's call it LM for right now, for the QMK configurator (https://config.qmk.fm/). While pressed LM acts like a regular modifier (it does "nothing" on its own) and in combination with a number (0-9) it switches to the according layer. Pressing LM and "3" (KC_3 and/or KC_P3) switches to layer 3 and so on.
That way layer switching uses only one key per layer ("LM" (or KC_TRNS in non-default layers) and 0-9 on a number row or num pad), you can switch from any layer to any other with an easy to set up and easy to remember combination and there is no guessing involved as to where you'll end up or how you got there.
I hope you consider this idea if at all technically possible and thanks for reading!

**Comment by spidey3** [comment]
Isn't this exactly the behavior that MO(_layer_) provides?

See [Switching and Toggling Layers](https://docs.qmk.fm/#/feature_layers?id=switching-and-toggling-layers).

**Comment by JonasGessner** [comment]
This can be done with #11422 (there is even an example in the docs for toggling a momentary layer), but not in qmk configurator.

**Comment by bad1080** [comment]
> but not in qmk configurator.

That's why I specifically mentioned the configurator

**Comment by JonasGessner** [comment]
It's not even trivially possible without the configurator currently, but #11422 makes something like what you are asking for very easy.

The configurator will only get you so far before you have to start coding if you want any kind of advanced functionality in your firmware.

**Comment by bad1080** [comment]
> The configurator will only get you so far before you have to start coding if you want any kind of advanced functionality in your firmware.

Fair enough. This wasn't meant as "how can I do this" but as "feature suggestion" because I think it would simplify the process and the introduction into layers for beginners like me.
