### ISSUE TITLE
[Feature Request] Support for Raspberry Pi Pico

### ISSUE THREAD

**Issue by ryanm101** [qmk/qmk_firmware#11649]
https://www.raspberrypi.org/blog/raspberry-pi-silicon-pico-now-on-sale/

Would be nice to support this device as an alternative to arduino

**Comment by dsalaj** [comment]
I would very much like that feature too.

**Comment by fauxpark** [comment]
Please see this page for information on adding support for a new MCU family: https://docs.qmk.fm/#/platformdev_selecting_arm_mcu?id=add-new-mcu-family

In short, it is non-trivial, and would require someone to commit to maintenance of the code in ChibiOS.

**Comment by tzarc** [comment]
No USB support, though.

**Comment by siddacious** [comment]
I'll take a look at this; I just got some rp2040 pro micros that I'm itching to use

**Comment by hanya** [comment]
We have USB driver in ChibiOS-Contrib now.

**Comment by Agilulfo** [comment]
https://github.com/qmk/qmk_firmware/pull/14208 was recently merged.
Does it mean that this issue is now solved? :smile:

**Comment by rhruiz** [comment]
Hey seem to have merged 20.3 in not 21.6. And 20.3 does not seem to have RP2040 support yet, can anyone confirm that?

**Comment by tzarc** [comment]
21.6.x was canceled by ChibiOS itself.
This PR has to wait for 21.11.x to get released, and due to the timing will not make this breaking changes cycle.

**Comment by gompa** [comment]
> 21.6.x was canceled by ChibiOS itself. This PR has to wait for 21.11.x to get released, and due to the timing will not make this breaking changes cycle.

i think 21.11.x released on the 7th 
https://forum.chibios.org/viewtopic.php?f=7&t=5963

**Comment by tzarc** [comment]
It's a release candidate.

![image](https://user-images.githubusercontent.com/2985843/140791843-46467211-7e28-46f5-a78d-f12114df66a1.png)

**Comment by tzarc** [comment]
Also, ChibiOS-Contrib is not yet tracking 21.11.x, so there's no path for upgrade regardless.

**Comment by charlie-hotel** [comment]
Looks like 21.1.1 is out now.

**Comment by tzarc** [comment]
> Looks like 21.1.1 is out now.

Of ChibiOS, yes. Of ChibiOS-Contrib, no.

**Comment by hamano** [comment]
I was waiting rp2040 support for qmk as well as you.
Now, I question the necessity of ChibiOS support, since I found sekigon's branch that works very well with rp2040.
https://github.com/sekigon-gonnoc/qmk_firmware/tree/rp2040

You can try example/rp2040_example and example/rp2040_split with rp2040.
It works with pico-sdk, and the split keyboards communicate using PIO.
As you already know, the biggest advantage of Pico is PIO. Is it possible to use PIO on ChibiOS?
Dou you have interest to be able to do matrix scanning using PIO instead of CPU?
Would you consider merging sekigon's branch or linking pico-sdk instead of ChibiOS?
Thanks.

**Comment by tzarc** [comment]
>  Would you consider merging sekigon's branch or linking pico-sdk instead of ChibiOS?

Given that the branch is quite out of date compared to QMK and doesn't follow the structural patterns, it'd require a fair bit of work to do so. ChibiOS is still preferable at this point, as we're not having to rely on a single person making changes or bugfixes.

**Comment by tzarc** [comment]
This commit, for instance, goes in the opposite direction of QMK:
https://github.com/sekigon-gonnoc/qmk_firmware/commit/838055cf9edda32033d6745294844809202074b9

**Comment by hanya** [comment]
ChibiOS uses pico-sdk to support RP2040. So you can call some functions from pico-sdk in QMK code.

**Comment by hamano** [comment]
I believe that ChibiOS is the better choice if PIO is available.
Thanks.

**Comment by zykrahgaming** [comment]
Just to update anyone still interested regarding QMK RP2040 support, check out https://github.com/ChibiOS/ChibiOS-Contrib/pull/310. From what I know, work on getting preliminary RP2040 support in QMK cannot happen until chibios-contrib maintainers merge this PR.

**Comment by ankitsxchdeva** [comment]
Thank you for linking that PR! Looks like there's progress being made on it. Probably a stupid question but would that ChibiOS PR allow all RP MCUs to be QMK compatible?

**Comment by zykrahgaming** [comment]
> Probably a stupid question but would that ChibiOS PR create the possibility of all RP MCUs to be QMK compatible?

As far as it wont add support for existing MCUs (ie on other raspis), but it could make adding future RP MCUs easier if they ever do come out in the future.

**Comment by nodupe** [comment]
I'm happy to see that the commit on Chibios-contrib was merged!

**Comment by maberalc** [comment]
Will this lead to the support finally? Or it is already supported as it was merged???

**Comment by KarlK90** [comment]
> Will this lead to the support finally? Or it is already supported as it was merged???

https://github.com/qmk/qmk_firmware/pull/14877 is the tracking PR for RP2040 support in QMK. It is actively being worked on but no ETA yet.

**Comment by gril002** [comment]
Congrats to everyone involved on merging #14877 to everyone involved. I can see it's now part of the develop branch. When can we expect the full release and what else need to be done before? Or is the develop branch stable enough to use?

**Comment by tzarc** [comment]
`develop` is usually pretty stable, so should be fine for use.
Otherwise, the next merge of `develop` into `master` will occur on August 28.

**Comment by xbliss** [comment]
> `develop` is usually pretty stable, so should be fine for use. Otherwise, the next merge of `develop` into `master` will occur on August 28.

Is this still on schedule or have the dates moved?

**Comment by kaerbr** [comment]
I guess its now available via https://config.qmk.fm/#/adafruit/macropad/LAYOUT (:
