### ISSUE TITLE
Unicode Input with WinCompose fails because of it is case-sensitive

### ISSUE THREAD

**Issue by nishio** [qmk/qmk_firmware#1165]
WinCompoese under default settings doesn't accept unicode hex inputs because it suppose U and A~F are all uppercase.
However hex_to_keycode in quantum.c (called from process_unicode.c) generate lowercase keycodes.

https://github.com/qmk/qmk_firmware/blob/b794719952edafa174a1eea031c3433be820ad29/quantum/quantum.c#L1015

To Configure WinCompose to case insensitive works as a walk-around.

**Comment by drashna** [comment]
This function is defined weakly, so you could replace this in your keymap to handle it "correctly".

If that does work, then it may be worth opening a PR that changes the default functionality.

**Comment by drashna** [comment]
Unicode was significantly overhauled a bit ago.  This issue may no longer be an issue.

**Comment by nishio** [comment]
Thank you. Should I close the issue?

**Comment by drashna** [comment]
Yeah. I can do so too.  But I would recommend updating your repo and WinCompose, and testing the changed code, just to make sure it fixes the issue. 

If it does, close the issue, if not, let us know.
