### ISSUE TITLE
How to realize the synchronization of light animation in split keyboard?

### ISSUE THREAD

**Issue by XBowsTech** [qmk/qmk_firmware#11702]
I am using IS31FL3731 chip, what should I do to synchronize the lights of the split keyboard? Are there any reference cases?

**Comment by elfmimi** [comment]
Maybe this PR is sharing the same objective. https://github.com/qmk/qmk_firmware/pull/11055

**Comment by drashna** [comment]
This is actually a very tricky issue.   

If you're using i2c for the split communications, then you need to change the drivers/etc to only run on the master side.  

If you're using serial, then ... that's even trickier, and I'm not sure would work, given how the feature and driver is set up.
