### ISSUE TITLE
[Bug] Incorrect keycode lighting when keymap by VIA

### ISSUE THREAD

**Issue by dongocduy** [qmk/qmk_firmware#11783]
- I try the latest revision of source, make <keyboard>:via then flash result firmware
- When keymap by Via, some keycode of lighting are incorrect, ex: set BL_TOGG in Via but in keyboard is BL_INC....
similar with some keycode RGB, BL
I try with older revision, this bug not appear

**Comment by zvecr** [comment]
Duplicate of #11157
