### ISSUE TITLE
[Bug] brew qmk/qmk/qmk does not build on M1 Mac

### ISSUE THREAD

**Issue by jknotzke** [qmk/qmk_firmware#11794]
Using brew 2.7.7 calling "brew install qmk/qmk/qmk ends in an error:

brew install qmk/qmk/qmk
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> Updated Casks
Updated 5 casks.

==> Installing qmk from qmk/qmk
avr-gcc@8: The x86_64 architecture is required for this software.
Error: An unsatisfied requirement failed this build.

## Describe the Bug

The brew cask appears to be broke when on an M1 (ARM based) Mac using MacOS 11.2

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by fauxpark** [comment]
Issue is with avr-gcc, not qmk.
https://github.com/osx-cross/homebrew-avr

**Comment by dgdosen** [comment]
Before I recompile - Does anyone know if that means that you could compile firmware to run on either "arm64" OR 'x86_64"?

**Comment by fauxpark** [comment]
The firmware does not run on either - arm64 and x86_64 are the architectures of the host system, ie. the compiler itself. The target architecture will be either `avr` or one of several subsets of ARM designed specifically for microcontrollers. QMK cannot run on the host, as it is fairly tied to some aspects of microcontrollers that a full x86_64 system, for example, would not have. However, there is a vague plan for a "libqmk" which would abstract some of the core of QMK out into something that could potentially run on the host: https://github.com/qmk/libqmk

**Comment by mmshivesh** [comment]
You can build avr-gcc from source as they discuss in this issue https://github.com/osx-cross/homebrew-avr/issues/237
