### ISSUE TITLE
endpoint The problem

### ISSUE THREAD

**Issue by aihk** [qmk/qmk_firmware#11800]
Compiling: tmk_core/protocol/vusb/vusb.c                                                           tmk_core/protocol/vusb/vusb.c:72:6: error: #error Mouse/Extra Keys share an endpoint with Console. Please disable one of the two.

How can I shut down redundant endpoint

**Comment by yiancar** [comment]
if you want Console enabled.
in rule.mk 
set
MOUSEKEY_ENABLE = no       # Mouse keys
EXTRAKEY_ENABLE = no       # Audio control and System control

if you want either mousekeys , extrakeys, or both
set
CONSOLE_ENABLE = no         # Console for debug
