### ISSUE TITLE
My keymap doesn't work on my keyboard (code compiles and I can flash keyboard)

### ISSUE THREAD

**Issue by javieriko96** [qmk/qmk_firmware#11844]
Hello everyone, thanks for the help

I'm creating a 5x15 ortholinear keyboard from nothing.
I have generated a new project in qmk and i have configured everything
My problem is that when I flash the keyboard it doesn't work.
I am using an ARDUINO PRO (not pro micro) in a PCB of my own, and in the debug of the QMK toolboox I can see when I press the keys one by one, and they are recognized in the matrix, but the Keycode that the pc receives are not the corresponding to the kc_XX that I put in the keymap.c

All the keys send a code like "0x7F25" of 4 characters, and the pc writes for that code an "8", that I have seen that it has the code "0x25", I don't know if it is useful information.

I attach the code of the config, rules, .c, .h and keymaps in pastelbin

https://pastebin.com/gvBhPK3c

PD: some keys are "ES_1" because I removed some macros and layers to avoid possible errors with those.
PD2: sorry for my English, in spanish and i am using DeepL for translate better....

**Comment by fauxpark** [comment]
Can you try setting `BOOTMAGIC_ENABLE` to `lite`, then holding the top left key while plugging the board in?
