### ISSUE TITLE
XD87 ALT codes with separate numpad does not work

### ISSUE THREAD

**Issue by 00-monkey** [qmk/qmk_firmware#11856]
I have flashed my XD87 with ISO layout specifying xd87:default_tkl_iso as build enviroment. I am using Windows 10 with language  setted as Italian. I would like to do ALT codes with my separate numpad that works with other full size keyboard like a Logitech K120. I have searched a lot to resolve this issue without succes. I have made some mistake flashing the rom or there could be a issue?

Thanks in advance.

**Comment by drashna** [comment]
Have you checked the unicode documentation?   it may not be quite what you're looking for, but contains information that may be helpful (eg, alt codes are tricky)
