### ISSUE TITLE
[Keyboard] Add leafcutterlabs/minimacro5

### ISSUE THREAD

**Issue by joncojonathan** [qmk/qmk_firmware#11902]
I have done some work with @leafcutterlabs in the past and wish to add the [miniMACRO5](https://github.com/LeafCutterLabs/miniMACRO5) keyboard to the QMK repo.  I'm happy to work on this and will open a work in progress PR shortly.

**Comment by zvecr** [comment]
We don't require an issue for adding a keyboard, so im going to close this one.
