### ISSUE TITLE
Backlight support breaks dynamic macro on ergodox

### ISSUE THREAD

**Issue by sboesebeck** [qmk/qmk_firmware#1199]
I tried to get dynamic macros up and running, but I had my issues compiling it. In the file "dynamic_macro.h" there is an explicit call to "backlight_toggle()" - which causes a linker error, when using it with a non-backlit setup (i assume).

Commenting out those lines workes, but it probably not exactly what is intended...

**Comment by jayliu50** [comment]
Leaving the backlight_toggle() uncommented in dynamic_macro.h, you can define which LED to turn on to signal that the buffer is full, like so:

```c
// keymap.c
void backlight_toggle(void) {
    ergodox_board_led_on();
}
```
