### ISSUE TITLE
Incorrect spelling of 'persistent'

### ISSUE THREAD

**Issue by Khord** [qmk/qmk_firmware#1201]
Would it be feasible to correct this [spelling error of persistent (`persistant`)](https://github.com/qmk/qmk_firmware/search?utf8=%E2%9C%93&q=persistant&type=Code) repo wide? Looks like it stemmed from copying the default keymaps for boards in most cases. I guess it's not a big deal, but just seems like a good thing to do for formality's sake.

**Comment by jackhumbert** [comment]
Haha, yeah - I'm pretty sure that's my fault :)
