### ISSUE TITLE
[Feature Request] Make mac homebrew install only affect dependencies

### ISSUE THREAD

**Issue by memco** [qmk/qmk_firmware#12059]
Mac homebrew install should not upgrade all of a user's packages.

`brew upgrade` should not be run without specific packages to avoid unintended side-effects.

## Feature Request Type

- [X] Alteration (enhancement/optimization) of existing feature(s)

## Description

When dong a `qmk [setup|doctor]` the default behavior is to run `brew update && brew upgrade --ignore-pinned`, which updates every package installed via homebrew.  Since the next step installs the QMK specific dependencies it does not seem necessary to upgrade every package on the user's system: this increases install time and potentially introduces unintended side-effects to the QMK install. This could probably be solved by changing `_qmk_install_prepare()`  to simply run `brew update` since that will update only homebrew itself and then the rest can proceed as is.

**Comment by fauxpark** [comment]
This is very much intentional, to make sure the user is fully up to date before installing anything. We have had issues with this before, IIRC.

**Comment by iandunn** [comment]
#12794 looks to be the same request, and has much more discussion.
