### ISSUE TITLE
shell.nix not up to date on latest python package dependencies 

### ISSUE THREAD

**Issue by EdenEast** [qmk/qmk_firmware#12050]
The packages `dotty-dict` and `jsonschema` were recently added as requirements to the requirements.txt file. These requirements were not reflected in the shell.nix file causing `./bin/qmk` to fail.

`dotty-dict` added in commit: ef6329af7c
`jsonschema` added in commit: ededff8556

These requirements should be reflected in the shell.nix file.

**Comment by EdenEast** [comment]
I used the wrong template this is not a question and should be labeled as a bug/regression.

**Comment by purcell** [comment]
See #11181 :-)

**Comment by EdenEast** [comment]
This issue was solved with the merge of #12295.
