### ISSUE TITLE
Hi, do you know why the layout in the QMK Configurator does not match that in the keymap.c file?

### ISSUE THREAD

**Issue by YangPiCui** [qmk/qmk_firmware#12071]
Hi, do you know why the layout in the QMK Configurator does not match that in the keymap.c file?
https://config.qmk.fm/#/handwired/evk/v1_3/LAYOUT
https://github.com/qmk/qmk_firmware/blob/master/keyboards/handwired/evk/v1_3/keymaps/default/keymap.c

![Capture](https://user-images.githubusercontent.com/15274205/109388000-77846d00-793f-11eb-8dac-f4a00d2b10af.JPG)
![Capture1](https://user-images.githubusercontent.com/15274205/109388005-7c492100-793f-11eb-8ddf-abf098925da0.JPG)

_Originally posted by @YangPiCui in https://github.com/qmk/qmk_firmware/issues/11880#issuecomment-787069007_

**Comment by YangPiCui** [comment]
v1_3.h looks fine, too:
![Capture](https://user-images.githubusercontent.com/15274205/109447034-c6382100-7a7d-11eb-8f31-a8ccf78a5335.JPG)
https://github.com/qmk/qmk_firmware/blob/master/keyboards/handwired/evk/v1_3/v1_3.h

**Comment by fauxpark** [comment]
Default keymaps for the Configurator are added here: https://github.com/qmk/qmk_configurator/tree/master/public/keymaps

It does not use the `default` keymap.c from the qmk_firmware repo.

**Comment by YangPiCui** [comment]
Hi, 
My changes to the .json file has been commited.
https://github.com/qmk/qmk_configurator/pull/891

Do you know why the keymap still hasn't been updated on the QMK Configurator?
https://config.qmk.fm/#/handwired/evk/v1_3/LAYOUT

**Comment by noroadsleft** [comment]
The deployment task had a failed test unrelated to your changes.

I've restarted the deployment task.

**Comment by noroadsleft** [comment]
@YangPiCui,

Okay, deployment succeeded, but the keymaps still isn't rendering correctly. Let me investigate.

**Comment by noroadsleft** [comment]
Apparently I had some cached data that was loading the previous keymap even though Configurator's data was current.

Everything should be fine now.

![image](https://user-images.githubusercontent.com/18669334/109875681-9c216300-7c25-11eb-8899-88d2786c6ed9.png)

**Comment by YangPiCui** [comment]
Wonderful. Thank you.
