### ISSUE TITLE
[Bug] Audio Clicky is bugged. 

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_firmware#12080]
## Describe the Bug

On AVR, it's not too bad.  A sound get get stuck until another note is played. Not a big deal. 
On ARM, instead of getting stuck on a note, the controller locks up, and must be unplugged. 
* Note:  ARM's PWM Hardware audio driver doesn't seem to have this issue but the DAC driver (eg, on the F303) does. 

## System Information

 - Keyboard:  
   - Revision (if applicable):  DM, Moonlander
 - Operating system: MacOS/Windows
 - AVR GCC version: 8.3.1

 - ARM GCC version: 8.4.0

 - QMK Firmware version: 0.11.x

## Additional Context

This didn't happen on develop when testing... 

I suspect that music mode and the like will trigger this too, but haven't tested. But it's pretty random when it will happen.  Sometimes it's right away, sometimes it takes half an hour.

**Comment by drashna** [comment]
May be related to #8503

**Comment by taotien** [comment]
Preonic rev3, seemingly only locks up when `AUDIO_ENABLE_TONE_MULTIPLEXING` is `#define`d. Otherwise, typing fast causes die.

Making with util/docker_build.sh
ARM GCC version: 6.3.1
QMK Firmware version: 0.14.29

**Comment by drashna** [comment]
> Preonic rev3, seemingly only locks up when `AUDIO_ENABLE_TONE_MULTIPLEXING` is `#define`d. Otherwise, typing fast is fine for me.
> 
> Making with util/docker_build.sh ARM GCC version: 6.3.1 QMK Firmware version: 0.14.29

happens for me with or without that defined. 

Also, seems to only happen on dac basic on ARM.  DAC Additive seems to work without issue.

**Comment by drashna** [comment]
@JohSchneider since you wrote the original overhaul code and have been active recently, any thoughts?

**Comment by JohSchneider** [comment]
ah - a mention... sry for the delay
i vaguely remember the clicky feature as being... fineky. IIRC a "hanging note" could happen when the state for the currently playing note was not terminated properly, or too many where queuing up... which would match the observations with TONE_MULTIPLEXING.
would have to dig into the code again O:-)

**Comment by JohSchneider** [comment]
> 8+ keys at once

that might be a hint - there is a stack of active notes which happens to default to 8 elements in size; do you still observe this bug when setting AUDIO_TONE_STACKSIZE to say 16?

if so, this would point to a bug in the handling of all the tones/notes that are supposed to be currently active

**Comment by drashna** [comment]
> > 8+ keys at once
> 
> that might be a hint - there is a stack of active notes which happens to default to 8 elements in size; do you still observe this bug when setting AUDIO_TONE_STACKSIZE to say 16?
> 
> if so, this would point to a bug in the handling of all the tones/notes that are supposed to be currently active

Sorry, I lost track of this.  

I'll have to double check, but the code isn't configurable, so it would be an "edit core code" test.

**Comment by fsargent** [comment]
I'm having this issue on my RGBKB SOL3 when flashing from my M1 mac, so would love to try anything to fix it.

**Comment by drashna** [comment]
No, changing the define to 16 doesn't help, with this, at all.  And looks like music mode can reliably trigger it on 3 simultaneous presses/notes.

**Comment by fsargent** [comment]
I no longer have this issue as of updating my branch to the latest master/main branch. I think we can consider this resolved!!!

**Comment by drashna** [comment]
Fixed, yeah
