### ISSUE TITLE
[Feature Request] Move to GitHub Actions and combine various build scripts

### ISSUE THREAD

**Issue by adamgordonbell** [qmk/qmk_firmware#12196]
Would there be interest in a PR to move the Travis build to GitHub Actions and combine and simplify some of the scripts under /util like travis_push.sh and so on?

I work on this open-source build tool called [earthly](http://earthly.dev) and I think I could simplify the QMK build significantly using earthly and get you off of Travis at the same time.  Travis is restricting minutes for open source projects and with earthly, the build can be run locally on any machine which makes it easier to iterate on.

 I've done similar work from [other open-source projects](https://twitter.com/josevalim/status/1346404430275612683). 

Does it sound useful?

**Comment by zvecr** [comment]
Already being worked on, its unlikely we are to introduce another layer and instead build out some of the functionality within the cli.
