### ISSUE TITLE
How to use ChibiOS APIs in QMK?

### ISSUE THREAD

**Issue by Leonezz** [qmk/qmk_firmware#12219]
I need to use **uart** APIs in my project, but when I directly add `#include "uart.h"` to my code, I got a lot of ERRORs.
I think maybe there are other steps I need to follow before using the APIs, if anyone konws what the steps are, please let me know,thanks a lot.

**Comment by elfmimi** [comment]
just leaving a quick note while passing by .
- [uart.h](https://github.com/qmk/qmk_firmware/blob/master/drivers/chibios/uart.h) is QMK's API.
- in terms of ChibiOS you need a low level driver for 'SERIAL'. in other words you need HAL_USE_SERIAL .
- QMK's [chibios/uart.c](https://github.com/qmk/qmk_firmware/blob/master/drivers/chibios/uart.c) seems a bit dependent on STM32. you may want to re-implement it in your keyboard's directory.
- example: [halconf.h](https://github.com/qmk/qmk_firmware/blob/master/keyboards/zvecr/zv48/f411/halconf.h) [mcuconf.h](https://github.com/qmk/qmk_firmware/blob/master/keyboards/zvecr/zv48/f411/mcuconf.h)
- cf.  https://github.com/qmk/qmk_firmware/tree/master/platforms/chibios/keyboard-config-templates
- are there any documentation? I don't know.
