### ISSUE TITLE
[Bug] QMK Configurator for RGBKB Pan displaying all keys in 1 row with a very small font

### ISSUE THREAD

**Issue by sadiwali** [qmk/qmk_firmware#12215]
## Describe the Bug

When selecting RGBKB Pan 32a or poroton_c keyboard, the display shows all keys in a single row, instead of 5 rows.

## Additional Context

![image](https://user-images.githubusercontent.com/17219923/111019554-efb25000-838d-11eb-9a21-7ad9f050add4.png)

**Comment by fauxpark** [comment]
Looks like this board was missing an info.json, which specifies the location and size of the keys in Configurator. I've submitted a PR (linked above) to fix this. Thanks!
