### ISSUE TITLE
Tracking issue for keyboards with no info.json

### ISSUE THREAD

**Issue by fauxpark** [qmk/qmk_firmware#12222]
```
vision_division
```

**Comment by fauxpark** [comment]
@moyi4681 would you be able to provide an info.json for the kbdmini?

**Comment by fauxpark** [comment]
`technika` appears to be [this board](https://geekhack.org/index.php?topic=104231.msg2853878#msg2853878), although the layout macro doesn't match up with the image. @Gondolindrim ?

**Comment by skullydazed** [comment]
Can we remove vision_division? Its complex LAYOUT generation will never play nicely with our data-driven efforts and I don't think it's a design that more than a handful of people have, as evidence by the lack of updates over the years.

@IBNobody do you have any thoughts on this?

**Comment by Gondolindrim** [comment]
> `technika` appears to be [this board](https://geekhack.org/index.php?topic=104231.msg2853878#msg2853878), although the layout macro doesn't match up with the image. @Gondolindrim ?

The reason I haven't PR'd the board to VIA and a configurator json yet is that there were changed to PCB and layout since the IC. I will PR them as soon as we have a finalized version.
