### ISSUE TITLE
error: ISO C99 requires whitespace after the macro name

### ISSUE THREAD

**Issue by H-Gerlatzek** [qmk/qmk_firmware#12250]
I just finished creating the Keymap for my first handwired build and wanted to build it using the

`make -kb <keyboard> -km <keymap>`
or
`qmk compile -kb <keyboard> -km default`

command. But when I run it it hands back following error:

`<command-line>: error: ISO C99 requires whitespace after the macro name [-Werror]`

I don't know where this error comes from or how to solve it.

**Comment by fauxpark** [comment]
Your keyboard name probably has a `-` in it, change it to `_`.

**Comment by H-Gerlatzek** [comment]
yes it has I'll try

**Comment by H-Gerlatzek** [comment]
I created a new keyboard folder and copy + pasted my keymap and other settings.
The error seems to be solved but now I get the following error:
`error: backslash-newline at end of file [-Werror]
#define LAYOUT( \`
It also says the error is in the <keyboard>.h file.

**Comment by H-Gerlatzek** [comment]
This solved the error, thank you!

**Comment by darkmatterxuan** [comment]
How?Why I can not?
