### ISSUE TITLE
[Feature Request] BM60EC RGB Support

### ISSUE THREAD

**Issue by bry95** [qmk/qmk_firmware#12253]
Hi! I'd really appreciate BM60EC support. It's nearly identical to the standard BM60 but with a rotary encoder in the top right corner. VIA firmware is on the kprepublic site if that's at all helpful. Thanks!

## Feature Request Type

- [ ] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

**Comment by fauxpark** [comment]
The Google Doc contains the VIA JSON, which defines the matrix layout, but it doesn't provide any information on pinout. If it's identical to the standard BM60 the matrix pins are probably the same, but the encoder pins will need to be found.

**Comment by SuperVi** [comment]
Hi there, 
I recenty bought this board and would love to see it officially supported. I am quiete new to the topic but I have a background in CS and could at least test or tweak if someone with more experience simply doesn't have the board at hand. 

i found a user who forked the repo and already added the board. I think it could be useful.
https://github.com/umbacos/qmk_firmware/tree/master/keyboards/bm60ec_rgb

**Comment by peepeetee** [comment]
Oh no I mentioned the wrong person, I meant @umbacos

**Comment by Didel** [comment]
It looks like the solution provided in #15104 (approved by @fauxpark 8 hours ago) will be merged into QMK soon. Would that resolve this issue?

**Comment by Didel** [comment]
#15104 has been approved and merged by f6a7bf2, so I assume that closes this issue.
