### ISSUE TITLE
[Bug] SET_HAND_PIN implicit declaration of function setPinInput(), readPin()

### ISSUE THREAD

**Issue by mcp292** [qmk/qmk_firmware#12261]
## Describe the Bug
When I `#define SET_HAND_PIN` on my crkbd I get the following errors on complie:
```
bd/rev1/split_util.c: In function 'is_keyboard_left':
keyboards/crkbd/rev1/split_util.c:50:5: error: implicit declaration of function 'setPinInput' [-Werror=implicit-function-declaration]
     setPinInput(SPLIT_HAND_PIN);
     ^
keyboards/crkbd/rev1/split_util.c:51:12: error: implicit declaration of function 'readPin' [-Werror=implicit-function-declaration]
     return readPin(SPLIT_HAND_PIN);
            ^
```

## System Information

 - Keyboard: crkbd
 - Operating system: Arch Linux 
 - AVR GCC version: 10.2.0
 - ARM GCC version: 10.2.0
 - QMK Firmware version: 0.8.153

**Comment by elfmimi** [comment]
0.8.153 is pretty old. In the latest master `make crkbd/rev1/common:default` should complete with no error.
but I confirm that the same problem persists for crkbd or crkbd/rev1 which is an alias for crkbd/rev1/legacy in the latest master.

**easy fix**:
adding `#include "quantum.h"` should solve the errors.
or use of `#include "gpio.h"` is better in case of the latest master.

and as a side note you may want to do like this.
```C
    setPinInputHigh(SPLIT_HAND_PIN);
    wait_us(10);
    return readPin(SPLIT_HAND_PIN);                          
```
