### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by mytigerjim** [qmk/qmk_firmware#1227]
Hi.
I have read your project. This is very wonderful one.
I am going to use your code, but I have some problem.
this problem is the USB communication.
I don't know USB communication in your project. and i can't understand keyboard keycode variable.
Thanks, regard.

**Comment by fredizzimo** [comment]
Hi @mytigerjim,

I read you messages in the Gitter chat and I don't understand what you are trying to do.

I don't think think you need to modify the USB protocol. Most things can be done directly from the keymaps. 

So could you please explain what you want to do on the keyboard and you want to send to the host?

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @mytigerjim please reopen this or open a new issue.
