### ISSUE TITLE
$100 Bounty for Hot-switch of host computer for Massdrop Ctrl

### ISSUE THREAD

**Issue by GreyAsteroid** [qmk/qmk_firmware#12321]
This bounty is related to https://github.com/qmk/qmk_firmware/issues/10025 and https://github.com/qmk/qmk_firmware/issues/5185 but specifically for the Ctrl keyboard as that is the qualifying keyboard I own.

I'd like to be able to switch between the hosts plugged into the keyboard with a keypress.

The bounty is payable via PayPal. Conditions are that this feature is merged into QMK and I'm personally able to verify its functionality.

**Comment by fauxpark** [comment]
See https://github.com/qmk/qmk_firmware/issues/11119
