### ISSUE TITLE
[Bug] mouse keys inside macros stopped working

### ISSUE THREAD

**Issue by Draic** [qmk/qmk_firmware#12365]
KC_BTN1 still works fine but X_BTN1 does not

## System Information

 - Keyboard: Minivan
 - Operating system: Manjaro
 - AVR GCC version: 8.3.0
 - ARM GCC version: 10.2.0
 - QMK Firmware version: 0.12.20
 - Any keyboard related software installed? no

## Additional Context

I use macros which include mouseclicks, but while editing my layout today and upgrading QMK I realized that I can now longer get X_BTN1 to work, but mouseclick functions work fine outside of a macro

**Comment by zvecr** [comment]
Fixed with #12367.
