### ISSUE TITLE
Layer indicator using ws2812 led strip

### ISSUE THREAD

**Issue by bartiosze** [qmk/qmk_firmware#1240]
Hi,
I'm looking for inspiration or pointers where to start if I would like to add a layer indicator using ws2812 led strip.  Sometimes my keyboard (atreus) gets stuck on a layer and I have problems switching to a default one. I would like to add either a dedicated diode and assign colors to layers or use a led strip for that.

Thanks in advance for any suggestions.
Regards,
ba

**Comment by priyadi** [comment]
My handwired keyboard uses RGB LED strip for layer indicator, among other things. Those are SK6812 minis actually, but electrically should be compatible with WS2812s.

https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/promethium/keymaps/priyadi

**Comment by bartiosze** [comment]
@priyadi your build looks amazing. 
I will try to steal some ideas from your LED indicators. Those look dope!
I hope I will be able to figure out the code;)

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @bartiosze please reopen this or open a new issue.
