### ISSUE TITLE
Where are MIDI notes, eg. MI_C_1, implemented?

### ISSUE THREAD

**Issue by molleweide** [qmk/qmk_firmware#12423]
Hi,

Currently, midi keycodes are written as MI_C_1, MI_Cs_1, MI_D_1, etc..
I would like to change midi note keycodes to start from 0, eg. MI_NOTE_000, _001,...
Could somebody please point me to the file where the midi keycodes are created?
I want to do this because for my usecase it will be easier to handle them when I can see the
number instead of the pitch.

**Comment by fauxpark** [comment]
`quantum_keycodes.h`. Don't edit that file, create your own header with:
```c
#pragma once

#define MI_NOTE_000 MI_C
// etc...
```

**Comment by molleweide** [comment]
Allright thanks! I will try it and see if I get it to work how I want.

**Comment by molleweide** [comment]
Allright so now I have tested this and it turns out that the midi not C0 on qmk outputs note number
56 which means that one can use a maximum of 127 - 56 which is 72, which is probably more than enough for a while! Should I want a larger range of numbers in the future then I have to modify quantum_keycodes.h, nice thanks!
