### ISSUE TITLE
Board Compatibility

### ISSUE THREAD

**Issue by whitef0x0** [qmk/qmk_firmware#1242]
What chipsets/dev boards are compatible with QMK? Just AVR boards?

Is it possible to use something like the Teensy 3.2 with qmk?

**Comment by skullydazed** [comment]
Besides AVR we support anything that ChibiOS supports, here's a list of everything we've tested with so far: https://github.com/qmk/qmk_firmware/wiki/Compatible-Microcontrollers

Take a look at the chibios_test keyboard which I believe supports one of the arm teensy's: https://github.com/qmk/qmk_firmware/tree/master/keyboards/chibios_test

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @whitef0x0 please reopen this or open a new issue.
