### ISSUE TITLE
CTL_T and ALT_T speed issue

### ISSUE THREAD

**Issue by kthibodeaux** [qmk/qmk_firmware#1256]
I have an ergodox and an atreus62.  On my atreus62 I have to type much slower because CTL_T and ALT_T activate much quicker than they do on my ergodox.

Here are my layouts:
https://github.com/kthibodeaux/ergodox-layout
https://github.com/kthibodeaux/atreus62-layout

Any insight is appreciated

Edit: after playing with it a little more it appears that it is not a timing thing.  I think the ergodox will wait a bit after key press before turning the key into a modifier, but it feels like the atreus turns it into a modifier if another key is pressed before the original is let go.  If that is the case, can it be changed?

**Comment by fredizzimo** [comment]
I haven't checked the code to see what the real issue is. But I did a quick search and [this issue](https://github.com/qmk/qmk_firmware/issues/142) seems to be the same.

**Comment by kthibodeaux** [comment]
@fredizzimo I added `#define IGNORE_MOD_TAP_INTERRUPT` to my config.h and all is well in the world.  Thank you!
