### ISSUE TITLE
[Bug] whitefox build fails when visualizer is enabled

### ISSUE THREAD

**Issue by ToyKeeper** [qmk/qmk_firmware#12660]
In the current version of QMK (0.12.38), the configurator can't build firmware for Whitefox keyboards.  The source of the error seems to be related to the visualizer code.  It can build when using "VISUALIZER_ENABLE = no" in rules.mk, but the configurator doesn't do that.

The error I see is:
```
lib/ugfx/src/gdisp/gdisp.c: In function '_gdispInit':
lib/ugfx/src/gdisp/gdisp.c:566:4: error: useless type name in empty declaration [-Werror]
    extern GDISPVMTLIST        GDISP_DRIVER_LIST;
    ^~~~~~
```

I'm not sure how long it has been like this, but I see in [qmk#10175](https://github.com/qmk/qmk_firmware/pull/10175) that there were some concerns about the visualizer, and no one was able to test it.  It passed CI, but it's possible the configurator might use different options.

It's probably an easy fix, but I'm a QMK noob; just tried it for the first time yesterday so I don't know much about the internals.

**Comment by zvecr** [comment]
qmk/qmk_configurator#201

> sorry, we can't build ugfx automatically because the license is incompatible with distribution.
