### ISSUE TITLE
visualizer and keycodes to operating system

### ISSUE THREAD

**Issue by pvinis** [qmk/qmk_firmware#1270]
hello. I am thinking of building a small osx or electron app to visualize the keymap.
say I have a key like this: while it's pressed, the layer changes to another layer and stays active until it's released.
my question is this:
can I detect that it's pressed on the operating system? or is it only detectable on teensy?

**Comment by fredizzimo** [comment]
Right now it's not possible, but the plan is to add a protocol that would let you do something like that. 

For more information see https://github.com/qmk/qmk_firmware/issues/895

**Comment by skullydazed** [comment]
Closing in favor of discussion on #895.
