### ISSUE TITLE
LED control from 

### ISSUE THREAD

**Issue by kmplngj** [qmk/qmk_firmware#12702]
Hello,

is it possible to control the LEDs from an API or command line tool (macOS)?

I would like to set colours and brightness for the whole board and for individual keys. Perhaps it would also be cool to have an option to make a LED link for a specific time.

Would be great to have this. I like to somehow integrate keyboard LEDs more in my macOS and Home Assistant setup.

Thanks a lot for the help

**Comment by tzarc** [comment]
#11567 will hopefully provide this.
