### ISSUE TITLE
bootloader_jump() for HHKB not working?

### ISSUE THREAD

**Issue by tengg** [qmk/qmk_firmware#1271]
Re-editted:

I have tried both TMK and QMK with latest codes.
On TMK, using magic key to enter bootloader will enable the keyboard DFU mode. 
On QMK, same magic key doesn't work.

I traced the definition in ./tmk_core/common/command.h: -> ./tmk_core/common/avr/bootloader.c:bootloader_jump(), it seems QMK and TMK use same code.

I'm just confused.. any one can help?

**Comment by tengg** [comment]
I tried magic+pause, the hid_listen showed "Jumping to bootloader... [1]    8258 segmentation fault  ~/Downloads/hid_listen.mac", but dfu-programmer doesn't recognize it as boot loader.

Also tried key that mapped to "RESET", hid_listen doesn't show "jumping to bootloader", but just segmentation fault.

However, if I push the hardware button, dfu-programmer can see it.

**Comment by tengg** [comment]
Updated.
I think there's something wrong in QMK code in low level. But I'm not quite sure...

**Comment by skullydazed** [comment]
Check the Makefile or rules.mk, is BOOTLOADER_SIZE the same in both?

**Comment by tengg** [comment]
You are right.
Tmk is 4096 and qmk is 512.
Why is that? And should I change to 4096 in qmk/hhkb?

**Comment by skullydazed** [comment]
512 is the size for teensy. Other boards use a bootloader that is 4096 bytes. You should change that to match in qmk/hhkb.

**Comment by cinaeco** [comment]
I encountered the same issue before, but didn't think much about it. Updating `BOOTLOADER_SIZE` to 4096 does indeed allow the `RESET` keycode to work. We should change it! Unless anyone knows the reason it was set to 512?

**Comment by tengg** [comment]
Thanks! It worked.
The comment in rules.mk is "As per original Hasu settings".  But in TMK it's 4096 now. I agree that we might want to change that too! Unless there's a particular reason.

**Comment by skullydazed** [comment]
We'd love to have this fix if one of you wants to submit a PR. Otherwise it'll end up waiting until we have a chance to get around our own PR. :)

**Comment by tengg** [comment]
I'll do the PR, and close this issue.
