### ISSUE TITLE
Tipro?

### ISSUE THREAD

**Issue by thomasdesi** [qmk/qmk_firmware#12761]
Hi, 
anyone knows if Tipro keyboards could be programmed using qmk?

**Comment by noroadsleft** [comment]
I'm not convinced I'm qualified to answer this question, but I looked around and couldn't determine what sort of microcontroller is on the Tipro modules.

You could potentially set up something like a Hasu USB-to-USB converter, or a replacement controller in the style of Bathroom Epiphanies, but I'd consider both of those plans to be fairly advanced.
