### ISSUE TITLE
[Bug] Indicator leds and Media keys do not work on Duck Octagon v2

### ISSUE THREAD

**Issue by anhvu3594** [qmk/qmk_firmware#12823]
## Describe the Bug
I use QMK config to re-keymap my Duck Octagon v2 with some media keys, but it doesn't work.
Also, the indicator LEDs do not work. (default firmware doesn't work as well).

**Comment by drashna** [comment]
For the media keys, is extrakey enabled?  If not, then the media keys won't work. 

As for the host indicator LEDs, if the USB driver isn't passing along that information, then there isn't much that can be done. And I suspect that this is the issue here.

**Comment by lesterlxy** [comment]
were the indicators working before or were they always like this?
I am having the same issue and can find no indication of hardware fault
