### ISSUE TITLE
The gamakay MK61 slow latency 

### ISSUE THREAD

**Issue by fazuraaa** [qmk/qmk_firmware#12877]
Recenlty got the mk61 ,smoth lighting amazing quality and all that but when it comes down to typing,gaming and basically using it its 80ms slow and wont go under 80 if i type faster than 80 ms it wont register .Dont know what to do searched everywhere i am very disappointed such a cool keyboard for such terrible results ...If anyone knows how to fix this problem please notif me .

**Comment by fauxpark** [comment]
As far as I can tell this board doesn't run QMK.
