### ISSUE TITLE
Timer during key press to delay layer switch not working?

### ISSUE THREAD

**Issue by skatardude10** [qmk/qmk_firmware#1289]
[Here's what I am talking about.](https://github.com/skatardude10/dotfiles/blob/6cc61dcc5bbfc149a87fddb39484a22b0d4f79c0/config/keymap.c#L335-L340)

**Background**: I wanted my ACTION_LAYER_TAP_KEY be able to switch layers when held and send KC_SPC + run some code when tapped. I guess you can only do layers and KCs... so I am trying it with timers.

I having it working generally, and with timers running to check that less than _x_ time has passed, space and other keys gets entered just fine- at the end of the keystroke.

Where I run into problems is when I try to set a timer at the beginning of the keystroke (before release). I am trying to get this timer to work so the function layer only activates after a certain amount of time... Otherwise layers activate immediately even only on a tap, which causes me to miss keys when typing fast because of not being out of the function layer.

A timer for when the key is held to only turn on the function layer after a certain amount of time has passed never seems to work. Do you guys have any ideas? 

In the link above I have highlighted the section that shows what I am trying to do, but doesn't work no matter how I try it... all sorts of while loops, if else statements, nested ifs... I have run out of ideas.

**Comment by fredizzimo** [comment]
A loop like that will just stall the keyboard for 100ms, which is probably not what you want, and even if you wanted that, a sleep would be better.

What you should do instead is to add a `void matrix_scan_user(void)` function and check the timer there instead. You probably also need some other global variables for bookkeeping so that you know what to do on timeout.

**Comment by skatardude10** [comment]
That is *exactly* what was happening.  

I thought about the matrix scan but hesitated to try it because of the warnings. I will try some conditions in there, mindful of being as light as possible, and post back if I get it working :-) 

Thanks for pointing me in this direction, I'll give it a try now!

**Comment by skatardude10** [comment]
[Matrix scan](https://github.com/skatardude10/dotfiles/commit/cf408b5c96dd5e0d8d6f961c51d620946afae05e?diff=unified#diff-0b47e102997c5901cda7bfd33cdf69dc) worked great! 

Thanks again, now to consolidate stuff into functions and clean things up in my keymap.c, this issue is solved.
