### ISSUE TITLE
altgr

### ISSUE THREAD

**Issue by zerotrzy** [qmk/qmk_firmware#12911]
Not for polish language, In polish exist 32 chars.
Not for vi editor (no esc <> [] .)

in my opinion to wide spacebar and add more meta switch (Fn)

**Comment by precondition** [comment]
> in my opinion to wide spacebar and add more meta switch (Fn)

QMK is a firmware supported by over 1651 keyboards that come in all shapes and sizes; some QMK keyboards have a wide spacebar, some have a 1u space key and some others don't even have a space key in the first place so `qmk_firmware` issues is not the place to debate about the design of a particular keyboard.

If you have a keyboard that supports QMK, you're free to map any key you want to `Esc`, `<`, `>`, `[`, `]`, `.` or Fn aka `MO(layer)`.
