### ISSUE TITLE
[Bug] Can't compile VIA keymaps for keyboard with VUSB implementations

### ISSUE THREAD

**Issue by C1intMason** [qmk/qmk_firmware#12917]
## Describe the Bug

![image](https://user-images.githubusercontent.com/20373764/118395416-3b3be100-b5ff-11eb-99c1-346714972ce4.png)

I get this error whenever trying to compile a via keymap for any keyboard with VIA firmware.

Any help or insight would be appreciated.

## System Information

 - Keyboard:  coseyfannitutti/discipline
   - Revision (if applicable):  
 - Operating system: Ubuntu (WSL) & QMK MSYS
 - AVR GCC version: 5.4.0

 - ARM GCC version:  (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]

 - QMK Firmware version: 0.9.52

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by fauxpark** [comment]
Update your repo and submodules.
