### ISSUE TITLE
[Bug] BM16A USBC->USBC issue

### ISSUE THREAD

**Issue by ryanm101** [qmk/qmk_firmware#12929]
Hi.

When I connect USB-C -> USB-C it doesn't seem to get power / connection.. (Macbook Pro / Dell XPS with linux) I've tried a load of cables all known good.

If I connect using USB-C -> USB-A and an adaptor it works fine.

If I connect to my windows machine USB-C -> USB-A (no adaptor needed) it works fine.

The cables work with the Discipline 65% which uses the ATMEGA32A.

Anyone else encountered this / have a solution?

**Comment by tzarc** [comment]
Can you post a high-resolution photo of the board? I'm guessing it doesn't have the correct pull-down resistors on the board.

**Comment by ryanm101** [comment]
I'm away for a few days, will disassemble and get photo on Sunday when I'm back

**Comment by Xelus22** [comment]
https://kprepublic.com/products/bm16a-16-keys-custom-mechanical-keyboard-pcb-plate-programmed-numpad-layouts-qmk-firmware-with-rgb-bottom-underglow-alps-mx

From the website it is a hardware fault. Not a QMK error. 
The 5.1k pull-down resistors on the CC lines are not present. :(

**Comment by Electro707** [comment]
![image](https://user-images.githubusercontent.com/15680882/119430173-4ae1b680-bcde-11eb-8abd-4c42d8687a84.png)

There does seem to be 2 resistors next to the connector close to each other, but without a further closeup I can't tell if there are the 5.1k pulldown or something else.

**Comment by tzarc** [comment]
Those would be USB D+/D- termination resistors, rather than CC pull-downs. At this point, all I can suggest is not to bother using this with a C-to-C cable.

**Comment by ryanm101** [comment]
I've tried to add the pull downs but don't think I got the pins right

**Comment by qnm** [comment]
Did you resolve this? I think I have a similar issue.

I'm using the Hasu HHKB controller (atmega32u4) with QMK, which works perfectly with a USB-C to USB-A cable, however `dmesg` is empty when I connect using USB-C to USB-C (AMD b550 board).

I'm confirmed I can use the same cable and board with my USB-C SSD.

**Comment by tzarc** [comment]
Neither problem lies with QMK I'm afraid.
