### ISSUE TITLE
How to use LT in action_function?

### ISSUE THREAD

**Issue by tengg** [qmk/qmk_firmware#1293]
My idea is specify a behavior of a key: 
if some modifier key pressed:
    act as [KEY_CODE]
else
    LT(LAYER, KEY_CODE)

The macro LT() seems not a valid keycode to register. So I'm wondering any way to achieve this?

Thank you.

**Comment by fredizzimo** [comment]
I think you should be able to pass `LT(LAYER, KEY_CODE)` to the `register_code16`, but you also need unregister it at a suitable point.

There are probably a lot of other special cases that you need to take care of as well.

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @tengg please reopen this or open a new issue.
