### ISSUE TITLE
Is it possible to flash `.hex` files with `qmk` cli tool without re-building

### ISSUE THREAD

**Issue by x3rAx** [qmk/qmk_firmware#12965]
I would like to automate the process of building / flashing my firmware on Windows.

After I adjusted my configuration with the web configurator and downloaded the JSON file, I want my script automatically detect the new file, then build the config and then flash it. Flashing can usually be achieved with `qmk flash` (from QMK_MSYS) but building is horribly slow on MSYS compared to WSL so I'd like to build using WSL and then move the `.hex` file to some place on `/mnt/c` to be able to flash it with `qmk` in QMK_MSYS.

I did however not find a way to flash the `.hex` file with `qmk flash`. All it can do is to compile a JSON and flash it directly.

Is there some other (equally easy) way to flash the `.hex` file directly from the cli (ie. not with the qmk toolbox gui)?

**Comment by Electro707** [comment]
```
dfu-programmer atmega32u4 erase
dfu-programmer atmega32u4 flash HEXFILE.hex
dfu-programmer atmega32u4 reset
```

This is at least for an AVR based board. The commands where found in `tmk_core/avr.mk`, so if you have any other processor that directory is probably a good starting place.

**Comment by x3rAx** [comment]
Thank you @Electro707, this was very helpful 😊
