### ISSUE TITLE
Using tab and hold modifier without messing up typing?

### ISSUE THREAD

**Issue by MarkuBu** [qmk/qmk_firmware#13018]
I want to use tab and hold modifier (e.g. LSft_T) on the home row, but I always mess up what I type. I type something like Ctrl+m or, even worse, Ctrl+w to close a browser tab.

How can I fix this?

**Comment by ridingqwerty** [comment]
Give this a look, particularly the tap-hold configuration options that are good for this:

https://precondition.github.io/home-row-mods

**Comment by MarkuBu** [comment]
Home row mods, that's the keyword I needed, thanks

**Comment by MarkuBu** [comment]
I still mess up my typing sometimes. For example I accidentally hit Ctrl+c instead of "sc" on my layout which is common in German, but Ctrl+c is a problem on the terminal.

How can I tweak this?
