### ISSUE TITLE
[Bug] Keyboard unresponsive in UEFI

### ISSUE THREAD

**Issue by aacebedo** [qmk/qmk_firmware#13073]
## Describe the Bug
During boot in the rEFInd menu or in the UEFI of my machine, the keyboard inputs are not recognized.
I tried to change some of the options mentionned in the wiki (https://beta.docs.qmk.fm/faqs/faq_misc#problem-in-bios-uefi-setup-resume-sleep-and-wake-power-cycles) but it did not changed anything.

My rules.mk is:
```
# MCU name
MCU = STM32F303
BOARD = QMK_PROTON_C

# Build Options
#   change yes to no to disable
#
BOOTMAGIC_ENABLE = lite     # Virtual DIP switch configuration
MOUSEKEY_ENABLE = no       # Mouse keys
EXTRAKEY_ENABLE = yes       # Audio control and System control
CONSOLE_ENABLE = no        # Console for debug
COMMAND_ENABLE = no        # Commands for debug and configuration
# Do not enable SLEEP_LED_ENABLE. it uses the same timer as BACKLIGHT_ENABLE
SLEEP_LED_ENABLE = no       # Breathing sleep LED during USB suspend
# if this doesn't work, see here: https://github.com/tmk/tmk_keyboard/wiki/FAQ#nkro-doesnt-work
NKRO_ENABLE = no           # USB Nkey Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = yes          # Audio output
CUSTOM_MATRIX = yes
DEBOUNCE_TYPE = custom
SWAP_HANDS_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = IS31FL3731
#SERIAL_LINK_ENABLE = yes
EEPROM_DRIVER = i2c
NO_USB_STARTUP_CHECK = yes
#project specific files
SRC += matrix.c
QUANTUM_LIB_SRC += i2c_master.c
```

## System Information

 - Keyboard:  ZSA Moonlander  
 - Operating system: Arch
 - AVR GCC version: 5.4.0
 - ARM GCC version: 9.2.1
 - QMK Firmware version: 0.12.50
 - Any keyboard related software installed? 
None

**Comment by SgoSkz** [comment]
> Anyone who has the second issue, please try turning off the console feature or add `#define NO_DEBUG` and `#define NO_PRINT` in `config.h` and report back if it helped.
Mentioned [here](https://github.com/qmk/qmk_firmware/issues/1149#issuecomment-792042931)

Try going into config.h of your keyboard configuration and putting  `#define NO_DEBUG` and `#define NO_PRINT`
