### ISSUE TITLE
Custom code help

### ISSUE THREAD

**Issue by kalvinpearce** [qmk/qmk_firmware#1311]
I am wondering if it's possible to run code similar to what you would have in an arduino project.

What I want to do is to send the analog values of a pin over the serial comm every second or so. I am not sure if this is possible with QMK and if it is, where would I put such code?

Thanks

**Comment by fredizzimo** [comment]
You have direct access to the hardware, even from your keymaps, so yes it's possible without having to modify QMK itself.  You would have to write the code yourself though, either using avr-libc or ChibiOS, depending on the controller.

**Comment by skullydazed** [comment]
@kalvinpearce do you still have questions here, or can we close this issue?

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @kalvinpearce please reopen this or open a new issue.
