### ISSUE TITLE
[Bug] UnicodeDecodeError

### ISSUE THREAD

**Issue by carlosmonzonis** [qmk/qmk_firmware#13112]
## Describe the Bug

```console
☒ Could not run 'git clone --recurse-submodules --branch=master https://github.com/qmk/qmk_firmware C:/qmk_firmware': UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 12: invalid continuation byte
```

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system: Windows?
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

Windows locale?

**Comment by pujomania** [comment]
Same issue for me :(

Any suggestions for workaround it?

**Comment by tzarc** [comment]
Mitigation can be found on #13194.
