### ISSUE TITLE
[Feature Request] Support for Redragon K585 DITI

### ISSUE THREAD

**Issue by mnpenner** [qmk/qmk_firmware#13162]
## Feature Request Type

- [ ] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

![image](https://user-images.githubusercontent.com/1112998/121470416-09eed080-c973-11eb-81bb-da0234bb2770.png)

I don't see this keyboard listed on https://config.qmk.fm/ so I assume it's not supported. It comes with some software:

![image](https://user-images.githubusercontent.com/1112998/121470860-a1ecba00-c973-11eb-9963-af1849b8427d.png)

But that software doesn't let me map the G keys to F13-17 like I'd like. The <kbd>Fn</kbd> key is also unmappable, but that's less important to me.

The light controls are also very weak. I'd like to be able to set individual keys if I can.

Any chance of adding support for this keyboard?

**Comment by kb-elmo** [comment]
The Redragon boards use a Sonix controller which is not supported by the original QMK so porting it is not possible.

You can ask the guys at [SonixQMK](https://github.com/SonixQMK/qmk_firmware) if they would be able to port it.
It's a fork of QMK that adds support for some of the Sonix chips.
