### ISSUE TITLE
[Feature Request] QMK support for Muso Creator

### ISSUE THREAD

**Issue by codeMonkeyHopeful** [qmk/qmk_firmware#13181]
Currently do not see any support for my keyboard, hoping to get this in the mix. 

## Feature Request Type

- [x] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

Keyboard link: https://muso.design/

**Comment by kb-elmo** [comment]
It doesn't seem that there is any documentation on what kind of PCB that board uses.

Until that is provided it won't be possible to get QMK on it.
