### ISSUE TITLE
would the clueboard keymaps work with for the hasu fc660c controller?

### ISSUE THREAD

**Issue by unusedPhD** [qmk/qmk_firmware#1318]

**Comment by fredizzimo** [comment]
I'm pretty sure they would if QMK supported hasu's controller, so someone has to add support first. But obviously the RGB stuff would have to be disabled.

**Comment by robotmaxtron** [comment]
The clueboard keymaps will not support the Hasu controller FC660c. I've been looking at trying to port it (https://github.com/tmk/tmk_keyboard/tree/master/keyboard/fc660c) to QMK but I haven't had much luck yet.

**Comment by ramnes** [comment]
It has been done: https://github.com/qmk/qmk_firmware/tree/master/keyboards/fc660c
