### ISSUE TITLE
[Bug] QMK MSYS can’t clone repository

### ISSUE THREAD

**Issue by Evotron** [qmk/qmk_firmware#13194]
I cannot clone QMK’s qmk_firmware with QMK MSYS by running `qmk setup` because it fails due to the following:
`☒ Could not run 'git clone --recurse-submodules --branch=master https://github.com/qmk/qmk_firmware C:/qmk_firmware': UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 12: invalid continuation byte`

It’s failing at qmk_firmware/lib/vusb.
`Clonando en '/c/qmk_firmware/lib/vusb'...
☒ Could not run 'git clone --recurse-submodules --branch=firmware20 https://github.com/zsa/qmk_firmware C:/qmk_firmware':
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 12: invalid continuation byte`

## Describe the Bug

QMK MSYS does not clone the QMK qmk_firmware github repository when using the `qmk setup` command.
## System Information

 - Keyboard:  Ergodox EZ
   - Revision (if applicable):  
 - Operating system: Windows 10
 - AVR GCC version:  avr-gcc.exe (GCC) 8.4.0

 - ARM GCC version: arm-none-eabi-gcc.exe (GCC) 10.1.0

 - QMK Firmware version: can’t install it

 - Any keyboard related software installed? 
   - [ Yes] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

QMK MSYS can’t clone the repository. I’ve tried cloning it to different drives and folders, but nothing works.

**Comment by jbanaszczyk** [comment]
Try to use `qmk setup -y`. Do it twice

**Comment by jbanaszczyk** [comment]
Duplicate #13112

**Comment by oco9oco** [comment]
try `LANG = "en_US.UTF-8"` before `qmk setup`, then you can find the missing trident-like QMK icon appears.
