### ISSUE TITLE
Ergodox Infinity QMK key backlighting not working

### ISSUE THREAD

**Issue by packman86** [qmk/qmk_firmware#1326]
I am unable to get the key LED backlighting to work with QMK. The LEDs work just fine when I run KLL. I really want to keep using QMK because of the added functionality, but it is a bummer that I cannot get the backlighting to work.

Is the key backlighting possible for the Ergodox Infinity on QMK?

**Comment by fredizzimo** [comment]
Please, see [this](https://github.com/qmk/qmk_firmware/issues/1077#issuecomment-304289018).

In short, not yet, but hopefully soon.
