### ISSUE TITLE
[Feature Request] Provide a way to modify the `led_state` consumed by `led_update_kb` from `led_update_user`

### ISSUE THREAD

**Issue by t-8ch** [qmk/qmk_firmware#13272]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Currently when a user wants to override the handling of standard LED indicators from `led_update_user` they have to return `false` from this handler.
This means that the `_kb` handler is completely skipped and the user has to reimplement all of its functionality they want to actually still use.
While this is not a lot of code to carry around this could be optimized.

One easy way would be for `led_update_user` to take `led_state` as pointer which could be modified and then used in its modified form by `led_update_kb`

**Comment by t-8ch** [comment]
/unstale

This has a PR open

**Comment by t-8ch** [comment]
/unstale

This has a PR open

**Comment by tzarc** [comment]
Closed by #14452.
