### ISSUE TITLE
Requesting support for KBD75v3

### ISSUE THREAD

**Issue by rezellmine** [qmk/qmk_firmware#13315]
KBDfans came out with a new revision for the KBD75 series and there is no talk about it being supported yet like its previous two revisions.

It'd be great to see support for the v3 in the near future. Thank you!

**Comment by zvecr** [comment]
<https://kbdfans.com/products/kbd75-v3-soldered-customized-mechanical-keyboard-diy-kit>

> INCLUDES
...
> * KBD75 Rev 2.0 Soldered PCB 

You sure its not just the case?

**Comment by rezellmine** [comment]
Ah. My mistake. I thought they made a revised board for v3 as well. Sorry.
