### ISSUE TITLE
Mouse keys messed up for anyone else?

### ISSUE THREAD

**Issue by ezuk** [qmk/qmk_firmware#1339]
Seems like after [this change](https://github.com/qmk/qmk_firmware/pull/1327/files#diff-eda9a477b1fb87dced86023b342008c4L314), `KC_MS_BTN1` and  `KC_MS_BTN2` stopped working on my boards. Anyone else experience this, or is it just the EZ?

**Comment by Maartenwut** [comment]
It's not just you - I'm having this issue as well after updating the source & compiling new firmware.

**Comment by Dbroqua** [comment]
Hello,

I'm sorry for the code regression. I've trying this with IBM Trackpoint and all works.

Maybe we can include an other IF in this function to check if PS2_MOUSE is enabled or not ? If enabled enter in the actual switch and if not enabled send default event ? `mousekey_on(action.key.code); mousekey_send();`

Regards,
Damien

**Comment by Maartenwut** [comment]
Confirmed working properly again 👍
