### ISSUE TITLE
1 push = all keycode of the col

### ISSUE THREAD

**Issue by Dbroqua** [qmk/qmk_firmware#1345]
Bad title...

I'm trying to realize my own keyboard and I'm a little disappointed...

After soldering all the parts and flashing the keyboard with QMK, all keycodes work except those of a row (f/j row).

Example:
If I press key `4`, computer receive `4`.
If I press key `f`, computer receive `4rfv`...

All diode are connected on the rows and in my `config.h` I wrote `#define DIODE_DIRECTION COL2ROW`.

I'm not sure if the problem is on my PCB, on my soldering or in the wrong configuration of my QMK directory.

Do you have any idea? 

It's really strange :(

**Comment by Dbroqua** [comment]
My configuration can be found here: https://github.com/Dbroqua/qmk_firmware/tree/feature/DK60/keyboards/dk60

Regards,
Damien

**Comment by jackhumbert** [comment]
That usually happens when there's a short somewhere on the `f` key - does it happen anywhere else on the keyboard? If not, it sounds like it'd be hardware-related.

**Comment by Dbroqua** [comment]
All the keys of the row have the same issue (a, s, d, f, g,.....).

**Comment by jackhumbert** [comment]
It may be that row that's shorted to GND then - if you can attach photos, we might be able to see where the short is.

**Comment by Dbroqua** [comment]
Ok,
Now I know what I need to search :D

**Comment by Dbroqua** [comment]
And... It's that :'( .

Thank you!

**Comment by Dbroqua** [comment]
RED: no separation between GND/Row2
BLUE: problem solved! :|

![Preview](https://cloud.darkou.fr/index.php/apps/files_sharing/ajax/publicpreview.php?x=1280&y=340&a=true&file=IMG_20170529_214522-2.jpg&t=ezEumjEV5QD5qCJ&scalingup=0)

https://cloud.darkou.fr/index.php/s/ezEumjEV5QD5qCJ

Thanks!
