### ISSUE TITLE
[Bug] RBG lights stopped working after update

### ISSUE THREAD

**Issue by LechuckThePirate** [qmk/qmk_firmware#13561]
I just updated my qmk firmware repo and rebuilt my corne firmware and the rgb lights are not working anymore, all of the are turned off... I checked my code and it's still the same.. no changes.

## System Information

 - Keyboard:  crkbd
   - Revision (if applicable): rev1  
 - Operating system: Windows 10
 - AVR GCC version: 8.4.0

 - ARM GCC version: 10.1.0

 - QMK Firmware version: 0.13.20

 - Any keyboard related software installed? NO

   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

This is how it looked before the update:
![cornehalf](https://user-images.githubusercontent.com/4067255/125908086-53484974-8f27-4d65-96b0-a71586876527.jpg)
And this is how it looks now, with no changes in the template files
![cornehalf_norgb](https://user-images.githubusercontent.com/4067255/125908499-f03e7b41-d8ac-48b4-896a-805049e407e2.jpg)

**Comment by filterpaper** [comment]
All supported RGB lighting schemes are disabled by default. You will need to enable them manually:
https://github.com/qmk/qmk_firmware/blob/master/keyboards/crkbd/rules.mk
