### ISSUE TITLE
hello, most of docs in ch-zn is 404 error

### ISSUE THREAD

**Issue by idiotstone** [qmk/qmk_firmware#13659]
Hello, I want to read docs of QMK, but most of docs in ch-zn is 404 error, what happend!

**Comment by filterpaper** [comment]
Not everything documentation page has been ported over to `zh-cn`. Available pages that were translated are here:

https://github.com/qmk/qmk_firmware/tree/master/docs/zh-cn

You can help by contributing translation of more pages:

https://docs.qmk.fm/#/translating
