### ISSUE TITLE
[Bug] PS/2 Mouse can‘t be support when using STM32F103C8T6 microcontrollers.

### ISSUE THREAD

**Issue by LiangBeam9810** [qmk/qmk_firmware#13737]
PS/2 Mouse can‘t be support when using STM32F103c8t6 microcontrollers

## Describe the Bug
     I'd like to hook up a Trackpoint to my keyboard ,which base on pill60.
     Tested the Trackpoint by an ATMEGA32U4 microcontrollers ,flash the example in qmk_firmware/keyboards/handwired/trackpoint ,it work well. 
     When I add the code of PS/2 Mouse to pill60,the firmware can't  be built. 
     The error is " tmk_core/protocol/ps2_mouse.c            tmk_core/protocol/ps2_mouse.c:19:10: fatal error: avr/io.h: No such file or directory" . 
     Here is my custom keyboard raw code, thanks a lot.
[pill60_ps2.zip](https://github.com/qmk/qmk_firmware/files/6883697/pill60_ps2.zip)

**Comment by drashna** [comment]
It looks like the current implementation is AVR specific, so it won't work on STM32 devices in it's current state.

It will need to be updated to fix that.
