### ISSUE TITLE
[Bug] Massdrop CTRL Endgame - Build Error 'undefined reference to g_suspend_state'

### ISSUE THREAD

**Issue by SmokeMonsterPacks** [qmk/qmk_firmware#13782]
## Describe the Bug
Massdrop CTRL Endgame: Firmware building fails with the error 'undefined reference to g_suspend_state'

It can be resolved by deleting the reference to g_suspend_state from keymap.c and keymap.h in the Endgame files

It looks like it might be related to this (May 21 breaking changes): [https://github.com/qmk/qmk_firmware/commit/1646c0f26cfa21a7023d404008e4d0aa4917193d ](https://github.com/qmk/qmk_firmware/commit/1646c0f26cfa21a7023d404008e4d0aa4917193d )
One of the changes mentions USB Suspend changes, which points to this pull request: [https://github.com/qmk/qmk_firmware/pull/12697/files](https://github.com/qmk/qmk_firmware/pull/12697/files)

## System Information
 - Keyboard:  
   - Massdrop CTRL

## Additional Context
The error was confirmed by two other users helping me:
![1unknown](https://user-images.githubusercontent.com/33355340/127614335-7201fb93-4c58-4f52-8ef3-3080ef2f3cde.png)
![2image0](https://user-images.githubusercontent.com/33355340/127614340-4bac2c9e-4914-48dd-8934-6a1d4124bd26.jpg)

**Comment by tzarc** [comment]
Our `develop`-targeting CI doesn't build any keymaps other than `default` or `via`, so this wasn't going to get picked up unless someone explicitly built it.

Feel free to make a PR if what you've done fixes it.

**Comment by SmokeMonsterPacks** [comment]
I'm afraid to mess something up with a PR, but here are the two fixed files if someone could please pull them in? 

I've simply removed the two references to g_suspend_state.

![unknown](https://user-images.githubusercontent.com/33355340/127716121-f2406e26-b28c-4e3c-9f1f-0524f1ce7f59.png)
[Fixed Keymaps - Massdrop CTRL Endgame.zip](https://github.com/qmk/qmk_firmware/files/6910141/Fixed.Keymaps.-.Massdrop.CTRL.Endgame.zip)
