### ISSUE TITLE
Add eeconfig define with an offset for user data

### ISSUE THREAD

**Issue by belak** [qmk/qmk_firmware#1381]
I've been playing around with storing data in the eeprom for some keymap settings, but there's no offset which can be used which represents the start of where a user can put data.

Optionally (and arguably preferably) this could be a define in the eeprom include, rather than eeconfig, as there isn't currently a good way to hook into eeconfig for the user.

**Comment by fredizzimo** [comment]
This and more was already discussed a bit, well at least a discussion was opened #969. However no action was taken.

I suggest we continue the discussion there and fix all the EEPROM issues in one go.

**Comment by belak** [comment]
That works for me. I wasn't even aware of the 32 byte limitation on some boards.

**Comment by skullydazed** [comment]
We'll keep talking about this in #969.
