### ISSUE TITLE
[Bug] X-Bows Knight Plus enters reboot loop when setting to Direct mode for OpenRGB with initial RGB values set to 255.

### ISSUE THREAD

**Issue by Inventor22** [qmk/qmk_firmware#13899]
## System Information

 - Keyboard:  
   - Revision (if applicable):  X-Bows  Knight Plus
 - Operating system:
    - Windows 10 Pro
 - AVR GCC version: 
    avr-gcc.exe (GCC) 8.4.0
 - ARM GCC version: 
    arm-none-eabi-gcc.exe (GCC) 10.1.0
 - QMK Firmware version:
    0.10.51
 - Any keyboard related software installed? 
    No

## Additional Context
When entering Direct mode for Knight Plus through either OpenRGB or cycling through RGB modes via the keyboard with Fn+Q, the keyboard will enter a reboot loop until unplugged.  The default RGB values when entering Direct mode are 255 for all channels.

If the default values are changed to 254, the keyboard does not reboot continuously.
Default values are modified in the config.mk file by adding the following overrides:

#define OPENRGB_DIRECT_MODE_STARTUP_RED 254
#define OPENRGB_DIRECT_MODE_STARTUP_GREEN 254
#define OPENRGB_DIRECT_MODE_STARTUP_BLUE 254

[rules.mk](https://github.com/qmk/qmk_firmware/files/6941962/rules.txt)
[config.txt](https://github.com/qmk/qmk_firmware/files/6941967/config.txt)

**Comment by zvecr** [comment]
OPENRGB support isnt merged, so you will have to seek support on the users fork(https://github.com/Kasper24/QMK-OpenRGB), or maybe their PR (#13036).
