### ISSUE TITLE
KC_AGAIN documentation?

### ISSUE THREAD

**Issue by pvinis** [qmk/qmk_firmware#13923]
What exactly is KC_AGAIN doing?

**Comment by tzarc** [comment]
As per the table [here](https://docs.qmk.fm/#/keycodes?id=basic-keycodes):
* Windows: Nothing
* macOS: Nothing
* Linux: Bindings are dependent on your configuration of your WM (i.e. note 1).

**Comment by tzarc** [comment]
It's part of the HID spec, but the operating system needs to choose to implement it.

**Comment by pvinis** [comment]
Oh snap. I missed that. Thank you!
