### ISSUE TITLE
hi I have a problem and need help asap pls pls pls flashed planck with wrong firmware now its dead

### ISSUE THREAD

**Issue by Hizad** [qmk/qmk_firmware#13958]
I accidently flashed my cousins new planck board with the wrong firmware and now it doesn't work at all and every time i try to reflash using the correct firmware using the QMK it says hex file not found I need help as the board is dead its not resetting or anything and there is no solution on the internet I need help

**Comment by uqs** [comment]
Did you download the stock firmware from https://docs.qmk.fm/#/faq_build?id=i-just-flashed-my-keyboard-and-it-does-nothingkeypresses-dont-register-its-also-arm-rev6-planck-clueboard-60-hs60v2-etc-feb-2019 ?

What OS are you trying to flash this for, what is the error output?
