### ISSUE TITLE
[Bug] Flashing OLED on timeout

### ISSUE THREAD

**Issue by mah51** [qmk/qmk_firmware#14012]
## Describe the Bug

Hi, I have a problem with my sofle keyboard, when the OLED times out it flickers. This has only been happening since earlier today, I got an error with QMK MSYS saying packages werent installed. Reinstalling the software worked, however when i used the compile command it said my firmware was too big, even though I havent changed anything in my files. To try and save space I enabled LTO which allowed me to compile and this flickering started happening, however since I have disabled LTO and removed some features such as autoshift and it still flickers, leading me to believe it is due to the update of QMK MSYS. Anyone encountered anything similar or have any advice?

## System Information

 - Keyboard:  
 - Sofle/rev1
   - Revision (if applicable):  
 - Operating system:
 - Windows
 - AVR GCC version:  8.4.0

 - ARM GCC version:  10.1.0

 - QMK Firmware version:
 - 0.13.34

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by drashna** [comment]
I think this got resolved on discord. 

If so, it was likely that the custom animations on it call `oled_on` and `oled_off`, which can cause issues with flickering.  Disabling the timeout can fix that.
