### ISSUE TITLE
[Bug] RGB_MATRIX_TYPING_HEATMAP lights up wrong keys

### ISSUE THREAD

**Issue by Lilalas** [qmk/qmk_firmware#14041]
## Describe the Bug

According to the documentation, the heatmap RGB matrix effect should normally light up a key and its neighboring keys when pressed. (I don’t understand why it’s designed to also light up neighboring keys in the first place, but that’s not the point of this issue.) The problem is that for quite a number of keys, it will not light up the neighboring keys, but a few keys on the opposite side of the board instead – I does this in a consistent manner, but I cannot see a pattern.

I have found buggy keys like this in every row except the home row. For example the <kbd>Y</kbd> key will light up <kbd>Y</kbd>, <kbd>U</kbd>, <kbd>H</kbd> and <kbd>J</kbd> as expected (using a standard QWERTY layout here), but then also the first and second key in the bottom row (instead of <kbd>T</kbd> and <kbd>G</kbd>). I could post more detailed information regarding the other keys if needed, but about a third or so of the keys behave weird like this.

## System Information

 - Keyboard: Planck EZ
 - Operating system: Ubuntu 20.04.2 LTS
 - AVR GCC version: `avr-gcc (GCC) 5.4.0`
 - ARM GCC version: `arm-none-eabi-gcc (15:9-2019-q4-0ubuntu1) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]`
 - QMK Firmware version: 0.13.33

## Additional Context

Is this a known issue? Does it also affect other boards? I know it affected me ever since I go the keyboard a few years ago, but I couldn’t find other people mentioning this issue online.

I personally don’t really care so much if this will be fixed or not, because I usually don’t use the heatmap effect. (Maybe I will after it gets fixed, who knows.) Unfortunately I don’t know how to fix this myself, as I have only ever used the predefined lighting effects and haven’t looked into how individual LEDs are addressed by the firmware.

**Comment by drashna** [comment]
It's a known issue, with how the switch matrix is laid out and how the rgb matrix handles it. 

No fix for it, yet.
