### ISSUE TITLE
qmk setup issue

### ISSUE THREAD

**Issue by ggumtlee12** [qmk/qmk_firmware#14116]
when i start qmk setup, it fails with the error message in the picture. I tried it on another pc, but the same thing happened.
![qmk2](https://user-images.githubusercontent.com/89350479/130367053-baaa8f22-f150-4111-8bfd-fea703e399ef.PNG)

**Comment by hobby-grade** [comment]
Does this happen when using [QMK MSYS?](https://msys.qmk.fm)
