### ISSUE TITLE
Combos don't play well with leader keys

### ISSUE THREAD

**Issue by mneme** [qmk/qmk_firmware#1411]
When shadowing combos and leader keys the shadowed keys get sent by the keyboard even if you are in a leader combination.

In my case I have a combo for `asdf` and a leader string using `s => s`

Expected:
`LEAD => s  => s = ¯\(ツ)/¯`

Result: 
`LEAD => s => s = ss¯\(ツ)/¯`

This only applies to cases where combos and leaders overlap, even if only partly.

Probably a pretty hard interaction to actually fix but I just thought I'd throw it up here anyways.

**Comment by drashna** [comment]
Hmmm, that's pretty nasty though.

**Comment by Talljoe** [comment]
`process_leader` [allows the keyup to go through](https://github.com/qmk/qmk_firmware/blob/master/quantum/process_keycode/process_leader.c#L36). This causes `process_combo` to think a key has been released and [sends it out](https://github.com/qmk/qmk_firmware/blob/master/quantum/process_keycode/process_combo.c#L91-L103).

**Comment by AnonJohn** [comment]
FWIW, this no longer seems to be an issue. Fixed?

**Comment by jackhumbert** [comment]
If that's not the case, feel free to comment/reopen - thanks!
