### ISSUE TITLE
error from make ergodox-ez-default-teensy

### ISSUE THREAD

**Issue by meriops** [qmk/qmk_firmware#1417]
When building the default keymap for the ergodox ez, the compiler complains about incrementing a boolean expression on line 60 of `ez.c`. Is that a problem with a gcc flag to modify somewhere or is it a problem in the code itself?

**Comment by fredizzimo** [comment]
It will be fixed by this pull request https://github.com/qmk/qmk_firmware/pull/1331

**Comment by ezuk** [comment]
And #1331 has been merged!
