### ISSUE TITLE
How to individually control RGB lighting with WS2812?

### ISSUE THREAD

**Issue by Ptomerty** [qmk/qmk_firmware#1420]
If possible, I want to have WS2812s wired to produce [these LED effects](http://imgur.com/a/DnE2W) on each layer: is this currently possible using QMK? The only resources I have found are for general RGB backlighting and underglow effects.

**Comment by Dbroqua** [comment]
Hello,

Do you know how to wire your LEDs to control each ones individually ?

Regards,
Damien

**Comment by iFreilicht** [comment]
related to #1399
I don't think QMK currently has built-in support for individually addressable LEDs.

**Comment by Ptomerty** [comment]
Actually, I was digging around and found [this keyboard layout](https://github.com/qmk/qmk_firmware/blob/1585fc4b616cb28b8d4a418cd31c8ce0dd64f731/keyboards/handwired/promethium/keymaps/priyadi/keymap.c#L171), where the guy manually calls `rgbsps_set` to turn each LED on or off.

**Comment by drashna** [comment]
Officially added in #2106: 
https://docs.qmk.fm/feature_rgblight.html#rgblight-keycodes

rgblight_setrgb_at(r,g,b, LED);  // control a single LED.  0 <= LED < RGBLED_NUM
rgblight_sethsv_at(h,s,v, LED);  // control a single LED.  0 <= LED < RGBLED_NUM
