### ISSUE TITLE
Tracking issue for keyboard removals

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#14211]
This issue exists to track keyboards that we may want to remove from the repository.

There is currently no automation to nominate a keyboard, keyboards are added here when maintainers are faced with doing maintenance work on a board that seems to be abandoned or not worth the work it would take to bring it inline with current practices.

Current list-

* [ ] `handwired/reddot`

**Comment by skullydazed** [comment]
`handwired/reddot` throws this error:

```
☒ handwired/reddot: Non-assignment code found in rules.mk. Move it to post_rules.mk instead.
☒ Non-assignment code on line +11 keyboards/handwired/reddot/rules.mk: ifdef TEENSY2
☒ Non-assignment code on line +15 keyboards/handwired/reddot/rules.mk: else
☒ Non-assignment code on line +20 keyboards/handwired/reddot/rules.mk: endif
```

It has not had any changes, except by QMK Maintainers, since the original PR #1056.

@upils is this something you want to maintain in the repo?

**Comment by upils** [comment]
@skullydazed As far as I know I am the only user of this layout. So I guess you may remove it if you want to do some cleanup. Thanks for your time maintaining and keeping the project clean :)

**Comment by jackokring** [comment]
It seems that as everyone makes a fork to do their own keymap, then PR to build in that keymap making it all bigger. Would it perhaps be easier to automate a fork list page of modifications and or additions in the whole QMK ecosystem of a stable type?

In that way, a single index `*.md` file could be looked at for links to forked repositories with added keymaps. And maybe even a fetching script could be added to extend QMK like `qmk gitmaps <user-name>`.

I'm not sure how complex this would be to automate using github actions or some other thing.

**Comment by tzarc** [comment]
Seems like we're done.
