### ISSUE TITLE
[Bug] Regarding the RGB matrix lighting error when the computer enters sleep 

### ISSUE THREAD

**Issue by XBowsTech** [qmk/qmk_firmware#14260]
## Describe the Bug

Regarding the RGB light display is wrong when the computer enters sleep。
In qmk_firmware/tmk_core/common/avr/suspend.c   line 169

//#    if defined(RGB_MATRIX_ENABLE)
//    rgb_matrix_set_suspend_state(true);
//#    endif

Cannot be called correctly. 

I tried to change it and successfully turned off the keyboard light when the computer went to sleep. 
As shown below: 
//#    if defined(RGB_MATRIX_ENABLE)
//    rgb_matrix_set_color_all(0, 0, 0);
//    rgb_matrix_task();
//#    endif

/************split line ******************/
In qmk_firmware/tmk_core/protocol/lufa/lufa.c    line1087
I don't know the specific reason, but this flag（USB_Device_RemoteWakeupEnabled）   will prevent the keyboard from waking up the computer under certain conditions. For example, after the computer is not operated for a long time, and the keyboard cannot wake up the computer after it is kept in the sleep state for a period of time.
But when I remove this flag bit, everything is normal. 

## System Information

 - Keyboard:  
   - Revision (if applicable):  xbows nature
 - Operating system:win10
 - AVR GCC version:  up to date 

 - ARM GCC version: 

 - QMK Firmware version: up to date 

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context
Possibly a duplicate of issue #13088 and #14127

**Comment by vinorodrigues** [comment]
This seems to be fixed now with pull request #14084
