### ISSUE TITLE
[Bug] BootloaderHID keyboard not recognized by my pixel 5 phone

### ISSUE THREAD

**Issue by xsrvmy** [qmk/qmk_firmware#14272]
## Describe the Bug

I have noticed that my pixel 5 does not recognize my wheatfield/split75 as a keyboard. It does get recognized as a usb device, but the phone tries to charge it rather than considering it a keyboard. It doesn't even seem to be responsive - hitting the reset keycode does nothing. I can however enter bootloader by holding control when connecting the device.

The issue seems to be specifically with this combination of keyboard/controller/bootloader and my pixel 5 phone. Other Android 11 phones as well as iPads can detect the keyboard, and my phone can detect my new planck. The pixel 5 is known to be stricter than other phones with usb c cables, but this doesn't seem to be the problem here.

## System Information

 - Keyboard:  wheatfield/split75
   - Revision (if applicable):  
 - Operating system: compiled on WSL2 Ubuntu 20.04, flashed from toolbox on Win10, phone runs Android 11
 - AVR GCC version: 5.4.0

 - ARM GCC version: 9.2.1

 - QMK Firmware version: 0.14.3

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by hsgw** [comment]
The MCU (ATMEGA32A) on the wheatfield/split75 does not support native USB.
So, it uses VUSB, which emulates the protocol by software, but unfortunately, it is not perfect and may be unstable and unrecognized by some hosts.

Try connecting it through a USB hub or try a shorter cable.
If it is still not recognized, it may have a hardware compatibility issue.

**Comment by tzarc** [comment]
No updates in nearly a year. Feel free to reopen if/when more information comes to light.
