### ISSUE TITLE
[Bug] rgb_matrix effect confusion after breaking changes of 2021Q3

### ISSUE THREAD

**Issue by moyi4681** [qmk/qmk_firmware#14328]
-keymap:
VIA
- Keyboard:  
DZ60RGB , DZ60RGB ANSI, DZ60RGBWKL
with source code after breaking change to compile a via firmware, the light effect is not correct
with release 0.13.38 works fine

**Comment by kb-elmo** [comment]
Can confirm this.
It's not just an issue with DZ boards.

It's the link time optimization that causes this.
Enabling LTO completely breaks the RGB matrix now!

**Comment by drashna** [comment]
Do you know what commit specifically breaks it?  

Because I haven't seen issues with rgb matrix and LTO being enabled.

**Comment by kb-elmo** [comment]
This doesn't exactly look like "out of order RGB animation".
It just doesn't work anymore at all.

It works perfectly fine with LTO disabled (which is only possible with the non-VIA firmware because with VIA it would be too big for the flash)

![image](https://i.imgur.com/X57LdNA.jpg)

**Comment by drashna** [comment]
Could you try reverting 70fb3e1aaf406cbbd5137916a93ed814d6891ef2 and see if that fixes the issue?

**Comment by kb-elmo** [comment]
> Could you try reverting [70fb3e1](https://github.com/qmk/qmk_firmware/commit/70fb3e1aaf406cbbd5137916a93ed814d6891ef2) and see if that fixes the issue?

yup reverting those changes fixed it.

RGB works now with LTO enabled.

**Comment by sigprof** [comment]
With what versions of `avr-gcc` does the problem appear? E.g., Debian/Ubuntu distros have 5.4 with significant Atmel/Microchip modifications; MSYS uses 8.4.0; on Arch Linux the distro-provided version is usually rather recent (11.2.0 at the moment), but the QMK install script for Arch Linux tries to install the 8.3.0 version from archive. There might be significant differences between the LTO implementations in these versions.

**Comment by kb-elmo** [comment]
> With what versions of `avr-gcc` does the problem appear? E.g., Debian/Ubuntu distros have 5.4 with significant Atmel/Microchip modifications; MSYS uses 8.4.0; on Arch Linux the distro-provided version is usually rather recent (11.2.0 at the moment), but the QMK install script for Arch Linux tries to install the 8.3.0 version from archive. There might be significant differences between the LTO implementations in these versions.

5.4.0 on Ubuntu WSL (in my case. No idea what version DZ uses)

**Comment by Andrew-Fahmy** [comment]
I also had an issue with the rgb matrix changes breaking lighting on my K-type (specifically commit 70fb3e1aaf406cbbd5137916a93ed814d6891ef2). I removed `__flash` and it seemed to fix my issue but I'm not really sure if this is a great way to solve it

**Comment by moyi4681** [comment]
looks like the issue appears happen on IS31FL3733 microchip. IS31FL3741 works fine, I've not tested on other microchip.

**Comment by Andrew-Fahmy** [comment]
After more testing it seems like the problem was not at all related with the `__flash` and that it was just a coincidence that it worked when I changed that. I think it has something to do with flashing the firmware.

I build two versions of the firmware, one from master and the other from a older commit (70fb3e1aaf406cbbd5137916a93ed814d6891ef2). Both of them work fine, but if I flash the same firmware a second time the lighting doesn't work at all.

Could this be a bug with the bootloader?

**Comment by kb-elmo** [comment]
> Could this be a bug with the bootloader?

Doesn't apply for me.

Only disabling LTO or removing the `__flash` fixes the issues here.

**Comment by Andrew-Fahmy** [comment]
> Only disabling LTO or removing the `__flash` fixes the issues here.

Neither of these fixes my problem.  There is another issue #11775  that seems to be more similar to mine.

**Comment by arnmar** [comment]
Removing __flash seems to fix the RGB issue for me on my DZ60RGB ANSI. Compiling with gcc 9.3.0 on WSL Ubuntu.
