### ISSUE TITLE
QMK on a TKL?

### ISSUE THREAD

**Issue by johndierks** [qmk/qmk_firmware#1460]
Are there any TKLs available that run QMK? Seems like QMK is most popular with boards 65% and under.

**Comment by skullydazed** [comment]
We support the Phantom, which you can pick up here: https://mechanicalkeyboards.com/shop/index.php?l=product_detail&p=536

**Comment by Talljoe** [comment]
You can also run QMK on the [Frosty Flake](https://1upkeyboards.com/qfr-frosty-flake-controller.html) replacement controller for the QuickFire Rapid (coincidentally by the creator of the Phantom).
