### ISSUE TITLE
The macro interval is double of what it should be

### ISSUE THREAD

**Issue by fredizzimo** [qmk/qmk_firmware#1477]
The macro interval, `I(ms)` which is supposed to change the stroke interval of the keypresses is applied both for keydown and keyup, which makes it twice as long as it should be. This could be a documentation issue, or it could be a real issue, but either the code or documentation should be fixed.

Another more minor issue is that the delay is also applied to the `I(ms)` statement itself, so if you start a macro with that, there will be a delay before the first key is sent.

See `test_macro.cpp` for more information.

**Comment by drashna** [comment]
Macros are depreciated now.  
Should this be closed?

**Comment by fredizzimo** [comment]
I'm not sure, the newer `SEND_STRING` doesn't allow you to change these intervals in the middle so that's still something that the old macros do better. So I would leave this open at least until that is implemented.

**Comment by jackhumbert** [comment]
I think this can be closed - we can have a new issue for implementing intervals in send_string, but my suspision is that people will be using custom keycodes for this sort of thing.
