### ISSUE TITLE
Line ending issues with recent pull

### ISSUE THREAD

**Issue by That-Canadian** [qmk/qmk_firmware#1480]
So I'm having issue with the recent QMK master update, where now git is yelling that almost all files in the lib/lufo directory are modified, even on a hard reset and checkout. It looks like this is an issue with un-normalized line endings being commited to the branch. Can anyone else confirm? I'm on Bash for Windows, here's a screencap of part of the issue : 
![image](https://user-images.githubusercontent.com/6474430/27987501-a63f97f4-63dc-11e7-9234-dd5ada6b4c88.png)

**Comment by fredizzimo** [comment]
Yes. it's a known issue. Yesterday we were working on fixing it correctly in the LUFA repository https://github.com/qmk/lufa, but got interrupted in the process, so it never got fixed.

Sorry for the invconvenience, we will try to fix it soon.

**Comment by That-Canadian** [comment]
Cool glad I'm not going crazy, will just hold back on any pull requests for now

**Comment by fredizzimo** [comment]
It should be fixed now.
