### ISSUE TITLE
[Documentation Bug] Tap dance example 5, missing cases on switch

### ISSUE THREAD

**Issue by cobac** [qmk/qmk_firmware#14836]
Hey,

I've implemented the behaviour explained in the 5th example of the tap dance section, but the compiler threw the following errors:

`error: enumeration value 'TD_NONE' not handled in switch`
`error: enumeration value 'TD_UNKNOWN' not handled in switch`

I've fixed it adding 

```
...	
			
case TD_NONE:
    break;
case TD_UNKNOWN:
    break;
	}
}

```
to both functions with a case switch.

https://github.com/qmk/qmk_firmware/blob/235323269c372f40044ad2f73a602c9c60af6195/docs/feature_tap_dance.md?plain=1#L384

https://github.com/qmk/qmk_firmware/blob/235323269c372f40044ad2f73a602c9c60af6195/docs/feature_tap_dance.md?plain=1#L399

I'm not submitting a PR because I can't write C and I don't know if my fix is a good solution.

Thanks for maintaining this package!

**Comment by joukewitteveen** [comment]
I believe this can be closed given that #14893 is merged.
