### ISSUE TITLE
[Bug] Magic Keycode GUI_TOG doesn't work

### ISSUE THREAD

**Issue by ForsakenRei** [qmk/qmk_firmware#14885]
Magic keycode `GUI_TOG` doesn't work

## Describe the Bug
I want to use `GUI_TOG` instead of the macro for Windows lock. 
While `GUI_TOG` failed to toggle whe GUI key status no matter it is on or off. But both `GUI_ON` and `GUI_OFF` work without issue.

## System Information

 - Keyboard:  
   - Revision (if applicable):  GMMK Por ANSI
 - Operating system: Win10 21H1
 - AVR GCC version: 8.4.0

 - ARM GCC version: 10.1.0

 - QMK Firmware version: 0.14.23

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by sigprof** [comment]
Yes, the `GUI_TOG` (==`MAGIC_TOGGLE_GUI`) keycode does not work; #14886 should fix that.
