### ISSUE TITLE
QMK不支持STM32F103吗？MCU改成 STM32F103不能编译 Does QMK not support STM32F103? Cannot compile when MCU is changed to STM32F103

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#14915]
QMK不支持STM32F103吗？MCU改成 STM32F103不能编译 Does QMK not support STM32F103? Cannot compile when MCU is changed to STM32F103
MCU = 应该写什么型号？MCU = What model should be written?
![image](https://user-images.githubusercontent.com/5648129/138494588-e704772e-32fc-4b0d-b744-ab19dcd5428e.png)
![image](https://user-images.githubusercontent.com/5648129/138494943-b2c391c0-3992-4db1-a7eb-80602783f779.png)

**Comment by elfmimi** [comment]
At least [handwired/onekey/bluepill](https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/onekey/bluepill) compiles ok.
