### ISSUE TITLE
SPLIT_KEYBARD F_CPU = 8000000

### ISSUE THREAD

**Issue by jmwolner** [qmk/qmk_firmware#14951]
When using itsy bitsy 3v the CPU must be set to 8mzh.  When I set split keyboard, after flashing to the board, the USB device is no longer recognized.  When I remove split keyboard, the USB device is working.  Something is up with the split keyboard code.

**Comment by drashna** [comment]
You're using serial for the communication, correct?  And this is the atmega32u4 controller? 

If so, it may be that it's very sensitive to timing, and may need to be adjusted to fix that.

Also, the serial drivers for split uses interrupt, which may be art of the issue.

**Comment by jmwolner** [comment]
Yes this is a atmega32u4 running at 8mzh.  I can get it to work as one side without an issue.  Soon as I add SPLIT_KEYBOARD = yes, and re-flash the controller, the USB device is no longer detected.  So there is something up with the code for SPLIT_KEYBOARD.  I was guessing it was maybe with the timing...but wasn't sure where to find that code and make some changes.

My wiring is using a TRRS for I2C.  Based on the Redox Handwire. https://hackaday.io/project/160610-redox-keyboard/log/151316-redox-handwire.   I was just wiring directly to SCL and SDA with VCC and Ground between the controllers.

I thought I would try the Pterodactyl keyboard definition, since it uses a Feather(very much like the Itsy Bitsy, but it uses an IO expander.  https://marcyoung.us/post/pterodactyl/   Since I don't have an IO expander, it never recognizes it.

Any help and guidance is much appreciated how to change the code so SPLIT_KEYBOARD will work at 8mzh.

**Comment by drashna** [comment]
You have `#define USE_I2C` correct?

**Comment by jmwolner** [comment]
Yes in the /keymaps/default/config.h

The keyboard(left side) boots ok and puts out keystrokes when I have the SPLIT_KEYBOARD commented out.  Soon as I change it use in the rules.mk and recompile/reflash the controller is when the USB device is no longer recognized.

**Comment by drashna** [comment]
Do you have the same issue if you remove the `USE_I2C` and default to serial comms?

**Comment by jmwolner** [comment]
USE_SERIAL worked and the HID was detected.  But nothing was coming from the right side.  I moved the SOFT_SERIAL_PIN to D2 to see if that was the issue and it wasn't.  I eventually figured it out that I needed #define SPLIT_USB_DETECT.
It would appear that I2C won't work.
I've been struggling with this for months I extremely appreciate your reply and assistance.

**Comment by doctorkelp** [comment]
This is an issue for me, too! `i2c` is borked

**Comment by Kriechi** [comment]
SERIAL vs. I2C issues might be related to #15217
