### ISSUE TITLE
KPrepublic updating their boards to have a second version

### ISSUE THREAD

**Issue by peepeetee** [qmk/qmk_firmware#14964]
As titled, KPrepublic is updating their boards to have a second version. Should we plan to add a rev1 and a rev2 directory to keyboards that are impacted in this breaking change? 

Also, the current naming of KPrepublic boards is a little messy, we could clean that up as well

**Comment by charlesnchr** [comment]
Hi @peepeetee,

I see you closed this issue, but has a rev2 QMK version actually been added to any of their boards yet?  

As you note, the changes to the second version of the board indeed seem to be breaking. I'd be very keen to have a rev2 configuration.

**Comment by peepeetee** [comment]
> Hi @peepeetee,
> 
> I see you closed this issue, but has a rev2 QMK version actually been added to any of their boards yet?
> 
> As you note, the changes to the second version of the board indeed seem to be breaking. I'd be very keen to have a rev2 configuration.

https://github.com/qmk/qmk_firmware/pull/15177
https://github.com/qmk/qmk_firmware/pull/15103
https://github.com/qmk/qmk_firmware/pull/15095
https://github.com/qmk/qmk_firmware/pull/15060

**Comment by peepeetee** [comment]
Also, for the record, the renaming PR is #15047

**Comment by charlesnchr** [comment]
Excellent. Thanks for your hard work 👍

**Comment by peepeetee** [comment]
I'd like to reopen this, as #15060 hasn't been merged yet
