### ISSUE TITLE
[Bug] Moonlander Keyboard: Incorrect RGB-matrix neighbors for thumb-cluster.

### ISSUE THREAD

**Issue by NorthGuard** [qmk/qmk_firmware#14966]
## Describe the Bug
Some reactive RGB matrix lighting use the LED specifications to determine which keys are neighbors (I think it is in `g_is31_leds`), like the reactive heatmap.
I use the Moonlander from Ergodox-ez and noticed that the neighboring keys do not really make sense for the thumb-cluster.

### Specifics
- Some keys on the main part of the keyboard are neighboring to keys of the thumb-cluster, even though they shouldn't (they light up together though the shouldn't).
- Some keys on the main part of the keyboard should be neighboring to keys of the thumb-cluster, but aren't (they should light up together but don't). 
- Finally the keys on the thumb-cluster should be neighboring but aren't really (they should light up together but do not).

Here's a video shoving a couple of examples: https://drive.google.com/file/d/1ZSg2fuWe9Fy7GwoCCkaerQJbuuqffoBP

## System Information

 - Keyboard:  Moonlander
 - Operating system: Ubuntu 20.04
 - AVR GCC version: 5.4.0
 - ARM GCC version:  9.2.1
 - QMK Firmware version: Firmware20

**Comment by filterpaper** [comment]
Duplicate of #14041. See the explanation in that issue.

**Comment by NorthGuard** [comment]
> Duplicate of #14041. See the explanation in that issue.

Ah yes, thanks! I'll close this one :)
