### ISSUE TITLE
Ergodox ez steno layout mouse doesnt work

### ISSUE THREAD

**Issue by johnwalker** [qmk/qmk_firmware#1499]
Hi, I flashed my ez with the ergodox ez steno layout. But it looks like none of the mouse buttons and navigation works on layout 2.

**Comment by Maartenwut** [comment]
Change MOUSEKEY_ENABLE = no to MOUSEKEY_ENABLE = yes in your Makefile.

**Comment by Talljoe** [comment]
The virtual serial port and the mousekeys feature use the same interrupt and therefore can't be enabled at the same time. It's something I'm looking into to better support the stenography change that I submitted today.

**Comment by drashna** [comment]
Was this resolved?

**Comment by johnwalker** [comment]
no

**Comment by razajafri** [comment]
Has there been any resolution to this? 

My symbol layer isn't working either. whats the work around to that?

**Comment by drashna** [comment]
It may be worth applying this PR, and see if it fixes the issues:
https://github.com/qmk/qmk_firmware/pull/3951

**Comment by jackhumbert** [comment]
The endpoint limit isn't something we can really address here - if you have any code snippets or additional complications, feel free to post them here, but I think we can close this for now.
