### ISSUE TITLE
RGB Underglow

### ISSUE THREAD

**Issue by Dbroqua** [qmk/qmk_firmware#1500]
Hello,

I'm currently working on a new custom keyboard (https://github.com/Dbroqua/DK60TP) and I'm a little bit confused about the RGB underglow.

On my PCB I have 8 leds but if in my config.h I set `#define RGBLED_NUM 8` only the 6 first leds work.

I have made some tests ( `#define RGBLED_NUM 1` to ``#define RGBLED_NUM 10`) and I have seen that the leds 3 and 7 generate the gap.

I think it's an electronic issue but why and how to fix them?

Regards,

Damien.

**Comment by drashna** [comment]
I think I remember seeing this in the gitter (or maybe reddit). 

Probably a bad strip.  And if so, replacing would be the only real solution. 

Also, did you get this resolved?

**Comment by Dbroqua** [comment]
Hello,

I don't use strip but a custom PCB with leds soldered one by one on the PCB.

**Comment by drashna** [comment]
Sorry for the super long delay. :(

Most likely, it's a burned out LED, as the individual LEDs are very sensitive.
