### ISSUE TITLE
keyboard.c is ignored in keymap folder

### ISSUE THREAD

**Issue by Maartenwut** [qmk/qmk_firmware#1501]
I wanted to slightly customize how the caps lock led handles things, so I put a file called tada68.c in my keymap folder, tada68/keymaps/maartenwut. Like other files such as Makefile and config.h, I expected it to be included when building the firmware, but it's not.

**Comment by jackhumbert** [comment]
Did you add `tada68.c` to the `SRC +=` in your `rules.mk`?

**Comment by Maartenwut** [comment]
I did not. I've never seen it before.

**Comment by fredizzimo** [comment]
You should not really need to modify things from the keymap files.

Normally keyboards have a `led_set_user`, which you can override in your keymap. The `tada68` doesn't however, I suggest that you look at some examples from other keyboards and fix the real `tada68.c` file to support it and send a pull request.

**Comment by Maartenwut** [comment]
This worked. Thanks!
