### ISSUE TITLE
[Feature Request] Add Lelelab Keyboard

### ISSUE THREAD

**Issue by andywith** [qmk/qmk_firmware#15023]
**Types of Changes**

- [x]  Keyboard (addition or update)
- [x]  Keymap/layout/userspace (addition or update)

 **Documentation**
 
- [x] Issues Fixed or Closed by This PR

**Checklist**
- [x]  My code follows the code style of this project: C
- [x]  I have read the PR Checklist document and have made the appropriate changes.
- [x]  My change requires a change to the documentation.
- [x]  I have updated the documentation accordingly.
- [x]  I have read the CONTRIBUTING document.
- [x]  I have added tests to cover my changes.
- [x]  I have tested the changes and verified that they work and don't break anything (as well as I can manage).

**Comment by tzarc** [comment]
Not sure what this is for. Closing.
