### ISSUE TITLE
Cycling and Directly Choosing Layers with the same key?

### ISSUE THREAD

**Issue by classabbyamp** [qmk/qmk_firmware#1507]
I am creating a macro pad that is 1 row by 6 columns. I intend to have the column 0 key be used to switch layers so I can have different sets of macros. The table below should work so that I can cycle through each layer with a momentary press of the key.

|         | Col 0 | Col 1 | Col 2 | Col 3 | Col 4 | Col 5 |
|---------|-------|-------|-------|-------|-------|-------|
| Layer 4 | TO(0) | M40   | M41   | M42   | M43   | M44   |
| Layer 3 | TO(4) | M30   | M31   | M32   | M33   | M34   |
| Layer 2 | TO(3) | M20   | M21   | M22   | M23   | M24   |
| Layer 1 | TO(2) | M10   | M11   | M12   | M13   | M14   |
| Layer 0 | TO(1) | M00   | M01   | M02   | M03   | M04   |

**Is it possible to have layer cycling *and* use it like a modifier for layer switching when held?** For example: if I press Col0 + Col1 on any layer, it should switch to layer 0 (See the table below).

| Key Combo | Action |
|---------|-------|
| Col0 + Col5 | Go to layer 4 |
| Col0 + Col4 | Go to layer 3 |
| Col0 + Col3 | Go to layer 2 |
| Col0 + Col2 | Go to layer 1 |
| Col0 + Col1 | Go to layer 0 |

**Comment by galengold** [comment]
One thought I had was to set the col0 key as the Leader and create leader combinations to go to layers, but that doesn't allow me to cycle through like in the first table.

**Comment by drashna** [comment]
Tap dance may actually be perfect for this.  Just use the count to set the layers. 
https://docs.qmk.fm/feature_tap_dance.html

**Comment by foosinn** [comment]
did anyone implement this using the tap dance?

**Comment by foosinn** [comment]
for anyone interested: i use a currently use a macro to reset the layers to google back to my default:

```c
const macro_t *action_get_macro(keyrecord_t *record, uint8_t id, uint8_t opt) {
  switch(id) {
  case 100:
    layer_clear();
    return MACRO_NONE;
    break;
  default:
    return MACRO_NONE;
    break;
  };
};
```

On the default layer i have `OSL(1)`, on the second `OSL(2)` and on the third `M(100)`.

**Comment by jackhumbert** [comment]
This sounds like a good fit - if you have any complications with implementing this, feel free to comment/reopen this.
