### ISSUE TITLE
Can STM32 not use VIA?

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#15084]
Can't STM32 use VIA? The \zvecr\zv48 keyboard is compiled with via and flashed into STM32. F401 is recognized in via, but it cannot be saved after modification. After unplugging it, plug it in and restore the default keys. The 32U4 can be saved normally after unplugging and then plugging in the computer is the modified key.

**Comment by fauxpark** [comment]
F4 has no working EEPROM emulation IIRC, you need to add a separate EEPROM chip to allow VIA to save the keymap: https://docs.qmk.fm/#/eeprom_driver

**Comment by zvecr** [comment]
Was implemented in #14195. Develop is targeted for merge end of the month.
