### ISSUE TITLE
[Feature Request] OSM SHIFT should always produce shifted letter (oryx, moonlander)

### ISSUE THREAD

**Issue by urza** [qmk/qmk_firmware#15135]
I expected that pressing osm shift and then letter will always produce the letter in uppercase (shifted) variation. However when you press the osm shift down and hold it longer than tapping term, then release the shift and press some letter, result is lowercase letter, because by holding the shift longer it switched to holding shift mode and hence was released before next key was pressed.

I would like to make sure somehow that when I press the osm shift, that next key will always be shifted (uppercase letter etc) regardless of timing.

Is this possible somehow? I would like to be able to configure my osm shift behave like this.

I can modify tapping term but that doesnt seem like ideal solution.

My keyboad is Moonlander mk I using Wally and Oryx.

**Comment by drashna** [comment]
That is expected behavior.  If you hold a OSM past the tapping term, it's treated as if you're holding a normal modifier key, rather than a oneshot key.  once you release it, the mod is released, too.
