### ISSUE TITLE
Can't click the anchor on headings in the docs

### ISSUE THREAD

**Issue by ddeklerk** [qmk/qmk_firmware#1515]
The anchor to link to a specific heading in the docs cannot be clicked unless it is the first page of a group. Otherwise the clickable area for the back arrow overlaps it. There are also two icons shown overlapping each other when hovering over a heading.

**Comment by drashna** [comment]
Is this still an issue? 

Also, on what page(s)?

**Comment by ddeklerk** [comment]
The overlapping icons is fixed, I think. The back button overlapping heading links is still an issue on small viewports. Maybe changing the z-index of the heading links or putting them to the right of the heading text works.
