### ISSUE TITLE
[Feature Request] Support GMMK PRO's "Cycle through Active RGB Zone"

### ISSUE THREAD

**Issue by dxps** [qmk/qmk_firmware#15267]
### Description

Dear QMK community,

Any change to add the _Cycle through Active RGB Zone_ key option of GMMK Pro to QMK Configurator, please?

As stated in the [Product Guide](https://www.pcgamingrace.com/pages/product-guides?guide=GMMK_PRO#Quick-Start-Guide), section _RGB LED Light Settings_, `FN + 1` allows choosing whether both (front+side) or one of them to get lights on. [This reddit thread](https://www.reddit.com/r/glorious/comments/nhtvvw/gmmk_pro_how_to_turn_off_all_lights_except_side/) confirms its existence on their firmware.

**I'm particularly interested in having only the side lights on.**

I own two GMMK Pro models, and very happy with QMK firmware, btw. :blush: 

Notes:
1. If it's already there, just enlight me. I searched though existing issues before raising this one.
2. If this request should actually first be raised to QMK firmware repo, I'll do it.

Thanks!

**Comment by dxps** [comment]
@yanfali Thanks for moving it into the proper repo. If there anything I can do to help, please tell me.

**Comment by drashna** [comment]
I believe that this can be done by using the rgb matrix set flags function.

**Comment by dxps** [comment]
@drashna 
You mean using `rgb_matrix_set_flags` function.
Thanks for the hint! :pray: 

Meanwhile, without further details, I assume that I should try to understand how to use it based on concrete examples
such as [/keyboards/moonlander/moonlander.c#L436](https://github.com/qmk/qmk_firmware/blob/f718a10889e6adf33f3fc2f41b61cad7fe9e0c2e/keyboards/moonlander/moonlander.c#L436).
