### ISSUE TITLE
[Bug] 0.14.33 breaks backlight levels

### ISSUE THREAD

**Issue by karlshea** [qmk/qmk_firmware#15331]
## Describe the Bug

I have a higher number of backlight levels (20) so it's more obvious, but even a smaller number shows this behavior: increasing/decreasing the backlight levels jumps the light intensity all over the place (e.g. starting from backlight level 0 -> intensity 0, 1 -> intensity 50 (estimated), 2 -> intensity 10, 3 -> intensity 200, 4 -> intensity 50, 5 -> intensity 190).

0.14.32 works normally. If I check out the first commit (b47bdee93c5dc39353477126abd344476c736132 ) after that tag it starts to break.

## System Information

 - Keyboard:  Both KBDfans KBD75 rev2 _and_ Treasure type9s2 show this behavior.
 - Operating system: macOS
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

Building using latest qmkfm/qmk_cli Docker image.

**Comment by tzarc** [comment]
Do you know how to do a `git bisect`?

**Comment by karlshea** [comment]
I didn't, but now I do, it says e0a5056963beddc3430dd3c8372858288dc85809 is the first bad commit.

**Comment by karlshea** [comment]
It's something to do with `cie_lightness()`. If I revert just those changes it works fine too.

**Comment by karlshea** [comment]
Figured it out, it's losing bits doing division.
