### ISSUE TITLE
Paramedic in need of help

### ISSUE THREAD

**Issue by Bobheim** [qmk/qmk_firmware#15367]
I am trying to code my gmmk pro to have some macro buttons that when I press they populate a pre written text paragraph. 

I have the key map I like and have put stars in the empty buttons on the second layer I would like the macros to go but lack the technical know how to code it.  

I have had a go but as youll see I really dont know what I am doing
[bobheim's crap attempt.txt](https://github.com/qmk/qmk_firmware/files/7629367/bobheim.s.crap.attempt.txt)

If anyone wouldn't mind giving me some pointers or helping I would be forever greatful. Below is the keymap.
[Bobheim keymap without macro.txt](https://github.com/qmk/qmk_firmware/files/7629359/Bobheim.keymap.without.macro.txt)

**Comment by osleg** [comment]
TBH the code doesn't seem so bad, the problem tho is that we don't know what is the problem that you encounter.

It would be useful if you describe the problem that rises when you try to compile that, because I doubt that anyone will compile it locally just to see the errors.
Give us more info :)
