### ISSUE TITLE
[Bug] PS/2 Mouse ARM interrupt version does not work

### ISSUE THREAD

**Issue by freznel10** [qmk/qmk_firmware#15373]
Tested the ARM interrupt version for PS/2 mouse on Bluepill and the Blackpill. Used A8 and A9 for the clock and data. Built FW using the onekey templates. It does not seem to work. Tested the USART AVR version on an Elite C to verify if my trackpoint is working and it it.

**Comment by sigprof** [comment]
The A9 pin might not work properly for this purpose on STM32F401/F411 chips; you should test with some other pin instead.

**Comment by freznel10** [comment]
Oooof thanks. I forgot about A9 on a blackpill.

**Comment by freznel10** [comment]
Tried several other pins with no success.

**Comment by freznel10** [comment]
B1 and C15 works
