### ISSUE TITLE
QMK Compile not finding folder 

### ISSUE THREAD

**Issue by JoakoV3** [qmk/qmk_firmware#15428]
I have tried to compile a keyboard with qmk MSYS and when I enter `qmk compile -kb planck -km default` It returns
```
qmk compile -kb planck -km default
usage: qmk.exe compile [-h] [-c] [-e ENV] [-j PARALLEL] [-n] [-km KEYMAP] [-kb KEYBOARD] [filename]
qmk.exe compile: error: argument -kb/--keyboard: invalid keyboard_folder value: 'planck'

```

I tried putting absolute paths to it and all kinds of keyboard_folder values but it is just not working. I tried changing my path to keyboards, planck, qmk_firmware, but it's the same output on all paths.

Is there a solution to this?

**Comment by fauxpark** [comment]
There is no keyboard in the repo named `planck`.
![image](https://user-images.githubusercontent.com/4781841/145115613-70e71f58-acb6-4407-9a17-c2ead8023fcf.png)

**Comment by JoakoV3** [comment]
Oh okay, but when I put the `qmk compile -kb planck/rev1 -km default` it gives me an error 

```
tmk_core/protocol/lufa.mk:13: lib/lufa/LUFA/makefile: No such file or directory 
make: *** [Makefile:478: planck/rev1:default] Error 1
```
and says Make finished with errors.

**Comment by fauxpark** [comment]
https://docs.qmk.fm/#/newbs

**Comment by JoakoV3** [comment]
weird bug, had to run qmk setup again. closing...
