### ISSUE TITLE
Compile Error: "No rule to make target 'drivers/avr/i2c_master.c'" for dactyl_manuform

### ISSUE THREAD

**Issue by skoenen** [qmk/qmk_firmware#15476]
_Keyboard_: handwired/dactyl_manuform/5x6
_QMK-Version_: 1.0.0 (installed via pip)
_QMK-Source_: 99b35940bc4166eae3853c9e2fa94bd2be72742e
_QMK-Firmware: 0.15.6

AVR-GCC: 11.2.0

Command:
```Shell
qmk -v compile -kb handwired/dactyl_manuform/5x6 -km myKeymap
```

Error:
```Shell
Compiling: quantum/command.c                                                                        [OK]
make[1]: *** No rule to make target 'drivers/avr/i2c_master.c', needed by '.build/obj_handwired_dactyl_manuform_5x6_myKeymap/i2c_master.o'.  Stop.
Make finished with errors
make: *** [Makefile:478: handwired/dactyl_manuform/5x6:myKeymap] Error 1
```

I searched already the internet, but no idea what has to be changed, that the keymap will compile again.

**Comment by drashna** [comment]
run `qmk clean -a`, and then recompile.

**Comment by skoenen** [comment]
Thanks, now I'm feeling dump.

Should have been an obvious for me _(as an programmer :man_facepalming:)_

**Comment by powelleric** [comment]
> Thanks, now I'm feeling dump.

No matter how dumb you feel, there are always people dumber.  I would never have thought to run the clean command.  Thanks for asking this issue because I had the same problem.

**Comment by drashna** [comment]
Yup, this is one of those things that is not immediately obvious what the correct solution is.  It is definitely one of those things that comes with experience.

**Comment by daveriedstra** [comment]
Perhaps this could be more visible in the docs, maybe in the FAQ?
