### ISSUE TITLE
Questions about timer units

### ISSUE THREAD

**Issue by Weirdo-F** [qmk/qmk_firmware#15502]
When I use the timer_read() and timer_elapsed functions, I get results in ms, but I need either ns or cycle precision. How can I do that?

**Comment by Weirdo-F** [comment]
Maybe there's another function or method to implement timers in ns or cycles? @drashna

**Comment by drashna** [comment]
Not really, unfortunately.  

There may be chibiOS specific calls that can be used for ARM, but I'm not sure about AVR.

**Comment by Weirdo-F** [comment]
> 不幸的是，不是真的。
> 
> 可能有一些特定于chibiOS的调用可用于ARM，但我不确定AVR。



> Not really, unfortunately.
> 
> There may be chibiOS specific calls that can be used for ARM, but I'm not sure about AVR.

I'm using STM32

**Comment by Weirdo-F** [comment]
> Not really, unfortunately.
> 
> There may be chibiOS specific calls that can be used for ARM, but I'm not sure about AVR.

I'm using STM32

**Comment by tzarc** [comment]
Step back. Why? What needs this sort of timing resolution?

**Comment by Weirdo-F** [comment]
> 

I want to obtain the time of capacitor charging process, so as to determine whether the capacitance changes, that is, to realize the electrostatic capacitance keyboard.

**Comment by Weirdo-F** [comment]
> Step back. Why? What needs this sort of timing resolution?

I want to obtain the time of capacitor charging process, so as to determine whether the capacitance changes, that is, to realize the electrostatic capacitance keyboard.
