### ISSUE TITLE
The win key cannot be set, the bug is still a firmware compilation problem

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#15587]
The win key cannot be set. After any key is set to win, the key is invalid, and it is normal to set it to other keys. Is it a bug or a firmware compilation problem? The mcu is 32U4.

**Comment by filterpaper** [comment]
Is "win key" referring to `KC_LWIN` and `KC_RWIN`?

**Comment by jeromeli002** [comment]
> Is "win key" referring to `KC_LWIN` and `KC_RWIN`?

All useless, set to other keys is normal. Eliminate hardware problems

**Comment by filterpaper** [comment]
They are aliases to the GUI key. Have you tried `KC_LGUI`?

**Comment by peepeetee** [comment]
I see that you are using a translation program, do you need language help?

您看起来在用翻译工具，您需要语言帮助吗

**Comment by jeromeli002** [comment]
> I see that you are using a translation program, do you need language help?
> 
> 您看起来在用翻译工具，您需要语言帮助吗

Google翻译的 ，就是编译的时候是设置的win键刷上后按键没反应 通过via设置也是一样，但是设置其他键是正常的排除硬件问题不触发
![image](https://user-images.githubusercontent.com/5648129/147425270-987e198f-e097-4c31-96b3-02e5b878d9e3.png)

**Comment by jeromeli002** [comment]
> They are aliases to the GUI key. Have you tried `KC_LGUI`?

![image](https://user-images.githubusercontent.com/5648129/147425284-89b4b53d-8e3e-4057-9a84-2c18f80e9280.png)

**Comment by peepeetee** [comment]
您看看是不是您电脑上有锁定windows键的软件？ 如果是笔记本的话试一下fn+windows

See if there's any software on your computer that affects the windows key

**Comment by jeromeli002** [comment]
> 您看看是不是您电脑上有锁定windows键的软件？ 如果是笔记本的话试一下fn+windows
> 
> See if there's any software on your computer that affects the windows key

这样？ 笔记本自带的键盘win键是有用的能触发，晚上回去再试试吧
