### ISSUE TITLE
[XAP] implement keyboard- and user-level `xap.json`

### ISSUE THREAD

**Issue by tzarc** [qmk/qmk_firmware#15628]
## XAP Task Info

[Original Issue](https://github.com/qmk/qmk_firmware/issues/11567)
[Original spec document](https://hackmd.io/hhjooQ6UQhWV3MvTlbQiqQ)
[Current XAP Definitions](https://github.com/qmk/qmk_firmware/tree/xap/data/xap)
[Current XAP Generated Docs](https://github.com/qmk/qmk_firmware/blob/xap/docs/xap_protocol.md)
[Placeholder PR](https://github.com/qmk/qmk_firmware/pull/13733)

## Description

**Any work in this area needs to be discussed with QMK Collaborators first.**

Add support for keyboard-level and user-level `xap.json` to be provided, such that it's merged and included in the firmware.

**Comment by zvecr** [comment]
Currently implemented with the following:

* `xap.hjson` to match up with `xap_<version>.hjson`
* user/keyboard specs can only augment the 2 "special" routes
  * this limitation protects core functionality from overrides
* Validation does not currently handle the invalid case of `type: command` with `routes: { ... }`
  * jsonschema doesnt seem to provide the ability to validate an object based on a child keys value
* docs/codegen will ignore user/keyboard level customisation
