### ISSUE TITLE
[XAP] implement HID reports for ChibiOS, VUSB, LUFA

### ISSUE THREAD

**Issue by tzarc** [qmk/qmk_firmware#15620]
## XAP Task Info

[Original Issue](https://github.com/qmk/qmk_firmware/issues/11567)
[Original spec document](https://hackmd.io/hhjooQ6UQhWV3MvTlbQiqQ)
[Current XAP Definitions](https://github.com/qmk/qmk_firmware/tree/xap/data/xap)
[Current XAP Generated Docs](https://github.com/qmk/qmk_firmware/blob/xap/docs/xap_protocol.md)
[Placeholder PR](https://github.com/qmk/qmk_firmware/pull/13733)

## Description

**Any work in this area needs to be discussed with QMK Collaborators first, and in this case primarily with @tzarc due to their prior work in this area.**

Initial HID endpoint has been implemented for LUFA on the `xap` branch. Need to implement equivalent functionality for ChibiOS, VUSB, perhaps others given the state of their implementations.

**Comment by zvecr** [comment]
As of 70c9905cb647c345b7d8dda479c1c16f6776b1b5, VUSV and ChibiOS should be up to the same state as LUFA.
