### ISSUE TITLE
Tracking issue for YMDK organization

### ISSUE THREAD

**Issue by peepeetee** [qmk/qmk_firmware#15639]
Here, I will track my attempt to move known YMDK boards into the YMDK folder, picking up the broken pieces of #12177

## Boards to move
 - [x] YD60MQ
 - [x] YMD75
 - [x] YMD96
 - [x] YMD_NP21
 - [x] Melody96

## Related Development
* #12177

## Progress
* #15641
* #15643
* #15645
* #15647
* #15680

**Comment by peepeetee** [comment]
@ennation

**Comment by vinorodrigues** [comment]
Don't forget the **Melody96**
