### ISSUE TITLE
Tracking issue for IDOBAO organization

### ISSUE THREAD

**Issue by peepeetee** [qmk/qmk_firmware#15658]
Here, I will track organization of IDOBAO boards into a vendor folder, picking up the broken pieces of #14369 and #14468

## Boards to move
 - [x] idobo
 - [x] ID67
 - [x] ID80
 - [x] ID87
 - [x] Montex

## Related Development
* #14468
* #14369

## Progress
* #15661
* #15662
* #15665
* #15992
* #15667
* #15668

**Comment by vinorodrigues** [comment]
See #15558 affecting the `id67` folder.  This PR is attempting to move from RGB Lighting (usually used for backlighting) to RGB Matrix (usually used for keycap effects).
