### ISSUE TITLE
Chained OSM

### ISSUE THREAD

**Issue by jaksco** [qmk/qmk_firmware#1580]
I'd like to be able to tap OSM_ctrl, then tap OSM_shift, then tap kc_n and get CtrlShiftN if done within ONESHOT_TIMEOUT. I believe what's happening right now is when I tap OSM_ctrl and then OSM_shift it applies ctrl to shift which isn't as helpful and probably not intended by the user

**Comment by nooges** [comment]
Duplicate of https://github.com/qmk/qmk_firmware/issues/856

**Comment by drashna** [comment]
For same reason (very hard to implement), closing. 

If needed, reopen or open new issue.
