### ISSUE TITLE
WKL versions of community layouts

### ISSUE THREAD

**Issue by Wraul** [qmk/qmk_firmware#15950]
Is there a reason that there doesn't exist default community layouts for WKL version of keyboards? I might be missing something but I have looked and I can't find any other explanation than that nobody have bothered creating them.

There exists a few boards that uses layouts named `LAYOUT_tkl_ansi_wkl` and `LAYOUT_tkl_iso_wkl`. I ran into trouble when I tried to create a personal layout for those boards, with `make` showing the following error `Claims to support a community layout that does not exist: tkl_ansi_wkl`

If I were to create a PR with default mappings for those layouts, is this something that would get accepted?

**Comment by tzarc** [comment]
> If I were to create a PR with default mappings for those layouts, is this something that would get accepted?

I see no reason why they wouldn't.
