### ISSUE TITLE
When using a USB-USB with a CODE keyboard, the backlights flash whenever a layer key is pressed.

### ISSUE THREAD

**Issue by BalzGuenat** [qmk/qmk_firmware#1602]
This is with the Pro Micro variant of the converter. Not sure if it exists with other variants.

By "flash", I mean they turn off for a split second before turning on again. Happens on both key press and release.

Unsure what would cause this behavior of the CODE. It doesn't use a driver to manage the backlight, only on-keyboard controls.

If it's not something in the code, I suspect a sudden voltage drop because the chip has to do more work for layer switching. Would need an oscilloscope to measure. Alternatively, hook up power supply for keyboard separately from converter.

**Comment by BalzGuenat** [comment]
Could not get separate power supply to work at all. Keystrokes do not reach PC. Unsure why. Will look at code next.

**Comment by drashna** [comment]
Were you able to get this resolved?

**Comment by BalzGuenat** [comment]
@drashna Sadly no. I also sold the CODE so I'm unable to explore this further.
