### ISSUE TITLE
Readme Links Incorrect

### ISSUE THREAD

**Issue by ryanmaclean** [qmk/qmk_firmware#1605]
The readme clobber introduced two links that do not work: 

* https://docs.qmk.fm/build_environment_setup.html

* https://docs.qmk.fm/make_instructions.html

Happy to update the links for boards I'm working on, just need to know where they should now point. 

It may also be worth fixing them all 😂

**Comment by jackhumbert** [comment]
Ah, big oversight there! I added some redirects to Gitbook for those - thanks!

**Comment by ryanmaclean** [comment]
Yep no problem! Just crossing the Ts and dotting the Is on the changes.
