### ISSUE TITLE
[Bug] AUDIO_CLICKY tuneables cause random lockups on Preonic

### ISSUE THREAD

**Issue by era1112** [qmk/qmk_firmware#16105]
## Describe the Bug

- After tuning parameters for the faux-clicky mode, using the instructions in [/docs/feature_audio.md](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_audio.md#audio-click), Preonic locks up and becomes unresponsive after a short period of use.
- Keyboard becomes completely non-responsive, but RGB LEDs do stay on.
- Lockup happens randomly 30 seconds to 3 min after startup, although typing fast sometimes brings it on immediately.
- Unplugging and replugging the keyboard clears the lockup.

**Code details (all in config.h):**

Enabling clicky mode on it's own (ie, with default parameters) is stable.

```
#define AUDIO_CLICKY            
``` 

Problem presents when making reasonable adjustments to the parameters that the guide says are tuneable. This is one example of settings that cause the lockups:
	
```
// Clicky mode parameter deviations
#define AUDIO_CLICKY_FREQ_MIN 		65.0f     	// Default 65
#define AUDIO_CLICKY_FREQ_DEFAULT 	800.0f   	// Default 440
#define AUDIO_CLICKY_FREQ_MAX 		1500.0f 	// Default 1500
#define AUDIO_CLICKY_FREQ_FACTOR	1.18921f	// Default 1.18921
#define AUDIO_CLICKY_FREQ_RANDOMNESS	1.0f   		// Default 0.05, guide suggests 1.0 for an interesting effect
#define AUDIO_CLICKY_DELAY_DURATION 	1    		// Default 1
```

You can inspect my code [on my dev_branch](https://github.com/era1112/qmk_firmware/tree/dev_branch/keyboards/preonic/keymaps/era1112). There are a lot of other features enabled in that keymap, but the problem is the same if I start with the default firmware and only add clicky mode.

## Possible steps to remediate

- Add a note in the documentation in [/docs/feature_audio.md](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_audio.md#audio-click). Specifically, add a warning to the table of options that making deviations can lead to keyboard lockups.
- Someone with deeper knowledge of QMK than me could investigate what these settings are doing behind the scenes that puts the keyboard into a lockup.

## System Information

 - Keyboard:  OLKB Preonic
   - Revision (if applicable): rev3_drop 
 - Operating system: win10, win11 (many different computers)
 - AVR GCC version: 8.4.0
 - ARM GCC version: 10.1.0
 - QMK Firmware version: 0.15.17
 - Any keyboard related software installed? No

**Comment by drashna** [comment]
Is a known issue: https://github.com/qmk/qmk_firmware/issues/12080
