### ISSUE TITLE
[QUESTION] What C mode style is used for editing keymaps

### ISSUE THREAD

**Issue by mcp292** [qmk/qmk_firmware#16258]
I am using (spac)emacs and would like to be able to set the `c-mode` style with `c-set-style`. 

Is there actually a supported style used or is it just convention to make everything fit on the screen?

Is this documented anywhere?

**Comment by tzarc** [comment]
You'll probably be best off inferring from:
https://github.com/qmk/qmk_firmware/blob/master/.editorconfig
https://github.com/qmk/qmk_firmware/blob/master/.clang-format

**Comment by mcp292** [comment]
Thank you for the links.

I settled on using `text-mode` as a workaround. This prevents most of the re-alignment that happens when editing keycodes in `c-mode`.

**Comment by mcp292** [comment]
I will close this issue for now, but if anyone has better suggestions please add them here.
