### ISSUE TITLE
QMK支持光轴吗？和普通机械轴通用吗？Does QMK support optical axis? Is it common with ordinary mechanical shafts?

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#16439]
QMK支持光轴吗？和普通机械轴通用吗？

Does QMK support optical axis? Is it common with ordinary mechanical shafts?

**Comment by peepeetee** [comment]
https://github.com/qmk/qmk_firmware/pull/16340

**Comment by 7-liang** [comment]
光轴只和你的硬件有关，和 qmk 无关，你做好矩阵后，同样可以使用，问题就是光轴那两个光感小元件哪里能买到呢？拆机？
