### ISSUE TITLE
[Bug] kinesis/kint41 firmware does not successfully compile

### ISSUE THREAD

**Issue by negatv** [qmk/qmk_firmware#16440]
### Describe the Bug

Firmware for kinesis/kint41 does not currently successfully compile using the configurator.   

I have pulled latest code from master and was able to build locally.

```
Compiling: keyboards/kinesis/kinesis.c                                                             In file included from ./lib/chibios/os/common/ports/ARMCMx/chcore.h:70:0,
                 from ./lib/chibios/os/rt/include/ch.h:112,
                 from ./lib/chibios/os/hal/osal/rt-nil/osal.h:32,
                 from ./lib/chibios/os/hal/include/hal.h:28,
                 from tmk_core/common/chibios/platform_deps.h:18,
                 from quantum/quantum.h:18,
                 from keyboards/kinesis/kint41/kint41.h:19,
                 from keyboards/kinesis/kinesis.h:20,
                 from keyboards/kinesis/kinesis.c:1:
./lib/chibios-contrib/os/common/startup/ARMCMx/devices/MIMXRT1062/cmparams.h:70:24: fatal error: MIMXRT1062.h: No such file or directory
 #include "MIMXRT1062.h"
                        ^
compilation terminated.
 
make: *** kconfig41/keyboards/kinesis/kinesis.o] Error 1
```

**Comment by stapelberg** [comment]
> @stapelberg what was the reason for adding this, and is there a way to eliminate the need for it?

For older NXP controllers, ChibiOS uses its own USB low-level driver.

However, NXP switched to an entirely different IP for USB 2.0 in their newer controllers (used in Teensy 4.x), which works in an entirely different way.

Updating the ChibiOS driver to the new IP is way too much work — I spent weeks trying, unsuccessfully.
Hence, we ended up using the well-tested NXP USB SDK in ChibiOS instead to get reliable USB support.

So, the mcux-sdk is absolutely required and I don’t see any way to get rid of it.
