### ISSUE TITLE
QMK Configurator web site can't use keymap UI

### ISSUE THREAD

**Issue by tatsujin2006** [qmk/qmk_firmware#16500]
QMK Configurator web site can't use keymap UI

![图片](https://user-images.githubusercontent.com/7369435/156488783-78e8a125-4a88-4660-af6a-5daea4de069c.png)

**Comment by fauxpark** [comment]
Duplicate of https://github.com/qmk/qmk_configurator/issues/1093

**Comment by tatsujin2006** [comment]
thanks
