### ISSUE TITLE
[Bug] Cannot compile preonic/rev3_drop on LAYOUT_preonic_1x2uC

### ISSUE THREAD

**Issue by xmjaj** [qmk/qmk_firmware#16515]
It seems that I cannot successfully bake a new firmware using LAYOUT_preonic_1x2uC. QMK configurator gives out this error message:

> ☒ Invalid JSON keymap: /qmk_compiler/qmk_firmware/preonic-rev3_drop-preonic-3.json : 'LAYOUT_preonic_1x2uC' is not valid under any of the given schemas

I uploaded a .json file that I was able to compile a few weeks back and wanted to add a few keys to one of my layers. But after compiling, I get the error message above. Here is the .json file contents:

> {
  "version": 1,
  "notes": "",
  "documentation": "\"This file is a QMK Configurator export. You can import this at <https://config.qmk.fm>. It can also be used directly with QMK's source code.\n\nTo setup your QMK environment check out the tutorial: <https://docs.qmk.fm/#/newbs>\n\nYou can convert this file to a keymap.c using this command: `qmk json2c {keymap}`\n\nYou can compile this keymap using this command: `qmk compile {keymap}`\"\n",
  "keyboard": "preonic/rev3_drop",
  "keymap": "preonic-3",
  "layout": "LAYOUT_preonic_1x2uC",
  "layers": [
    [
      "KC_1",
      "KC_2",
      "KC_3",
      "KC_4",
      "KC_5",
      "KC_6",
      "KC_7",
      "KC_8",
      "KC_9",
      "KC_0",
      "KC_MINS",
      "KC_EQL",
      "KC_TAB",
      "KC_Q",
      "KC_W",
      "KC_E",
      "KC_R",
      "KC_T",
      "KC_Y",
      "KC_U",
      "KC_I",
      "KC_O",
      "KC_P",
      "KC_BSPC",
      "LT(1,KC_ESC)",
      "KC_A",
      "KC_S",
      "KC_D",
      "KC_F",
      "KC_G",
      "KC_H",
      "KC_J",
      "KC_K",
      "KC_L",
      "KC_QUOT",
      "KC_ENT",
      "KC_LSFT",
      "KC_Z",
      "KC_X",
      "KC_C",
      "KC_V",
      "KC_B",
      "KC_N",
      "KC_M",
      "KC_COMM",
      "KC_DOT",
      "KC_SLSH",
      "KC_RSFT",
      "KC_LCTL",
      "MO(3)",
      "KC_LGUI",
      "KC_LALT",
      "MO(2)",
      "KC_SPC",
      "MO(1)",
      "KC_LEFT",
      "KC_UP",
      "KC_DOWN",
      "KC_RGHT"
    ],
    [
      "KC_F1",
      "KC_F2",
      "KC_F3",
      "KC_F4",
      "KC_F5",
      "KC_F6",
      "KC_F7",
      "KC_F8",
      "KC_F9",
      "KC_F10",
      "KC_F11",
      "KC_F12",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_DEL",
      "KC_CAPS",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_MPRV",
      "KC_MPLY",
      "KC_MNXT",
      "KC_NO",
      "KC_BSLS",
      "KC_TRNS",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_MUTE",
      "KC_VOLD",
      "KC_VOLU",
      "KC_NO",
      "KC_TRNS",
      "KC_TRNS",
      "KC_NO",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO"
    ],
    [
      "KC_GRV",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_UP",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_P7",
      "KC_P8",
      "KC_P9",
      "KC_LBRC",
      "KC_RBRC",
      "KC_NO",
      "KC_LEFT",
      "KC_DOWN",
      "KC_RGHT",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_P4",
      "KC_P5",
      "KC_P6",
      "KC_SCLN",
      "KC_ENT",
      "KC_TRNS",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_P1",
      "KC_P2",
      "KC_P3",
      "KC_PSLS",
      "KC_TRNS",
      "KC_TRNS",
      "KC_NO",
      "KC_NO",
      "KC_TRNS",
      "KC_TRNS",
      "KC_SPC",
      "KC_P0",
      "KC_NO",
      "KC_PDOT",
      "KC_NO",
      "KC_NO"
    ],
    [
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "BL_TOGG",
      "BL_STEP",
      "BL_BRTG",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_PSCR",
      "KC_NO",
      "KC_NO",
      "RGB_MOD",
      "RGB_SPI",
      "RGB_SPD",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "RGB_HUI",
      "RGB_VAI",
      "RGB_VAD",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_UP",
      "KC_NO",
      "KC_NO",
      "KC_TRNS",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_NO",
      "KC_LEFT",
      "KC_DOWN",
      "KC_RGHT"
    ]
  ],
  "author": ""
}

**Comment by Erovia** [comment]
A fix (#16520) has been merged for this. It might take some time for it to reach Configurator, but I've tested your keymap and it builds fine locally now.
