### ISSUE TITLE
Endgame failing to compile

### ISSUE THREAD

**Issue by C4RP3N0CT3M** [qmk/qmk_firmware#16535]
QMK fails to compile the "Endgame" keyboard keymap with the following error (see screenshot):

![Endgame_Compile_Error](https://user-images.githubusercontent.com/58274597/156895190-7e9fd040-1750-4206-92db-50b84690416c.png)

**Comment by waffle87** [comment]
Looks like that function was renamed to `rgb_matrix_indicators_advanced_kb` as per [#12097](https://github.com/qmk/qmk_firmware/pull/12097)

**Comment by zvecr** [comment]
https://github.com/qmk/qmk_firmware/pull/14746 contains a fix.

**Comment by rshutt** [comment]
> #14746 contains a fix.

Yes but I have been unable to get my PR merged for various reasons...  :(
