### ISSUE TITLE
redox_w firmware broke with switch to UART

### ISSUE THREAD

**Issue by achatham** [qmk/qmk_firmware#16553]
I could no longer produce a working firmware via configurator, while it worked before. I've built maually and verified that it broke between 0.15.25 (works) and 0.16 (does not work), and head also doesn't work. I've tried git bisect but must not be doing it right yet. I'll keep searching to try to figure out the cause.

The bad firmware flashes successfully but no keypresses register.

**Comment by achatham** [comment]
Confirmed it's from c12268807d8622a05dc445e6101a575eae16860d, which changed UART. I'm on windows 11 and the receiver being flashed has a USB-C connection.

**Comment by achatham** [comment]
Based on the variables, I'm guessing this is about USB-C and not redox_w. But I'm at my limit of being able to debug the next step, as I'm not too familiar with serial comms.

**Comment by drashna** [comment]
@fauxpark any insight?

**Comment by tomaszj** [comment]
I can confirm this — compiling firmware on `0.15.25` works as expected. 

`0.16.9` tag and `master` branch locally are broken, whether compiled on a MacBook Air or via Docker — I have tried both routes.

Using firmware from QMK Configurator suffers from the exact same issue.

Note that I can get keys fine **after** erasing EEPROM and then flashing. Keys stop being sent after a single reset.

cc @mattdibi

**Comment by danielmitchell** [comment]
I'm also experiencing this issue and have been unable to update my firmware using QMK Configurator since the issue was introduced. Thanks for addressing the issue since my layout is causing RSI and needs to be updated. Hoping this can be fixed soon.

**Comment by achatham** [comment]
I'm curious what the common thread is. Do others experiencing this have a
usb-c connection? A redox-w?

**Comment by danielmitchell** [comment]
Yes, I'm using a usb-c connection with a redox-w

**Comment by mffseal** [comment]
I have the same problem.

**Comment by tomaszj** [comment]
The fix is now in `master` @achatham @danielmitchell @mffseal
