### ISSUE TITLE
[Feature Request] Multifunction key(3 in 1) request + full single symbol key

### ISSUE THREAD

**Issue by tzdhbo21** [qmk/qmk_firmware#16587]
Hi
1. add multifunction keys in layer switching or other sections. 
2. add full single symbol keys in the Shifted Symbols section. For example , . / ; \ are all stay in single and separate with < > ? : and | 

## Feature Request Type

- [Y ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description
I am building a 34 split keyboard and having some ideas on layer switching. I'm thinking are there any possibilities in coding that can create a function key which allows me to tap, hold, and tap 2-3 times, and even combing with other function keys while hold at the same time to active function. 
For the symbols, I'm thinking of building a layer that is full of symbols, which requests each symbol key represents one symbol only. Now, in the Shifted Symbols section, there are shifted symbols can stay alone. 
Thank you

**Comment by drashna** [comment]
Tap Dances is probably what you're looking for.
