### ISSUE TITLE
TM680 Single Mode Lock issue

### ISSUE THREAD

**Issue by Frosty680** [qmk/qmk_firmware#16582]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Hi,
Idk if this is the right website to submit, but can I request a new firmware for TM680 Single Mode, it has a bug or issue that it will lock your keyboard, you cannot use win and fn key and the knob and side LED is stuck to color purple/violet.
I hope you can help me if this is the right page.

Thank you :)

**Comment by zvecr** [comment]
Sorry but this is not a QMK supported keyboard.

**Comment by Frosty680** [comment]
Alright, thank you.

**Comment by bintuananh1107** [comment]
> Alright, thank you.

can you help me, my keyboard is the same as yours

**Comment by bintuananh1107** [comment]
> Alright, thank you.

email me , bintuananh@gmail.com
