### ISSUE TITLE
[Bug] Making crkbd/rev1 with keymap default oversize

### ISSUE THREAD

**Issue by geedmo** [qmk/qmk_firmware#16631]
On windows 10 with QMK Toolbox

Cloned QMK Firmware 0.14.29

After run `qmk compile -kb crkbd/rev1 -km default -e RGB_MATRIX_ENABLE=yes`

It outputs 

```
QMK Firmware 0.14.29
Making crkbd/rev1 with keymap default

avr-gcc.exe (GCC) 8.4.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text    data     bss     dec     hex filename
      0   28698       0   28698    701a .build/crkbd_rev1_default.hex

Copying crkbd_rev1_default.hex to qmk_firmware folder                                               [OK]
Checking file size of crkbd_rev1_default.hex
 * The firmware is too large! 28698/28672 (26 bytes over)
 [ERRORS]

make[1]: *** [tmk_core/rules.mk:473: check-size] Error 1
Make finished with errors
make: *** [Makefile:510: crkbd/rev1:default] Error 1```

**Comment by zvecr** [comment]
`qmk compile -kb crkbd/rev1 -km default -e RGB_MATRIX_ENABLE=yes -e RGBLIGHT_ENABLE=no`

Outputs
` * The firmware size is fine - 24626/28672 (85%, 4046 bytes free)`

**Comment by geedmo** [comment]
Thanks. Did not notice and I thought it would not be necessary since `RGBLIGHT_ENABLE=no` is  already declared in rules.mk

**Comment by zvecr** [comment]
https://github.com/qmk/qmk_firmware/blob/7fde30979986732433126d50911efdef928c2b64/keyboards/crkbd/keymaps/default/rules.mk#L2
