### ISSUE TITLE
RESET vs QK_BOOT?

### ISSUE THREAD

**Issue by mcp292** [qmk/qmk_firmware#16648]
There seems to be two documented ways to put the keyboard in bootloader mode:
1. [`RESET`](https://docs.qmk.fm/#/ref_functions?id=resetting-the-keyboard).
2. [`QK_BOOT`](https://docs.qmk.fm/#/quantum_keycodes?id=qmk-keycodes).

Which is best practice and what are the differences?

Similarly, `EEP_RST` vs `EE_CLR`?

**Comment by KarlK90** [comment]
`QK_BOOT` or `QK_BOOTLOADER` is the recommended way. Same is true for `EE_CLR`.

**Comment by mcp292** [comment]
Thank you. Is this documented somewhere that I missed?

**Comment by mcp292** [comment]
Ah, okay thanks!

@fauxpark based on my experience with these changes, do you think it worthwhile to document these as the new standard and remove [the keycodes they replace in the documentation](https://docs.qmk.fm/#/ref_functions?id=resetting-the-keyboard) with a note.

**Comment by fauxpark** [comment]
Not sure how I missed those in the above PR... I know Configurator also needs to be updated to recognise these new names.

**Comment by mcp292** [comment]
Okay great!
