### ISSUE TITLE
Spanish <> keycap not found on firmware. 

### ISSUE THREAD

**Issue by Sharker** [qmk/qmk_firmware#1667]
Hi, 

i see a new kbd75 keyboard and cannot find a key for spanish layout  <> , 

i use KC_COMM & KM_DOT with and without left shift and don' t mapped this key

I see that extra con quantum but don't see this key also. 

https://github.com/qmk/qmk_firmware/blob/master/quantum/keymap_extras/keymap_spanish.h

**Comment by skullydazed** [comment]
The key you're looking for is `KC_NUBS`, which is the "non-us backslash." It looks like that has been mapped to `ES_LESS` per that file.

**Comment by Sharker** [comment]
Thx @skullydazed it's this key :)
