### ISSUE TITLE
qmk更新后现在特殊是废了了嘛？After the qmk update, is it special now that it is abolished?

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#16730]
编译出来不能用了，以前都正常的，不知道何时更新qmk后编译出来的就不能正常触发了
It can't be used after compiling. It used to be normal. I don't know when to update the qmk and it will not trigger normally.
![image](https://user-images.githubusercontent.com/5648129/160050311-777af8cf-1baf-4eb1-ac4a-2e0d00ec5319.png)
这种重复使用IO脚的矩阵阵亡了？？
This matrix that reuses IO pins is dead? ?

**Comment by tzarc** [comment]
English, please.

**Comment by elfmimi** [comment]
Is it related to this issue? https://github.com/qmk/qmk_firmware/issues/14359

**Comment by jeromeli002** [comment]
> Is it related to this issue? #14359

yes， but this matrix do not work in new code
