### ISSUE TITLE
Keypresses When Board Is Plugged In

### ISSUE THREAD

**Issue by zachfedor** [qmk/qmk_firmware#1678]
I have a Let's Split flashed with [this layout](https://github.com/zachfedor/qmk_firmware/tree/master/keyboards/lets_split/keymaps/zach). When I plug my keyboard into my laptop, it registers a few keypresses:

```
down: Ctrl + A
up: Ctrl
up: A
down: Tab    // this 4 key combo repeats 2 more times
down: Q
down: R
down: T
up: Tab
up: Q
up: R
up: T
```

Does anyone know what might cause this? Or is there someway to delay keypresses for a certain duration to avoid the bug?

**Comment by jackhumbert** [comment]
Do you have your right side or left side plugged into the computer? I wonder if this is something with the logic that makes the sides talk to each other, since they all come from the left side.

**Comment by zachfedor** [comment]
I have the right side plugged in. There was some issues with the left side as master (in more detail [here](https://github.com/nicinabox/lets-split-guide/issues/12)), so I had to do some overrides and force right hand as master. That's an interesting thought though, I hadn't made that connection.

**Comment by drashna** [comment]
The Ctrl A is odd, but the rest looks like it's in the same row.   Could be the logic, but could be an issue with the row (a short somewhere, or a cold joint maybe).

Either way, were you able to resolve this?
