### ISSUE TITLE
[Bug] After the WS2812 is powered on, the first light is always on green

### ISSUE THREAD

**Issue by biuboom-jun** [qmk/qmk_firmware#16867]
Describe the Bug
WS2812上电后第一个灯一直亮绿色，重新打开和关闭RGB效果后恢复正常
After the WS2812 is powered on, the first light is always on green, and it returns to normal after re-opening and closing the RGB effect

System Information
Keyboard:
Revision (if applicable):
Operating system:win10 20h2
Main control model: STM32F401RCT6
QMK Firmware version:0.13.34
Any keyboard related software installed?
 AutoHotKey
 Karabiner
[1 ] Other:VIA

**Comment by Timception** [comment]
I am also getting this using rgb matrix. hopefully we get an answer.

**Comment by gezhaoyou** [comment]
同样遇到这个问题，解决了吗

**Comment by biuboom-jun** [comment]
改用pwm控制就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qmk/qmk_firmware"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 中午11:01
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [qmk/qmk_firmware] [Bug] After the WS2812 is powered on, the first light is always on green (Issue #16867)





 
同样遇到这个问题，解决了吗

**Comment by HorrorTroll** [comment]
If u use WS2812 at bitbang wiring, there a way bypass this issue by adding this code on <keyboard.c> file.
```
#ifdef RGB_MATRIX_ENABLE
bool process_record_kb(uint16_t keycode, keyrecord_t *record) {
        case RGB_TOG:
            if (record->event.pressed) {
                switch (rgb_matrix_get_flags()) {
                    case LED_FLAG_ALL: {
                        rgb_matrix_set_flags(LED_FLAG_NONE);
                        rgb_matrix_set_color_all(0, 0, 0);
                    }
                    break;
                    default: {
                        rgb_matrix_set_flags(LED_FLAG_ALL);
                        rgb_matrix_enable_noeeprom();
                    }
                    break;
                }
            }
            return false;
    }
    return process_record_user(keycode, record);
}

Another way is just use GPIO support PWM control.

**Comment by gezhaoyou** [comment]
> 求教：pwd方式对芯片接RGB灯的引脚有具体要求吗？还是只要在 rules.mk 中指定 `WS2812_DRIVER = pwm`就可以

**Comment by gezhaoyou** [comment]
求教：pwd方式对芯片接RGB灯的引脚有具体要求吗？还是只要在 rules.mk 中指定 WS2812_DRIVER = pwm就可以呢 @biuboom-jun

**Comment by ganjianggaoshaoze** [comment]
我用的主控是apm32f072 ，pwm操纵rgb灯光但他还是一直亮绿灯啊
