### ISSUE TITLE
I want to add new keyboard. but it is not available. Can you help me? Thank you

### ISSUE THREAD

**Issue by SEAN-JOU** [qmk/qmk_firmware#16894]
Pushing to https://github.com/qmk/qmk_firmware.git
remote: Permission to qmk/qmk_firmware.git denied to SEAN-JOU.
fatal: unable to access 'https://github.com/qmk/qmk_firmware.git/': The requested URL returned error: 403

**Comment by zvecr** [comment]
You need to submit a `Pull Request`.

<https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request>
<https://opensource.com/article/19/7/create-pull-request-github>
<https://docs.qmk.fm/#/contributing?id=how-do-i-make-a-contribution>

**Comment by SEAN-JOU** [comment]
I finished the pulling request.why I still haven’t successful
