### ISSUE TITLE
[Bug] i can't flash qmk firmware to stm32f103c6t6a

### ISSUE THREAD

**Issue by izbj** [qmk/qmk_firmware#16908]
Opening DFU capable USB device...
Device ID 1eaf:0003
Device DFU version 0110
Claiming USB DFU Interface...
Setting Alternate Interface #2 ...
Determining device status...
DFU state(5) = dfuDNLOAD-IDLE, status(0) = No error condition is present
Aborting previous incomplete transfer
Determining device status...
DFU state(2) = dfuIDLE, status(0) = No error condition is present
DFU mode device DFU version 0110
Device returned transfer size 1024
Copying data from PC to DFU device
Download	[=========================] 100%        21192 bytes
Download done.
DFU state(8) = dfuMANIFEST-WAIT-RESET, status(0) = No error condition is present
Resetting USB to switch back to runtime mode
error resetting after download (LIBUSB_ERROR_TIMEOUT)
Done!
gmake[1]: *** [platforms/chibios/flash.mk:98: flash] Error 74
gmake: *** [Makefile:413: stm32test:default:flash] Error 1
Make finished with errors

it always has a error when i flash qmk firmware to stm32f103c6t6a 

the stm32duino bootloader was flashed in stm32f103c6t6a alread

**Comment by izbj** [comment]
i am M1 mac 
i don't know if it about M1

**Comment by zvecr** [comment]
```
Download [=========================] 100% 21192 bytes
Download done.
DFU state(8) = dfuMANIFEST-WAIT-RESET, status(0) = No error condition is present
Resetting USB to switch back to runtime mode
error resetting after download (LIBUSB_ERROR_TIMEOUT)
Done!
gmake[1]: *** [platforms/chibios/flash.mk:98: flash] Error 74
```
Flash was successful, however its likely you have not applied the additional changes listed in #15297.

**Comment by izbj** [comment]
> ```
> Download [=========================] 100% 21192 bytes
> Download done.
> DFU state(8) = dfuMANIFEST-WAIT-RESET, status(0) = No error condition is present
> ```
> 
> Flash was successful, however its likely you have not applied the additional changes listed in #15297.

i also have a error that “./lib/chibios/os/hal/ports/STM32/LLD/USBv1/hal_usb_lld.h:127:2: error: #error "USB not present in the selected device"
127 | #error "USB not present in the selected device"”

i saw #15297 the error was fixed from https://github.com/qmk/ChibiOS/pull/1

**Comment by izbj** [comment]
> ```
> Download [=========================] 100% 21192 bytes
> Download done.
> DFU state(8) = dfuMANIFEST-WAIT-RESET, status(0) = No error condition is present
> ```
> 
> Flash was successful, however its likely you have not applied the additional changes listed in #15297.

i also have a error that “./lib/chibios/os/hal/ports/STM32/LLD/USBv1/hal_usb_lld.h:127:2: error: #error "USB not present in the selected device"
127 | #error "USB not present in the selected device"”

i saw https://github.com/qmk/qmk_firmware/issues/15297 the bug was fixed from https://github.com/qmk/ChibiOS/pull/1

**Comment by sigprof** [comment]
Can you test the STM32F103C6 support code from #17853?

Note that you need to use at least `board.h` and the bootloader-related section of `rules.mk` from the `handwired/onekey/bluepill_f103c6` keyboard in your custom code, because the bootloader parameters also specify `MCU_LDSCRIPT = STM32F103x6_stm32duino_bootloader`. Also use `EEPROM_DRIVER = transient` for now, because the proper firmware size check which takes the EEPROM backing store into account is not implemented yet, and with only 24 KiB of flash available for QMK it would be easy to get the backing store overlapping the firmware code.

**Comment by zvecr** [comment]
Closing as #17853 added tested examples.
