### ISSUE TITLE
I can't add a new keyboard item in the dropdown but i have pulled the project and added the updated item

### ISSUE THREAD

**Issue by SEAN-JOU** [qmk/qmk_firmware#16911]
I have pulled the project and added the updated item
https://github.com/qmk/qmk_firmware/pull/16907

<img width="761" alt="截圖 2022-04-22 上午9 11 31" src="https://user-images.githubusercontent.com/25901493/164577110-a10f48c6-9a0e-47d7-9ce8-6a07514495f1.png">

**Comment by zvecr** [comment]
https://github.com/qmk/qmk_firmware/pull/16907 has to be merged (after it has been reviewed) before it will appear in that list.

Basically the previously mentioned on qmk_configurator/issues/1110.

**Comment by SEAN-JOU** [comment]
Thank your answer. When it will be reviewed?
