### ISSUE TITLE
A Question: is marco parameter opt not available?

### ISSUE THREAD

**Issue by hiro2016** [qmk/qmk_firmware#1693]
I have tried to set the value of `action func.opt` in  `void process_action(keyrecord_t *record, action_t action)` by using the following macro to pass it to the action_get_macro function.  But the bits I set are being deleted by `clear_weak_mods();`.

     #define MWP(macro_id, four_bit_param)  (QK_MACRO | four_bit_param<<8 | macro_id)

`action_get_macro` 

        case 2:
          // With this defined, `MWP(2,3)` should set the effective layer to 3.
          if(record->event.pressed){
            layer_state = 1 << (opt & 0xf);
            print_val_bin16(opt);//prints 00...
          }
        break;

The line that is deleting macro parameter bits at action.func.opt in `void process_action(keyrecord_t *record, action_t action)`:

            clear_weak_mods();

Workround:

        uint8_t opt = action.func.opt;
        if (event.pressed) {
            // clear the potential weak mods left by previously pressed keys
            clear_weak_mods();
        }

Then:  

         action_macro_play(action_get_macro(record, action.func.id, opt));

Am I doing it right or is opt cleared without saved for a reason?  
I personally want access to macro param as hard coding everything in macro seems stupid. And thought it is a nice place to start hacking qmk before jumping into the wilder sections of code.

**Comment by drashna** [comment]
I believe weak mods get cleared with the next key press).

As for the rest, I'm not sure.
