### ISSUE TITLE
[Bug] Teensy LC Ez-maker Direct Pin will not flash (HEX PARSE ERROR LINE 3)

### ISSUE THREAD

**Issue by Xecuted-Toast** [qmk/qmk_firmware#16986]
I cannot get QMK Configurator to make a hex file (it creates a .bin). I am unable to open and review the .bin file. 
When trying to flash the Teensy LC with the .bin file i get from compile. I get this error. "HEX PARSE ERROR LINE 3"

[Screen Shot 2022-05-01 at 9.30.06 PM.pdf](https://github.com/qmk/qmk_firmware/files/8600526/Screen.Shot.2022-05-01.at.9.30.06.PM.pdf)

Any help is greatly appreciated!

## System Information

handwired TarTarus pro RAzer with choc switches
[IMG_1106.pdf](https://github.com/qmk/qmk_firmware/files/8600539/IMG_1106.pdf)

**Comment by fauxpark** [comment]
This would be partially fixed by https://github.com/qmk/qmk_firmware/pull/14420 - it sets `FIRMWARE_FORMAT = hex` for all of the ARM Teensys. However you will still not be able to flash it in the Toolbox at it only has MCU values for AVR parts.

For now, you will have to manually add the above line to your rules.mk, and use the Teensy Loader GUI to flash.

**Comment by Xecuted-Toast** [comment]
When I open teensyduino I am unable to bring the .bin file into it. Is the teenysduino the Teensy Loader GUI? When attempting with the traditional teensy loader the program key is greyed out when the .bin file is selected. Is there a video tutorial that could assist me? I am feeling like a bit of a noob with the software end of things. I still feel a bit lost?

**Comment by fauxpark** [comment]
No, you need a .hex file.

**Comment by Xecuted-Toast** [comment]
so I added the line 108 to 111 on the builddefs/bootloader.mk to make the LC teensy changes 
"# Teensy LC, 3.0, 3.1/2, 3.5, 3.6
    ifneq (,$(filter $(MCU_ORIG), MKL26Z64 MK20DX128 MK20DX256 MK64FX512 MK66FX1M0))
        FIRMWARE_FORMAT = hex
    endif"
but how do I get a hex file, I have no way to alter the way QMK configurator runs and makes a .bin; sorry I am still a bit lost?

**Comment by fauxpark** [comment]
You won't be able to do this in the Configurator; you need to compile it yourself.

**Comment by Xecuted-Toast** [comment]
when picking a layout to compile for .hex with MSYS2 can I use a .Json made with configurator? And I do not attempt to flash with qmk toolbox, but need to try teensy flasher or qmk flash directly with MSYS2?

**Comment by Xecuted-Toast** [comment]
![photo error](https://user-images.githubusercontent.com/104745344/166844781-f73bf5bb-cba3-40e6-aefe-67c39ea850d6.jpg)
So now I am getting : <qmk.exe compile: error: argument -kb/--keyboard: invalid keyboard_folder value: 'ez_maker/directpins/teensy_lc'>

I am not sure why this is happening in MSYS264bit?

**Comment by fauxpark** [comment]
Does that folder exist?

**Comment by Xecuted-Toast** [comment]
yes qmk_firmware/keyboards/ez_maker/directpins/teensy_lc

**Comment by fauxpark** [comment]
Have you modified it in some way? What's the output of `git status` from your `qmk_firmware` folder?

**Comment by Xecuted-Toast** [comment]
do I need to set up git to get it to work? I have not forked yet

**Comment by Xecuted-Toast** [comment]
no modifications yet

**Comment by fauxpark** [comment]
Did you download the zip file from Github then? That's not going to work. You need to follow the newbs guide in the docs.

**Comment by Xecuted-Toast** [comment]
I downloaded zip from github and changed rules.mk like we talked about for .hex within the teensy_lc folder. I went through newbs section

**Comment by fauxpark** [comment]
I did not tell you to download the zip.

**Comment by Xecuted-Toast** [comment]
Yes I am pretty terrible at this and following directions.  I deleted everything, forked with git. Then updated folder and still get the same qmk.exe compile error?

**Comment by Xecuted-Toast** [comment]
![Untitled](https://user-images.githubusercontent.com/104745344/166850079-b7b29c12-5042-4268-9c9d-d9c4d774a92c.png)

**Comment by Xecuted-Toast** [comment]
![Untitled](https://user-images.githubusercontent.com/104745344/166850207-372e0399-bd0e-46c7-83b9-f7650ba45ae4.jpg)

**Comment by fauxpark** [comment]
Please post the output of `qmk doctor`.

**Comment by Xecuted-Toast** [comment]
![Untitled](https://user-images.githubusercontent.com/104745344/167041021-c8889606-1c50-41df-8854-ec4fcac69828.png)
Thank you for all your help! I am learning but still having trouble when I hit a bump

**Comment by fauxpark** [comment]
So that's claiming there are modifications, what is the output of `git status` as well?

**Comment by Xecuted-Toast** [comment]
![Untitled](https://user-images.githubusercontent.com/104745344/167059322-d6ac8036-8709-4ae2-808f-cd70219e3ffe.jpg)

 //So I did add the line "FIRMWARE_FORMAT = hex "
//"rules.mk":
# MCU name
USE_CHIBIOS_CONTRIB = yes
FIRMWARE_FORMAT = hex 
# Enter lower-power sleep mode when on the ChibiOS idle thread
OPT_DEFS += -DCORTEX_ENABLE_WFI_IDLE=TRUE

**Comment by Xecuted-Toast** [comment]
it appears to have compiled hex! will give update tomorrow :)

**Comment by Xecuted-Toast** [comment]
IT WORKS! You helped me sooo much! Thank you !!!!!!
