### ISSUE TITLE
KLE (keyboard-layout-editor.com) code generation from keymap.c

### ISSUE THREAD

**Issue by mnesarco** [qmk/qmk_firmware#17004]
I have published a KLE generator for keymaps. It is based on my previous generator for KMonad. It is a simple python script that parse layers and some comments in your keymap file and generates the code required for visualization in KLE.

![example_output](https://user-images.githubusercontent.com/1087317/166833508-13e6de1f-34c4-47dc-a90d-21d71e1b8904.png)

I know that everyone is moving to VIA now to create keymaps, but this can be useful for someone who wants to go in the opposite direction.

Here is the code: https://github.com/mnesarco/qmk_kle

**Comment by tzarc** [comment]
Nice.

> I know that everyone is moving to VIA now to create keymaps

Not really, VIA is all but dead at this point. There's just no simple viable (heh) alternative... yet.
