### ISSUE TITLE
LT variant suporting premature LT key release and LT down tap release cycle.

### ISSUE THREAD

**Issue by hiro2016** [qmk/qmk_firmware#1709]
I liked LT but it was too slow for me, so I wrote what I needed.    
https://github.com/hiro2016/ergodox_gui_configurator/blob/master/README_DLT.md  
  
Noticeable bugs are removed and while code is still not optimized, it's good enough for use and testing.  
I would like to hear opinions from others about whether or not DLT is worth included in qmk.

**Comment by drashna** [comment]
LT's speed is determined by TAPPING_TERM, so it can be sped up. 

Also, there are a number of config.h settings that can influence its behavior.
https://docs.qmk.fm/config_options.html

**Comment by fredizzimo** [comment]
`LT` currently lacks some control compared to the `MT` for example. This will hopefully be fixed very soon, and after that you should be able to control it to get the behaviour you want.

**Comment by hiro2016** [comment]
Thanks for the comments.  
I have tested some ideas and gave up writing them as action codes long time ago, so closing this issue.
  
>LT's speed is determined by TAPPING_TERM, so it can be sped up.  

Yes, but I feel a single TAPPING_TERM for all keys is wrong. TAPPING_TERM right for `E` key is wrong for `F` key and having to make sure LT key is held down while other keys are tapped does not contributes to a comfortable typing experience. Now I have given up on my DLT idea as an action code.      
  
In the end I wrote code that more or less:  
+ can be called from custom function or macro; so a variable that serves as tapping_term can be set there.  
+ toggles on buffering/filtering of all user inputs at key down time  
+ evaluates user inputs and decide what to do at key release time  
    
Since a combo input function of a similar design which I wrote later is working fine, the design is functional I believe;DLT itself has been abandoned for a long time now.

**Comment by fredizzimo** [comment]
Another change that I'm planning for tapping keys, is to provide custom settings, like `TAPPING_TERM` for every key separately. So once that's implemented, it will hopefully be enough for your needs, or at least one step closer.

**Comment by hiro2016** [comment]
@fredizzimo  
>Another change that I'm planning for tapping keys, is to provide custom settings, like TAPPING_TERM for every key separately. So once that's implemented, it will hopefully be enough for your needs, or at least one step closer.    

Wow, that truly is an improvement.     
But I must warn you that:  
+ Most people don't know the right tapping term for each finger, so they may not be able to fine tune them.  
+ without an option to disable LT etc for the same keyboard half, with TAPPING_TERM  set to a fairly low value, roll over typing becomes difficult.    
+ Apart from Index finger home low keys like `F` and `J`, other fingers/keys require relatively high and similar TAPPING_TERMs, so the usefulness of the option might be limited.  
  

#### Low LT TAPPING_TERM even for a single key and roll over typing don't get along quite well.    
My case, learning not to do roll over with F and J was not hard at all; especially with my custom LT function disabled for the same keyboard half. But casual users would likely to refuse changing their typing habit, so introducing variable TAPPING_TERM for each key would mean only reducing LT threshold time by like 30ms for some keys by factory default;still a rather noticeable difference though.   
  
#### In the end, combo input might be better than LT  
Faster smoother typing experience for LT is capped by the habit of rolling over. From the keyboard side, detecting whether the user is requesting for LT action performed or just rolling over is hard to tell when TAPPING_TERM is set low.     
  
On the other hand, combo inputs always have a very detectable signature; two keys presses within a 50ms interval almost never happens when I'm typing normally.     
   

Having said all the above, enthusiasts like myself would love variable TAPPING_TERM for each column/key as it makes using LT a lot more comfortable.
