### ISSUE TITLE
rgblight.c - Bug in Swirl function

### ISSUE THREAD

**Issue by jay-c88** [qmk/qmk_firmware#1713]
the swirl animation function

`void rgblight_effect_rainbow_swirl(uint8_t interval)`

in rgblight.c is currently using the constant

`RGBLED_RAINBOW_MOOD_INTERVALS`

instead of

`RGBLED_RAINBOW_SWIRL_INTERVALS`

I dont have the means to do a pull request right now, if someone would be so kind and fix it.

Thanks

edit: line 492

**Comment by skullydazed** [comment]
Fixed by @Khord
