### ISSUE TITLE
[Feature Request] add a new bootloader support of stm32f103?

### ISSUE THREAD

**Issue by zhaqian12** [qmk/qmk_firmware#17197]
Add a new bootloader option of stm32f103.(UF2)

## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description
Stm32duino is the default bootloader for QMK STM32F103,but because it would wait before entering the app, so its experience was not good.I found an open source bootloader project [uf2-stm32f103](https://github.com/zhaqian12/uf2-stm32f103).After testing, I think it works well so far.It takes up 16 kB of flash.So,is it necessary to add an option for this bootloader?If yes,maybe I can make a contribution.

**Comment by drashna** [comment]
Most likely, this would need a new ld script for the controller, and probably a new board folder, for the different config. 

You can look at the blackpill uf2 support to see how to add that, I think.

**Comment by zvecr** [comment]
#19594
