### ISSUE TITLE
[Bug] Shifted Keys are Not Shifted When Used with a Modifier

### ISSUE THREAD

**Issue by ChristianBingman** [qmk/qmk_firmware#17251]
## Describe the Bug
When using a modifier such as LGUI_T() and a shifted character KC_QUES (LGUI_T(KC_QUES)). Only the unshifted character is used. (KC_SLSH)

## System Information

**Keyboard:** Ferris Sweep Low Profile
**Revision (if applicable):** 
**Operating system:** Mac OS
**`qmk doctor` output:** 
```
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.0.0
Ψ QMK home: /Users/christianbingman/qmk_firmware
Ψ Detected macOS 12.3.1.
Ψ Git branch: master
Ψ Repo version: 0.15.21
⚠ Git has unstashed/uncommitted changes.
Ψ CLI installed in virtualenv.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 8.3.1
Ψ Found avr-gcc version 8.4.0
Ψ Found avrdude version 6.4
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ QMK is ready to go, but minor problems were found
```

**Any keyboard related software installed?** 
 - [ ] AutoHotKey (Windows)
 - [ ] Karabiner (macOS)
 - [ ] Other: Amethyst

## Additional Context

Description should be clear, but I can explain anything in more detail if needed.

**Comment by amrsoll** [comment]
See #11512
