### ISSUE TITLE
[Bug] ChibiOS SPI problems, requires upgrade.

### ISSUE THREAD

**Issue by tzarc** [qmk/qmk_firmware#17285]
## Describe the Bug

SPI usages in ChibiOS when the MCU is set to the 21.11.1 "SPIv2...v2" driver seem to be broken.
In some cases the fix was to swap to SPI mode 3.

This will require a bugfix of ChibiOS -- their devs assisted in diagnosis and will be producing a fix as part of 21.11.2, coming in the next week or two.

Refer #17262 #17263 to known affected peripherals -- also affects Djinn but that's not in the repo. May have an effect on SPI EEPROM.

**Comment by tzarc** [comment]
Once mitigation is in place, need to rollback the aforementioned PRs.

**Comment by drashna** [comment]
This is fixed now?
