### ISSUE TITLE
Being able to Address RGB Lighting from USB or BT[Feature Request] 

### ISSUE THREAD

**Issue by RobertoBiundo** [qmk/qmk_firmware#17299]
There should be a way of changing the values of the RGB Matrix (color and brightness) by sending a USB package to the keyboard. This feature is present (but proprietary) in other existing keyboards.

## Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

## Description

Since the keyboards support both USB and Bluetooth connectivity it should be possible to send messages to them to affect heir current configuration.

Basically a program running on a computer could build a USB or bluetooth package with a specific payload and send it to the keyboard in order to change its current configuration.
This would allow software to sync they keyboard with other devices such as mouse, rgb strips, etc. But also to change the RGB on each key based on (for example) the program that is currently in foreground as well as providing feedback on current hardware states (for example, turning on a specific key RED if the CPU of the computer is running hot, or you are running out of battery on a laptop)

**Comment by drashna** [comment]
Long term, that's the goal that QMK XAP hopes to solve.
