### ISSUE TITLE
Incorrect keyboard information

### ISSUE THREAD

**Issue by developomp** [qmk/qmk_firmware#17309]
The information for the [mode/m75h](https://github.com/qmk/qmk_firmware/tree/master/keyboards/mode/m75h/) keyboard does not seem to be the right one.
The page is supposed to contain information about the [sonnet](https://modedesigns.com/products/sonnet/) keyboard ([qmk config](https://config.qmk.fm/#/mode/m75h/LAYOUT_all/)), but it has information about the [Mode SixtyFive M65S](https://modedesigns.com/products/sixtyfive) keynboard ([qmk config page](https://config.qmk.fm/#/mode/m65s/LAYOUT_all)).

**Comment by filterpaper** [comment]
@developomp It is probably a copy-paste error and the linked PR should resolve this.
