### ISSUE TITLE
Problems found in the MAC system

### ISSUE THREAD

**Issue by EasonQian1** [qmk/qmk_firmware#17303]
Entering sleep mode under MAC system will automatically wake up the trigger button.what caused it? It works normally under the windows, only under the MAC, it will automatically wake up and trigger the button. 
https://github.com/qmk/qmk_firmware/tree/master/keyboards/eason/capsule65

qmk doctor
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.0
Ψ QMK home: C:/Users/Administrator/qmk_firmware
Ψ Detected Windows 10 (10.0.19041).
Ψ Git branch: master
Ψ Repo version: 0.16.9
⚠ Git has unstashed/uncommitted changes.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.1.0
Ψ Found avr-gcc version 8.4.0
Ψ Found avrdude version 6.4
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ QMK is ready to go, but minor problems were found

**Comment by mechmerlin** [comment]
Zsolid and Sesame from ClickClack reached out to me to check this out. 

I just flashed my Capsule 65 with both the via and default firmware files and tested it on my M1 and Intel macOS machines.
I am unable to reproduce this with QMK I updated just a few minutes ago. 

M1 is running Monterey 12.4
Intel is running 10.15.7

This is the output of my QMK Doctor

Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.0
Ψ QMK home: /Users/mechmerlin/dev/qmk_firmware
Ψ Detected macOS 12.4.
Ψ Git branch: master
Ψ Repo version: 0.17.0
Ψ CLI installed in virtualenv.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 8.3.1
Ψ Found avr-gcc version 8.4.0
Ψ Found avrdude version 7.0
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ QMK is ready to go

**Comment by EasonQian1** [comment]
Thanks, maybe it is caused by the peripheral power supply of mcu

**Comment by EasonQian1** [comment]
![1654447795982](https://user-images.githubusercontent.com/98533237/172061365-2db53e16-b521-4035-aeca-e8eb09928fec.jpg)

**Comment by EasonQian1** [comment]
> Zsolid and Sesame from ClickClack reached out to me to check this out.
> 
> I just flashed my Capsule 65 with both the via and default firmware files and tested it on my M1 and Intel macOS machines. I am unable to reproduce this with QMK I updated just a few minutes ago.
> 
> My Capsule 65 is connected to my laptop directly thru Apple USB C to C cable.
> 
> I am testing this by going to the Apple logo on the top left and selecting sleep and watching what happens. Keyboard is not triggering random key press to exit sleep mode. I am able to exit sleep mode by manually pressing a random key.
> 
> M1 is running Monterey 12.4 Intel is running 10.15.7
> 
> This is the output of my QMK Doctor
> 
> Ψ QMK Doctor is checking your environment. Ψ CLI version: 1.1.0 Ψ QMK home: /Users/mechmerlin/dev/qmk_firmware Ψ Detected macOS 12.4. Ψ Git branch: master Ψ Repo version: 0.17.0 Ψ CLI installed in virtualenv. Ψ All dependencies are installed. Ψ Found arm-none-eabi-gcc version 8.3.1 Ψ Found avr-gcc version 8.4.0 Ψ Found avrdude version 7.0 Ψ Found dfu-util version 0.11 Ψ Found dfu-programmer version 0.7.2 Ψ Submodules are up to date. Ψ QMK is ready to go

I compiled with angle 17.0 and still have this problem.Could it be caused by the peripheral circuit of the MCU?please help me check
