### ISSUE TITLE
After the update, the previous keyboard could not be compiled normally

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#17325]
After the update, the previous keyboard could not be compiled normally. It could be compiled before, but the following error appeared after the update. Changing the name of other keyboard folders that can be compiled normally will also cause this error, what else do I need to modify? ?

![image](https://user-images.githubusercontent.com/5648129/172285057-08362c9b-600a-468c-b26a-4aa2c01082e6.png)

**Comment by waffle87** [comment]
The `keyboard.c/h` file names need to match the name of the keyboard directory.
