### ISSUE TITLE
I encountered a problem while generating the firmware. I want to know how to solve it

### ISSUE THREAD

**Issue by 1219008126** [qmk/qmk_firmware#17410]
Compiling: keyboards/Gorilla/Gorilla.c                                                             In file included from quantum/rgb_matrix/rgb_matrix.h:23,
                 from quantum/quantum.h:36,
                 from keyboards/Gorilla/Gorilla.h:6,
                 from keyboards/Gorilla/Gorilla.c:1:
quantum/rgb_matrix/rgb_matrix_types.h:81:23: error: 'DRIVER_LED_TOTAL' undeclared here (not in a function)
     led_point_t point[DRIVER_LED_TOTAL];
                       ^~~~~~~~~~~~~~~~
 [ERRORS]
 |
 |
 |
make[1]: *** [tmk_core/rules.mk:443：.build/obj_Gorilla_via/keyboards/Gorilla/Gorilla.o] error 1
Make finished with errors
make: *** [Makefile:510：Gorilla:via] error 1

**Comment by tzarc** [comment]
Add `#define DRIVER_LED_TOTAL ???` to your `config.h` with the number of LEDs.

**Comment by 1219008126** [comment]
thx
