### ISSUE TITLE
[XAP] First boot initialisation

### ISSUE THREAD

**Issue by zvecr** [qmk/qmk_firmware#17455]
## XAP Task Info

[Original Issue](https://github.com/qmk/qmk_firmware/issues/11567)
[Original spec document](https://hackmd.io/hhjooQ6UQhWV3MvTlbQiqQ)
[Current XAP Definitions](https://github.com/qmk/qmk_firmware/tree/xap/data/xap)
[Current XAP Generated Docs](https://github.com/qmk/qmk_firmware/blob/xap/docs/xap_protocol.md)
[Placeholder PR](https://github.com/qmk/qmk_firmware/pull/13733)

## Description

**Any work in this area needs to be discussed with QMK Collaborators first.**

Bind eeprom reset logic so that dynamic keymap is populated.
* reset condition?
  * enabled features?
* via -> stores date to detect "significant" firmware change
* xap version?
* introduce version for dynamic keymap format?

**Comment by tzarc** [comment]
Maybe now with the introspection capabilities, we can use a CRC over the keymap and encodermap and use that instead of the date?
