### ISSUE TITLE
[Feature Request] CH572 chip based keyboard support

### ISSUE THREAD

**Issue by pospanet** [qmk/qmk_firmware#17474]
Hi there,
there is very popular 3 to 12 keys keyboard like [this](https://www.walmart.com/ip/USB-Mini-12-Key-Gaming-Keyboard-Programmable-Keys-with-2-Knobs-Custom-Shortcuts-White/793527197), yet you can find it on AliExpress for very reasonable price as well. Is it possible to add support for this keyboard, please? It is based on [WCH CH572 chip](https://w.electrodragon.com/w/WCH_Chips). Chip spec [here](https://www.cnx-software.com/2019/02/16/wch-ch572-risc-v-mcu-bluetooth-le/). Thanks

**Comment by zvecr** [comment]
`one-time-programmable` + `QMK` isnt really going to go anywhere so im going to close this as `wont fix`.
