### ISSUE TITLE
[Feature Request] CH579M chip based keyboard support

### ISSUE THREAD

**Issue by ryanm101** [qmk/qmk_firmware#17477]
Is it likely that support for [mini keyboard](https://www.aliexpress.com/item/1005004231035046.html?spm=a2g0o.order_list.0.0.598b1802MpHjLq) Could be added?  [Bluetooth Version](https://www.aliexpress.com/item/1005004232999410.html?spm=a2g0o.detail.100009.4.11c3a85du1luTy)
datasheet here:
[CH579M.pdf](https://github.com/qmk/qmk_firmware/files/8985300/CH579M.pdf)

**Comment by tzarc** [comment]
You'd need to upstream the MCU support into https://github.com/ChibiOS/ChibiOS-Contrib first.

**Comment by ryanm101** [comment]
in progress https://github.com/ChibiOS/ChibiOS-Contrib/pull/437

**Comment by ryanm101** [comment]
More progress https://github.com/qmk/qmk_firmware/pull/26097
