### ISSUE TITLE
[Bug] Some keys deactivate the CAPS WORD mode

### ISSUE THREAD

**Issue by mug-3-n** [qmk/qmk_firmware#17574]
## Describe the Bug

Hi,

First of all, thank you for your excellent work.

I am having some problems with the new CAPS WORD feature.
There are some keys on my keyboard that reset CAPS WORD mode to lower case. 

These keys are "w, ç, ê, g, h, f, n, m, z".

Actual result -> "\<CAPS WORD on\>BÉPOnbépo"
Expected result -> "\<CAPS WORD on\>BÉPONBÉPO"

## System Information

**Keyboard:** Planck EZ Glow
**Revision (if applicable):** A
**Operating system:** Ubuntu 22.04
**`qmk doctor` output:** 
```
$ qmk doctor
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.0
Ψ QMK home: /home/####/qmk_firmware
Ψ Detected Linux.
Ψ Git branch: master
Ψ Repo version: 0.17.5
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.3.1
Ψ Found avr-gcc version 5.4.0
Ψ Found avrdude version 6.3-20171130
Ψ Found dfu-util version 0.9
Ψ Found dfu-programmer version 0.6.1
Ψ Submodules are up to date.
Ψ QMK is ready to go
```

**Any keyboard related software installed?** 
 - [ ] AutoHotKey (Windows)
 - [ ] Karabiner (macOS)
 - [x] Other: Wally EZ flash tool

## Additional Context

The keyboard was flashed from Oryx website -> https://configure.zsa.io/planck-ez

My keymap -> https://configure.zsa.io/planck-ez/layouts/55Wge/latest/0

**Comment by filterpaper** [comment]
The default function that 'continues' caps word covers just the basic keycodes:
https://github.com/qmk/qmk_firmware/blob/master/quantum/process_keycode/process_caps_word.c#L154-L157

For other languages that uses keycodes not covered by that function, you'll need to implement your own `caps_word_press_user` function in your `keymap.c` to add keycodes that 'continues' caps word:
https://docs.qmk.fm/#/feature_caps_word?id=configure-which-keys-are-word-breaking
