### ISSUE TITLE
[Bug] - Caps word in spanish layout

### ISSUE THREAD

**Issue by naudor** [qmk/qmk_firmware#17587]
Caps word deactivate when I press underscore key in spanish layout

I'm not sure about it's a bug maybe i'm doing something wrong but when I pressed the underscore key caps words deactivate and with this behavior it's completly useless for me. I reviewed the code, but the process_caps_word have this key like exception. May be the proble it's because i have spanish layout. I tried to change the behavior of my key to send the underscore in english but without luck.
I tried to change the code of the procces_caps_code to include the keymaps in spanish and force to make a exception but no luck too.

It's my fault or there are some problems with diferents layouts?

Thanks.

## System Information

**Keyboard:** Moonlander MK I
**Revision (if applicable):** 
**Operating system:** Windows 10
**`qmk doctor` output:** 
```
 qmk doctor
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.0
Ψ QMK home: C:/Users/Naudor/qmk_firmware
Ψ Detected Windows 10 (10.0.19041).
Ψ Git branch: firmware21
Ψ Repo version: 0.17.0
⚠ Git has unstashed/uncommitted changes.
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.1.0
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 6.4
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ QMK is ready to go, but minor problems were found
```

**Any keyboard related software installed?** 
 - [ ] AutoHotKey (Windows)
 - [ ] Karabiner (macOS)
 - [ ] Other:

**Comment by mug-3-n** [comment]
Hi all,

Same problem with a "fr bépo" keymap, the underscore disables the CAPS WORD mod.
In my case, it’s not the only key that triggers this behaviour, see #17574 for more details.

**Comment by filterpaper** [comment]
Try implementing `caps_word_press_user` to add the underscore keycode from the Spanish language:
https://docs.qmk.fm/#/feature_caps_word?id=configure-which-keys-are-word-breaking

**Comment by naudor** [comment]
Yes, now works. Thanks very much @filterpaper ;-)

P.D: I promise read twice the "facking manual" before :-$
