### ISSUE TITLE
Where is the Default Layout?

### ISSUE THREAD

**Issue by nickmcsimpson360** [qmk/qmk_firmware#1764]
I used to have the default layout of the Preonic Keyboard bookmarked so I can quickly reference where a key is if I am not sure (Blank keycaps). I am currently unable to find this document anymore, has it been changed or moved?

-A link to the default key bindings/mappings like the old doc would be great.

**Comment by jackhumbert** [comment]
The default keymap for each keyboard is located at `/keyboards/<keyboard>/keymaps/default`, so the one for the Preonic is [here](https://github.com/qmk/qmk_firmware/blob/master/keyboards/preonic/keymaps/default/keymap.c) :)
