### ISSUE TITLE
BDN9 rev2: RGB lighting code at keyboard level can interfere with keymap-level code

### ISSUE THREAD

**Issue by aidalgol** [qmk/qmk_firmware#17691]
In the keyboard-level `.c` file for the [BDN9 rev2](https://github.com/qmk/qmk_firmware/blob/master/keyboards/keebio/bdn9/rev2/rev2.c), `eeconfig_init_kb` calls `rgblight_*` functions to set up RGB lights if the feature is enabled in the `rules.mk` file (`RGBLIGHT_ENABLE`).  This clashes with any keymap that tries to use `rgblight_*_noeeprom` functions.  I had to comment out this function for [my keymap](https://github.com/aidalgol/qmk_firmware/blob/bdn9-rev2-fkeypad/keyboards/keebio/bdn9/keymaps/fkeypad/keymap.c) that uses the underglow to indicate the active layer.

Putting `BOOTMAGIC_ENABLE = no` in the keymap's `rules.mk` may also work, but only as long as the keymap does not need to use EEPROM.  Setting up RGB lighting seems to me that it should be the responsibility of the keymaps.  Or maybe a `config.h` flag that compiles out this function would be more appropriate?

**Comment by zvecr** [comment]
Few things here that are conceptually wrong,

* Its perfectly fine for `eeconfig_init_kb`  to configure state, as long as it calls `eeconfig_init_user` last
  * Users should implement `eeconfig_init_user` calling non `_noeeprom` functions if they want a different default state
* `BOOTMAGIC_ENABLE` does not enable/disable use of eeprom
  * `eeconfig_init_kb` will still run, regardless of `BOOTMAGIC_ENABLE` state.

It could be refactored now the various `STARTUP` options exist, but that shouldnt change the interaction with `keyboard_post_init_user`.
