### ISSUE TITLE
[Bug] Boardsource/Beiwagon keymap displayed wrong

### ISSUE THREAD

**Issue by AzGoalie** [qmk/qmk_firmware#17756]
### Describe the Bug

The Boardsource/Beiwagon keymap is displayed as a 3x3 when the keyboard is a 4x3
It seems to correctly load the layout, as it loads the 2 layers each with 12 keys, and just a graphical issue with the configurator.

What is displayed in the configurator currently:
![image](https://user-images.githubusercontent.com/3059429/180584614-b59bfd56-c184-4571-a5a6-c2c6b9d942d8.png)

What the keyboard looks like:
![image](https://user-images.githubusercontent.com/3059429/180584653-73c1913a-617a-478d-8854-a69eab6114a0.png)

**Comment by yanfali** [comment]
@0x6A73@pm.me looks like your commit b99ccd4f064e15c7ea94184986e396603bfa1dc2 needs some love.

**Comment by waffle87** [comment]
oops, that's my bad. thanks @noroadsleft!
