### ISSUE TITLE
Is there any OLED example of stm32 mcu, I have no idea to use smt32f401 to drive OLED

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#17838]
Is there any OLED example of stm32 mcu, I have no idea to use smt32f401 to drive OLED

**Comment by waffle87** [comment]
See [keyboards/handwired/onekey/blackpill_f401](https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/onekey/blackpill_f401) & [I2C Driver Doc](https://docs.qmk.fm/#/i2c_driver?id=arm-configuration)

**Comment by drashna** [comment]
Also, my tractyl manuform uses sh1107 oled (i2c). 

Namely, you need to enable the i2c peripherial, and set config, if needed.
