### ISSUE TITLE
RGB_ constants block RGB_VAD and RGB_VAI

### ISSUE THREAD

**Issue by max3-2** [qmk/qmk_firmware#17946]
Hi,

I am using a HSV_ORANGE and other color constants for setup and lighting layers, like so

in _config.h_
`#define RGBLIGHT_STARTUP_MODE	HSV_ORANGE`

or in _keymap.c_ following the layer lighting tutorial
```
const rgblight_segment_t PROGMEM my_win_fn_layer[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 8, HSV_CYAN}
);
```

This works very good with the single exception that after the call to a `HSV_` constant any following `RGB_VAI` or  `RGB_VAD` seem to have no effect.

Is this a bug? Is there a way to get both working? I have no issues setting the HSVs myself but I cant seem to find a good funtion that works in `RGBLIGHT_LAYER_SEGMENTS(...);`

*UPDATE*
So I think I worked out that this is because lighting layers are prioritized and HSV obviously contains a _value_. I can unroll this in the layer settings and then have a variable there. But - Since the layers are in _PROGMEM_ - any good advice to create a custom keycode that changes these placeholders?

**Comment by drashna** [comment]
Do you mean that you want to change the HSV value later on?

**Comment by max3-2** [comment]
Yes, I want to change the value (e.g. brightness) as one would do using RGB_VAD and RGB_VAI but thats blocked by the layer settings.

**Comment by drashna** [comment]
I think you want `#define RGBLIGHT_LAYERS_RETAIN_VAL` then.  That looks to use the boards current val, rather than the hard set one.

**Comment by max3-2** [comment]
Yes, perfect, thank you. I just skipped that little part in the documentation no idea why. Thanks!
