### ISSUE TITLE
The layer cannot exceed 17 layers. If the layer exceeds 17 layers, some layer functions will have errors.

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#17960]
The layer cannot exceed 17 layers. If the layer exceeds 17 layers, some layer functions will have errors. For example, when qmk has 20 layers, when TO (0) is set, the output is TO (16). Is this a qmk problem or a vial problem?

**Comment by tzarc** [comment]
Is this still a problem when you add `#define LAYER_STATE_32BIT` to `config.h`?

**Comment by jeromeli002** [comment]
> Is this still a problem when you add `#define LAYER_STATE_32BIT` to `config.h`?

OK, thank you

**Comment by jeromeli002** [comment]
> Is this still a problem when you add `#define LAYER_STATE_32BIT` to `config.h`?

Invalid, still the same situation,

**Comment by zvecr** [comment]
<https://github.com/qmk/qmk_firmware/blob/master/quantum/quantum_keycodes.h#L792>

> 16 layers max

Not a problem, its by design.

**Comment by zvecr** [comment]
17989
