### ISSUE TITLE
Is the link to the RGB Matrix Subsystem in the RGB matrix doc page broken?

### ISSUE THREAD

**Issue by pitommasi** [qmk/qmk_firmware#17965]
I'm referring to this page:
https://github.com/qmk/qmk_firmware/blob/master/docs/feature_rgb_matrix.md
 
in the first paragraph it says:
"If you want to use RGB LED's you should use the [RGB Matrix Subsystem](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_rgb_matrix.md) instead."

as you can see, the link points to the same page, where I can't find any reference to thuis RGB Matrix subsystem...
Bear with me, I'm new to QMK so maybe I am the problem...

**Comment by waffle87** [comment]
Unsure where you're seeing that. The current doc in master points to the LED matrix page.
> If you want to use single color LED's you should use the [LED Matrix Subsystem](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_led_matrix.md) instead.

**Comment by drashna** [comment]
May be a caching issue from an older revision?  Hard refreshing may fix the issue.

**Comment by zvecr** [comment]
.md files are fine
