### ISSUE TITLE
Can QMK make RGB follow music changes?

### ISSUE THREAD

**Issue by aihk** [qmk/qmk_firmware#18023]
Can QMK make RGB follow music changes?

**Comment by waffle87** [comment]
Not without implementing code to do so in QMK, and creating a [Raw HID](https://docs.qmk.fm/#/feature_rawhid) application to run on the host and send necessary data to the keyboard. I believe [OpenRGB](https://openrgb.org/) and their [QMK fork](https://github.com/Kasper24/QMK-OpenRGB) has this already implemented. But questions regarding OpenRGB and their fork should be taken to their [Discord server](https://discord.com/invite/AQwjJPY).
