### ISSUE TITLE
Add QMK/VIA Support for the Kegen G-Boy

### ISSUE THREAD

**Issue by mattchan** [qmk/qmk_firmware#18047]
The Kegen G-Boy firmware is almost non-existent. A cursory search on the Kegen Discord server yields a single JSON file that can be loaded in kbfirmware.com, which can produce QMK source files that look somewhat outdated.

To date, there has been no update from the group buy runners for the Kegen G-Boy. Shortly after Round 2 of the Kegen G-Boy boards were delivered, the group buy runners disappeared and have completely abandoned the Discord server.

**Comment by zvecr** [comment]
Fixed by https://github.com/qmk/qmk_firmware/pull/18048
