### ISSUE TITLE
Deprecated file references in Teensy_LC_Onekey

### ISSUE THREAD

**Issue by okaa** [qmk/qmk_firmware#1811]
In /keyboards/chibios_test/teensy_lc_onekey in the files Makefile.3.0 and Makefile.3.2 TMK_DIR is "../../tmk_core" but should be "../../../tmk_core" and the includes at the bottom have to be:
include $(TMK_DIR)/common.mk
include $(TMK_DIR)/chibios.mk

(instead of:
include $(TMK_DIR)/tool/chibios/common.mk
include $(TMK_DIR)/tool/chibios/chibios.mk)

Also /keyboards/chibios_test/teensy_lc_onekey/instructions.md references the path /keyboards/teensy_lc_onekey which obviously has been moved to /keyboards/chibios_test/teensy_lc_onekey.

Are these observations correct or am I mixing up files here?

**Comment by drashna** [comment]
are these actual `Makefile`'s? 
If so, they've been deprecated, in favor of `rules.mk`.  
And I think that this has been fixed/addressed already.

If not, please reopen or open a new issue.
