### ISSUE TITLE
[Bug] KBDFans75RGB

### ISSUE THREAD

**Issue by wildfingers2000** [qmk/qmk_firmware#18135]
### Describe the Bug

Visual Keymap layout is bugged - all other formats are fine except for this one. It *is* functional, but difficult to navigate. 

### Additional Context?

![image](https://user-images.githubusercontent.com/111713243/185817061-9d37bab4-c54f-4907-be98-ea306570383b.png)

**Comment by fauxpark** [comment]
Fixed by #18391
