### ISSUE TITLE
[Bug] hid_bootloader_cli is missing after "qmk setup"

### ISSUE THREAD

**Issue by osamuaoki** [qmk/qmk_firmware#18134]
"qmk setup" doesn't support hid_bootloader_cli  any more.
 * installed executable name has been changed but Makefile still call hid_bootloader_cli
 * new installed executable doesn't accept options for at90usb1286  (Lufa version still work)
 * This is probably regression due to the remote code "qmk setup" fetches.

## Describe the Bug

New fresh install of qmk doesn't create `hid_bootloader_cli` in `/usr/local/bin`.  I see bootloaderHID there now.

Moreover, it is not just name change.  I tried it by crating symlink to make Makefile to call bootloaderHID.  No luck.  It complains my use of at90usb1286 (This should be accepted)

```
$ make VERBOSE=1 --jobs=1 cgc56:pico:flash
...
Checking file size of cgc56_pico.hex                                                                [OK]
 * The firmware size is fine - 30026/126976 (23%, 96950 bytes free)
true && 	hid_bootloader_cli -mmcu=at90usb1286 -w -v .build/cgc56_pico.hex
error opening -mmcu=at90usb1286: No such file or directory
make[1]: *** [platforms/avr/flash.mk:185: flash] Error 1
if [ -f .build/error_occurred ]; then printf "\033[31;01mMake finished with errors\n\033[0m" & exit 1; fi;
Make finished with errors
make: *** [Makefile:414: cgc56:pico:flash] Error 1
Checking file size of cgc56_pico.hex                                                                [OK]
 * The firmware size is fine - 30026/126976 (23%, 96950 bytes free)
true && 	hid_bootloader_cli -mmcu=at90usb1286 -w -v .build/cgc56_pico.hex
error opening -mmcu=at90usb1286: No such file or directory
make[1]: *** [platforms/avr/flash.mk:185: flash] Error 1
if [ -f .build/error_occurred ]; then printf "\033[31;01mMake finished with errors\n\033[0m" & exit 1; fi;
Make finished with errors
make: *** [Makefile:414: cgc56:pico:flash] Error 1
```
I can compile standard Lufa source in submodule to `hid_bootloader_cli` and it is usable with qmk if I installed it.

So some regression happened qmk version of HID bootloader host program.  It is not just file name change problem.

## System Information
Keyboad is not published one but essentially teensy2++ based board.
I am on Debian

**Comment by zvecr** [comment]
`hid_bootloader_cli` has never been universally installed as part of the toolchain setup. However it is potentially installed under msys2. `bootloaderHID` is a completely different tool, the assumption that something has been renamed is incorrect. This would not be classified as a regression.

**Comment by sigprof** [comment]
> Keyboad is not published one but essentially teensy2++ based board.

Then you should use `handwired/onekey/teensy_2pp` as an example; `rules.mk` for that board is:
```makefile
# MCU name
MCU = at90usb1286

# Bootloader selection
BOOTLOADER = halfkay
```
And `platforms/avr/flash.mk` would use either `teensy-loader-cli` or `teensy_loader_cli` (depending on which is found in `$PATH`) for the `halfkay` bootloader, not `hid_bootloader_cli` (although `hid_bootloader_cli` is a fork of `teensy_loader_cli` and supports those Teensy boards too). The availability of prebuilt `teensy_loader_cli` binaries/packages may be better than `hid_bootloader_cli`, so if you are using a real Teensy++ 2.0 board, you should set `BOOTLOADER = halfkay`.

`hid_bootloader_cli` would be used for `BOOTLOADER = qmk-hid` (if that bootloader is used, `teensy_loader_cli` won't work, because `lufa-hid` and `qmk-hid` use a different VID:PID pair).

**Comment by osamuaoki** [comment]
Hi,  thanks for the reply

I should have been a bit more precise.  I have teensy 2++circuit compatible board
with LUFA's firmware installed by myself with Atmel's generic VID:PID.  Thus, I set
 `rules.mk`as:

```
# MCU name
MCU = at90usb1286

# Bootloader selection
BOOTLOADER = qmk-hid
```

Anyway, last time I introduced qmk, I thought qmk automatically installed its own
hid_bootloader_cli binary.  But as I see installer script, my memory is wrong.  (Only
msys has support for it.)

I suppose whoever bothers to compile mcu guest side of bootloader we expect him to
compile pc host side of code.

I guess someone need to package it for Debian.  hahaha....
