### ISSUE TITLE
[Feature Request] Support for Keychron V1

### ISSUE THREAD

**Issue by detrophy** [qmk/qmk_firmware#18155]
## Feature Request Type

- [x] Hardware support

## Description
Is it possible to get support for the Keychron V1 with ANSI & ISO layout?

Information from keychron of chips inside:
Ultra-low-power Arm Cortex-M4 32-bit 
STM32L432 (128KB Flash)

Keychron site of the [keyboard](https://www.keychron.com/products/keychron-v1-qmk-via-custom-mechanical-keyboard)

**Comment by waffle87** [comment]
Looks like there's support for it in [Keychron's fork](https://github.com/Keychron/qmk_firmware/tree/playground/keyboards/keychron/v1). There's already support for its MCU in upstream QMK, it's just up to them to open a PR for it if they'd like.
