### ISSUE TITLE
How to momentarily activate a layer with the right modifiers?

### ISSUE THREAD

**Issue by grumagargler** [qmk/qmk_firmware#18221]
Hi,
when I use LM(MyLayer, MOD_RCTL) the layer is activated with the left control, not the right one.
I tried to play with #define LAYER_STATE_8BIT in my config.h, alas, nothing works.

## System Information

**Keyboard**: Cantor (42-keys split) keyboard.
**Operating system**: Linux Mint 20.3 Cinnamon
`qmk doctor` output:

```
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.0.0
Ψ QMK home: /home/dmitry/qmk_firmware
Ψ Detected Linux.
Ψ Git branch: master
Ψ Repo version: 0.17.0
⚠ The official repository does not seem to be configured as git remote "upstream".
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 9.2.1
Ψ Found avr-gcc version 5.4.0
Ψ Found avrdude version 6.3-20171130
Ψ Found dfu-util version 0.9
Ψ Found dfu-programmer version 0.6.1
Ψ Submodules are up to date.
Ψ QMK is ready to go, but minor problems were found

```

**Comment by precondition** [comment]
You can checkout my PR for right hand modifier support in LM: https://github.com/qmk/qmk_firmware/pull/13085
