### ISSUE TITLE
Bluepill flashing issue 

### ISSUE THREAD

**Issue by Nightshadow1258** [qmk/qmk_firmware#18247]
I am trying to build my own keyboard with a bluepill board. I can upload the custom firmware fine and the keyboard is recognized and I can even type on it. But as soon as I reset it or replug it, it is not recognized anymore and I get an `unable to enumerate USB device` error.

I tried every possible configuration for the boot pins but I can not get it to be recognized. I can reflash the MCU again and the USB is working again until I reset the MCU.
At one point it was working but I can not figure out what lead to this in the past and was not able to recreate it.

Since I use a custom firmware I also tried different firmwares like [https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/onekey/bluepill](url) in order to rule out a configuration issue in the firmware itself. The issue still persists and I am out of ideas.

Is there a way to verfy if the code is running and only the USB interface is not working?

**Comment by alioth9** [comment]
I face the same problem but with this situation:
My board is a lily58 with elite-pi(rp2040)
I have no problem with my main computer under linux (debian) kernel 6.1
But I want to use it with a tablet (reMarkable) under linux (5.4 kernel) base on imx6 platform wich I can ssh to. 
I have the same problem when I first connect after flashing I can use the board but upon reconnect It is not working and I have this error
```
Jun 05 15:27:33 reMarkable kernel: usb 1-1: device no response, device descriptor read/64, error -71
Jun 05 15:27:33 reMarkable kernel: usb usb1-port1: attempt power cycle
Jun 05 15:27:34 reMarkable kernel: usb 1-1: new full-speed USB device number 40 using ci_hdrc
Jun 05 15:27:35 reMarkable kernel: usb 1-1: device not accepting address 40, error -71
Jun 05 15:27:35 reMarkable kernel: usb 1-1: new full-speed USB device number 41 using ci_hdrc
Jun 05 15:27:35 reMarkable kernel: usb 1-1: device not accepting address 41, error -71
Jun 05 15:27:35 reMarkable kernel: usb usb1-port1: unable to enumerate USB device
```
I have try his in config.h
```
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 5000
```
without success
