### ISSUE TITLE
[Feature Request] Add option similar to STRICT_LAYER_RELEASE but for mouse keys.

### ISSUE THREAD

**Issue by itsdogtime** [qmk/qmk_firmware#18300]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

[Mouse buttons are cleared on layer change.](https://github.com/qmk/qmk_firmware/blob/master/quantum/action.c#L1078-L1081) However, holding down buttons can cause strain for people with carpal tunnel. This is difficult when applications require a mouse button be held often.

Could you please add an option similar to `#define STRICT_LAYER_RELEASE` but for mouse keys so that the mouse button won't be cleared on layer change?

**Comment by drashna** [comment]
Ooooooh, that's why/where that happens!

**Comment by drashna** [comment]
Closing. This should be fixed now.

**Comment by itsdogtime** [comment]
Thanks!
