### ISSUE TITLE
Fatal error while compiling

### ISSUE THREAD

**Issue by csolje** [qmk/qmk_firmware#18325]
Hi,
I am on a cantor 42 keys keeb and I am trying to compile my firmware and I get a fatal error: printf.h: No Such file or directory
As upi can see on this screanshoot.
![image](https://user-images.githubusercontent.com/3214200/189461067-f28b9ed7-b068-4e61-befd-31576c026e11.png)

I am running version 0.18.5 of qmk, and I don't know what I am doing wrong.

**Comment by drashna** [comment]
Run "make git-submodule" from the qmk_firmware folder. 

The print code was moved to a submodule, and you may need to update them.

**Comment by csolje** [comment]
I have done that already and it still gives me that error

**Comment by csolje** [comment]
![image](https://user-images.githubusercontent.com/3214200/189482211-389f1b50-d942-4c8b-9579-b89f80f692d9.png)

**Comment by csolje** [comment]
Yeah I had it on both and now I found the issue and you where right the submodules need updating and I also had an error in my rules.c file so I will be closing this issue it is working on both now
