### ISSUE TITLE
What should I do if the IO pins are not enough?

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#18375]
![image](https://user-images.githubusercontent.com/5648129/190408368-59dfb5a5-3fc1-4b25-a164-15cd2643259b.png)
What should I do if the IO pins are not enough? The knob is mapped to the matrix. The firmware compiled with the 0th generation cannot be modified with via. What should I do?

**Comment by waffle87** [comment]
Not sure I understand your question — you're out of available IO pins on the microcontroller? You could look into using an IO expander like MCP23018, PCA9505/9555, or other options found in [drivers/gpio/](https://github.com/qmk/qmk_firmware/tree/master/drivers/gpio).
