### ISSUE TITLE
dead link in the QMK manual

### ISSUE THREAD

**Issue by morte-rictusgrin** [qmk/qmk_firmware#1845]
The link to [default Clueboard keymap](https://github.com/qmk/qmk_firmware/blob/master/keyboards/clueboard/keymaps/default/keymap.c) in the [Keymap Overview](https://docs.qmk.fm/keymap.html) leads nowhere. Most likely, cause clueboard has been forked to clueboard_17, clueboard_66 and clueboard_60. The entire reference is now useless: keymap for clueboard_66 is way different than described in the manual.

**Comment by fredizzimo** [comment]
This was fixed by #1845

**Comment by morte-rictusgrin** [comment]
still no: https://github.com/qmk/qmk_firmware/blob/master/keyboards/**clueboard_66**/keymaps/default/keymap.c leads nowhere again. Change underscore with slash and you're good.

https://github.com/qmk/qmk_firmware/blob/master/keyboards/**clueboard/66/**keymaps/default/keymap.c

**Comment by mmikeww** [comment]
I have fixed this in PR #2083
