### ISSUE TITLE
Qmk is not intended to support wireless?

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#18485]
Qmk is not intended to support wireless? Which Bluetooth is supported is also a very old module and Bluetooth protocol. Does qmk have stm32 bluetooth or 2.4G support? The bluetooth written only supports AVR, is there any example that supports nrf24l01? It is very useful and necessary to support wireless, you can not have it!

**Comment by tzarc** [comment]
Bluetooth radio stacks are usually incompatible with GPL. As such, QMK does not support most bluetooth capabilities unless they're handled by another chip and kept at arm's length.
