### ISSUE TITLE
[Bug] wear_leveling_rp2040_flash_config.h path of POST_CONFIG_H looks wrong

### ISSUE THREAD

**Issue by hajimen** [qmk/qmk_firmware#18529]
branch: develop
file: `builddefs/common_features.mk`
commit: https://github.com/qmk/qmk_firmware/commit/7c1797f52f74c9614615c0632ea1a2f5f11d3af6
line: 275

```
POST_CONFIG_H += $(DRIVER_PATH)/wear_leveling/wear_leveling_rp2040_flash_config.h
```

This line makes `drivers/wear_leveling/wear_leveling_rp2040_flash_config.h` path, but the file is not exist there. Isn't it `platforms/chibios/drivers/wear_leveling/wear_leveling_rp2040_flash_config.h`? If so, the line should be:

```
POST_CONFIG_H += $(PLATFORM_PATH)/$(PLATFORM_KEY)/$(DRIVER_DIR)/wear_leveling/wear_leveling_rp2040_flash_config.h
```

**Comment by zvecr** [comment]
`$(PLATFORM_PATH)/$(PLATFORM_KEY)` is on the VPATH so its not really an issue.

**Comment by tzarc** [comment]
Probably worth making it explicit, though. Will fix.
