### ISSUE TITLE
Are the docs just wrong?

### ISSUE THREAD

**Issue by burchill** [qmk/qmk_firmware#1858]
Spent a couple hours pulling my hair out today, trying to flash a layout to my Planck on my Mac.

The docs, specifically https://docs.qmk.fm/getting_started_make_guide.html, say to use the `make` command like: `make planck/rev4:default:dfu`, with colons. 

After going through the Makefile line by line, I realized that it says to use hyphens, i.e.:

```
# The entry point for rule parsing
# parses a rule in the format <keyboard>-<subproject>-<keymap>-<target>
# but this particular function only deals with the first <keyboard> part
```

Running this, e.g., `make planck/rev4-default-dfu` works.  I'm assuming that OSX is enough like Linux that the same would be true for that as well.  I've opened a pull request about this issue (#1859).

Am I missing something?

**Comment by jackhumbert** [comment]
Sorry, this was recently changed! If you pull/download the most recent version you'll be able to use the new format :) technically information on this change can be seen [here](http://qmk.fm/changes/2017-10-14-make-arguments-redo-subprojects-eliminated)!
