### ISSUE TITLE
[Bug] Installation instructions not working on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by BorisBrock** [qmk/qmk_firmware#18711]
### Describe the Bug

Following the instructions on https://docs.qmk.fm/#/newbs_getting_started does not work on Ubuntu 22.04 LTS.

`sudo apt install -y git python3-pip`
-> Works (OK)

`python3 -m pip install --user qmk`
-> Works (OK)

`qmk setup`
**-> Error: Command 'qmk' not found, did you mean: ...**

### Operating System

Ubuntu 22.04 LTS

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by fauxpark** [comment]
Please read the note in step 3.
