### ISSUE TITLE
numlock not responding under mac

### ISSUE THREAD

**Issue by biuboom-jun** [qmk/qmk_firmware#18786]
### Issue Description

In win10 mode, NumLock works normally, and the indicator light is normal. In mac mode, NumLock does not work, and the indicator light is off. The "/" of the numeric keyboard is recognized as other keys. Do you need to configure it separately in mac mode?

**Comment by fauxpark** [comment]
macOS does not have num lock.

**Comment by biuboom-jun** [comment]
> macOS 没有数字锁。

Is there no NumLock under mac?

**Comment by biuboom-jun** [comment]
> macOS 没有数字锁。

Why is the "/" key of my lowercase keyboard recognized as another key value

**Comment by fauxpark** [comment]
> Is there no NumLock under mac?

No. The keycode is interpreted as Clear in macOS.

**Comment by biuboom-jun** [comment]
> > mac下没有NumLock吗？
> 
> 不会。在 macOS 中，keycode 被解释为 Clear。

OK,Thank You
