### ISSUE TITLE
[Feature Request] Add Keychron Q4 and V series boards (V4, V3, V2, V1) 

### ISSUE THREAD

**Issue by lanes10000** [qmk/qmk_firmware#18797]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

I bought a Keychron V4 and I noticed that there was no QMK firmware for this on the repo (firmware jsons are listed on manufacturer's website), and as such VIA is not automatically recognizing the board and I have to manually load the json for the keyboard. I imagine this is also an issue for other V series boards, and I also noticed that the Q4 does not have an entry in the repo, so I thought I'd mention that, since upon review of that json, it looks almost identical to the V4 (not sure if they're the same PCB or not).

Thanks!

**Comment by lokher** [comment]
> V series boards are Sonix controllers, IIRC.
No, V series boards is almost same to Q Series, same MCU

**Comment by lokher** [comment]
> ### Feature Request Type
> * [x]  Core functionality
> * [ ]  Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
> * [ ]  Alteration (enhancement/optimization) of existing feature(s)
> * [ ]  New behavior
> 
> ### Description
> I bought a Keychron V4 and I noticed that there was no QMK firmware for this on the repo (firmware jsons are listed on manufacturer's website), and as such VIA is not automatically recognizing the board and I have to manually load the json for the keyboard. I imagine this is also an issue for other V series boards, and I also noticed that the Q4 does not have an entry in the repo, so I thought I'd mention that, since upon review of that json, it looks almost identical to the V4 (not sure if they're the same PCB or not).
> 
> Thanks!

We raise 2 or 3 keyboards PRs each time, Q10 is there, so we will start from V1 of V series soon. If you need the source code, you can get it from `playground` branch of Keychron fork 
https://github.com/Keychron/qmk_firmware/tree/playground/keyboards/keychron
