### ISSUE TITLE
[Feature Request] GMMK Numpad Support

### ISSUE THREAD

**Issue by keithvassallomt** [qmk/qmk_firmware#18854]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

This is my first time interacting with this project so please go ahead and chastise me if I'm doing something wrong by posting here!

Just putting in a request for QMK to be compatible with the GMMK Numpad. It should be possible, and I'd even be willing to help testing (have one of course). Since I have one, any information/details/files you need from my system would be available to anyone willing to work on this. 

Thanks for reading! Use QMK with my GMMK Pro and extremely happy, would love to see it on the numpad!

**Comment by adophoxia** [comment]
Currently, no PR has been made to add the GMMK Numpad, but if you want to be able to use QMK on it, you can try GloriousThrall's fork of it, specifically the `gmmk_numpad` branch where the [files](https://github.com/GloriousThrall/qmk_firmware/tree/gmmk_numpad/keyboards%2Fgmmk%2Fnumpad) are.

**Comment by keithvassallomt** [comment]
> Currently, no PR has been made to add the GMMK Numpad, but if you want to be able to use QMK on it, you can try GloriousThrall's fork of it, specifically the `gmmk_numpad` branch where the [files](https://github.com/GloriousThrall/qmk_firmware/tree/gmmk_numpad/keyboards%2Fgmmk%2Fnumpad) are.

Thanks! Will figure out how to give it a shot

**Comment by tzarc** [comment]
Unfortunately the QMK maintainers do not have access to these boards, so will be unable to help.
Your best bet is to go through the motions to add support yourself, then submit a Pull Request back to QMK.
