### ISSUE TITLE
audio can work at at90usb128 C6 B5 ?

### ISSUE THREAD

**Issue by YCF** [qmk/qmk_firmware#1885]
and the backlight is B5 B6 B7 ?

https://github.com/qmk/qmk_firmware/issues/414

**Comment by jackhumbert** [comment]
It should! Have you had the chance to try it yet? There may be complications with using pwm-controlled brightness.

**Comment by YCF** [comment]
I haven't that chip right now,maybe i need to buy a teensy ++.
