### ISSUE TITLE
Changing Layers with Tap Dance

### ISSUE THREAD

**Issue by K-rnivoro** [qmk/qmk_firmware#1893]
I tried using TG() and TO() like `ACTION_TAP_DANCE_DOUBLE(KC_F7,TG(layer))` but didn't work. 
How Can I insert a layer switching in a Tap Dance?

**Comment by drashna** [comment]
You can use the direct commands: https://github.com/drashna/qmk_firmware/blob/fix_docs/tmk_core/common/action_layer.h#L59-L66

layer_on and layer_off being the simplest commands.  You can look at the planck's default keymap for reference on how it's used.

**Comment by K-rnivoro** [comment]
That works!! Thanks!!
