### ISSUE TITLE
Easy $2 path for QMK Bluetooth + WIFI = ESP32 (K621) port

### ISSUE THREAD

**Issue by kanguru007** [qmk/qmk_firmware#19016]
### Feature Request Type

- [x] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

### Description

Has anyone ever thought of porting QMK to the ESP32?
I'm not very excited about bluetooth keyboards but a strong and stable WIFI connection would be awesome, and it would come for free.

It's 1 or 2 fast RISC CPUs with internal WIFI and Bluetooth (hardware + libraries) for < $2

p.s.
I bought a Redragon K621 but I could only type "sudo /opt/OpenRGB [TAB] [ENTER}" on it, and then it bricked.
It's an awfully nice keyboard with a lousy 8051. I thought of removing it and soldering in an ESP32 in its place. Then I would remove Redragon's logo sticker and put a small LCD screen in its place and add both VGA and a RCA composite video connectors to make a NES / Commodore 64 / Sinclair Spectrum / IBM PC (runs MS Flight Sim) emulator thingie.

**Comment by tzarc** [comment]
"Easy" is quite a relative term.
We have no plans to support it, at this point.
