### ISSUE TITLE
[Feature Request] Keychron K8 Pro Firmware

### ISSUE THREAD

**Issue by smiQi** [qmk/qmk_firmware#19019]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Hi,

I would appreciate if the firmware of the Keychron K8 Pro will be added.
Link to the firmware:
https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron/k8_pro

Thank you very much and keep up the great work!

**Comment by keyboard-magpie** [comment]
This should be addressed to keychron either through their fork or on discord.
