### ISSUE TITLE
[Feature Request] KBDPad Mk iii Support

### ISSUE THREAD

**Issue by graversenr** [qmk/qmk_firmware#19017]
### Feature Request Type

- [ ] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

The KBDPad Mk ii has had a a software revision to Mk iii, revising it from ATmega32u2 to ATmega32u4, preventing flashing of Mk ii configurations onto it. Mk iii support would be great!

KBDFans page with current Mk iii hex:
https://kbdfans.com/products/gb-kbdpad-markii-mechanical-keyboard-kit

**Comment by waffle87** [comment]
It has an open PR here #18795.

**Comment by drashna** [comment]
merged.
