### ISSUE TITLE
How can I send unicode with SEND_STRING?

### ISSUE THREAD

**Issue by ryan-nauman** [qmk/qmk_firmware#1901]
I enabled unicode in my rules and have tried various combinations of SEND_STRING, UC, SS_TAP and define UC with no luck. The error is always the same

```
error: \x used with no following hex digits
SEND_STRING(SS_TAP(UC(0x00AF)));
```

**Comment by hiro2016** [comment]
I don't know much myself but it seems you need to configure your os to use it:  
https://en.wikipedia.org/wiki/Unicode_input  
  
Xorg server does not seem to support it.

**Comment by drashna** [comment]
Not supported unfortunately.  (at least ad this time). 
You'd need to send it manually.  And use send string for the non-unicode input.

https://docs.qmk.fm/feature_unicode.html
