### ISSUE TITLE
[Bug] QMK Commands Updated? - Workaround/Solution

### ISSUE THREAD

**Issue by RbotJ** [qmk/qmk_firmware#19044]
### Describe the Bug

New User Here - Just loaded my first keyboard successfully. I wanted to point out I was unable to use the suggested 'make' command for the ferris sweep. Through looking at the setup tutorial test I modified the command with successful results to use qmk compile instead of 'make' in qmk msys. Hope this helps anyone else new to qmk to troubleshoot.

![image](https://user-images.githubusercontent.com/33506284/201472932-ad2b279c-229b-4135-bfaa-d196ac933f33.png)

When running the qmk compile the board (left or right) should be plugged in, you will need to reset the board when prompted.

### Keyboard Used

ferris/sweep

### Operating System

windows

### Is AutoHotKey / Karabiner installed

- [X] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by keyboard-magpie** [comment]
`make` can only be run inside a folder with a makefile, in this case running the appropriate command inside /qmk_firmware will work- if you are unsure how to change directories you can type `qmk cd` to get where you need to be. The "new" syntax you have found to work is well documented at docs.qmk.fm
