### ISSUE TITLE
cant compile and error doesn't make sense

### ISSUE THREAD

**Issue by thecodsman** [qmk/qmk_firmware#19092]
### Issue Description

![image](https://user-images.githubusercontent.com/34220198/202061833-298fd080-a5ec-4e3c-9035-ac4052c21dc3.png)
I dont understand this error what expression does it want ;-;

also heres the file
![image](https://user-images.githubusercontent.com/34220198/202061947-923e14e0-1efc-4840-b096-cc6cabb67666.png)
please help

**Comment by fauxpark** [comment]
You haven't shown the entire output.

**Comment by thecodsman** [comment]
![image](https://user-images.githubusercontent.com/34220198/202076299-7ac8e72b-cbc5-4d8a-9df3-a313d2d14661.png)

here you go

**Comment by fauxpark** [comment]
You should probably also post your keymap, and make sure there is no whitespace after the backslashes in the layout macro.

**Comment by thecodsman** [comment]
here is the keymap
![image](https://user-images.githubusercontent.com/34220198/202282772-19cff0f4-820c-4c68-9a9a-e272aac57cdd.png)
but wdym by the layout macro? the one in ansi.h?

**Comment by thecodsman** [comment]
wait

**Comment by fauxpark** [comment]
The layer names need to be wrapped in `[]`:
![image](https://user-images.githubusercontent.com/4781841/202335669-81785703-afe3-4bd5-b99a-3ac629f516d7.png)

**Comment by thecodsman** [comment]
lets goooooo it worked. thank you so much
