### ISSUE TITLE
"No such file or directory" issue when trying to create firmware

### ISSUE THREAD

**Issue by furret129** [qmk/qmk_firmware#19133]
Hi everyone,

This is my first time using QMK, Github, and a firmware in general, so please excuse me for anything I say that might seem obvious or dumb to you:
I am currently following the firmware section in the video linked below. I did everything what the video showed up to the part where he typed in "cd keyboards/handwired/(keyboard name)." When I tried doing that, the firmware told me that there is "no such file or directory". Unless cloning is irrelevant to this issue, I think that I already cloned my firmware beforehand since when I typed in "qmk clone", it showed this: Destination already exists: C:/Users/thisi/qmk_firmware.
 I also followed this tutorial: https://github.com/samhocevar-forks/qmk-firmware/blob/master/docs/getting_started_github.md
Although I am actually unsure if I cloned the firmware..
I tried to look for answers relating to my problem, but I couldn't find much information.

If it helps, I am trying to make a 4-key arrow cluster macropad by handwiring. I am using an arduino pro micro for this and instead of using a matrix for the macropad, I am planning on directly wiring the pins to the controller as there aren't many keys anyways. I am using this video to help me with creating my firmware: https://www.youtube.com/watch?v=hjml-K-pV4E&ab_channel=JoeScotto

Thank you if anyone is willing to help.

**Comment by filterpaper** [comment]
In @joe-scotto's video, his command prompt's current directory is already within `qmk_firmware` folder, and `cd keyboards/handwired/(keyboard name)` changes into the sub-folder within that directory path location.

If `C:/Users/thisi/qmk_firmware` if your source folder, you do likewise with `cd C:/Users/thisi/qmk_firmware/keyboards/handwired/(keyboard name)`
