### ISSUE TITLE
Why I can't found Ctrl+CMD modifiers

### ISSUE THREAD

**Issue by gshmu** [qmk/qmk_firmware#19156]
### Issue Description

I found LCA and LCAG, but no `LCG`? and via support Ctrl+CMD modifiers. and where the full key code definition file path? (`.h or .cpp` file path)

**Comment by waffle87** [comment]
[`quantum/quantum_keycodes.h`](https://github.com/qmk/qmk_firmware/blob/master/quantum/quantum_keycodes.h)
Would `LCTL(LGUI(kc))` work for your use case?
See [Advanced Keycodes](https://docs.qmk.fm/#/feature_advanced_keycodes) doc.

**Comment by gshmu** [comment]
thanks, @waffle87
