### ISSUE TITLE
[Feature Request] SOLID_SPLASH underglow affect enhancement

### ISSUE THREAD

**Issue by LeoLinny** [qmk/qmk_firmware#19272]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

### Description

Was playing around with the underglow effects on my Keychron Q3.

The effect currently refreshes with each key press, might be a personal taste, but coming from my old Keychron K2, the splash effect continued per key press, so to me, it looked better.

**Comment by drashna** [comment]
Have you tried using the "multi splash"?  that should do what you're looking for.

**Comment by LeoLinny** [comment]
That mode doesn't show up on my Keychron Q3

**Comment by drashna** [comment]
Yeah, looks like it's explicitly not enabled: 
https://github.com/qmk/qmk_firmware/blob/33cc81f36efd255447b47428f3198ef3793c1d41/keyboards/keychron/q3/config.h#L104

If you are compiling from source, you could add that to your keymap's config.h to enabled.
