### ISSUE TITLE
KC_NUHS working as non us backslash instead

### ISSUE THREAD

**Issue by theVDude** [qmk/qmk_firmware#1931]
https://github.com/qmk/qmk_firmware/blob/07017871e5eea9436458722ad74214b1f0f96e88/tmk_core/protocol/iwrap/main.c#L367

newest planck layout includes KC_NUHS, but that code doesn't seem to be working as expected.

**Comment by jackhumbert** [comment]
What language is your OS set to? Unfortunately I'm not familiar with what it's used for.

**Comment by theVDude** [comment]
en_us, the documentation looks like that key should be # and ~ ( i noticed it on the printout for the new plancks and wanted to see what it did)

**Comment by drashna** [comment]
Was this ever resolved/addressed?

**Comment by erodrig** [comment]
this is still happening to me with a preonic v3
