### ISSUE TITLE
Disposal depositor problem

### ISSUE THREAD

**Issue by aihk** [qmk/qmk_firmware#19388]
Does the chip of STM32F1 have a solution for the use of a displacement sender? Can the use of a displacement depositor not need a diode?

**Comment by tzarc** [comment]
What?

**Comment by aihk** [comment]
> What?

Hello, TZARC, I have seen that you are using ST's chips with 165 and 595 to achieve IO expansion. Can I not use the diode when using the 165 core 595? I have sent an email to you, and I may be blocked

**Comment by tzarc** [comment]
Not sure what you're asking -- 595's and 165's work fine, with and without diodes, depending on the configuration used. You'd need to write the code for it.
