### ISSUE TITLE
[Bug] Corne: EE_HANDS is not working with QMK Repo version: 0.19.5

### ISSUE THREAD

**Issue by DLopezGo90** [qmk/qmk_firmware#19414]
Corne: EE_HANDS is not working with QMK Repo version: 0.19.5
I have a Corne and I just updated qmk_firmware

slave LEDS are on but keycodes are not responding. Also OLED is off

Only the master is working (I have tried with left and right half as master, the slave never works)

I can make the keyboard work using SPLIT_USB_DETECT instead of EE_HANDS, but I prefer EE_HANDS

To flash I use these commands:

qmk flash -kb crkbd/rev1 -km neoncornelatin -bl avrdude-split-left

qmk flash -kb crkbd/rev1 -km neoncornelatin -bl avrdude-split-right

Help please

![image](https://user-images.githubusercontent.com/59780264/209424943-00e94b14-a2c5-4d2a-b77b-37c496758610.png)

![image](https://user-images.githubusercontent.com/59780264/209424958-0558c5fd-f08b-4097-9847-d609ea92da4f.png)

### Keyboard Used

crkbd

### Operating System

Windows 10

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.0
Ψ QMK home: C:/Users/dlopez/qmk_firmware
Ψ Detected Windows 10 (10.0.19045).
Ψ Git branch: master
Ψ Repo version: 0.19.5
Ψ - Latest master: 2022-12-23 18:14:23 +0000 (b56c0fa674) -- Bump actions/stale from 6 to 7 (#19392)
Ψ - Latest upstream/master: 2022-12-23 18:14:23 +0000 (b56c0fa674) -- Bump actions/stale from 6 to 7 (#19392)
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: 2022-12-23 18:14:23 +0000 (b56c0fa674) -- Bump actions/stale from 6 to 7 (#19392)
Ψ - Common ancestor with upstream/develop: None
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.1.0
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 6.4
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2022-09-18 10:01:17 +0000 --  (0e9d558b5)
Ψ - lib/chibios-contrib: 2022-10-03 18:09:41 +0200 --  (bb8356fb)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/pico-sdk: 2022-09-19 18:02:44 +0200 --  (8d56ea3)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ QMK is ready to go
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by daskygit** [comment]
This is not a bug, if the controller you're using does not have working VBUS detection SPLIT_USB_DETECT is required. EE_HANDS is not a replacement for SPLIT_USB_DETECT.

- EE_HANDS allows you to assign a handedness value to each side left/right.
- SPLIT_USB_DETECT modifies the USB detection to work out which half is plugged in the computer.

Both options may be used at the same time.
