### ISSUE TITLE
[Bug] LM() not working on V65 R2.

### ISSUE THREAD

**Issue by tradao2610** [qmk/qmk_firmware#19417]
### Describe the Bug

I tried using [LM()](https://docs.qmk.fm/#/feature_layers?id=switching-and-toggling-layers) on KBDLite and it works fine but when i change to V65 i can't use [LM()](https://docs.qmk.fm/#/feature_layers?id=switching-and-toggling-layers) anymore, it's the work same as **KC_NON** and Macro is overused for me. Is anyone know how to fix this problem.
![image](https://user-images.githubusercontent.com/112112934/209433557-89e0a9b2-2e73-4fbd-9aa2-dd07cbfe7afa.png)

### Keyboard Used

Cidoo V65 R2

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

VIA

**Comment by zvecr** [comment]
Via issues should be raised against <https://github.com/the-via/app>
