### ISSUE TITLE
STM32F103 Is the chip compilation firmware limit?

### ISSUE THREAD

**Issue by aihk** [qmk/qmk_firmware#19419]
Compilation error prompt `.rodata' will not fit in region `flash0'`，` region `flash0' overflowed by 8016 bytes`

The STM32F103CBT6 is 128K, and the size of the compiled firmware depends on the limit of within 64K.

**Comment by HorrorTroll** [comment]
The default ld files for F103 was using x8 version, not xB. U need to added some code into rules.mk

See my file at an example: https://github.com/HorrorTroll/qmk_firmware/blob/pila87/keyboards/phage_studio/pila87/rules.mk
