### ISSUE TITLE
Support for Massdrop x Input Club K-Type

### ISSUE THREAD

**Issue by KMontag42** [qmk/qmk_firmware#1942]
Wuddup yooooo!

Any plans to add support for the new K-Type to QMK??

**Comment by belak** [comment]
Adding basic support wouldn't be hard, but adding full LED support will most likely be a challenge. Last I knew there was still some work being done on the visualization front.

If you're interested in doing the port yourself, it should be as simple as copying a different TKL keyboard and updating it with the correct info (CPU, matrix layout, etc) from the following links:

* https://github.com/kiibohd/controller/blob/master/Keyboards/k-type.bash
* https://github.com/kiibohd/controller/blob/master/Scan/K-Type/matrix.h
* https://github.com/kiibohd/controller/blob/master/Scan/K-Type/scancode_map.p3.kll (Technically it should just be scancode_map.kll, but it's a symlink so this link is more useful at the moment)

**Comment by belak** [comment]
I started on it but haven't gotten it running yet. I've got most of the busywork and scancodes done... but I haven't been able to find any info on which chip this is built on (among other things) so it's definitely missing some important settings.

**Comment by KMontag42** [comment]
If you have a branch I'd be happy to help out however possible, let me know.

<3

**Comment by belak** [comment]
Once I have a build that flashes properly, I'll look at opening a PR. There is a branch at https://github.com/qmk/qmk_firmware/compare/master...belak:k-type-support but keep in mind this doesn't work at all right now.

**Comment by belak** [comment]
This patch is needed to get the firmware to boot (we'll look at including this in a board file similar to the clueboard support eventually). However, USB support is still broken.

The following code comes from here:

* https://github.com/kiibohd/controller/blob/1d8ee5786d80421eacb07d68b9133fbb3a31f53a/Lib/mk20dx.h#L728 
* https://github.com/kiibohd/controller/blob/1d8ee5786d80421eacb07d68b9133fbb3a31f53a/Lib/mk20dx.c#L530

```
chibios-contrib % git diff
diff --git a/os/hal/ports/KINETIS/K20x/hal_lld.c b/os/hal/ports/KINETIS/K20x/hal_lld.c
index e6eeed8..cb8edd8 100644
--- a/os/hal/ports/KINETIS/K20x/hal_lld.c
+++ b/os/hal/ports/KINETIS/K20x/hal_lld.c
@@ -93,8 +93,10 @@ void hal_lld_init(void) {
  *
  * @special
  */
+#define WDOG_TMROUTL            *(volatile uint16_t *)0x40052012^M
 void k20x_clock_init(void) {
 #if !KINETIS_NO_INIT
+  while (WDOG_TMROUTL < 2); // Must wait for WDOG timer if already running, before jumping^M

   /* Disable the watchdog */
   WDOG->UNLOCK = 0xC520;
```

**Comment by KMontag42** [comment]
sorry for the late reply, I will be trying this out over the weekend!!!!
