### ISSUE TITLE
[Bug]  Bug in autogenerated MIDI keycodes

### ISSUE THREAD

**Issue by rseymour** [qmk/qmk_firmware#19484]
### Describe the Bug

There's a bug in the generated midi keycodes [quantum/keycodes.h] which makes a discontinuity in the notes, making them wrong, from the jump from B to C1.  The hex goes  like this:
```
    QK_MIDI_NOTE_B_0 = 0x711B,
    QK_MIDI_NOTE_C_1 = 0x7120,
```
but it should just be 1 more, I think that puts the C1 as an E1, and the error continues to compound at every octave switch.

correct (as in I've tried the hex by hand in my keymap and heard the correct result):
```
    QK_MIDI_NOTE_B_0 = 0x711B,
    QK_MIDI_NOTE_C_1 = 0x711C,
```
If I can find what's autogenerating these I'll try to fix it myself, but it took me hours just to find the bug in the first place.

Thanks again for QMK.

### Keyboard Used

KradoIndustriesV2

### Operating System

Linux

### Is AutoHotKey / Karabiner installed
 - no all testing on Linux

### Additional Context

I've made 3 or 4 midi ortho keyboards with QMK, this is the first time I've flashed one and had the notes be wrong.  So it must be a relatively new change, I just don't know how this file is autogenned to fix it.

**Comment by zvecr** [comment]
#19468 is already in progress to resolve this issue.
