### ISSUE TITLE
UF2 problem of STM32F103

### ISSUE THREAD

**Issue by aihk** [qmk/qmk_firmware#19592]
I brushed STM32F103 through UF2. I found that the Bootmagic Lite function cannot be used. Can I only enter the guidance again through the reset button?

**Comment by fauxpark** [comment]
The firmware needs to have support for the particular bootloader you're using. AFAIK STM32Duino is the only bootloader supported for F103 boards, but it is fairly simple to add a new one: https://github.com/qmk/qmk_firmware/tree/master/platforms/chibios/bootloaders

**Comment by zvecr** [comment]
Assuming its the same bootloader, #19594 should cover this.
