### ISSUE TITLE
ChibiOS USB Serial - Ergodox Infinity (ARM) stenography

### ISSUE THREAD

**Issue by KoviRobi** [qmk/qmk_firmware#1961]
I was trying to get my Ergodox Infinity to use the stenography extension, but I was having trouble getting it to work. The way I understand it, the problem was with it relying on LUFA, whereas the ErgoDox Infinity uses ChibiOS, which doesn't use 'virtser_send'. I was wondering if someone knows about USB serial in ChibiOS and could help me get it working?

**Comment by seebs** [comment]
I think the right solution (probably?) is to implement a virtser_send for ChibiOS, so that there's one visible. But I don't know exactly how one would go about this.

**Comment by drashna** [comment]
Yeah, if ChibiOS doesn't have a virtual serial port, or it properly implemented .... then "no dice". 

Maybe @fredizzimo may know what the issue is, as I believe that he's the resident ChibiOS expert.

**Comment by fredizzimo** [comment]
Support for this was added in https://github.com/qmk/qmk_firmware/pull/2362
