### ISSUE TITLE
Tap dance not working

### ISSUE THREAD

**Issue by QuadDepo** [qmk/qmk_firmware#1967]
I have HHKB pro 2, with a husu controller. 

I followed the example with the esc + caps. but for some reason i have to

`tap tap hold` to active it.
 
deactivating it does work with just `tap tap`

anyone know how?

**Comment by drashna** [comment]
Is the tapping term set? 

And have you tried updating your repo, as that may help?

**Comment by drashna** [comment]
Was this still an issue?
