### ISSUE TITLE
[Feature Request] support for ISO variants of Durgod Venus and Hades.

### ISSUE THREAD

**Issue by optionaltoast** [qmk/qmk_firmware#19736]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Hi, I have come into possession of a few Durgod Venus and Hades boards. I see that there is support for the ANSI version of these boards. Would it be possible to bring QMK support to the ISO versions of these boards?

**Comment by tzarc** [comment]
Unfortunately the QMK maintainers do not have access to these boards, so will be unable to help.
Your best bet is to go through the motions to add support yourself, then submit a Pull Request back to QMK.

**Comment by pascalhansjosten** [comment]
@optionaltoast 
If still relevant, I just created a PR that adds ISO support for Venus.

See: https://github.com/qmk/qmk_firmware/pull/25526
