### ISSUE TITLE
Keychron Q1 JIS Layout[Feature Request] 

### ISSUE THREAD

**Issue by caiuscooke** [qmk/qmk_firmware#19744]
### Feature Request Type

- [X] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

I have recently purchased the Keychron Q1 JIS layout. On QMK configurator the only option is for the ISO and ANSI layout keyboards. Currently, because of that, I have three Japanese specific keys that I can't remap (The KANA key, the alphanumeric to Japanese letters key, and the Henkan/Muhenkan keys can't be recognized by windows out of the box no matter what settings I change in the windows OS). Please add this to QMK!

**Comment by keyboard-magpie** [comment]
https://imgur.com/a/r6XAZ8s

I am not overly familiar with this feature of config.qmk.fm but the language settings in the settings panel to the right, may be what you are looking for.
