### ISSUE TITLE
Multiple COMBO cause a key press for each occurence of the given key

### ISSUE THREAD

**Issue by gcaferra** [qmk/qmk_firmware#1984]
with my (Action) [layout](https://github.com/gcaferra/qmk_firmware/blob/master/keyboards/tada68/keymaps/devchords/keymap.c)

when I press F   3 [f] are typed when i press D 2 [d] are typed and so on for each occurrence in the combo_key matrix this seems like is needed to "exit" after the first sending  if  the key if already sent before this [line](https://github.com/qmk/qmk_firmware/blob/05f15b789f4f6098a72474e028a19fdbccdaf2d3/quantum/process_keycode/process_combo.c#L98)

Someone can point me to a solution for this?

**Comment by drashna** [comment]
Did the code change for #2561 fix this?
