### ISSUE TITLE
Having trouble getting OLED to show different infos on left and right halves.

### ISSUE THREAD

**Issue by ad-on-is** [qmk/qmk_firmware#19990]
I'm using a Redox keyboard and have handwired an OLED to it. Everything works fine, except, I cannot get each of the halves to show different infos on the OLED screen.

```
bool oled_task_user(void) {
    if (is_keyboard_left()) {
        oled_render_layer_state();
    } else {
        oled_render_logo();
    }
    return false;
}
```

```
#define USE_I2C
```

Attempts so far:

```
#define EE_HANDS
```
Flashing botch halves with `qmk flash -kb penguin/rev1 -km default -bl avrdude-split-left` and `qmk flash -kb penguin/rev1 -km default -bl avrdude-split-right` respectively.

```
#define MASTER_LEFT
```
Flashing both halves with `qmk flash -kb penguin -km default `

If I connect the left half to the USB both keyboards show the layer state, and if I connect the right half to the USB both show the logo. No matter what I try, I cannot get the left half to show the layer state and the right half to show the logo.

I also tried `is_keyboard_master()`, but then, no matter which half I connect to USB both show the layer_state.

What am I missing here?

**Comment by Aghrezar** [comment]
If you use serial connection and flashing with avrdude you can specify left or right half.

#ifdef OLED_ENABLE
//qmk logo for test 
static void render_logo(void) {
    static const char PROGMEM qmk_logo[] = {
        0x80, 0x81, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x8B, 0x8C, 0x8D, 0x8E, 0x8F, 0x90, 0x91, 0x92, 0x93, 0x94,
        0xA0, 0xA1, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xAB, 0xAC, 0xAD, 0xAE, 0xAF, 0xB0, 0xB1, 0xB2, 0xB3, 0xB4,
        0xC0, 0xC1, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xCB, 0xCC, 0xCD, 0xCE, 0xCF, 0xD0, 0xD1, 0xD2, 0xD3, 0xD4, 0x00
    };
oled_write_P(qmk_logo, false);
}


oled_rotation_t oled_init_user(oled_rotation_t rotation) {
  if (!is_keyboard_left()){
    return OLED_ROTATION_180;  // flips the display 180 degrees if offhand
  }
    return rotation;
}

bool oled_task_user() {
  // Set cursor position
  if (is_keyboard_left()) {
  // Switch on current active layer
  switch (get_highest_layer(layer_state)) {
      case _QWERTY :
          oled_write("QWERTY\n", false);
          break;
      case _NUM :
          oled_write("NUM Layer\n", false);
          break;
      case _FKEY : 
          oled_write("FKEY Layer\n", false);
          break;
      case _MOUSE :
          oled_write("MOUSE Layer\n", false);
          break;
      }
        // Host Keyboard LED Status
    led_t led_state = host_keyboard_led_state();
    oled_write_P(led_state.num_lock ? PSTR("NUM ") : PSTR("    "), false);
    oled_write_P(led_state.caps_lock ? PSTR("CAP ") : PSTR("    "), false);
    oled_write_P(led_state.scroll_lock ? PSTR("SCR ") : PSTR("    "), false);
    
  } else {
    
render_logo();  // Renders a static logo
        oled_scroll_left();  // Turns on scrolling
  }
  return false;
}

#endif

I have something weird going on. 
When right side is plugged in, left one wouldn't update led status or layer info. 
When left one is plugged in everything works as intended
