### ISSUE TITLE
[Bug] SouthPaw 65 keyboard incorrectly configured

### ISSUE THREAD

**Issue by elegantalchemist** [qmk/qmk_firmware#20014]
### Describe the Bug

When using QMK configurator, the default layouts for the Southpaw65 (default, ANSI and ISO) are incorrect,

Selecting to compile one of the defaults gives a hex file, which when flashed has all the keys shifted 16 steps to the right. I suspect there is a bug/issue in the column/pin configuration.

### Keyboard Used

southpaw_65

### qmk doctor Output

```text
n/a
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by sigprof** [comment]
You mean the `switchplate/southpaw_65` board?

Looks like the code for that board had been broken by the changes in #16277 (maybe wrongly copied from `xiudi/xd96`).

**Comment by elegantalchemist** [comment]
Yes that's right, that board

Something like that would make sense. The rows are fine, just that all columns are offset by 16 keys to the right. It's consistent across all rows, suggesting a config error

On 4 Mar 2023 19:08, Sergey Vlasov ***@***.***> wrote:

You mean the switchplate/southpaw_65 board?

Looks like the code for that board had been broken by the changes in #16277<https://github.com/qmk/qmk_firmware/pull/16277> (maybe wrongly copied from xiudi/xd96).

**Comment by elegantalchemist** [comment]
Close as completed - pending pull request #20015  solves the issue.
