### ISSUE TITLE
New massage with 0.20 compilation that was not present with the 0.19

### ISSUE THREAD

**Issue by AndroSteph** [qmk/qmk_firmware#20022]
### Issue Description

Hello,

I recompiled my firmware for my Keychron Q6 with the new files put here "..qmk_firmware\keyboards\keychron\q6" and I have this new message that appears (compilation with "default, keychron and VIA)

Is it a problem (I don't understand the meaning of this message) but the compilation finishes without error and I flashed the new firmware without problem in my keyboard.

So in the end no problem, I just report this difference between version 0.19 and 0.20.

Thanks for all your work :-)

**Comment by AndroSteph** [comment]
![exemple](https://user-images.githubusercontent.com/69978916/222961337-11e57ce7-2abe-4e5b-8071-34e7e2609aed.png)

**Comment by keyboard-magpie** [comment]
It's a warning, not an error.

**Comment by tzarc** [comment]
See [here](https://docs.qmk.fm/#/ChangeLog/20230226?id=i-m-t-i).

**Comment by AndroSteph** [comment]
Thank you very much for your answers ;-)
