### ISSUE TITLE
Capital letters not getting sent with `sendstring_swiss_fr.h`

### ISSUE THREAD

**Issue by AndroSteph** [qmk/qmk_firmware#20080]
### Issue Description

Hello to all,

These times I ask questions that are surely basic for you programmer. But I like to understand and I come across misunderstandings and unfortunately it is very difficult to find answers on the WWW other than here (I have not found any tutorial or explanation on this point).

Let me ask you one more question.

I specify that I am, unfortunately, not with an ANSI US keyboard but an ISO keyboard Swiss_fr keyboard (Keychron Q6).

Here are my observations.

First test if I have in my "**keymap.c**" file these two lines (classic)

**#include QMK_KEYBOARD_H
#include "keychron_common.h**

If I put in a macro (in VIA) programmed on a free key of my keyboard :

Test **Y**
Test A
Test **Z**

The capital letters are well recorded and displayed if I run this command, the Y and Z are reversed because my keyboard is not US (which is normal) so to do it right I have to put a "Z" in place of a "Y" and vice versa.

This gives this in display:
Test **Z**
Test A
Test **Y**

Now if I have in my "**keymap.c**" file these lines

**#include QMK_KEYBOARD_H
#include "keychron_common.h
#include "keymap_swiss_fr.h"
#include "sendstring_swiss_fr.h"**

And in my macro in VIA

**T**est **Y**
**T**est **A**
**T**est **Z**

This will look like this:
**t**est **y**
**t**est **a**
**t**est **z**

The "Y" and "Z" are right but I completely lose the characters in capital letters, **everything is in lower case**.

Would you have an explanation although you certainly don't have a keyboard other than ANSI and US, I don't know where else to ask my question (if I am not in the right section, my apologies)

Thank you for all your help and advice ;-) ... and my apologies for my bad English

**Comment by sigprof** [comment]
This looks like a bug in `quantum/keymap_extras/sendstring_swiss_fr.h` — [this area](https://github.com/qmk/qmk_firmware/blob/e0bd6fac10883fdce7d7c5b0c47fe454c9f2f0aa/quantum/keymap_extras/sendstring_swiss_fr.h#L36-L39) corresponds mostly to the capital letters in ASCII, so most of bits there should be 1, but they are 0 for some reason.  Looks like it has been that way since #8689, where the translation table was added.

**Comment by AndroSteph** [comment]
Thank you for your answer.

I don't know how to put a "BUG" tag in this topic, can you do it. Please and Thank you

**Comment by AndroSteph** [comment]
Thank you ! :-)

**Comment by AndroSteph** [comment]
I can confirm that I have changed the lignes in the "**sendstring_swiss_fr.h**" fichier, and it is working better.

lignes :
**36 -** KCLUT_ENTRY(0, 1, 1, 1, 1, 1, 1, 1, 1),
**37 -** KCLUT_ENTRY(1, 1, 1, 1, 1, 1, 1, 1, 1),
**38 -** KCLUT_ENTRY(1, 1, 1, 1, 1, 1, 1, 1, 1),
**39 -** KCLUT_ENTRY(1, 1, 1, 0, 0, 0, 0, 1),
