### ISSUE TITLE
Mapper (Convertor of sorts) for Waveshare RP2040 Zero controller

### ISSUE THREAD

**Issue by dunk2k** [qmk/qmk_firmware#20134]
### Issue Description

I created a [QMK convertor](https://drive.google.com/file/d/1H4g1lXP1yQewBdHKYHNF8JiXoLdphhLG/view?usp=sharing) for converting pro micro to Waveshare's rp2040 zero controller, which a user confirms simplified their redox build, with said controller. Aimed at use by those who aren't as well versed in QMK to define pins.

@drashna has given view on it not really being a convertor, which is fair enough as [I did ask](https://www.reddit.com/r/ErgoMechKeyboards/comments/11jvts9/questions_about_qmk/jb9hcfi/?context=3) 😉

Maybe more of a Mapper? regardless naming convention - upon reviewing the code and accompanying illustration, would this be something worth adding to QMK codebase to help simplify pro micro based keyboards converted/mapped to rp2040 zero controller?

**Comment by zvecr** [comment]
Personally, its not a scenario I would want to see the converter framework cover. At its core, the rp2040 zero is not a drop-in replacement, and would require handwiring or an adaptor, so has no place as a promicro alternative. I would also not want to see a competing framework implemented. Converters are already pushing the limits on what is maintainable.

What is required is a more modern version of kbfirmware that can cater for these non standard builds.
