### ISSUE TITLE
[Bug] brew install returns "Formulae fond in multiple taps" on Mac OS

### ISSUE THREAD

**Issue by orcinus** [qmk/qmk_firmware#20135]
### Describe the Bug

Running brew install qmk/qmk/qmk fails at:

```
Error: Formulae found in multiple taps: 
       * osx-cross/avr/avr-binutils
       * larsimmisch/avr/avr-binutils

Please use the fully-qualified name (e.g. osx-cross/avr/avr-binutils) to refer to the formula.
```

### Keyboard Used

N/A

### Link to product page (if applicable)

N/A

### Operating System

Mac OS Ventura 13.2.1

### qmk doctor Output

```text
N/A
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Additional Context

Manually installing osx-cross/avr/avr-binutils does not seem to help.

**Comment by orcinus** [comment]
Nvm.
Removed the offending larsimmisch/avr/avr-binutils tap, everything ok now.

Closing.

**Comment by orcinus** [comment]
(That said, it might be a good idea to use the fully qualified path anyway.)

**Comment by fauxpark** [comment]
We do.
https://github.com/qmk/homebrew-qmk/blob/master/Formula/qmk.rb#L25

**Comment by orcinus** [comment]
Weird o_O
