### ISSUE TITLE
[Bug] Incorrect RGB LEDs activating on right side of split keyboard when using `RGB_MATRIX_INDICATOR_SET_COLOR` in `rgb_matrix_indicators_advanced` callbacks

### ISSUE THREAD

**Issue by CobraSock** [qmk/qmk_firmware#20203]
### Describe the Bug

`RGB_MATRIX_INDICATOR_SET_COLOR` uses `led_min` and `led_max` in scope to restrict the range of LED indices that are allowed be set. However, inside of the `rgb_matrix_indicators_advanced_kb` and `rgb_matrix_indicators_advanced_user` callbacks, the range includes indices for the other side of a split keyboard. Setting color for an index for the other side can cause an incorrect LED to light up.

The `led_min` and `led_max` range in `rgb_matrix_indicators_advanced` should be restricted to correct split side.

For comparison, the `RGB_MATRIX_USE_LIMITS` macro used in rgb_matrix effects restricts the range to the split side. But the function `rgb_matrix_indicators_advanced` doesn't use it because of the need to use the previous iteration index.

```
void rgb_matrix_indicators_advanced(effect_params_t *params) {
    /* special handling is needed for "params->iter", since it's already been incremented.
     * Could move the invocations to rgb_task_render, but then it's missing a few checks
     * and not sure which would be better. Otherwise, this should be called from
     * rgb_task_render, right before the iter++ line.
     */
```

### Keyboard Used

keychron/q11

### Link to product page (if applicable)

https://www.keychron.com/products/keychron-q11-qmk-custom-mechanical-keyboard

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by KlausHans** [comment]
Hello,
i am using the indicator example from the documentation on a split kb:
```
bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
    for (uint8_t i = led_min; i < led_max; i++) {
        switch(get_highest_layer(layer_state|default_layer_state)) {
            case _LOWER:
                rgb_matrix_set_color(i, RGB_BLUE);
                break;
            case _RAISE:
                rgb_matrix_set_color(i, RGB_YELLOW);
                break;
            default:
                break;
        }
    }
    return false;
}
```
But only the halve where the usb cable is connected to lights up as defined in the function, not both halves. Is my problem connected to that what you describe? 
I am quite new to qmk, sorry. I defined the handedness by eeprom if that matters.

**Comment by KlausHans** [comment]
@CobraSock Thank you, that solved it 👍

**Comment by drashna** [comment]
Closing, as it looks like this has been fixed+merged in
