### ISSUE TITLE
[Feature Request] Use VIA to choose which RGB modes to cycle through 

### ISSUE THREAD

**Issue by ouyangde** [qmk/qmk_firmware#20336]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Threa are too many RGB modes, and not all of them are among my favorites. Can I use VIA to keep only part of the effects?

**Comment by tzarc** [comment]
A question for VIA, I'm afraid.

**Comment by ouyangde** [comment]
> A question for VIA, I'm afraid.

Does qmk provide interface for VIA doing this?

**Comment by tzarc** [comment]
VIA has its own definitions, based on the `via` keymap. Any changes to the setup have historically broken VIA compatibility.
