### ISSUE TITLE
No keycode to disconnect bluetooth connection from current device.

### ISSUE THREAD

**Issue by harshitgoel96** [qmk/qmk_firmware#2036]
I am currently working on a magicforce 68 mod to make it bluetooth capable. I am useing Bluefruit BLE 32u4. Everything is working fine, and I can easily use keyboard in bluetooth mode. The issue i have is when using multiple devices like phone or laptop, i need to disable the connection from the Device, i.e. laptop or mobile, is it possible to force disconnection for the keyboard itself ? i could not find a keycode or something that would make it possible.

**Comment by drashna** [comment]
Doesn't look like there is a way to do this currently. 
Switching between USB and BT mode would probably be a reasonable hack.

**Comment by harshitgoel96** [comment]
that is something i am currently using. thanks. i will close this request. as i half expected a resolution on this.

**Comment by drashna** [comment]
If you don't mind, I'm going to reopen it, and tag it.  Adding an actual disconnect or switch command would be a really good idea.

**Comment by Miodec** [comment]
Is there any progress with this feature? Is it even possible? Also @drashna im not sure what you mean by "switching between USB and BT is a reasonable hack" as this still leaves the board connected to the device and just stops sending keycodes. It doesnt actually disconnect, which still forces the user to dig through the settings of that device and forgetting the keyboard, before it can be connected to a new device.

**Comment by jackhumbert** [comment]
I think that solution is probably sufficient for now, until we get broader support for BT modules - you may want to track #2054.

**Comment by ts52** [comment]
I'm confused. The OUT_USB, OUT_BT 'solution' doesn't work for me on an Adafruit Bluefruit 32u4. And 2504 seems to only be asking which boards are supported. But having a keycode that specifically puts the bluetooth in pairing mode would be extremely useful.
