### ISSUE TITLE
KC_MAIL with Outlook always opens new instance

### ISSUE THREAD

**Issue by max3-2** [qmk/qmk_firmware#20428]
### Issue Description

Hi,

I have set up a new keyboard for windows which uses the `KC_MAIL` keycode. This works as expected, and also uses the default mail app as set in the system settings (in my case, Outlook) on Win10.

However, if there is an instance already open and minimized, it will create a new instance which is obviously not perfect since Outlook will run most of the time.

Is there a way around this? I would assume this is on OS Side but maybe there is a modifier to prevent the behaviour...

**Comment by filterpaper** [comment]
This is an operating system behaviour that is not related to QMK. A quick search on Google reveal this as a common "problem" with solutions that involves changing registry entries.
