### ISSUE TITLE
qmk cannot compile because there is a "\" error in keyboard.h

### ISSUE THREAD

**Issue by hvuitsme** [qmk/qmk_firmware#20465]
### Issue Description

hello everyone 
now i can't do compile with that error, is there any way to fix that problem

Compiling: keyboards/1test/1test.c                             In file included from keyboards/1test/1test.c:1:0:keyboards/1test/1test.h:5:17: error: backslash-newline at end of file [-Werror]
 #define LAYOUT( \
                             ^
cc1: all warnings being treated as errors
 [ERRORS]
 |
 |
 |
make[1]: *** [builddefs/common_rules.mk:360: .build/obj_1test_default/keyboards/1test/1test.o] Error 1
Make finished with errors
make: *** [Makefile:392: 1test:default] Error 1

**Comment by zvecr** [comment]
> backslash-newline at end of file

Add a newline to the end of the file, that extra blank line will fix the problem.

However layout data is now expected to be in `info.json` which you wouldnt then have the issue in the first place.
