### ISSUE TITLE
Can QMK output UARTx? 

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#20471]
Can QMK output UARTx? UARTx is connected to a 2.4G module cable to connect to a computer, such as NRF24L01, JCL24B.... It can sleep when not in use. Is there an example? The two bluetooths supported are also very old
![image](https://user-images.githubusercontent.com/5648129/232364827-a6baaa5d-90f3-42b8-ae2c-e885ffbe8867.png)

**Comment by drashna** [comment]
In theory, yes. https://docs.qmk.fm/#/uart_driver

As for actual code implementation, I believe that fauxpark has been working on this, in general.
