### ISSUE TITLE
Already pressed key gets released when switching layers

### ISSUE THREAD

**Issue by feidaman** [qmk/qmk_firmware#2053]
Full disclosure: I'm a newbie using an Ergodox EZ here, haven't actually built my own firmware (yet). I have a key configured as **Ins** on **Layer 0**. I also have another key mapped to MO(1). If I press and hold Ins, as soon as I press the layer toggle key Ins up is sent, but the key is still being physically held down. Wouldn't it be useful if QMK could remember the layer where key-down occurred, and preserve the context through to key-up?

**Comment by notg10** [comment]
Can we revisit this issue? Heres a perfect use case:

Holding W to walk in a game and using fn+1 for f1 and you stop moving until you re-hit w.

this is less then ideal and to my knowledge no other firmware has this limitation.

thanks,

**Comment by feidaman** [comment]
Is this really because of limited RAM? From a users  respective, the way this works ATM is wrong---If the key is physically down, key up should not be sent automatically for me.

**Comment by drashna** [comment]
This has been fixed now.  Update your repo, and it should be the default behavior.

You can revert by defining `STRICT_LAYER_RELEASE`.

**Comment by jackokring** [comment]
Hi. Nice to option but old builds could do with the old behaviour. As games and industrial process control systems have different ideas about safety of unexpected stuck keys. Any plans for a source build date #define?
