### ISSUE TITLE
JJ40 NKRO Error

### ISSUE THREAD

**Issue by RandTrawick** [qmk/qmk_firmware#2057]
I cannot get NKRO working with the JJ40.
when I set the NKRO_ENABLE = yes, I get this error:  
  
  
`Compiling: keyboards/jj40/jj40.c                                                                   In file included from ./quantum/keymap.h:29:0,
                 from ./quantum/quantum.h:26,
                 from keyboards/jj40/jj40.c:23:
./tmk_core/common/report.h:133:22: error: 'KEYBOARD_REPORT_BITS' undeclared here (not in a function); did you mean 'KEYBOARD_REPORT_SIZE'?
         uint8_t bits[KEYBOARD_REPORT_BITS];
                      ^~~~~~~~~~~~~~~~~~~~
                      KEYBOARD_REPORT_SIZE
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [.build/obj_jj40_fuck40/keyboards/jj40/jj40.o] Error 1`

How did I set the Keyboard Report size?
JJ40 uses a custom matrix.

**Comment by drashna** [comment]
Looks like you hard coded an error into this to block NKRO afterwards? 

I'm going to close this thread.  If wanted, reopen or open a new issue.
