### ISSUE TITLE
[Bug] Mistake in matrix description of the Keychron Q6 ISO encoder

### ISSUE THREAD

**Issue by FabienFellay** [qmk/qmk_firmware#20579]
### Describe the Bug

The line 105 of the file https://github.com/qmk/qmk_firmware/blob/master/keyboards/keychron/q6/iso_encoder/info.json has a wrong x coordinate (it is the same as the one of line 106): one should replace the line 105
```
                {"matrix":[4, 1], "x":2.25, "y":4.25},
````
by
```
                {"matrix":[4, 1], "x":1.25, "y":4.25},
````
Indeed, currently, both the `<>` touch and the `z` touch will be visually placed at the same location in the QMK Configurator and there is no way I can fix it from there. We have to correct this file.

Note that the Keychron Q6 ISO (no encoder) matrix description is correct.

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Additional Context

This issue impacts the use of the QMK Configurator: https://config.qmk.fm/#/keychron/q6/iso_encoder/LAYOUT_iso_110
The maintainer, @lalalademaxiya1, should have a look at this when time will allow it.

**Comment by adophoxia** [comment]
Tested the recommended change you suggested myself and it does correctly show the `KC_NUBS`/ `<>` key when loading the `info.json` file into Configurator via `Ctrl + Shift + I`.
![image](https://user-images.githubusercontent.com/100170946/234739190-3cf5d321-0e4e-40ec-ae4f-f193b368826e.png)
