### ISSUE TITLE
[Bug] [QP] Fonts don't render with `--no-ascii --unicode-glyphs "..."` 

### ISSUE THREAD

**Issue by tzarc** [qmk/qmk_firmware#20624]
### Describe the Bug

If disabling ASCII glyph generation, then supplying a subset of ASCII glyphs in order to only include needed glyphs, subsequent rendering of those glyphs at runtime doesn't work.

### Keyboard Used

tzarc/djinn

### Link to product page (if applicable)

-

### Operating System

-

### qmk doctor Output

```text
-
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

-

### Additional Context

-

**Comment by sigprof** [comment]
The unicode branch of `qp_drawtext_prepare_glyph_for_render()` has:
```c
                uint32_t data_offset  = sizeof(qff_font_descriptor_v1_t)
                            // Skip the font descriptor
                                       + sizeof(qff_ascii_glyph_table_v1_t)
                            // Skip the ascii table
```
That `+ sizeof(qff_ascii_glyph_table_v1_t)` probably needs to be `+ (qff_font->has_ascii_table ? sizeof(qff_ascii_glyph_table_v1_t) : 0)`.
