### ISSUE TITLE
concern about new imgur policy to delete some "old, unused, and inactive content that is not tied to a user account"

### ISSUE THREAD

**Issue by jepler** [qmk/qmk_firmware#20674]
### Issue Description

.. according to https://help.imgur.com/hc/en-us/articles/14415587638029-Imgur-Terms-of-Service-Update-April-19-2023- and https://arstechnica.com/gadgets/2023/04/hosting-site-imgur-will-remove-explicit-and-anonymous-content-next-month/

I know I uploaded an image not associated with an imgur user; I have no idea how imgur will determine "active" content, but it seems like a valid concern that some images referred to by qmk_firmware could be bound for deletion.

So, I wrote a script that grabs all the imgur images in markdown files. The script & the images are at https://github.com/jepler/qmk_images -- it totals about 500MB.

If it's desirable, I would be happy to (A) transfer this repo to qmk organization and (B) script or help script a mass change to use images from qmk_images on github instead of imgur. 

I recognize that I'm well outside the process that led to imgur being chosen as a preferred image host, so I'm not super invested in any particular outcome. I mostly want to help ensure this community is aware of a possible impending problem, and grabbing copies of all the relevant images turned out to be pretty easily done.

(investigating this is what led me to file #20673 about broken image links)

**Comment by jackhumbert** [comment]
Thanks for bringing this up and creating the repo of the images! It looks like the way you did it will make it pretty easy to automate a transition of the existing references. @noroadsleft also has a [repo of some manually archived images](https://github.com/noroadsleft/qmk_images) that we may be able to use to fill in some gaps. I think storing them all on Github should work, but we can also create some sort of mirror with a DigitalOcean Space if we'd need something self-hosted. 

As far as next steps, transferring the repo to the `qmk` org would be great!

**Comment by jepler** [comment]
@jackhumbert I do not have permissions to transfer directly to qmk organization. I see you're an organization member, would it be appropriate to transfer it to you so that you can transfer it into the organization?

**Comment by jackhumbert** [comment]
@jepler that'd be perfect - thanks!

**Comment by jepler** [comment]
I've offered the repo for transfer.
