### ISSUE TITLE
Support for the TN (Tony Studio) Alice + Owlab Spring clone / GPL Violation

### ISSUE THREAD

**Issue by indrora** [qmk/qmk_firmware#20803]
### Issue Description

There's a version of the Owlab Spring called the TN Alice Spring being sold on Aliexpress: https://www.aliexpress.us/item/3256805164071282.html

This appears to be also sold by G Cables in the Philippines: https://gcustomcables.com/products/custom-case-spring with a nice shot of the back of the pcb: https://cdn.shopify.com/s/files/1/0533/4056/9779/products/AcrylicSpringPCB.jpg

I've bought one of these and done some ground research:

* Built around a clone of the STM32F103 called the Geehey apm32f103cbt6 (a "drop in" replacement for the STM32)
* Ships with a stripped QMK with VIA support enabled
* Ships with a buzzer, RGB LEDs. 
* UF2 bootloader by default
* Non-populated reset button on the device?

I've reached out to KeeBox, the vendor on Aliexpress, and requested the GPL source to the board, and got told shortly "we don't have it, buzz off." I've reached out to G Cables as well.

**Comment by zvecr** [comment]
We no longer accept issues for "add support for keyboard x".

While its somewhat good to know about GPL compliance issues, its sadly up to the community to push for the files, or to not support the vendors selling the devices. We do not have the resources to handle the requests ourselves.
