### ISSUE TITLE
VIA doesn't interpret current kb config correctly.

### ISSUE THREAD

**Issue by seflm** [qmk/qmk_firmware#20898]
### Issue Description

Hello,

I have made QVEX Lynepad work with VIA using a custom matrix as it has a specific 4-way tilt switch (which is off the physical matrix). I had to make two "virtual" rows in the matrix to combine matrix and direct scanning, and make it programmable using VIA simultaneously. I've seen this method used by a few other keyboards. 

Even though, the Lynepad can be set using VIA perfectly now, it is having trouble with reading out the current configuration. All the keycodes are misplaced (apart from the first row). And I couldn't find how the VIA interprets the config in any documentation.

![Screenshot_22](https://github.com/qmk/qmk_firmware/assets/20502452/950dda9c-69fe-4530-b33c-9ad40b51bf72)
![Screenshot_23](https://github.com/qmk/qmk_firmware/assets/20502452/0b9c4376-ca97-4a87-acef-d5b939206539)

The code is in my repo fork https://github.com/seflm/qmk_firmware/tree/lynepad-rework

Any help would be appreciated

Thank you

**Comment by zvecr** [comment]
The Via team have a server here for support: https://discord.gg/4fMw7YkDfY
