### ISSUE TITLE
[Feature Request] way to have LT(1, [macro key here]) or LT(1,QK_LEADER)

### ISSUE THREAD

**Issue by DonjiKong** [qmk/qmk_firmware#21052]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

I would love to have a leader key also function as a layer key when held, and I would also like to define a macro key, and then have a way to make it a layer when held. 

I'm aware there are hacky ways to do the latter, but having an easier way to do that would be awesome, especially if there are multiple macros I want to define. 

but LT(1,QK_LEADER) is really what I'm looking for and would like to have built out. 
I tried implementing it myself in various hacky ways, but could not get it to work.

**Comment by sigprof** [comment]
1. Select some unused basic keycode (e.g., `KC_OPER`) — this keycode won't be actually sent to the host, but needs to be different from whatever else you may actually want to use in `LT()`.
2. Put `LT(1, KC_OPER)` into the keymap.
3. Intercept `LT(1, KC_OPER)` as described in the [Changing tap function](https://docs.qmk.fm/#/mod_tap?id=changing-tap-function) section (the example there shows a Mod-Tap keycode, but the method also applies to Layer Tap) and invoke `leader_start()` there.
```
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(1, KC_OPER):
            if (record->tap.count > 0) {
                if (record->event.pressed) {
                    leader_start();
                }
                return false;
            }
            break;
    }
    return true;
}
```
Having `return false;` in that branch is important — it stops any further processing of the keycode; if you return `true`, the keycode will be processed by the builtin leader key handling code, and `KC_OPER` (or `LT(1, KC_OPER)` if `LEADER_STRICT_KEY_PROCESSING` is defined) will be also inserted into the leader sequence.

If you want to add macros, you may override other `LT()` combinations in a similar way; you just need to select some distinct basic keycodes for placeholders.
