### ISSUE TITLE
Read and save current RGB mode after power cycle?

### ISSUE THREAD

**Issue by TurboMech** [qmk/qmk_firmware#2109]
Trying to get a few things working within RGB layer toggling and RGB keycode indication (CAPS_LOCK).   But no matter what after setting the `RGB_MOD` the setting does not save or persist after reboot of keyboard. 

I figured running the code under macros `const macro_t *action_get_macro(keyrecord_t *record, uint8_t id, uint8_t opt)` would bog down the keyboard so I opted for `bool process_record_user(uint16_t keycode, keyrecord_t *record) {`.  No matter what however I can't get the `RGB_MOD` to persist after reboot, it appears to have saved (meaning it will be in the last mode and HSV).  However,  as soon as you press a key that changes the RGB mode it will revert to `rgb_mode(1)` (meaning solid color), but the HSV will remain the same.

Here is the code I'm currently working with.  If you have any recommendations please let me know

CONFIG.C  for USERSPACE (just for testing purposes):

```
#include "turbomech.h"
#include "quantum.h"
#include "action_layer.h"
#include "action.h"
#include "rgblight.h"

extern keymap_config_t keymap_config;
extern rgblight_config_t rgblight_config;
bool RGB_INIT = false;
bool TOG_STATUS = false;
bool caps_is_active = false;
int RGB_current_mode;

void matirx_scan_kb (void) {
  if (RGB_INIT) {} 
  else {
    RGB_current_mode = rgblight_config.mode;
    RGB_INIT = true;
        }
  rgblight_mode(RGB_current_mode);   // revert RGB to initial mode 
  //prior to RGB mode change
  TOG_STATUS = false;
}
void persistent_default_layer_set(uint16_t default_layer) {
  eeconfig_update_default_layer(default_layer);
  default_layer_set(default_layer);
}
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case KC_CAPS:
     if (record->event.pressed) {
        register_code(KC_CAPS);
        caps_is_active = !caps_is_active;
      if (caps_is_active) {
        rgblight_mode(14);
      } 
      else if (!caps_is_active) {
        unregister_code(KC_CAPS);
        rgblight_mode(RGB_current_mode);
      }
    }
    return false;
    break;
    case RGB_MOD:
    //led operations - RGB mode change now updates the RGB_current_mode 
    //to allow the right RGB mode to be set after reactive keys are released
    if (record->event.pressed) {
      rgblight_mode(RGB_current_mode);
      rgblight_step();
      RGB_current_mode = rgblight_config.mode;
      // rgblight_set();
    }
    return false;
    break;
    case KC_RESET:
    if (record->event.pressed) {
      rgblight_enable();
      rgblight_mode(1);
      rgblight_setrgb(255, 255, 255);
      //_delay_ms(2000);
      reset_keyboard();
    }
    return false;
    break;

  return true;
  break;
  }
  return process_record_keymap(keycode, record);
};
```

CONFIG.H again for USERSPACE (testing purposes)
```
#ifndef USERSPACE
#define USERSPACE

#include "quantum.h"

// Definine layer names
#define _QWERTY 0
#define _FUNCTION 1
```

Config.h also has `enum` keycodes and color settings but excluded due to size.

**Comment by drashna** [comment]
Yeah, I had this issue, as well.  

I just use `rgblight_sethsv` rather than setrgb, since it works better.
