### ISSUE TITLE
[Feature Request] Document split fields in info.json

### ISSUE THREAD

**Issue by scottyeager** [qmk/qmk_firmware#21140]
### Feature Request Type

- [x] Documentation

### Description

Currently, the [reference_info_json](https://docs.qmk.fm/#/reference_info_json) page doesn't include any information about the subkeys of `split`. The [schema section](https://github.com/qmk/qmk_firmware/blob/e1c4b7ce30fde339f0f3c284aa5142bee66a6a4e/data/schemas/keyboard.jsonschema#L559) is helpful, along with referencing some existing configs, but it would be great to have this in the docs.

**Comment by fauxpark** [comment]
I'm already working on a rewrite of the info.json reference page. Expect that soon-ish.
