### ISSUE TITLE
If TO(XX) exceeds 16 floors, an error will occur. For example, if 32 floors are enabled by config, if TO(0) is selected in vial, the actual output is TO(16), TO(1) is TO(17)...There is no within 16 floors this mistake

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#21166]
If TO(XX) exceeds 16 floors, an error will occur. For example, if 32 floors are enabled by config, if TO(0) is selected in vial, the actual output is TO(16), TO(1) is TO(17)...There is no within 16 floors this mistake

**Comment by sigprof** [comment]
Vial-specific problems should be reported to the [vial-qmk repo](https://github.com/vial-kb/vial-qmk) (which you apparently already did); although the actual problem might be in the Vial GUI part.

`TO(n)` did not support layers above 15 before #17989 — but that change is present in the vial-qmk code too; maybe the Vial app has some keycode mismatch issues though (VIA certainly did for some time).
