### ISSUE TITLE
STM32F103 I2C boot error

### ISSUE THREAD

**Issue by KalamityStorm** [qmk/qmk_firmware#21185]
### Issue Description

hi,recentely i've update my QMK to v0.18 to v0.21.
but in this version,my firmware cannot boot correctly when i plug an I2C hardware(e.g. OLED).

when i plug an OLED and plug into my computer, device manager cannot detect any hardware(not even VID0000_PID0002),it just a blank in usbdevice.

but strange thing is,when i press RST switch ,it can boot to STM32duino bootloader well.and i also can download firmware correctly.

it seems when i deploy I2C function in firmware,and plug a device,then it will not boot correctly,and i didn't find out what happened.

i'm uses STM32F103RCT6,here are my codes for OLED and I2C:

in halconf.h:
`#define HAL_USE_I2C TRUE`

in mcuconf.h:
```
#define HAL_USE_I2C TRUE

#undef STM32_I2C_USE_I2C1
#define STM32_I2C_USE_I2C1 TRUE
```

in rules.mk:
```
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
OLED_TRANSPORT = i2c
```

in config.h:
```
#define OLED_IC OLED_IC_SH1106
#define OLED_COLUMN_OFFSET 2
#define OLED_DISPLAY_128X64

#define OLED_BRIGHTNESS 255
#define OLED_FADE_OUT 
```

i tried old firmware compile in v0.18 it shows good,only failed in v0.21.
thanks!

**Comment by SUzhouTaoTao** [comment]
rules.mk 
EEPROM_DRIVER = i2c
