### ISSUE TITLE
[Feature Request] add general lighting section to docs

### ISSUE THREAD

**Issue by CC-Ian** [qmk/qmk_firmware#21218]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

It'd be great to have the lighting header of of the docs go to a page or section containing the information from the bot in discord. I expect this to make the information much easier to find and comprehend.

![Screenshot_20230611-211546_1_1](https://github.com/qmk/qmk_firmware/assets/98569654/276d1ade-bc79-4dc0-ba39-fd58315b4512)

**Backlight**
Single color, per key, not individually addressable (all on or off) [(docs)](https://docs.qmk.fm/#/feature_backlight)

**RGBLight**
Underglow RGB, linear design (single chain), individually addressable [(docs)](https://docs.qmk.fm/#/feature_rgblight)

**LED Matrix**
Single color, per key, individually addressable [(docs)](https://docs.qmk.fm/#/feature_led_matrix)

**RGB Matrix:**
RGB, per key, individually addressable [(docs)](https://docs.qmk.fm/#/feature_rgb_matrix)

**Indicators:**
Scroll/Caps/Num Lock LEDs [(docs)](https://docs.qmk.fm/#/feature_led_indicators)

**Comment by myst729** [comment]
IMHO, `lighting` clearly addresses its use cases - visual effects. But [LED Indicators](https://docs.qmk.fm/#/feature_led_indicators?id=led-indicators) may not. It could have a more general name like `indicators`. LED is absolutely the most common use case, but you could do anything with the digital signal, e.g. drive a buzzer for blind people. It's for indicating, and has nothing to do with visual effects.
