### ISSUE TITLE
[Feature Request] Pico W BLE support

### ISSUE THREAD

**Issue by doesntfazer** [qmk/qmk_firmware#21229]
### Feature Request Type

- [ ] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Now that the Pico W has it's BLE enabled in the latest SDK, I would like to see about getting the BLE working for the pico w in QMK. 

Checked and I hadn't seen anything about this being added in the documentation or any feature requests for it yet.

**Comment by ams1** [comment]
Hi @doesntfazer - thanks for starting this issue. Any updates here?

I'd like to contribute somehow.

**Comment by ItsTerm1n4l** [comment]
+1

**Comment by MananShah9** [comment]
Any update?
