### ISSUE TITLE
LT([layer], [keycode]) not taking function from new layer into account

### ISSUE THREAD

**Issue by Pawnerd** [qmk/qmk_firmware#2128]
I am not sure if this should be considered as an issue or more as an (un)documented feature. 

To keep stuff simple, this example is given for a 2x1 keyboard, with this keymap:
KEYMAP = {
 [0] = { LT(2, KC_A), KC_B  },
 [1] = { LT(3, KC_C), KC_D  },
 [2] = { TRNS, TO(1) },
 [3] = { TRNS, TO(0) },
}

When the user is in layer 0 and holds the first key down and presses+releases the second key, he lands into layer 1. To be able to go back to layer 0, the user first has to release the first key, and press it again to let the `LT(3, KC_C)` take into effect. Is there a way to not requiring the user to release and press the first button? So that he/she can keep the first button down and easily switch between the two layers by repeatedly pressing the second button?

I understand that if qmk would do this for any sort of keycode, it would cause many undesired situations, but wouldn't the `LT()` command be a exception?

**Comment by drashna** [comment]
I believe that this has to do with the way that the layer stacking system works.  And more specifically, with the fact that TO() overrides all of the other layers, IIRC.  

so, for this example, I don't think  there is a good solution here, that doesn't leave you stuck.
