### ISSUE TITLE
Unable to set individual led color

### ISSUE THREAD

**Issue by dz46** [qmk/qmk_firmware#21319]
### Describe the Bug

When I'm trying to set an individual LED color, it seems not to work. In my prevoius tests I was getting a very fast color-change, which was immediately  overridden again. 

Current behavior is: After boot, whole keyboard is red, after pressing a button no change of an LED to RGB_BLUE can not be observed. (Setting all colors with `rgb_matrix_sethsv_noeeprom` works

config.h
```
#pragma once

#define RGB_MATRIX_LED_COUNT 9
#define RGB_DI_PIN E2
#define RGB_DISABLE_WHEN_USB_SUSPENDED
#define ENABLE_RGB_MATRIX_SOLID_COLOR
```
keymap.c
```
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    rgb_matrix_set_color(8, RGB_BLUE);

    return true;
};

void keyboard_post_init_user(void) {
    rgb_matrix_enable_noeeprom();
    rgb_matrix_mode(RGB_MATRIX_SOLID_COLOR);
    rgb_matrix_sethsv_noeeprom(HSV_RED);
}
```

I'm thankful for any insight on this...  

### Keyboard Used

ymdk/ymd09

### Link to product page (if applicable)

https://ymdkey.com/products/ymd-9-acrylic-numpad-qmk-via-rgb-hotswap-supported-gaming-photoshop

### Operating System

Windows

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by sigprof** [comment]
You can't use `rgb_matrix_set_color()` outside of indicator callbacks, unless you first use `rgb_matrix_set_flags()` to exclude some LEDs from effects.  The RGB matrix code refreshes all LEDs which are used by effects approximately 60 times per second (this is controlled by `RGB_MATRIX_LED_FLUSH_LIMIT`, which is the desired refresh period in milliseconds; the default value (16 ms) corresponds to ≈62.5 updates per second).  So if you just call `rgb_matrix_set_color()` at some random time, your change is likely to be overwritten again after at most 16 ms.

Some effects don't refresh all LEDs on every update, and with those effects you may be able to observe the result of random `rgb_matrix_set_color()` for some significant time; but those effects are an exception, and most effects just recalculate the state of all LEDs every update cycle, overwriting any manual changes.  The only reliable method to override the LED state which is set by effects is to implement `rgb_matrix_indicators_user()` (or `rgb_matrix_indicators_advanced_user()`) and perform your changes there — those functions are called on every update cycle after applying the effect, and any LED state which is set in those functions would persist until the next update cycle, at which time the function will be called again.
