### ISSUE TITLE
Add Keychron K10 Pro (is QMK compatible)

### ISSUE THREAD

**Issue by CinnamonDLX** [qmk/qmk_firmware#21371]
As advertised this is a QMK and VIA compatible keyboard. 
_(see link https://www.keychron.com/products/keychron-k10-pro-qmk-via-wireless-mechanical-keyboard)_

Can't find it in the drop down menu on your website _https://config.qmk.fm/_

Could you please add the board, as I don't want to brick mine while tinkering with QMK Firmware :D

**Comment by zvecr** [comment]
> Please refrain from asking maintainers to add support for specific keyboards -- it is unlikely they will have hardware available, and will not be able to help.
Your best bet is to take the initiative, add support, then submit a PR yourself.
