### ISSUE TITLE
[Feature Request] Morse Code

### ISSUE THREAD

**Issue by IllustratedMan-code** [qmk/qmk_firmware#21419]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

## The vision
You can set a key/2 keys to act as a Morse code key. When you press this key, QMK will interpret the long/short key sequences into characters (if 2 keys are set, one is long, the other short). Things like delay for character separation could be configurable.

## Why this would be cool
- It would be great for learning Morse code!
- 1 key keyboards would actually be feasible (30 wpm is possible!)
- It doesn't just have to be morse code. Maybe macros/keycodes could be bound to certain sequences. SOS could shut down the computer! 

## Implementation
I'm happy to try to implement this myself, but I would love it if someone could point me in the right direction on the source code. It should be simple to implement, but any tips would be great!

**Comment by Stanley00** [comment]
@IllustratedMan-code There's one implementation here, which based on timing different between dit and dash. You can also add two custom keycodes for as QK_DIT and QK_DASH so the  `process_record_user` function would be a little bit simpler:

https://github.com/daliusd/qmk_firmware/blob/morsilka/keyboards/a_dux/keymaps/morsilka/keymap.c

**Comment by myst729** [comment]
Interesting idea.

**Comment by IllustratedMan-code** [comment]
@Stanley00 Thanks! Looks like I would put the implementation  in the `qmk/quantum` directory right?

**Comment by Stanley00** [comment]
> @Stanley00 Thanks! Looks like I would put the implementation in the `qmk/quantum` directory right?

I would suggest you put the implementation in your keyboard keymap folder, the same as in the repos in shared above.

**Comment by pochoi** [comment]
I am wondering whether you are thinking about ["Straight Key" or "Semi-Automatic Key"](https://morsecode.world/keys.html#:~:text=A%20%22bug%22%20or%20%22semi,left%20or%20to%20the%20right.). It would be interesting to see an implementation of "Semi-Automatic Key".
