### ISSUE TITLE
Update Input Club keyboards to use I:C Vendor ID and matching device IDs

### ISSUE THREAD

**Issue by belak** [qmk/qmk_firmware#2143]
Relevant conversation is in the following comments:

- https://github.com/qmk/qmk_firmware/pull/1963#discussion_r149540325
- https://github.com/qmk/qmk_firmware/pull/1963#issuecomment-342670875
- https://github.com/qmk/qmk_firmware/pull/1963#issuecomment-342842597
- https://github.com/qmk/qmk_firmware/pull/1963#issuecomment-342919138

Essentially, this will allow even keyboards flashed with QMK to show up in the Input Club configurator.

**Comment by tengg** [comment]
Hi,
Just noticed the k-type support has been checked in.
How to flash it? Using what target?

Thanks

**Comment by tengg** [comment]
nvm, found it's dfu-util.

Just wondering if it works with RGB lighting?

**Comment by belak** [comment]
The QMK port for the K-Type doesn't support LEDs at all yet. Support needs to be written for the chip which controls the lighting and I'm not as familiar with how that works.

**Comment by tengg** [comment]
Thanks.
Another issue is the boot magic jump to bootloader seems not working.
I didn't see the bootloader size set in rules.mk, is it supposed to set some value or this chipset is different?

**Comment by drashna** [comment]
Looks like it's missing a "`BOOTLOADER = `" line is missing from the "rules.mk" file. 

`BOOTLOADER=atmel-dfu` may be the right option here, but I'm not sure.

**Comment by belak** [comment]
The bootloader shouldn't be overwritten as far as I know. Input:Club uses a custom bootloader.

However, I reverted this a while back which may have broken it. I thought I tested it but maybe there were stale objects or something.

https://github.com/qmk/qmk_firmware/commit/eb98af673a999ede17e293e00220b43d717d500f

**Comment by belak** [comment]
@tengg What makes you think the magic jump to bootloader isn't working? As far as I can tell, this port is working on my K-Type. The one oddity is that only the left USB port works.

**Comment by drashna** [comment]
Looks like the K-Type is using Input Club info, but the other boards are not. 

I'd add them myself, but I don't own a board to verify.
