### ISSUE TITLE
STM32F103 pin problem

### ISSUE THREAD

**Issue by aihk** [qmk/qmk_firmware#21525]
A13, A14 of STM32F103 Can it be used as a matrix pins?

**Comment by sigprof** [comment]
A13 and A14 are SWD pins, and on STM32F103 you need to change some special remapping bits to use those pins as plain GPIOs:
```c
void board_init(void) {
    // JTAG-DP Disabled and SW-DP Disabled
    AFIO->MAPR = (AFIO->MAPR & ~AFIO_MAPR_SWJ_CFG_Msk) | AFIO_MAPR_SWJ_CFG_DISABLE;
}
```
This may interfere with using SWD to reflash the bootloader, if you ever need to do that (you would need to perform the “connect under reset” procedure).
