### ISSUE TITLE
[Feature Request] Add support for the Keychron K5 RGB

### ISSUE THREAD

**Issue by nikolmedo** [qmk/qmk_firmware#21602]
### Feature Request Type

- [X] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Add full support to the Keychron K5.

## Feature Request Type

- [ ] Remapping 
- [ ] RGB control
- [ ] Macros

## Description

There is already support for several K-series keyboards, but no support for the K-5 model at all.

**Comment by zvecr** [comment]
> Please refrain from asking maintainers to add support for specific keyboards -- it is unlikely they will have hardware available, and will not be able to help.
Your best bet is to take the initiative, add support, then submit a PR yourself.
