### ISSUE TITLE
[Bug] PERMISSIVE_HOLD broken after 0.20.8

### ISSUE THREAD

**Issue by NaLG** [qmk/qmk_firmware#21632]
### Describe the Bug

Building on apple silicon, I'm finding that PERMISSIVE_HOLD does not work starting with 0.21.0.  Rolling modifiers submit both keys.  Reverting to 0.20.8 and rebuilding fixes this issue.

eg.

RSFT_R(KC_SLSH)  pushed down
KC_J     pushed down
RSFT_R(KC_SLSH)  released  (before TAPPING_TERM?)
KC_J     released before TAPPING_TERM

will output:  /j  - Not desired

RSFT_R(KC_SLSH)  pushed down
KC_J     pushed down
KC_J     released
RSFT_R(KC_SLSH)  released

will output:  J  - as expected

### Keyboard Used

atreus62

### Operating System

macos Ventura 13.4.1

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

BTT

**Comment by sigprof** [comment]
Your description is exactly how `PERMISSIVE_HOLD` is supposed to work — it treats the “nested press” case (the second of your examples) as a hold, but the “rolling press” (the first of your examples) is handled as a tap.  If you want the rolling press case to be handled as a hold too, you need to use the `HOLD_ON_OTHER_KEY_PRESS` mode.

You may be seeing the effect of the [`IGNORE_MOD_TAP_INTERRUPT` removal](https://docs.qmk.fm/#/ChangeLog/20230528?id=i-m-t-i) that has been done in 0.21.0 — before that version the special code for `MT()` keys still existed and could provide the behavior similar to `HOLD_ON_OTHER_KEY_PRESS` even if a different mode was configured; after that version `MT()` keys are always treated exactly like other dual-role keys (e.g., `LT()`), and you need to use `HOLD_ON_OTHER_KEY_PRESS` (or the per-key version) appropriately.
