### ISSUE TITLE
GD32F103 MUC problem

### ISSUE THREAD

**Issue by aihk** [qmk/qmk_firmware#21660]
I used to use the MUC of GD32F103C8T6. Can I not use it now? How to use GD32F103C8T6

**Comment by lowJ** [comment]
Try using the GD32 specific stm32duino bootloader:
https://github.com/rogerclarkmelbourne/STM32duino-bootloader/blob/master/binaries/gd32f1_generic_boot20_pc13.bin

Im using the gd32f103c8t6 and once I used the gd32 specific bootloader I could flash my keyboard using qmk toolbox.
