### ISSUE TITLE
[Feature Request] LED indicator for One Shot Key

### ISSUE THREAD

**Issue by lesca** [qmk/qmk_firmware#21681]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

Hello, 
I am using one shot key but to find it's easy to forget the status that if "one shot key" is on or off.

Currently, I define this to auto timeout one shot key after 2s. 
```C
#define ONESHOT_TIMEOUT 2000  /* Time (in ms) before the one shot key is released */
```

However, I think it would be better if there could be a LED indicator as **CAPS_LOCK** does. That is, when I hit CAPS_LOCK, the LED under the key is on; and when I hit it again, the LED is off.

Do you think it is possible to implement this for One Shot Key? Or can you point me to a direction to implement it myself. 

One shot key is really a good feature. Thanks for your great efforts!

Regards,
Lesca

**Comment by drashna** [comment]
`get_oneshot_mods` and `is_oneshot_layer_active()` can be used to determine the status. 

I use `get_oneshot_mods` to display the mod status on my oleds.
