### ISSUE TITLE
PS/2 Protocol

### ISSUE THREAD

**Issue by HelpNeeder** [qmk/qmk_firmware#21706]
### Feature Request Type

- [ ] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

I need PS/2 output for as I have issues with USB not supporting Older Keyboards.
Also why doesn't QMK support something as common as PS/2 its on almost every motherboard?

**Comment by tzarc** [comment]
Because QMK targets USB.
