### ISSUE TITLE
QMK DFU bootloader generation,echo missing '-e' with '\n'

### ISSUE THREAD

**Issue by YCF** [qmk/qmk_firmware#2171]
file:tmk_core/avr.mk

line 249:
`echo "#ifndef QMK_KEYBOARD\n#define QMK_KEYBOARD\n" > lib/lufa/Bootloaders/DFU/Keyboard.h`
should be:
`echo -e "#ifndef QMK_KEYBOARD\n#define QMK_KEYBOARD\n" > lib/lufa/Bootloaders/DFU/Keyboard.h`

line 246
`echo "\n#endif" >> lib/lufa/Bootloaders/DFU/Keyboard.h`
should be:
`echo -e "\n#endif" >> lib/lufa/Bootloaders/DFU/Keyboard.h`

missing the `-e` .

There is no time to install Git.
I'm sorry,Jack  ;-p

**Comment by drashna** [comment]
This has been fixed (in #2517, it looks like)
