### ISSUE TITLE
Opposite to LT(layer, kc) ?? Turn on layer when tapped, kc when held..

### ISSUE THREAD

**Issue by andmarti1424** [qmk/qmk_firmware#21739]
hello. 

I cannot seem to find an answer for "Turn on layer when tapped, kc when held" in here `https://docs.qmk.fm/#/keycodes`
My personal use case would be to switch to a layer NUM when tapped, and LALT when held..
Thank you!

**Comment by filterpaper** [comment]
You can code the solution for your use case with [intercepting mod tap](https://docs.qmk.fm/#/mod_tap?id=intercepting-mod-taps).

**Comment by glebsexy** [comment]
Indeed, that's what I ended up doing:

```
// hold for cmd, tap for layer
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(BASE, KC_RCMD):
            if (record->tap.count && record->event.pressed) {
                layer_move(BASE); // Intercept tap function to move to base
            } else if (record->event.pressed) {
                register_mods(MOD_MASK_GUI); // Intercept hold function to hold CMD
            } else if (!record->event.pressed) {
                unregister_mods(MOD_MASK_GUI); // Unpress CMD
            }
            return false;
    }
    return true;
}
```

**Comment by filterpaper** [comment]
The keycode `LGUI_T()` will activate GUI/CMD on hold as a normal function. So you can use that and just add codes to intercept tap. Do change the status of this issue if the matter is resolved.

**Comment by glebsexy** [comment]
Oh that's even better, thanks! Will change this in my keymap. This issue isn't mine though, I just wanted to chime in as I had the same question :)

**Comment by andmarti1424** [comment]
Will try this and report back. Thanks

**Comment by glebsexy** [comment]
Here is the updated code using the mod-tap feature:

```

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        // hold for cmd, tap for layer
        case RCMD_T(KC_NO):
            if (record->tap.count && record->event.pressed) {
                layer_move(BASE); // Intercept tap function to move to base
            } else {
                return true; // process hold normally
            }
            return false;
    }
    return true;
}
```

**Comment by filterpaper** [comment]
> Here is the updated code using the mod-tap feature:
> 
> ```
> 
> bool process_record_user(uint16_t keycode, keyrecord_t *record) {
>     switch (keycode) {
>         // hold for cmd, tap for layer
>         case RCMD_T(KC_NO):
>             if (record->tap.count && record->event.pressed) {
>                 layer_move(BASE); // Intercept tap function to move to base
>             } else {
>                 return true; // process hold normally
>             }
>             return false;
>     }
>     return true;
> }
> ```

Try
```c

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        // hold for cmd, tap for layer
        case RCMD_T(KC_NO):
            if (record->tap.count && record->event.pressed) {
                layer_move(BASE); // Intercept tap function to move to base
                return false;
            }
            break;
    }
    return true;
}
