### ISSUE TITLE
Questions about the QMK Configurator

### ISSUE THREAD

**Issue by ctt-t** [qmk/qmk_firmware#21759]
I fixed some bugs in my firmware and pushed them to the develop branch, but I didn't see any changes in the QMK Configurator, I wanted to know why

**Comment by fauxpark** [comment]
Configurator uses the master branch, not develop. Check back at the end of the month when it gets merged into master. https://docs.qmk.fm/#/breaking_changes?id=when-is-the-next-breaking-change
