### ISSUE TITLE
[Bug] KC_PLUS in MT() generates "=" instead "+" (shifted "=")

### ISSUE THREAD

**Issue by LemeRus** [qmk/qmk_firmware#21778]
### Describe the Bug

Default keymap use KC_PPLS to print "+".
`#define PLS_LCT MT(MOD_LCT, KC_PPLS)`
It works until I need not symbol "±" (Lvl3mod + Shift + KC_EQL).
When I tried to compile firmware with KC_PLUS instead KC_PPLS, I got kb without "+" on _LOWER layer at all. KC_PLUS in MT() function just sends "=".
`#define PLS_LCT LCTL_T(KC_PLUS)` has same effect, "=" instead "+"
Why can be so?

### Keyboard Used

jorne/rev1

### Operating System

Linux Mint Cinnamon 21 x86_64

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by LemeRus** [comment]
Now I fixed it with
```c
    case (PLS_LCT):
      if(record->tap.count && record->event.pressed) {
        tap_code16(KC_PLUS);
      }
      return false;
```
in process_record_user, but it's local fix :(

**Comment by filterpaper** [comment]
This is not a bug. See this [caveat section](https://docs.qmk.fm/#/mod_tap?id=caveats) for details.
