### ISSUE TITLE
`qmk flash` does not detect correct bootloader for Elite C 

### ISSUE THREAD

**Issue by xela144** [qmk/qmk_firmware#21779]
### Describe the Bug

Following the getting started guide, completed all steps up to "Flash your Keyboard from the Command Line". 

```
(master) alex:/home/alex/qmk_firmware
~> qmk flash -kb crkbd/rev1 -km alex
Ψ Compiling keymap with gmake --jobs=1 crkbd/rev1:alex:flash


QMK Firmware 0.21.6
Making crkbd/rev1 with keymap alex and target flash

avr-gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  26160	      0	  26160	   6630	crkbd_rev1_alex.hex

Compiling: quantum/keymap_introspection.c                                                           [OK]
Linking: .build/crkbd_rev1_alex.elf                                                                 [OK]
Creating load file for flashing: .build/crkbd_rev1_alex.hex                                         [OK]
Copying crkbd_rev1_alex.hex to qmk_firmware folder                                                  [OK]
Checking file size of crkbd_rev1_alex.hex                                                           [OK]
 * The firmware size is fine - 26160/28672 (91%, 2512 bytes free)
Flashing for bootloader: caterina
Waiting for USB serial port - reset your controller now (Ctrl+C to cancel)..............
```

At this point it just waits forever.

The docs state that I should see an error:

> WARNING: This board's bootloader is not specified or is not supported by the ":flash" target at this time.

However, no such error appears. After some digging on the internet, I discovered that passing a `-bl dfu` option will cause qmk to use the right bootloader.

This ticket is simply a usability request: It would be nice if the user were alerted to the problematic bootloader as promised in the docs. As it stands now, I had to doubt whether the reset button was soldered correctly, if there was a special sequence of plugging cables, etc.

Thanks for the awesome project. :clap:

### Keyboard Used

crkbd/rev1

### Operating System

Pop OS 22

### qmk doctor Output

```text
~> qmk doctor
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.2
Ψ QMK home: /home/alex/qmk_firmware
Ψ Detected Linux (Pop!_OS 22.04 LTS).
Ψ Git branch: master
Ψ Repo version: 0.21.6
Ψ - Latest master: 2023-08-16 09:01:11 +0100 (190738c66d) -- The PoweredByPorridge layout for the Keyboardio Atreus (#21737)
Ψ - Latest upstream/master: 2023-08-16 09:01:11 +0100 (190738c66d) -- The PoweredByPorridge layout for the Keyboardio Atreus (#21737)
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: 2023-08-16 09:01:11 +0100 (190738c66d) -- The PoweredByPorridge layout for the Keyboardio Atreus (#21737)
Ψ - Common ancestor with upstream/develop: None
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.3.1
Ψ Found avr-gcc version 5.4.0
Ψ Found avrdude version 6.3-20171130
Ψ Found dfu-programmer version 0.6.1
Ψ Found dfu-util version 0.9
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2023-04-15 13:48:04 +0000 --  (11edb1610)
Ψ - lib/chibios-contrib: 2023-01-11 16:42:27 +0100 --  (a224be15)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by zvecr** [comment]
> qmk flash does not detect correct bootloader for Elite C

It does if it has been configured to use the correct bootloader. It cannot automagically work this out.

<https://docs.qmk.fm/#/flashing?id=atmel-dfu>

Adding a keymap level `rules.mk` with `BOOTLOADER = atmel-dfu` will correct this.

> The docs state that I should see an error:

From the line before that in the docs, `However, this does rely on the bootloader being set by the keyboard`. Maybe the later line could be clarified slightly better. But the default for that keyboard is set to `caterina` and thus why it is expecting to find a matching device.

> It would be nice if the user were alerted to the problematic bootloader as promised in the docs.

Unfortunately this is not possible, as the command line environment has zero knowledge of what development board has been installed.
