### ISSUE TITLE
[Bug] RETRO_SHIFT doesn't work

### ISSUE THREAD

**Issue by VasilyKrainov** [qmk/qmk_firmware#21794]
### Describe the Bug

`rules.mk`:
`AUTO_SHIFT_ENABLE = yes`
`config.h`:
 `#define RETRO_SHIFT 1000`

Holding and releasing `GUI_T(KC_F)` shows nothing, but `F` should be shown. Using `#define RETRO_SHIFT` without the value doesn`t give desired result neither.

### Operating System

MacOS 13.5

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by IsaacElenbaas** [comment]
Did you add `GUI_T(KC_F)` to Auto Shift with [`get_custom_auto_shifted_key`](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_auto_shift.md#auto-shift-per-key)? The docs were just updated to make it more clear that that is also a necessary step.

**Comment by VasilyKrainov** [comment]
It helps, thank you so much!
