### ISSUE TITLE
[Bug]  b_sides/rev41lp 

### ISSUE THREAD

**Issue by Blunderbuss** [qmk/qmk_firmware#21873]
### Describe the Bug

qmk compile -kb b_sides/rev41lp -km default
Ψ Compiling keymap with make --jobs=1 b_sides/rev41lp:default

QMK Firmware 0.14.29
      1 [] make 320 cygwin_exception::open_stackdumpfile: Dumping stack trace to make.exe.stackdump
☒ Invalid return_code: 35584

### Keyboard Used

b_sides/rev41lp

### Operating System

Win10

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.1
Ψ QMK home: C:/Users/Matt/qmk_firmware
Ψ Detected Windows 10 (10.0.19045).
Ψ Git branch: master
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.1.0
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 7.0
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ QMK is ready to go
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Additional Context

Downloaded files directly from https://github.com/qmk/qmk_firmware/tree/master/keyboards/b_sides/rev41lp

**Comment by fauxpark** [comment]
Your repo is out of date.
