### ISSUE TITLE
[Feature Request] Enable double-reset for bootsel for RP2040-based chips

### ISSUE THREAD

**Issue by t-8ch** [qmk/qmk_firmware#21974]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

To enter the bootloader/flashing mode on RP2040 the BOOT button needs to be pressed.

When used as a pro-micro replacement there is no pin broken out for the BOOT button so one has to use the button on the board itself. However that button may be hard or even impossible to access, for example when the board is mounted upside-down.

The pico-sdk already contains a small utility[0] that is meant to provide double-reset to bootsel on a RP2040.
Maybe it can be enabled in QMK.

[0] `lib/pico-sdk/src/rp2_common/pico_bootsel_via_double_reset/pico_bootsel_via_double_reset.c`

**Comment by Kriechi** [comment]
@t-8ch is this what you are looking for?
https://github.com/qmk/qmk_firmware/blob/master/docs/platformdev_rp2040.md#double-tap-reset-boot-loader-entry-iddouble-tap
