### ISSUE TITLE
i want command for one key that i want to enter 2 times at 1 click

### ISSUE THREAD

**Issue by 23UMANG23** [qmk/qmk_firmware#22083]

**Comment by 23UMANG23** [comment]
i want to use enter button twice with single use

**Comment by JellyTitan** [comment]
Have you read through the [macro documentation](https://docs.qmk.fm/#/feature_macros)? 
It sounds like that's what you're looking to accomplish:
>Macros allow you to send multiple keystrokes when pressing just one key

**Comment by 23UMANG23** [comment]
Dear, i go through macro , but the concern is that i want to enter 2 times
enter button when i press that macro , i wrote down macro according it but
not working
