### ISSUE TITLE
Trackpoint as PS2 Mouse on Pro Micro clones (blue and purple ones)

### ISSUE THREAD

**Issue by herpiko** [qmk/qmk_firmware#22165]
### Issue Description

In Juli 2020, [I successfully made a trackpoint module for my keyboard](https://github.com/herpiko/unk#202007018). I was using Pro Micro clone (pictured bellow). And then last month the USB port get broken.

![image](https://github.com/qmk/qmk_firmware/assets/2534060/87a007e1-1bb4-4966-b02d-14d85098e7c8)

I believe that I was using this commit that time (July 2020):

```
commit 7ff57644e181dda1b4e577517cf72cc962bf8f9e
Author: skullY <skullydazed@gmail.com>
Date:   Fri Jul 12 12:39:57 2019 -0700

    Fix vusb compiling after clang-format
```

Unfortunately:
- I didn't remember whether I was using UART or interrupt. Most likely interrupt because D5 is already occupied by the LED
- I didn't push the modified/working code to any repo, so there is no backup

The I proceed to bought another Pro Micro clone but this time is the USB-C version (purple one, pictured bellow). It didn't work. I've switched back and forth between that commit and the master branch of QMK, also various pin. Sometime, the interrupt driver on D1 and D0 responded on my finger pressure on the trackpoint, but it's very unresponsive/unusable.

![image](https://github.com/qmk/qmk_firmware/assets/2534060/b510c59f-e20f-46ca-8627-289ae54e8e3b)

I am using this as pin reference,

![Screenshot from 2023-09-30 01-14-36](https://github.com/qmk/qmk_firmware/assets/2534060/3d0121b9-ea61-497b-a65b-aac7416b6bea)

------

In meantime, I am planning to buy the old micro-usb version of Pro Micro clone and will try again.

Question:
- Is the Pro Micro only support interrupt for the PS2 mouse? If so then I'll focus on interrupt and dropping the UART effort.
- Does the USB-C version (purple one) have different implementation with the generic pro micro (blue one)?
- Let's say I will continue using interrupt, is there any way to improve the unresponsive/jumpy movement?

Thank you!

**Comment by myst729** [comment]
- If you have any soldering tools, just remove the LED and resistor on PD5, then you can go with USART mode.
  - By the way, you could use PB0 too (the other onboard LED), just like PD5.
  - There are also a few unused pins, you can flying wire from the chip pads. This is more difficult, not recommended unless you are skilled with your tools.
- I don't have a Type-C pro micro myself. After observing it roughly I think the only difference is the USB connector. Micro USB is kinda outdated. People want one wire to do all the things (Yes, Apple sucks).
- Any possibilities that your track point module is broken?
