### ISSUE TITLE
[Feature Request] Allow configuring dip switches in info.json

### ISSUE THREAD

**Issue by tomasr8** [qmk/qmk_firmware#22176]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Encoders, for instance, can be specified either via `config.h` or via `info.json` while it seems that dip switches (e.g. `DIP_SWITCH_PINS`) can only be specified via `config.h`. Would it make sense to also support it in `info.json`?

**Comment by elpekenin** [comment]
There is an open PR for it: #22017
