### ISSUE TITLE
Adafruit Feather 32U4 LE, sending signal over Bluetooth and USB simultaneously

### ISSUE THREAD

**Issue by harshitgoel96** [qmk/qmk_firmware#2223]
I have made  a board using the Adafruite feather32u4. all of it works fine over bluetooth. but when i connect the board with a usb port, when the bluetooth is connected, it is not switching to USB only mode and send the keycode over both USB and Bluetooth.

the code and and keyboard is used from the folder mf_ble

**Comment by exiva** [comment]
There's a keycode to switch it. I think it's `OUT_BT` possibly there's a bug in the auto-select. It's been a long time since I've used qmk though.

**Comment by harshitgoel96** [comment]
documentation states that it will work on those board that support it. does it require some kind of implementation ?
