### ISSUE TITLE
[Feature Request] Modular Keymap Definitions for Improved Layer Organization

### ISSUE THREAD

**Issue by m-c-frank** [qmk/qmk_firmware#22293]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

# Problem:
When defining layers in QMK, many keys remain consistent across multiple layers. However, in the current structure, users have to redundantly specify these consistent keys for each layer. This can be especially cumbersome for layouts where only a subset of keys (e.g., thumb cluster) changes between layers.

## Proposal:
Introduce a method to define "sections" or "modules" of keys, which can be combined to build full layers. This would reduce redundancy and make the keymaps more maintainable and readable.

## Example:

Consider the base layer definition:

```c
#define MIRYOKU_LAYER_BASE \
KC_Q, KC_W, ..., KC_TAB, KC_LEFT_SHIFT, ...
```

Instead of redefining the entire layer for a slight modification in the thumb cluster, we can define modular sections:

```c
const uint16_t PROGMEM LEFT_HAND[]  = { KC_Q, KC_W, ... };
const uint16_t PROGMEM THUMB_BASE[] = { KC_TAB, KC_LEFT_SHIFT, ... };
const uint16_t PROGMEM THUMB_MOD[]  = { KC_ESC, KC_LEFT_SHIFT, ... };
```

Using these modules, layers can be constructed as:

```c
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [BASE_LAYER] = LAYOUT(
        LEFT_HAND, THUMB_BASE
    ),
    [MOD_LAYER] = LAYOUT(
        LEFT_HAND, THUMB_MOD
    ),
    // ... other layers
};
```

## Benefits:

- Reduces repetitive key definitions in keymaps.
- Provides a clearer visualization of what changes between layers.
- Offers backward compatibility, as users can opt to use the modular approach or the traditional full-layer definition.

**Comment by fauxpark** [comment]
We already have the Transparent key for exactly this purpose.
