### ISSUE TITLE
TG does not work if it is under an MT

### ISSUE THREAD

**Issue by ReagentX** [qmk/qmk_firmware#2235]
If you have an MT to hold modifiers while you hold a key and try to set the tap to TG a layer, the TG will not execute.

**Comment by drashna** [comment]
MT, as it Mod Tap, correct?

**Comment by ReagentX** [comment]
Correct.

**Comment by drashna** [comment]
Hmmm, it seems to work just fine for me.
I'm using MT(ctrl, KC_z), and it triggers all of my TG() layers just fine.

Could you post your keymap config?

**Comment by drashna** [comment]
Sounds like this may have been abandoned.

If not, please reopen.
