### ISSUE TITLE
[Bug]=Main

### ISSUE THREAD

**Issue by darker16** [qmk/qmk_firmware#22362]
### Describe the Bug

#22357 #22333

!!!Brick device

### Keyboard Used

make

### qmk doctor Output

```text
qmk doctor
```

### Is AutoHotKey / Karabiner installed

- [X] AutoHotKey (Windows)
- [X] Karabiner (macOS)

### Other keyboard-related software installed

Yes

**Comment by zvecr** [comment]
Bug report template not filled out with correct information, nor contains the bare minimum to understand what the problem is.

**Comment by tzarc** [comment]
And other PRs on other repos are absolute garbage.
