### ISSUE TITLE
[Bug] The fan file is not present

### ISSUE THREAD

**Issue by i4sd2000** [qmk/qmk_firmware#22442]
### Describe the Bug

The fan file is not present The fan coil is missing and there is an RGB lamp in it

### Operating System

ونديز 10 

### Is AutoHotKey / Karabiner installed

- [x] AutoHotKey (Windows)
- [X] Karabiner (macOS)

**Comment by i4sd2000** [comment]
The fan coil is missing and there is an RGB lamp in it

**Comment by keyboard-magpie** [comment]
This does not appear to relate to QMK keyboard firmware.
