### ISSUE TITLE
I want use random delay between the keys

### ISSUE THREAD

**Issue by sandadadad** [qmk/qmk_firmware#22487]
### Issue Description

When I map the key I can set the delay certain ms, Can I set the random delay in certain time interval?

Like {+KC_1}{50<random<80}{-KC_1}

**Comment by coliss86** [comment]
Have a look to custom keycode : https://docs.qmk.fm/#/custom_quantum_functions?id=custom-keycodes
It involves little C programming, there is no other way to do it.
