### ISSUE TITLE
Firmware for the Keychron Q4 Pro

### ISSUE THREAD

**Issue by Suppresed** [qmk/qmk_firmware#22527]
Should I just use the one that says Q4 ansi v1 or v2? Where else can i find the firmware for the Keychron Q4 Pro?

Thanks

**Comment by adophoxia** [comment]
It lives in [another fork](https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron/q4_pro), Keychron's specifically. You should work off of there.
