### ISSUE TITLE
Can STM32 be used as a split keyboard? Is there any reference?

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#22613]
Does the split keyboard only support avr chips? The examples are all 32U4, can't smt32f103 be used as a split version? Find out if zvecr is a split of STM32? Compiling and testing on the development board is not possible
The B6 connection between the two development boards is invalid. Do I need to connect other pins? Is there a complete wiring diagram reference for this?

**Comment by fauxpark** [comment]
Split works just fine on ARM. It's mostly the same process as AVR.
Please read the docs.

**Comment by jeromeli002** [comment]
> Split 在 ARM 上工作得很好。其过程与 AVR 基本相同。 请阅读文档。

Are there any requirements for hardware wiring? Or can any IO be used? The firmware compiled by split_blackpill is flashed and connected to B6 but it doesn't work. How should I connect other pins?

![image](https://github.com/qmk/qmk_firmware/assets/5648129/bae1677d-962c-4263-b12a-442e385cb3ee)
