### ISSUE TITLE
[Feature Request] "qmk compile" non-zero exit code on compilation error

### ISSUE THREAD

**Issue by xudongzheng** [qmk/qmk_firmware#22686]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Having `qmk compile` exit with non-zero makes it easier to use as part of a larger script.

To demonstrate issue:

```
# Add some garbage to C file.
date >> keyboards/adafruit/macropad/macropad.c

qmk compile -kb adafruit/macropad -km default
echo $?
```

**Comment by tzarc** [comment]
Was fixed as of #22639.
