### ISSUE TITLE
Error un the layout 3

### ISSUE THREAD

**Issue by WaltJT** [qmk/qmk_firmware#22694]
### Describe the Bug

I access the layout 3, but no write nathing. What resolve this? Thanks 

### Keyboard Used

Crbdk

### Link to product page (if applicable)

To my property

### Is AutoHotKey / Karabiner installed

- [X] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Other keyboard-related software installed

R2G

**Comment by waffle87** [comment]
You need to provide more information, like the keyboard you have, your keymap, etc.

**Comment by zvecr** [comment]
Closing as there is nothing we can do with the little information supplied.
