### ISSUE TITLE
Outdated hint regards WSL+USB

### ISSUE THREAD

**Issue by pustekuchen91** [qmk/qmk_firmware#22737]
This hint is actually not correct. 
https://github.com/qmk/qmk_firmware/blob/master/util/qmk_install.sh#L48C3-L48C4

Actually its possible to route a usb device into the wsl (windows 11 + WSL2 required)
https://learn.microsoft.com/en-us/windows/wsl/connect-usb

Example to mount for STM32 Bootloader:

`usbipd list`
> 1-8    0483:df11  STM32  BOOTLOADER                                             Shared

`usbipd attach -w -i 0483:df11 --auto-attach`

# Needed adjustments
Check for requirements instead of using powershell
[    if 'microsoft' in platform.uname().release.lower():](https://github.com/qmk/qmk_firmware/blob/5031e0e35c6c497b58b1f3122d8e9d17f0284733/lib/python/qmk/flashers.py#L62)

**Comment by pustekuchen91** [comment]
Here is a proof that the firmware can be flashed in a devcontainer + WSL

> vscode ➜ /workspaces/qmk_firmware (add-dev-container) $ qmk flash keychron_q6_iso_encoder_keychron.bin 
> Flashing binary firmware...
> Please reset your keyboard into bootloader mode now!
> Press Ctrl-C to exit.
> 
> dfu-util 0.9
> 
> Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
> Copyright 2010-2016 Tormod Volden and Stefan Schmidt
> This program is Free Software and has ABSOLUTELY NO WARRANTY
> Please report bugs to http://sourceforge.net/p/dfu-util/tickets/
> 
> Opening DFU capable USB device...
> ID 0483:df11
> Run-time device DFU version 011a
> Claiming USB DFU Interface...
> Setting Alternate Setting #0 ...
> Determining device status: state = dfuERROR, status = 10
> dfuERROR, clearing status
> Determining device status: state = dfuIDLE, status = 0
> dfuIDLE, continuing
> DFU mode device DFU version 011a
> Device returned transfer size 2048
> DfuSe interface name: "Internal Flash  "
> Downloading to address = 0x08000000, size = 34484
> Download        [=========================] 100%        34484 bytes
> Download done.
> File downloaded successfully
> Transitioning to dfuMANIFEST state

**Comment by drashna** [comment]
> Windows 11 (Build 22000 or later)
