### ISSUE TITLE
[Bug] SpiderIsland QH42 keyboard with QMK installed but without source code

### ISSUE THREAD

**Issue by johndoe1983** [qmk/qmk_firmware#22755]
### Describe the Bug

I bought "VIAL Keyboard Programable 42 Key Programable Mechanical Split Keyboard Gaming DIY QMK Firmware Hot waps RGB Backlit Keypad Kit" from Aliexpress.

It's other keyboard from SpiderIsland. This project have only one keyboard from them added on this repository, specifically "[split78](https://github.com/qmk/qmk_firmware/tree/master/keyboards/spiderisland/split78)": https://github.com/qmk/qmk_firmware/tree/master/keyboards/spiderisland

It arrived with VIAL, so the QMK is installed but the seller doesn't share the source code even upon request.

The bootloader is https://github.com/devanlai/dapboot and the QMK installed have Bootmagic enabled, so I could to access to the bootloader easily. It's based on Corne but with RGB per-key/underglow and USB-C instead of TRRS. The PCB have a dolphin in the back.

Could we make a port from a similar keyboard?

Here more information:
input,hidraw4: USB HID v1.11 Keyboard [jsen QH42] on usb-0000:00:1d.7-1.4/input0
hid-generic 0003:5653:0001.000C: hiddev99,hidraw5: USB HID v1.11 Device [jsen QH42] on usb-0000:00:1d.7-1.4/input1
input: jsen QH42 Mouse as /devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1.4/2-1.4:1.2/0003:5653:0001.000D/input/input29
input: jsen QH42 System Control as /devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1.4/2-1.4:1.2/0003:5653:0001.000D/input/input30
input: jsen QH42 Consumer Control as /devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1.4/2-1.4:1.2/0003:5653:0001.000D/input/input31
input: jsen QH42 Keyboard as /devices/pci0000:00/0000:00:1d.7/usb2/2-1/2-1.4/2-1.4:1.2/0003:5653:0001.000D/input/input32
hid-generic 0003:5653:0001.000D: input,hidraw6: USB HID v1.11 Mouse [jsen QH42] on usb-0000:00:1d.7-1.4/input2
idVendor=5653, idProduct=0001, Product: QH42, Manufacturer: jsen

In Bootloader mode:
idVendor=1209, idProduct=db42, Product: DAPBoot DFU Bootloader, Manufacturer: Devanarchy, UF2 Bootloader, bcdDevice= 1.10
![output](https://github.com/qmk/qmk_firmware/assets/56751223/62d1071f-7354-4a05-9ae5-6259d7876090)

### Keyboard Used

spiderisland/qh42

### Link to product page (if applicable)

https://www.aliexpress.com/item/1005005959808644.html

### Operating System

GNU/Linux (Gentoo)

**Comment by zvecr** [comment]
> Please refrain from asking maintainers to add support for specific keyboards -- it is unlikely they will have hardware available, and will not be able to help.
Your best bet is to take the initiative, add support, then submit a PR yourself.
