### ISSUE TITLE
Add Support for cidoo abm066[Feature Request] 

### ISSUE THREAD

**Issue by JoeSchonbok** [qmk/qmk_firmware#22810]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

**Comment by zvecr** [comment]
As mentioned in the issue template...
> Please refrain from asking maintainers to add support for specific keyboards -- it is unlikely they will have hardware available, and will not be able to help.
Your best bet is to take the initiative, add support, then submit a PR yourself.

**Comment by JoeSchonbok** [comment]
Sorry, perhaps the documentation here should be updated: https://docs.qmk.fm/#/configurator_step_by_step - it directly advises to create a ticket if the keyboard is not on the list for the configurator. Sorry if I've done it wrong - I don't know how to add support for the keyboard myself.
