### ISSUE TITLE
Documentation improvements wishlist

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#2298]
We've been talking a lot lately about what further improvement to documentation we want to make. This is a non-exaustive list, it's mainly so I have somewhere to track this stuff until I have time to tackle it. If you would like to work on something listed below please feel free!

* Environment setup
  * Explain how to clone qmk_firmware
    * Windows
    * Mac
    * Linux
* HOWTO/Guides to Write
  * Update `info.json` files (converter, etc)
  * Code a completely custom key
  * ARM/ChibiOS Development
* How To Do Common Tasks (With Examples)
  * How to clear mods
  * How to send key down, key up

**Comment by joedevivo** [comment]
Keyboard development for ARM / ChibiOS? :D

**Comment by DanielGGordon** [comment]
Some clarity on Permissive hold and ignore mod tap interrupt - and how they work together.

**Comment by lbibass** [comment]
Talk more about Tap Dancing: the documentation wasn't very clear to me, and I feel like some improvements could be made.

**Comment by evantravers** [comment]
Where do we stand on this now… I made a pass through documentation a while back… but I'd like to help out again.

**Comment by drashna** [comment]
I think that everything but the ARM/ChibiOS stuff exists in the docs.  
However, some of this could be cleaned up.

**Comment by drashna** [comment]
Hmm, I think most, if not all of this exists now.

**Comment by jackhumbert** [comment]
Yeah, I think we've implemented a good portion of this - we can tackle any outliers in another round :)
