### ISSUE TITLE
The layer change keys except TO(x) cannot switch the front layer and can only switch the back layer.

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#22996]
Except for TO(x), the layer changing keys cannot switch the front layer and can only switch the back layer. How to make it switch layers forward. For example, currently at level 2, MO(1) is invalid and MO(4) is valid. How to make MO(1) also valid?

**Comment by drashna** [comment]
You can't.

They are processed top down, so higher layers always take precedence. 

For more information: https://docs.qmk.fm/#/keymap?id=keymap-and-layers
