### ISSUE TITLE
Compilation error : ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by bill-alan** [qmk/qmk_firmware#23068]
![屏幕截图(91)](https://github.com/qmk/qmk_firmware/assets/45714227/9104cc25-c0ab-4081-8501-da0e3020e9b1)
Using QMK for the first time, I don't know what the problem is.

**Comment by fauxpark** [comment]
Make sure your repo is up to date then start over with `qmk new-keyboard`.
