### ISSUE TITLE
[Help Wanted] First time compiling QMK, getting errors.

### ISSUE THREAD

**Issue by DuckersMcQuack** [qmk/qmk_firmware#23060]
Info.json:

![image](https://github.com/qmk/qmk_firmware/assets/9039370/541b370c-2bc1-42c3-950d-c555a05d3cd4)

Keymap.c

![image](https://github.com/qmk/qmk_firmware/assets/9039370/a6516ade-ad5e-4c4c-bb44-a3c33d91ca00)

Error i'm getting

![image](https://github.com/qmk/qmk_firmware/assets/9039370/a1e4fca3-d766-4f8d-a0cd-a90bcf6e2523)

**Comment by keyboard-magpie** [comment]
`KEYBOARD_duckers_3x4_macropad` should be replaced with `LAYOUT_ortho_3x4`
