### ISSUE TITLE
Compilation error: quantum/keymap_introspection.c

### ISSUE THREAD

**Issue by bill-alan** [qmk/qmk_firmware#23079]
Hello everyone, I am a new user of qmk for the first time who also asked questions yesterday. I have a new problem today and hope to consult you.
I followed the file and found no problem, and the previous code without RGB matrix and rotation encoder can be compiled. Usage should not be an issue for quantum.

Compiling: quantum/keymap_introspection.c                                                          In file included from quantum/keymap_introspection.c:12:
quantum/keymap_introspection.h:12:1: error: expected ',' or ';' before 'uint8_t'
   12 | uint8_t keymap_layer_count_raw(void);
      | ^~~~~~~
 [ERRORS]
 |
 |
 |
make: *** [builddefs/common_rules.mk:373：.build/obj_hwpad2_default/quantum/keymap_introspection.o] 

![屏幕截图(93)](https://github.com/qmk/qmk_firmware/assets/45714227/e26a54ce-d74e-4c2a-8dea-5b16d53c32e8)

**Comment by fauxpark** [comment]
The issue is in your keymap, this is just a side effect of how QMK compiles it.

**Comment by fauxpark** [comment]
You're missing a semicolon.

**Comment by bill-alan** [comment]
> You're missing a semicolon.
endif before, my question. Thank you very much for your help.
