### ISSUE TITLE
[Feature Request] Enhance Macro support (Repeat-loop-cancel)

### ISSUE THREAD

**Issue by KpochMX** [qmk/qmk_firmware#23115]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Hi.
macros are excellent but there is a feature that is missing that could lead into a potential function.

The ability to customize macros by adding modifications like:
 **Loop macro indefinitely** - This will loop the macro until the same Key is pressed again (Example: Macro that loop "LEFT KEY->RIGHT KEY->A>"

**Play macro while Macro key is being held** - This will run the macro (Loop) until the key is released again.

Thanks!

**Comment by drashna** [comment]
Generally, this is handled by the OS.  
However, features such as deferred executors can make this very simple.
