### ISSUE TITLE
Thanks for creating this great project! Consider adding Github Sponsors.

### ISSUE THREAD

**Issue by SimonFischer04** [qmk/qmk_firmware#23137]
I'm quite new into QMK, but I'm already loving it.
Thanks for creating and maintaining such an amazing project.

I know there is a link to the OpenCollective on https://qmk.fm/support/, but I think also adding OpenCollective link to Github Sponsors would create more visibility for support directly on the Github repo page.
Maybe (additionally to linking to OpenCollective) also add native / direct Github Sponsors option.

**Comment by tzarc** [comment]
![image](https://github.com/qmk/qmk_firmware/assets/2985843/0a3a758e-8234-4007-b822-773407e117c9)

Great success? Thanks for the kind words!
