### ISSUE TITLE
[Bug] USB mode Keyboard failure

### ISSUE THREAD

**Issue by nuphy-src** [qmk/qmk_firmware#23203]
### Describe the Bug

Hello everyone, I have recently encountered the following USB problems with my keyboard:
1. After the computer is turned on, the keyboard cannot be woken up immediately, and it takes a while for the keyboard to light up
2. When you restart the computer in USB mode, the computer does not recognize the keyboard USB
The above problem only occurs on individual computers, and it is suspected that it is a USB compatibility problem

### Keyboard Used

nuphy/air75 v2

### Link to product page (if applicable)

https://github.com/qmk/qmk_firmware/pull/22751

### Operating System

windows

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by KarlK90** [comment]
QMK's `develop` branch landed #21656 which overhauls much of the USB handling for ChibiOS boards. Please check if this changes any of the observed problems.
