### ISSUE TITLE
STM32F103 matrix pins problem

### ISSUE THREAD

**Issue by Vem-596** [qmk/qmk_firmware#23229]
By default, the state of matrix pins (all cols and rows) is high input or high output. If I want to set these pins low, can I? How to do

**Comment by myst729** [comment]
Have you tried [Custom Matrix](https://docs.qmk.fm/#/custom_matrix)?

**Comment by Vem-596** [comment]
> Have you tried [Custom Matrix](https://docs.qmk.fm/#/custom_matrix)?
Thank you for the tip！！
