### ISSUE TITLE
OLED brightness not working as expected

### ISSUE THREAD

**Issue by metalinspired** [qmk/qmk_firmware#23270]
### Issue Description

Hi,

Just starting out with QMK.
My setup is RP2040 with SSD1306 OLED.
Setting brightness level (OLED_BRIGHTNESS) acts more like a bool than as if it has levels.
Setting it to 128 has same effect as if it is 255 and if I set it to lower values (I tried: 42, 30, 5 and 0) simply dims the OLED regardless of actual value.
Is this expected behaviour? Am I missing something?

Regards

**Comment by fauxpark** [comment]
Yes, this seems to be expected, at least in my experience with the module I have (an old Adafruit 128x64 panel). The range of brightness levels is not very wide for some reason.

**Comment by metalinspired** [comment]
Thanks @fauxpark
