### ISSUE TITLE
Any membrane keyboards QMK supports

### ISSUE THREAD

**Issue by korpe1** [qmk/qmk_firmware#23315]
Are there any membrane keyboards that QMK supports?

**Comment by RajeevDash007** [comment]
can you explain what you want to know ?

**Comment by korpe1** [comment]
I just try find [membrane keyboards](https://en.wikipedia.org/wiki/Keyboard_technology#Membrane) that QMK support? What do you don't understand?😅

**Comment by keyboard-magpie** [comment]
There are no natively supported membrane boards. There are some adapters/handwire/conversion projects out there, search the repository for "membrane".
