### ISSUE TITLE
Add KB29B-01 keyboard

### ISSUE THREAD

**Issue by DoctorKnowsBetter** [qmk/qmk_firmware#23319]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

@DOIO2022 Please add source codes for KB29B-01.

**Comment by zvecr** [comment]
From the template you filled out
> Please refrain from asking maintainers to add support for specific keyboards -- it is unlikely they will have hardware available, and will not be able to help.
Your best bet is to take the initiative, add support, then submit a PR yourself.
