### ISSUE TITLE
This device cannot start (Code 10) - Plover Steno layout

### ISSUE THREAD

**Issue by millipz** [qmk/qmk_firmware#2344]
![image](https://user-images.githubusercontent.com/1217784/35797565-ffc80a8c-0a57-11e8-86b7-8aa3a28b7af1.png)
My Plover layout reports this error when connected to my Windows 7 PC. Works as expected on Mac. No keypresses work in Plover. Any suggestions of how to troubleshoot gratefully received.

**Comment by millipz** [comment]
Nope, the issue persists. I can only use my steno layer on Mac for now.

**Comment by drashna** [comment]
hmmm.  

My best recommendation is to manually uninstall the drivers, and then install the QMK Toolbox (as that should prompt to install the drivers). Or re-run the QMK build enviroment setup script, to force install all the drivers again. 

If that doesn't help, ... then sorry. :(

**Comment by millipz** [comment]
I only have QMK toolbox as a standalone .exe. Should I be running an installer? I flashed the keyboard and did all the main setup on my Mac, just downloaded QMK Toolbox to the PC to see if it helped.

**Comment by millipz** [comment]
Which drivers should I be uninstalling? I tried removing the driver for the HID device with the issue, but I don't get any driver prompts when installing QMK.

**Comment by millipz** [comment]
I finally have this working! I'm writing this in steno!

Steps to fix:

1. Download Zadig http://zadig.akeo.ie/

2. Open and Let's Split should show up

![image](https://user-images.githubusercontent.com/1217784/39475411-0c2b5fd2-4d50-11e8-9006-322cc0414cbd.png)

3. Install USB Serial (CDC) driver

4. Relaunch Plover

5. Profit
