### ISSUE TITLE
new keyboard

### ISSUE THREAD

**Issue by Legonut** [qmk/qmk_firmware#2346]
Hi, I've got firmware for a new keyboard
https://legonut.gitbooks.io/zen-keyboard/content/
I've got ~60 people who will need the firmware, so merging it with QMK master seems like the best plan. Do I need permission to make a pull request?

**Comment by jackhumbert** [comment]
Awesome! No permission needed - just go ahead! [We do have guidelines](https://docs.qmk.fm/hardware_keyboard_guidelines.html) :)

**Comment by Legonut** [comment]
Thanks, I'm trying to do it through the github windows client, and when I make a pull request it says I don't have permission to publish

**Comment by Legonut** [comment]
Ah I needed to fork it, trying again now

**Comment by drashna** [comment]
Yeah, fork it, push to the fork and then create a pull request. :)
