### ISSUE TITLE
Debug messages on matrix_init_kb() and pointing_device_init()

### ISSUE THREAD

**Issue by raycewest** [qmk/qmk_firmware#2353]
Trying to get an ADNS9800 working alongside my matrix on a Pro Micro - might elaborate on that in a separate issue, but for here:  can i expect to the init functions to output any print() messages I have in there, or do they run too early in boot process for hid_listen to pick up on them?  I'm not sure if the firmware for the ADNS is getting loaded or not, when the keyboard gets plugged in.

**Comment by raycewest** [comment]
If I could follow up:  has anyone else observed this (lack of) behavior?  I can notice a change of a static variable inside of pointing_device_init(), but nothing I can print off.

**Comment by skullydazed** [comment]
Have you tried QMK Toolbox instead of hid_listen? I've found that hid_listen doesn't always connect in time, but QMK Toolbox connects in time to catch anything printed after "Keyboard Start". I don't know if the init functions run before or after that.

**Comment by drashna** [comment]
Did you get this resolved?

**Comment by raycewest** [comment]
No, although I'm no longer looking at this matter to address the problems I'm working through.  Thanks!

**Comment by drashna** [comment]
Would you be okay with us closing this issue?

**Comment by raycewest** [comment]
Yes, thanks.
