### ISSUE TITLE
[Feature Request] Password manager/generator functionality

### ISSUE THREAD

**Issue by paat** [qmk/qmk_firmware#23538]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

Hi!
What do you think about the solution:
1. Input pin and store pin in memory
2. If pin is set, then some key combination would trigger password generation:
 1. input for hash: PIN + entered key in combination + my hardcoded secret custom salt
 2. hash the input
 3. Find the password characters from allowed password characters array (with the help of applying hash_byte % array_length)
 4. tap each character.
3. Locking key combination Win+L would reset the pin.

Is it safe enough? Any ideas what would go wrong? As far as I see in worst case scenario, somebody could steal the keyboard, decompile the firmware and brute force to some service which allows invalid retries infinite amount of times (if the pin is not complex enough).

I implemented this in my keymap.c file, at it works for me. Maybe it is worth pushing some functions to core functionality?

**Comment by tzarc** [comment]
Unfortunately we're not going to entertain any security-related matters within QMK. You're more than welcome to implement it in your fork of qmk_firmware, or even under [external userspace](https://docs.qmk.fm/#/newbs_external_userspace).
