### ISSUE TITLE
Clueboard 60% not compiling: weird error. 

### ISSUE THREAD

**Issue by lbibass** [qmk/qmk_firmware#2368]
I'm having this error when trying to compile the firmware for the clueboard 60%

![screen shot 2018-02-08 at 9 26 36 pm](https://user-images.githubusercontent.com/27320050/36008825-1fe9e51c-0d17-11e8-8ef8-fb8c916d7e3c.png)
Anyone know how to fix? This is with the most recent revision of QMK by the way.

**Comment by drashna** [comment]
Have you tried running "make git-submodule" yet?

**Comment by lbibass** [comment]
@drashna unfortunetly, that didn't work. I tried cloning ChibiOS into lib, still didn't work. :(

**Comment by lbibass** [comment]
*I fixed it, I just downloaded the newest version of QMK.
