### ISSUE TITLE
SharkyDevBoi45/qmk_firmware addition

### ISSUE THREAD

**Issue by SharkyDevBoi45** [qmk/qmk_firmware#23701]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

I found online that I have to add my repository here and it will be added to QMK so I can make keeeb. its https://github.com/SharkyDevBoi45/qmk_firmware

**Comment by zvecr** [comment]
> I found online that I have to add my repository here and it will be added to QMK

Nothing will automatically create a PR to add a keyboard based on an issue being created.

You would have to raise a PR yourself, following the guidance on <https://docs.qmk.fm/#/contributing> and <https://docs.qmk.fm/#/pr_checklist>.
