### ISSUE TITLE
[doc bug] remove ofiical support for APM32

### ISSUE THREAD

**Issue by DFWJunior** [qmk/qmk_firmware#23702]
### Issue Description

in QMK's doc/Flashing,it said QMK has support for APM32.
[](https://docs.qmk.fm/#/flashing?id=stm32apm32-dfu)

but first,QMK doesn't have offical support for APM32,
second,APM32 cannot replace STM32,i've tested to use APM32F103CBT6 to replace STM32F103CBT6,
it will randomly RESET.

and some STM32's replacement MCU such as GD32,it can be written stm32duino bootloader,and it also can written QMK's firmware,
but it still cannot be used,it need's other QMK fork.

to help users don't use APM32 as a replacement of STM32,i suggested to completely removed doc's APM32 part to avoid misunderstanding.

**Comment by tzarc** [comment]
The docs say flashing APM32 is supported, not that every APM32 chip is supported by QMK.
