### ISSUE TITLE
[Feature Request] Support for WinChip CH58xx MCU platform

### ISSUE THREAD

**Issue by JavierRiosN** [qmk/qmk_firmware#23837]
### Feature Request Type

- [ ] Core functionality
- [X] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

Hi! First of all, I want to thank everyone involved on the QMK project... It's a wonderful world of possiblities!

I know that asking for a specific keyboard support is not such a good and polite thing to do, but I've seen an increasing number of Ali Express (or Taobao) keyboards using a MCU from WinChip.

In my case I bought a PCKey016 which has a CH582M chip on it. It has VIA support, but QMK doen't recognize it... I was unable to create a firmware in QMK and I think it's useful because actually the keyboard lacks of advanced features like tap-hold, tap- dance and so on. 

The vendor didn't give me the firmware nor some guidance on how they make it work with VIA/VIAL, but not with QMK.

I've found a [QMK CH582 port](https://github.com/O-H-M2/qmk_port_ch582) and managed to create a functional firmware but  in the programmers words, it's not a port but a layer betwen QMK and the MCU and also lacks of some of the advanced features.

I think it could be useful to have a native QMK WinChip support for it has a few chips that has similar specifications:
- Are 32 bits RISC-V based. Perhaps an extension of Chibios could work.
- BLE support in some chips (CH582M and CH583x).
- The [Datasheet](https://www.wch-ic.com/downloads/CH583DS1_PDF.html) are available in english and chinese.
- Works well with MCU Boot. I'm unaware if it can work with another bootloader, I guess it does.
- There are many clones for these chips, so I think we'll find more and more keyboards like this one.

Unfortunately, I'm not a C programmer (although I can understand a little bit) and am unable to understand how to make QMK work with this platform although I'm trying my best.

For any word, advice o guidance, I thank you in advance.

**Comment by tzarc** [comment]
https://docs.qmk.fm/platformdev_selecting_arm_mcu#add-new-mcu-family explains what’s involved. QMK maintainers themselves aren’t likely to do so — it’ll be a community-led project.

**Comment by JavierRiosN** [comment]
Thank you! I uderstand that the maintainers aren't so willing to do it... I'm looking the information you give me and I'll try to follow it.

**Comment by tzarc** [comment]
That’s the information. We use ChibiOS to supply the HAL/BSP, so to make it compatible with QMK you need to make it compatible with ChibiOS first. Explaining how to do so isn’t something QMK describes in-depth; ChibiOS a different project.

**Comment by JavierRiosN** [comment]
I understand... I'm looking on ChibiOS now. I hope I can collaborate with this... Again, thank you.

**Comment by tzarc** [comment]
The GD32VF103 port in ChibiOS-Contrib may prove useful as a reference.
