### ISSUE TITLE
[Bug] rgb matrix effect bug.

### ISSUE THREAD

**Issue by itarze** [qmk/qmk_firmware#23850]
### Describe the Bug

https://github.com/qmk/qmk_firmware/blob/master/quantum/rgb_matrix/animations/pixel_fractal_anim.h  

This RGB effect does not limit the NO_LED and will cause access to the wild pointer, which will cause the MCU to malfunction.

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by drashna** [comment]
I'm curious which controller this is for.  I can't replicate the MCU crash using an STM32F303 (using a moonlander, which does have a bunch of NO_LED values)

**Comment by jiaxin96** [comment]
See https://github.com/qmk/qmk_firmware/pull/23348

**Comment by jiaxin96** [comment]
same as https://github.com/qmk/qmk_firmware/pull/23348

**Comment by itarze** [comment]
> I'm curious which controller this is for. I can't replicate the MCU crash using an STM32F303 (using a moonlander, which does have a bunch of NO_LED values)

Set NO LED to the left half of the keyboard RGB MATRIX， Like this.   
<img width="461" alt="image" src="https://github.com/user-attachments/assets/e0573f8f-cb46-4a57-8603-04595f5b88b0">

**Comment by itarze** [comment]
And， This will slove it.   
```c
void rgb_matrix_set_color(int index, uint8_t red, uint8_t green, uint8_t blue) {
    if (index >= RGB_MATRIX_LED_COUNT) {
        return;
    }
    rgb_matrix_driver.set_color(index, red, green, blue);
}
```

**Comment by itarze** [comment]
This problem was generated randomly because this lamp effect used random8(), and it may be that you were not able to reproduce it for this reason.
