### ISSUE TITLE
Any way to customise the RGB Ligting (not a matrix)?

### ISSUE THREAD

**Issue by ipg0** [qmk/qmk_firmware#23909]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

Currently there is a well-documented and relatively straightforward way to implement custom RGB matrix effects/animations, but no complementary functionality for non-matrix RGB lighting (a single LED strip).

I have not been able to find any info on creating custom non-matrix RGB lighting modes or hooking into/overriding any functionality regarding non-matrix RGB lighting, in a similar way to how matrix effects are customised. If there is a way of doing so that is considered "proper", the documentation should be updated to include it, otherwise, I think, this functionality should be implemented and documented afterwards.

Anyway, I would appreciate if anyone pointed me in the right direction on how I can implement a custom RGB lighting mode in the current version of QMK.

**Comment by ipg0** [comment]
I'm in the process of implementing this functionality right now, will open a PR once I'm done

**Comment by zvecr** [comment]
Given the current state of rgblight, and its maintenance issues, this is unlikely the direction we would want to go in.

The suggestion would be to just use RGB Matrix instead, as this supports the additional functionality you are after.
