### ISSUE TITLE
how to use two uart in qmk?

### ISSUE THREAD

**Issue by cckuzan** [qmk/qmk_firmware#23956]
### Issue Description

I need two uart to send data， my MCU is stm32f103。
Now I can only use uart1 to send data through the uart_write() function。
thanks!

**Comment by fauxpark** [comment]
Currently not possible with the UART API. You can probably still use the underlying ChibiOS API though, but that will require a bit more code.

**Comment by cckuzan** [comment]
ok. thanks.
