### ISSUE TITLE
[Feature Request] Split Keyboard support for IS31FL3737

### ISSUE THREAD

**Issue by vinaykomaravolu** [qmk/qmk_firmware#24081]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

I see that for IS31FL3731 LED driver qmk supports split keyboards using two drivers with same address for each split keyboard:

**For split keyboards using `RGB_MATRIX_SPLIT` with an LED driver, you can either have the same driver address or different driver addresses. If using different addresses, use `IS31FL3731_I2C_ADDRESS_1` for one and `IS31FL3731_I2C_ADDRESS_2` for the other one. Then, in `g_is31fl3731_leds`, fill out the correct driver index (0 or 1). If using one address, use `IS31FL3731_I2C_ADDRESS_1` for both, and use index 0 for `g_is31fl3731_leds`.**

Is this supported for IS31FL3737 LED driver as well? If not can we get this supported?

**Comment by fauxpark** [comment]
This is part of the LED/RGB Matrix feature itself, the driver is irrelevant.
