### ISSUE TITLE
[Feature Request] Only send the last pressed key

### ISSUE THREAD

**Issue by darix** [qmk/qmk_firmware#24166]
### Feature Request Type

- [X] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

### Description

To basically implement what can be seen here

https://www.youtube.com/watch?v=Feny5bs2JCg

**Comment by miathetrain** [comment]
Duplicate of https://github.com/qmk/qmk_firmware/pull/24000

**Comment by Geczy** [comment]
whats up with that pr? why's it taking so long @darix
