### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Jark5455** [qmk/qmk_firmware#24167]
### Issue Description

Hello,

Currently I am trying to compile a custom firmware in msys, however I get the error.

```
☒ Unknown error attempting to load C:/Users/Me/qmk_firmware/keyboards/gmmk/pro/rev1/ansi:
        [Errno 13] Permission denied: 'C:/Users/Me/qmk_firmware/keyboards/gmmk/pro/rev1/ansi'
```

The `qmk_firmware` folder is owned by my user and my user has read and write access to that folder. I am not sure why qmk doesn't have permission to access that folder.

**Comment by fauxpark** [comment]
Impossible to tell without additional information and context. It could be solved by deleting and recloning, or it might simply be that your Windows install is broken in some weird way.

**Comment by Jark5455** [comment]
Setting a default keyboard allows it to read, but without a default keyboard, I get the permission error.

**Comment by fauxpark** [comment]
I have no idea what that means. What command are you running?

**Comment by Jark5455** [comment]
`qmk config user.keyboard=gmmk/pro/rev1/ansi`

**Comment by fauxpark** [comment]
I can't reproduce this with the `default` keymap. The issue is something to do with your machine.
