### ISSUE TITLE
QMK MSYS default repo change

### ISSUE THREAD

**Issue by teasimon** [qmk/qmk_firmware#24243]
### Issue Description

how can i change in QMK MSYS to use 
https://github.com/Keychron/qmk_firmware/tree/bluetooth_playground/keyboards/keychron
instead of 
https://github.com/qmk/qmk_firmware/tree/master/keyboards/keychron

keychron k6 pro is not listed in the second repo so I cant edit the code.

**Comment by fauxpark** [comment]
`qmk setup -b bluetooth_playground keychron/qmk_firmware`
If you have already cloned the Keychron fork, just `git checkout bluetooth_playground`
