### ISSUE TITLE
[Bug] Mouse wheel assignment not working

### ISSUE THREAD

**Issue by is-uko** [qmk/qmk_firmware#24264]
### Describe the Bug

I assigned the up and down mouse wheel actions in Remap, but when I press the assigned keys, the mouse wheel doesn't scroll up or down.

### Keyboard Used

Keyball44

### Operating System

macOS Sonoma 14.5

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [X] Karabiner (macOS)

**Comment by waffle87** [comment]
This keyboard's firmware does not appear to be in upstream `qmk_firmware` repository, nor is QMK Firmware affiliated with [Remap](https://remap-keys.app). This issue should be pointed towards Remap. However from a quick look at [this keyball44 firmware](https://github.com/Yowkees/keyball/blob/main/qmk_firmware/keyboards/keyball/keyball44/rules.mk#L29), mouse keys do not appear to be enabled. Nonetheless, this probably isn't a QMK issue.
