### ISSUE TITLE
Unrecognized after re-plugging, thick line unknown USB device (device descriptor request failed)

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_firmware#24278]
### Issue Description

STM32F103C8T6 can be recognized normally after flashing the firmware for the first time, but cannot be recognized after re-plugging and plugging. Thick line unknown USB device (device descriptor request failed). What is the problem? Is the hardware or firmware wrong?

![image](https://github.com/user-attachments/assets/da23fe03-9359-432f-a32d-58a586ace4e0)

**Comment by fauxpark** [comment]
Please use Discord for questions like these.
https://discord.gg/Uq7gcHh
