### ISSUE TITLE
I would like to remove the like_jis keymap.

### ISSUE THREAD

**Issue by marksard** [qmk/qmk_firmware#24287]
This is a keymap that was PR'd and added by me long ago.
I would like to remove these as I do not use them myself and they are also a workload for the maintainer, is it possible to PR them?

. /keyboards/marksard/treadstone32/keymaps/like_jis
. /keyboards/marksard/treadstone48/keymaps/like_jis
. /keyboards/thevankeyboards/minivan/keymaps/like_jis
. /keyboards/recompile_keys/nomu30/keymaps/like_jis

Thanks.

**Comment by dunk2k** [comment]
Hi @marksard 
Are you able to create a Pull Request with the named keymaps removed?

**Comment by marksard** [comment]
Of course. I will create and PR it.
