### ISSUE TITLE
[Feature Request] Overload key, but only if last normal key press happened n time ago

### ISSUE THREAD

**Issue by nilsherzig** [qmk/qmk_firmware#24323]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [X] New behavior

### Description

I think this behavior is best described in the keyd docs: https://github.com/rvaiya/keyd/blob/393d341464fe567515e767bfae8167a38fa6fb3d/docs/keyd.scdoc#L709-L739

**Comment by anuramat** [comment]
still valid for me :cry:
