### ISSUE TITLE
Error: Bootloader not found

### ISSUE THREAD

**Issue by corygrapher** [qmk/qmk_firmware#2437]
Hello, 
When I was trying to make jc65/v32u4:default:dfu, I got this error:

D:/MSYS2/home/user/qmk_utils/dfu-programmer/dfu-programmer.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
Error: Bootloader not found. Trying again in 5s.

What do I do? 
Thanks.

**Comment by mkerfoot** [comment]
Did you first change directories to the qmk_firmware directory?

cd /c/qmk_firmware

**Comment by corygrapher** [comment]
Yes I did.

**Comment by corygrapher** [comment]
Update:
I solved the problem by pressing the reset button on JC65 PCB.
