### ISSUE TITLE
QK_RBT displays 0x7c01 in the VIA APP

### ISSUE THREAD

**Issue by BillTercel** [qmk/qmk_firmware#24381]
### Issue Description

Why doesn't my keyboard say OK_RBT on the VIA APP instead of -0x7c01?
![image](https://github.com/user-attachments/assets/7be739df-cbdb-43bc-8a99-a452830b9b42)

**Comment by tzarc** [comment]
Probably worth asking the VIA team. We don't have any influence over it.
