### ISSUE TITLE
[Bug] latest QMK seems doesn't support stm32L4 anymore, sounds like major change on endpoint?

### ISSUE THREAD

**Issue by kbladewht** [qmk/qmk_firmware#24401]
### Describe the Bug

 latest QMK seems doesn't support stm32L4 anymore, sounds like major change on endpoint?
 when I build qmk stm32L4 firmware, it can't run anymore in my stm32L433 mcu

### Keyboard Used

stm32L433 DIY keyboard

### Operating System

windows

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by sigprof** [comment]
Add this to your `mcuconf.h`:
```c
#undef STM32_LSI_ENABLED
#define STM32_LSI_ENABLED FALSE
```
This is a workaround for a ChibiOS bug which affects some STM32 chips; #23822 changed the default configs for G431 and L432 to avoid the bug, but missed the L433 config.

**Comment by kbladewht** [comment]
closed
