### ISSUE TITLE
Error installing QMK cli on mac os Sequoia

### ISSUE THREAD

**Issue by iKreateCode** [qmk/qmk_firmware#24494]
### Issue Description

every time i run

 `brew install qmk/qmk/qmk`

i get the following error:

```
==> Installing qmk/qmk/qmk
==> Pouring qmk--1.1.5_1.arm64_sonoma.bottle.tar.gz
Error: No such file or directory - /opt/homebrew/bin/qmk
```
Steps taken so far:
- I have removed brew and installed it again.
- Ran brew doctor
- Ran brew cleanup

**Comment by fauxpark** [comment]
This is an issue with your Homebrew install, not QMK.

**Comment by tacmac24** [comment]
I'm a beginner with the same problem.
I understand that it's a problem with Homebrew and not QMK, but I don't think there was an error when installing Homebrew. What could be the problem?

**Comment by drewish** [comment]
For anyone else that ends up here https://github.com/qmk/homebrew-qmk/issues/82#issuecomment-3453135672 solved it for me.
