### ISSUE TITLE
[Bug]  invalid JSON files in data/constants/keycodes 

### ISSUE THREAD

**Issue by ngrigoriev** [qmk/qmk_firmware#24527]
### Describe the Bug

Some files in data/constants/keycodes have minor syntax issues preventing them from being parsed by JSON parser. While it does not break QMK, it causes some troubles for those who want to use these files for any extra tools. I hope correcting the syntax won't hurt.

### Keyboard Used

n/a

### Link to product page (if applicable)

n/a

### Operating System

n/a

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.5
Ψ QMK home: /home/nik/git/qmk-firmware
Ψ Detected Linux (Arch Linux).
Ψ Userspace enabled: False
Ψ Git branch: master
Ψ Repo version: 0.26.9
⚠ Git has unstashed/uncommitted changes.
Ψ - Latest master: 2024-10-24 22:35:53 -0700 (32b6faaf35) -- Add Vanguard65 Keyboard (#24497)
Ψ - Latest upstream/master: 2024-10-24 22:35:53 -0700 (32b6faaf35) -- Add Vanguard65 Keyboard (#24497)
Ψ - Latest upstream/develop: 2024-10-18 08:06:12 +0000 (22e6a8d15e) -- Merge remote-tracking branch 'origin/master' into develop
Ψ - Common ancestor with upstream/master: 2024-10-24 22:35:53 -0700 (32b6faaf35) -- Add Vanguard65 Keyboard (#24497)
Ψ - Common ancestor with upstream/develop: 2024-10-18 09:04:29 +0100 (7f22cb52e3) -- Correct layouts/default/readme.md (#23805)
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 14.1.0
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 8.0
Ψ Found dfu-programmer version 1.1.0
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2024-02-17 19:20:06 +0000 --  (be44b3305)
Ψ - lib/chibios-contrib: 2024-04-03 20:39:24 +0800 --  (77cb0a4f)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go, but minor problems were found
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Additional Context

```
$ for f in *.hjson ; do echo -n "$f: " ; test -s $f && cat $f | sed -e 's,//.*$,,g' | jsonlint > /dev/null  && echo "OK" ; done
```

I will provide the PR shortly for your consideration.

**Comment by zvecr** [comment]
> Some files in data/constants/keycodes have minor syntax issues preventing them from being parsed by JSON parser.

The files are `hjson` and not `json`. The format is not as strict, and allows content such as comments. Content that would fail most `json` parsers.

If you need `json`, then you should be consuming the converted files from the API endpoint (For example <https://keyboards.qmk.fm/v1/constants/keycodes_0.0.1.json>).

This includes any processing that happens with merging content, avoiding the consuming process having to duplicate any of the `lib/python` logic.
