### ISSUE TITLE
[Feature Request] Please add Keychron K5 Max German ISO

### ISSUE THREAD

**Issue by SpartanPartyPoop** [qmk/qmk_firmware#24544]
### Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

**Comment by zvecr** [comment]
From the form you filled in...
> Please refrain from asking maintainers to add support for specific keyboards -- it is unlikely they will have hardware available, and will not be able to help.
