### ISSUE TITLE
qmk setup failed to compile a simple program with arm-none-eabi-gcc and avr-gcc

### ISSUE THREAD

**Issue by pallas42** [qmk/qmk_firmware#24614]
### Issue Description

I'm running Catalina 10.15.7 which is not supported by homebrew, so instead of `brew install qmk/qmk/qmk`, I tried `python3 -m pip install --user qmk` to install the qmk cli.

After adding qmk location to PATH I tried `qmk setup `,  it failed with the error message `Ψ Major problems detected, please fix these problems before proceeding.`

relevant messages as follows.

```

Ψ Found qmk_firmware at /Users/xxxx/qmk_firmware.
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.6
Ψ QMK home: /Users/xxxx/qmk_firmware
Ψ Detected macOS 10.15.7 (Intel).
Ψ Userspace enabled: False
Ψ Git branch: master
Ψ Repo version: 0.26.11
Ψ - Latest master: 2024-11-17 16:05:57 +0100 (3a6df60ba5) -- docs: fix RWIN alias (#24610)
Ψ - Latest upstream/master: 2024-11-17 16:05:57 +0100 (3a6df60ba5) -- docs: fix RWIN alias (#24610)
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: 2024-11-17 16:05:57 +0100 (3a6df60ba5) -- docs: fix RWIN alias (#24610)
Ψ - Common ancestor with upstream/develop: None
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 14.2.0
☒ Failed to compile a simple program with arm-none-eabi-gcc, return code 1
☒ Command: arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb -mno-thumb-interwork --specs=nosys.specs --specs=nano.specs -x c -o /var/folders/r0/z5rqdtjx4qb9clrnzfq95g2w0000gp/T/tmpqa_ho6je/test.elf -
Ψ Found avr-gcc version 14.2.0
☒ Failed to compile a simple program with avr-gcc, return code 1
☒ Command: avr-gcc -mmcu=atmega32u4 -x c -o /var/folders/r0/z5rqdtjx4qb9clrnzfq95g2w0000gp/T/tmphfehy0pv/test.elf -
Ψ Found avrdude version 7.3
Ψ Found dfu-programmer version 0.7.2
Ψ Found dfu-util version 0.11
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2024-02-17 19:20:06 +0000 --  (be44b3305)
Ψ - lib/chibios-contrib: 2024-04-03 20:39:24 +0800 --  (77cb0a4f)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ Major problems detected, please fix these problems before proceeding.
Ψ Check out the FAQ (https://docs.qmk.fm/#/faq_build) or join the QMK Discord (https://discord.gg/qmk) for help.

```

**Comment by pallas42** [comment]
problem solved by downloading the [qmk toolchains](https://github.com/qmk/qmk_toolchains/releases) and adding to $PATH.

**Comment by SerikDM** [comment]
Had same issue, solved with installing `avr-libc`

**Comment by jirikrepl** [comment]
here are my two cents.

Before I saw this error I even did not have arm-none-eabi-gcc installed.
I had to manually install with brew.
then when running again `qmk setup` i saw this error

if you create a `test.c` file they it's possible to see why it is not compiling

```
int main() {
    return 0;
}
```

```
$ arm-none-eabi-gcc -mcpu=cortex-m0 -mthumb --specs=nosys.specs --specs=nano.specs -o test.elf test.c
```

I uninstalled arm-none-eabi-gcc from brew and installed newest pkg on my macos from arm website

my error was that nosys.specs is not found.
I downloaded this software and installed it
https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

pkg on my mac was installed in 
`/Applications/ArmGNUToolchain/14.2.rel1/arm-none-eabi/bin/`

so in my `.zshrc` I added it on path `
export PATH="/Applications/ArmGNUToolchain/14.2.rel1/arm-none-eabi/bin/:$PATH"
`

and then test program can be compiled and `qmk setup` uses manually installed version and finish fine

**Comment by fauxpark** [comment]
**Do not do this.** The ARM toolchain from osx-cross which the QMK setup process installs should work fine.

Typically the issue here is that `osx-cross/arm/arm-none-eabi-gcc@8` fails to install or link properly because something else is in the way. Homebrew core has a broken toolchain formula that users might be installing by mistake; Homebrew will refuse to link the proper toolchain as it collides with the existing one. Currently the QMK install script does not handle this, but on the develop branch I have changed it so that it nukes all of the known incorrect toolchains before attempting to install the right one (https://github.com/qmk/qmk_firmware/pull/24637).

There may also simply be something wrong with your Homebrew install that is causing the formula not to be symlinked - this is out of scope for QMK, and you'll need to go elsewhere for help fixing that. Running `brew doctor` is a good starting point.
