### ISSUE TITLE
New way to toggle layer request

### ISSUE THREAD

**Issue by lbibass** [qmk/qmk_firmware#2470]
So I was thinking of a new way to add layers. Looking at the way that EAGLE/Rhino do it, it seems really nice. Type in the layer you want, hit enter, and you're set. I just don't know where to start to implement this functionality. Maybe a stripped down version of the terminal function? Have it read the characters that are stored in the RAM/ROM and then use the toggle layer function. The only issue would be the amount that it would add to the firmware size...

**Comment by pattulus** [comment]
I can see this would be a nice thing to have, but I can also see unwanted behaviors, when for instance only parsing the last 10 entered characters.

I set up the leader key to have a similar behavior:

      //Layer switching
      SEQ_ONE_KEY(KC_1) { ang_tap (TT(NUMPAD), 0); } // Numpad
      SEQ_ONE_KEY(KC_2) { ang_tap (TT(MOUSE), 0); } // Mouse

Of course you could just use `SEQ_FOUR_KEYS` to have a longer input sequence.

**Comment by lbibass** [comment]
@pattulus well of course there would be some limitations, like the ten entered characters. Most layer names are simple after all. Thanks for the help! So basically my idea basically already exists in leader key?

**Comment by pattulus** [comment]
If you're willing to accept the leader key as _the first letter to enter_ in the word that represents your layer, then yes.

**Comment by lbibass** [comment]
could it also be more than one letter if I used something like SEQ_THREE_KEY?

**Comment by pattulus** [comment]
Yep, @jackhumbert implemented up sequences up to 5 letters on [June, 22](https://github.com/qmk/qmk_firmware/commit/98f0807359cfa78d25442b91ff4c5bbfc5679661).
