### ISSUE TITLE
Link to "dedicated RP2040 page" is gone.

### ISSUE THREAD

**Issue by DuckersMcQuack** [qmk/qmk_firmware#24735]
### Issue Description

Link at the bottom here directs to a page that doesn't have content anymore.

https://github.com/qmk/qmk_firmware/blob/master/docs/compatible_microcontrollers.md

**Comment by tzarc** [comment]
Use the actual docs page, not GitHub: https://docs.qmk.fm/compatible_microcontrollers

See #24151.
