### ISSUE TITLE
Increase the time required for a hold without affecting TAP_DANCE

### ISSUE THREAD

**Issue by danielo515** [qmk/qmk_firmware#2477]
Hello.

Currently I use space both as space and as shift keys. However, when I type fast I am facing a big problem: sometimes I want an space and I get a shifted key (ej: helloBuddy instead of hello buddy).

I can increase TAPPING_TERM, but that will affect tap dance, which uses (badly chosen IMO) the same config variable.

Any advice will be greatly appreciated.
Regards

**Comment by danielo515** [comment]
I have a solution that almost works. It is not my code, it was suggested by a user at gitter, I think his name is @fredizzimo .
The only non working part from his code is effectively determining the pressed keycode. I'll document here the changes:

add the following to `action_tapping.c`

```c
// This was the old line
// #define WITHIN_TAPPING_TERM(e)  (TIMER_DIFF_16(e.time, tapping_key.event.time) < TAPPING_TERM)
#define WITHIN_TAPPING_TERM(e)  (TIMER_DIFF_16(e.time, tapping_key.event.time) < get_tapping_term(&e))
// Overridable tapping term
__attribute__ ((weak))
uint16_t get_tapping_term(keyevent_t* event) {
    return TAPPING_TERM;
}
```

Of course add the declaration to `action_tapping.h`

```c
uint16_t get_tapping_term(keyevent_t* event);
```

Then you can override the `get_tapping_term` function at any point on your keymap:

```c
uint16_t get_tapping_term(keyevent_t* event) {    
    uint16_t keycode = keymap_key_to_keycode(layer_switch_get_layer(event->key), event->key);
    if (keycode == SFT_T(KC_SPC) )    {
        return TAPPING_TERM + 1250;
    }
    //dprintf("Keycode found is %u", keycode);
    return TAPPING_TERM;
}
```

However the keycode identification thing is not working. I know that it works because if I omit the if statement and just send an high time it works as expected. But it is kinda useless without identifiying the key pressed.

**Comment by drashna** [comment]
Why couldn't this use a case?  Or could it?

**Comment by drashna** [comment]
You mean that it doesn't work for `SFT_T(KC_SPC)`, but only `SFT_T`?

**Comment by drashna** [comment]
Did you ever get this working?

**Comment by drashna** [comment]
Well, if you didn't, I did.

Check out #5009. I tracked down the issue here, and got this working.  And the solution/problem is in the comments.

**Comment by danielo515** [comment]
I'll check it out! Thanks

**Comment by jackhumbert** [comment]
Now that #5009 is merged, I think this can be closed - if you have any issues with implemenation, feel free to comment here!
