### ISSUE TITLE
REMOVE THE ATMEL FLIP INSTALLER IT NUKES PATH VARIABLES

### ISSUE THREAD

**Issue by ForsakenHarmony** [qmk/qmk_firmware#2486]

**Comment by drashna** [comment]
Which OS, and global system paths?

**Comment by ForsakenHarmony** [comment]
windows 10

it wiped everything in PATH and replaced it with itself

glad I could rescue them from webstorm which doesn't auto update the path

**Comment by drashna** [comment]
That's really odd.  I tested this and I'm not seeing this behavior on three different systems.

**Comment by ForsakenHarmony** [comment]
uhhh ok, well it really freaked me out and I'm very glad I could restore it

**Comment by drashna** [comment]
Yeah, I totally understand that. That's ... pretty scary! 

Either way, I'll keep an eye out for anyone reporting this in the future. And if it happens again...
