### ISSUE TITLE
Keycodes for Swap Hands

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_firmware#2497]
The docs for the "swap hands" feature got re-added in #2489.
However, it looks like it only supports the `fn_action` functions. 

The problem with that, is that in all of the documentation, this implementation has been depreciated, and "shouldn't be used".  
In fact, because I use the linker optimization compilation flag, I can't use it, since the `fn_action` function errors out.

Specific keycodes for this feature should be added. Both for consistency, and for newer users. 
But the way to do so... is still a bit above my head

**Comment by Talljoe** [comment]
Fixed in #2520.
