### ISSUE TITLE
Leader Not Working

### ISSUE THREAD

**Issue by shmcgrath** [qmk/qmk_firmware#2514]
My/the leader key is not working. When I hit the leader key followed by the sequence, I get the character I am typing. I have tried it with 1, 2, and 3 keys in sequence. I have made sure that the key is not physically broken. The code is compiling fine and loads onto my Planck without issue. [Here is they keymap I am using.](https://github.com/shmcgrath/qmk_firmware/tree/master/keyboards/planck/keymaps/shmcg) Let me know if you need further information.

**Comment by jackhumbert** [comment]
Here are some other threads on /r/olkb that were having issues as well:

* https://www.reddit.com/r/olkb/comments/837dyv/leader_key_troubles/
* https://www.reddit.com/r/olkb/comments/7u7362/leader_key_timing/

**Comment by randywallace** [comment]
AH HA.  I was tracking this one down, and put together that those settings _must_ go in config.h for them to take effect; otherwise, the default LEADER_TIMEOUT (200ms), which is _very_ short, is set. 

https://docs.qmk.fm/reference/config-options

**Comment by drashna** [comment]
Actually, I think upping the default timeout would be a good idea too.
