### ISSUE TITLE
Cant turn off switch backlighting on DO60

### ISSUE THREAD

**Issue by gh-n** [qmk/qmk_firmware#2538]
I got this pcb from doyu studio's giveaway. I think that this is a prototype pcb

I already tried ACTION_BACKLIGHT_TOGGLE() on keymap.c, #define BACKLIGHT_ON_STATE 0 on config.h

BL_TOGG, BL_DEC also doesnt work.

What do I need to do?

Pin is F4 according to doyu studio.

Here are my files.

[doyu_60.zip](https://github.com/qmk/qmk_firmware/files/1815822/doyu_60.zip)

**Comment by drashna** [comment]
Make sure you've updated your repo, and try running `make clean` and then recompile it.

If that doesn't help, let us know.

**Comment by gh-n** [comment]
the issue is caused by the hardware and not the firmware.
