### ISSUE TITLE
Request push access

### ISSUE THREAD

**Issue by Atlacat** [qmk/qmk_firmware#2567]
How exactly do i get granted access to upload my files?

**Comment by skullydazed** [comment]
Hi @Atlacat, GitHub works by forking a repo to create your own source tree, making the changes there, and submitting a Pull Request back to the main repo from your own repo. We've outlined the process in our own documentation here:

https://docs.qmk.fm/getting_started_github.html

You can also read about the process in the main GitHub documentation:

https://help.github.com/articles/creating-a-pull-request/
