### ISSUE TITLE
New project with Teensy 3.2 support?

### ISSUE THREAD

**Issue by huytd** [qmk/qmk_firmware#2657]
Hi, I'm having an issue with Teensy 3.2

I'm building a custom layout.

When I created a new project using `./utils/new_project.sh`, and flashing the compiled firmware, the computer did not recognize the keyboard.

Is Teensy 3.2 fully supported in QMK yet?

Thanks,
Huy

**Comment by drashna** [comment]
It is.  But I think that the default file is geared more for AVR. 

You need to make sure that all of the settings are correct. 

I'm not an expert here, so somebody like @skullydazed may be better to help.  

But ... you may want something like: 
https://github.com/qmk/qmk_firmware/blob/ab197af2ead7c764aa48ee4a5aa7b1b9633ce5b7/keyboards/k_type/rules.mk

**Comment by huytd** [comment]
@drashna Thanks you so much, I'll try this again!

**Comment by huytd** [comment]
Great! with a bit modification, I'm able to get my board working now!

Thank you so much @drashna

**Comment by drashna** [comment]
Glad to hear it, and you're welcome!

**Comment by DmitryMyadzelets** [comment]
> ... with a bit modification, I'm able ...
@huytd could you tell more what your modifications are, please? I have Teensy 3.2 and have no idea where to start from.

**Comment by huytd** [comment]
@DmitryMyadzelets sorry man, it's quite a long time ago, I still ran into some trouble after that. I ended up writing my own firmware instead of using QMK.

**Comment by DmitryMyadzelets** [comment]
@huytd, would you mind sharing? Can't find in your repos.

I'm new to keyboards, but feel ok with embedded stuff. Don't really want to start from ground though.

**Comment by huytd** [comment]
It's this https://gist.github.com/huytd/8dabf762a868b86d2aa597b878e53df0

You gonna need Teensyduino to compile, don't forget to set the USB Type to Keyboard as commented in the file header.

This version is a 2x2 matrix, but basically you can expand it by changing the constants without the need to modify any other part of the code.

- Change the rows/cols here https://gist.github.com/huytd/8dabf762a868b86d2aa597b878e53df0#file-keyboard-prototype-c-L16-L17
- And change the key mapping matrix here https://gist.github.com/huytd/8dabf762a868b86d2aa597b878e53df0#file-keyboard-prototype-c-L24-L30

The two REGISTER_DELAY and REPEAT_DELAY are for debouncing https://gist.github.com/huytd/8dabf762a868b86d2aa597b878e53df0#file-keyboard-prototype-c-L18-L19

I'm using Cherry MX Brown, if you also using cherry switches, you probably don't have to modify these.

Hope it can help :)

**Comment by huytd** [comment]
Oh, and it's lack of per-key-debouncing, modifiers and layout switching at this moment. But I think it's easy to implement these once we have a barebone code above.

**Comment by DmitryMyadzelets** [comment]
Oh, great! Thank you, @huytd. I have installed the toolchain already and uploaded a first test to the Teensy. So far so good.

**Comment by huytd** [comment]
@DmitryMyadzelets hey, if you're (and anyone) still interested, I'm just finished my keyboard, you can take a look at the code here https://github.com/huytd/snackymini-keyboard/blob/master/firmware/firmware.ino

It has 2 layouts and I think it's pretty easy to customize now.
