### ISSUE TITLE
RSFT + RPRN break board

### ISSUE THREAD

**Issue by crilith** [qmk/qmk_firmware#2726]
I have a row with TILD,EXLM .... LPRN,RPRN on it, but if I hold FN2 and RSFT and press any of these keys, nothing responds the way it should and I have to reset my board.  For example, BSPC because LGUI,  R becomes 2 etc...

**Comment by drashna** [comment]
Yeah, it's triggering the COMMAND key, which is both shifts.  

You can change trigger for this, by adding something like this to your config.h:
```c
#ifdef IS_COMMAND
#undef IS_COMMAND
#endif
#define IS_COMMAND() ( \
    keyboard_report->mods == (MOD_BIT(KC_LSHIFT) | MOD_BIT(KC_LALT)) \
```

Or by disabling the "COMMAND" feature.
