### ISSUE TITLE
chaining one shot mods

### ISSUE THREAD

**Issue by manogna4** [qmk/qmk_firmware#2796]
I would like to tap 'ctrl', tap 'shift' and then tap 'a' to get 'Ctrl+Shift+a'. At present this can be done with only one modifier. Tapping the second modifier cancels the first one. The above combination produces 'Shift+a' i.e. 'A'

This is a duplicate of [856](https://github.com/qmk/qmk_firmware/issues/856) and of [1580](https://github.com/qmk/qmk_firmware/issues/1580) but has been opened because @algernon asked for it on reddit/olkb. Both issues were closed because they were too difficult to do.

**Comment by manogna4** [comment]
it works 😃 This is brilliant. Thanks.
Such a simple change too. I wonder why the the comments on the previous issues said it was too hard...

I'll let you know if it leads to any problems. I ran some simple tests, and it didn't cause any issues. I do not use any tapping toggles so I won't be able to tell you if it works with them.

**Comment by algernon** [comment]
It may look simple, but it took me about four hours to find the right places to modify =)
It is almost always simple in hindsight.

**Comment by manogna4** [comment]
whoa! Thanks a lot for your effort then. This frees up several keys on my layer.

**Comment by drashna** [comment]
Awesome!

**Comment by DanielGGordon** [comment]
Woah cool - can we make a PR for this?

**Comment by algernon** [comment]
There is a PR for this, #2799.
