### ISSUE TITLE
Daisy40: Msys2 sh: dfu-programmer: command not found

### ISSUE THREAD

**Issue by chamster22** [qmk/qmk_firmware#2841]
![image](https://user-images.githubusercontent.com/38803028/39403772-4ef2229c-4bb6-11e8-9a78-e01653b168e9.png)

My board is on bootloader mode already. I tried cloning the dfu-programmer into the qmk_firmware folder from this link: https://github.com/dfu-programmer/dfu-programmer.

Same error still shows up.

**Comment by drashna** [comment]
Try re-running the installation script. 

If that doesn't help...
Download dfu-programmer from here: http://downloads.sourceforge.net/project/dfu-programmer/dfu-programmer/0.7.2/dfu-programmer-win-0.7.2.zip
And extract that to `C:\MSYS64\home\(username)\qmk_utils\dfu-programmer`
And download http://dfu-util.sourceforge.net/releases/dfu-util-0.9-win64.zip
And extract that to `C:\MSYS64\home\(username)\qmk_utils\dfu-util-0.9-win64`
