### ISSUE TITLE
How can I print the debug info via USB ?

### ISSUE THREAD

**Issue by YipCharles** [qmk/qmk_firmware#2872]
I wanna print some info or message through the keyboard itself, what should I do?
I currently use "add_key(KC_XXX);   send_keyboard_report();" , which is dumb. I want print(String) instead of it.

**Comment by drashna** [comment]
it sounds like you are referring to two different things.

If you want to send keystrokes, there are a couple of ways to do that: 
`register_code(KC_xxxx)` and `unregister_code(KC_xxxx)`, and
`SEND_STRING`.  

Both of these type out stuff on the keyboard (as if you pressed the keys).

If you want to print debugging information, that's completely different.  For this,  need to add `CONSOLE_ENABLE=yes` to your rules.mk file, and use HID_LISTEN (part of QMK Toolbox) to see the output on the host system. 
Then you need to inable debug printing: https://docs.qmk.fm/faq/debugging-troubleshooting-qmk#cant-get-message-on-console
