### ISSUE TITLE
Compile failing due to HIDParser

### ISSUE THREAD

**Issue by sQVe** [qmk/qmk_firmware#2912]
I'm running Arch Linux and I keep failing to compile the `default` keymap for `ergodox_ez` on a fresh clone. It errors at:
```
lib/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.c:93:5: error: 'memcpy' accessing 42 bytes at offsets 28 and 0 overlaps 14 bytes at offset 28 [-Werror=restrict]
     memcpy((CurrStateTable + 1),
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
            CurrStateTable,
            ~~~~~~~~~~~~~~~
            sizeof(HID_ReportItem_t));
            ~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
 [ERRORS]
 | 
 | 
 | 
make[1]: *** [tmk_core/rules.mk:360: .build/obj_ergodox_ez_default/./lib/lufa/LUFA/Drivers/USB/Class/Common/HIDParser.o] Error 1
Make finished with errors
make: *** [Makefile:549: ergodox_ez:default] Error 1
```
Would love some help getting this sorted. Here's a list of the dependencies and their versions that I have installed: [dependencies.txt](https://github.com/qmk/qmk_firmware/files/1984287/dependencies.txt)

___________________________________
_EDIT_

I tried compiling via Docker and that worked fine. This is, very likely, a problem with `qmk_firmware` not supporting a newer version of a dependency.

**Comment by RomanRiesen** [comment]
Have the exact error. Also on Arch.

**Comment by sQVe** [comment]
@RomanRiesen Yeah. Like I noted in my _edit_ this is likely due to not supporting a new dependency version. We should revert back to building with Docker until it is fixed.

The docker build solution is actually pretty damn smooth, I must say.

**Comment by RomanRiesen** [comment]
@sQVe I've just installed Debian in a VM and fought it to accept shared folders and it worked without a flaw.

Yeah. The docker solution sounds pretty neat.

**Comment by fredizzimo** [comment]
This looks like a bug in the lufa library. `memcpy` does not support overlapping regions, so `memmove` (bad name) should have been used instead.

**Comment by drashna** [comment]
@fredizzimo #2914 would fix this, correct?

**Comment by AstroProfundis** [comment]
Tried this patch on ArchLinux with `avr-gcc` 8.1.0, and worked fine for me. Thanks!

**Comment by jackhumbert** [comment]
Awesome - that's been merged, so I think we can close this. Please let us know if it doesn't fix it!
