### ISSUE TITLE
Add TOC to documentation pages

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#2919]
Currently our documentation site does not display a Table of Contents. We'd like a floating box on each page to display a clickable TOC.

We are looking for a frontend developer who can write a docsify plugin to achieve this. The documentation for writing a plugin is here: https://docsify.js.org/#/write-a-plugin

**Comment by drashna** [comment]
Yeah, that was one of the things I noticed and miss. :(

**Comment by Viroide** [comment]
As far as I can tell this is done, right? 
![Screenshot 2020-10-01 at 01 04 35](https://user-images.githubusercontent.com/713362/94748689-26695080-0382-11eb-8eaa-192388b88ce9.png)

**Comment by tzarc** [comment]
Done.
