### ISSUE TITLE
Help with hex, msys64, make command not found

### ISSUE THREAD

**Issue by neanic** [qmk/qmk_firmware#2948]
I've been trying to get qmk going for my iris. I made it to the make hex part but now I'm stuck. I was following this guide-  https://www.reddit.com/r/olkb/comments/7pnsrc/qmk_guide_for_flashing_keyboards/

I'm getting "make :command not found" after running make iris/rev2:default

**Comment by drashna** [comment]
make sure that you are actually in the qmk folder.

You may need to run `cd qmk` or `cd qmk_firmware` before running the make command.

**Comment by neanic** [comment]
I've tried a few different folders with the same result. I'm pretty sure I'm in the right one though. 
I had a similar message earlier in the install when I was trying to run a git command. I ended up having to run this command:  pacman -S git﻿ . I was wondering if there was something like that that I'm missing. It took me a while to find that and I haven't been able to find anything, except what you recommended, about it.

**Comment by neanic** [comment]
Thanks for trying guys. I think I'm just too dense.  I followed everything, to the best of my ability, with the same result. 
./util/qmk_install.sh didn't seem to do anything...
Anyone want to buy a soldered iris with blue leds?

**Comment by drashna** [comment]
If you are fine with using the default layout: http://qmk.fm/compiled/iris_rev2_default.hex
https://github.com/qmk/qmk_firmware/tree/master/keyboards/iris/keymaps/default/keymap.c

Otherwise, if you have a customized keymap that you want to use, you can link it here, and and I can see about helping. 

And I do have some remote support tools, so I could possibly help with gitting it installed.

**Comment by neanic** [comment]
I deleted qmk and reinstalled it.

![capture](https://user-images.githubusercontent.com/38307461/40028421-58f65ed0-57a4-11e8-983a-b99bee17e041.JPG)

**Comment by jbtompkins** [comment]
Have you installed gcc on msys2? I think the command is

`pacman -S mingw-w64-x86_64-toolchain`

**Comment by neanic** [comment]
Installed it. 
Same result.

**Comment by drashna** [comment]
try `util/msys2_install.sh`instead

**Comment by neanic** [comment]
It works!
Thanks for all the help. I'll try to flash it tomorrow.

**Comment by neanic** [comment]
Having issues flashing my pro micros. Should I start a new issue?

**Comment by neanic** [comment]
![avrdudes](https://user-images.githubusercontent.com/38307461/40813616-6f01033c-6501-11e8-918e-ca41f84ce9fc.JPG)

I'm sure I'm doing something wrong. I also tried to do it in msys, but couldn't connect either.

**Comment by drashna** [comment]
AVRDUDESS needs to use the "avr109" programmer, and use the PORT in question. 

![image](https://user-images.githubusercontent.com/2584963/40814398-dc85bdd8-64f4-11e8-8477-519dc8ce1854.png)

**Comment by neanic** [comment]
![avrdude](https://user-images.githubusercontent.com/38307461/40880976-e8043742-6680-11e8-92b3-eb9f746f4127.JPG)

**Comment by neanic** [comment]
Do I hold the button when turning it on or  push it after? Should I keep it pressed while flashing? Do I have to change the port manually somehow?

**Comment by neanic** [comment]
It changes from com4 to com5 but still doesn't work.

**Comment by neanic** [comment]
I think it may be a driver problem, but I'm not sure how to fix it.

**Comment by neanic** [comment]
Thanks for the help. Sorry for being so dense.
