### ISSUE TITLE
K-type RGB lighting

### ISSUE THREAD

**Issue by sonnius** [qmk/qmk_firmware#2964]
Opening an issue to track this, I know it's been mentioned before here:
https://github.com/qmk/qmk_firmware/pull/1963

Would it be fair to assume the massdrop CTRL and/or ALT (https://www.massdrop.com/buy/massdrop-alt-mechanical-keyboard)  will use the same backlight chip as the k-type? If it does we might be able to leverage the CTRL configs as the new keyboard would run QMK

**Comment by emersonriver** [comment]
Any news on this?
The Ctrl is shipping rn.

**Comment by drashna** [comment]
Support for the CTRL is already added, actually.

As for the K-Type, what chip is it using for both the MCU and the RGB controller (if separate)?

**Comment by sonnius** [comment]
> Support for the CTRL is already added, actually.
> 
> As for the K-Type, what chip is it using for both the MCU and the RGB controller (if separate)?

MK20DX256VLH7 | NXP / Freescale | ARM   Microcontrollers - MCU KINETIS 256K
and
IS31FL3733 | ISSI | 12x16 DOTS   MATRIX LED DRIVER, QFN-48

Complete BOM can be found here: https://github.com/kiibohd/pcb/tree/master/K-Type

I'd love to program up (full) support for the K-type but I'm not a good enough programmer, that said I've been using qmk with the k-type for months now without issues, great stuff!!!

**Comment by drashna** [comment]
Ah, okay. It's using the same MCU as the WhiteFox which exists in the QMK repo already, and uses ChibiOS.

The CTRL uses a completely different MCU and should not be compared to the K-Type, at all. 

But the board definitely can be ported over.  The biggest difference here may be that the K-Type uses a 3733 while the whitefox uses a 3731 controller for the LEDs.   But the RGB Matrix feature should support ARM already. 

So if anyone is willing to put in the work, it should be possible. 
https://github.com/qmk/qmk_firmware/tree/master/keyboards/whitefox
https://docs.qmk.fm/#/feature_rgb_matrix?id=is31fl3733
