### ISSUE TITLE
I'm still a bit confused with the make command. I want to compile a hex for my satan gh60 in the poker layout and when I do this  "satan:poker" it says make: *** No rule to make target 'satan:poker'.

### ISSUE THREAD

**Issue by anorraq** [qmk/qmk_firmware#2988]

**Comment by drashna** [comment]
What folder are you in?

**Comment by anorraq** [comment]
I'm a bit confused with your question (first time really doing this stuff). If you mean which folder was the command window in, I hadn't entered any folder so I was entering the code. I did try to use "/c/qmk_firmware/keyboards/satan:poker" and still got the same result (if that was what you were wondering).

**Comment by drashna** [comment]
For the linux shell, the folder matters.  You should be in the qmk_firmware folder.  And from there, you want to run `make satan:poker`. 

so ... for here, run `cd /c/qmk_firmware`, and then run `make satan:poker`

**Comment by anorraq** [comment]
awesome it works now! Thanks for bearing with me.

**Comment by drashna** [comment]
awesome, glad to hear it!

**Comment by drashna** [comment]
Since this is solved, closing.

**Comment by speakeasymy** [comment]
this has helped me too. thank you!
