### ISSUE TITLE
Switching and Toggling Layers with shifted keys

### ISSUE THREAD

**Issue by loloArctic** [qmk/qmk_firmware#3008]
Shifted keys don't work with layer tapping.
For example:
LT(_LOWER, KC_QUES) or LT(_LOWER, S(KC_SLSH)) typed "/".
It's bug?

**Comment by drashna** [comment]
Yeah, it's a know bug. 

It has to do with the way that it processes the keycode.  Eg, it needs to be updated/fixed.

**Comment by Maxr1998** [comment]
So, I dived a bit into this (before even seeing the issue), and found out that the Shift key (225) in e.g. `LM(_LAYER, KC_LSFT)` is interpreted as left Ctrl (224). Using `KC_LSFT + 1`, or, interestingly, also  `KC_LSFT + 1` fixes the issue
