### ISSUE TITLE
Option to disable double tap.

### ISSUE THREAD

**Issue by fi0** [qmk/qmk_firmware#3144]
When I tap once, release, and hold, i want to use it as a single hold, or a single tap with a single hold. Currently, it repeats the tap key. But i couldn't find the right setting. Is this supported?

**Comment by drashna** [comment]
You may want to try adding `#define TAPPING_FORCE_HOLD` to your `config.h` file then.  

IIRC, that should do what you want.

**Comment by fi0** [comment]
thank you!! That's the option I'm looking for!
