### ISSUE TITLE
Best way to use spacebar in dual-role?

### ISSUE THREAD

**Issue by broken-username** [qmk/qmk_firmware#3184]
No matter which modifications I've tried on any of my keyboards running QMK, using spacebar as Control when held will, at least every so often, act as Control when it hasn't been depressed for very long and I happened to hit another key very shortly after the space. I'm not sure if it's because my thumb is lingering for the tiniest amount of time longer than I mean to, or something else. Regular typing suffers as a result. I observe no spacing issue when the spacebar is not dual-role. 

I thought setting the TAPPING_TERM to something outrageously high (like over 4000) might do the trick, but the problem persists, though reduced. I've adjusted my typing technique a bit, which does help, but always ends up feeling very deliberate, and the goal is to be rid of the problem altogether.

Is there any clever way to adjust the timing further? Maybe have a required, very slight, delay in which the Control won't engage with another key if the timing between them is too brief?

I think TAPPING_TERM and other settings could afford to have more in-depth documentation on matters like these.

**Comment by drashna** [comment]
Try adding this to your config.h file: 
```c
#define IGNORE_MOD_TAP_INTERRUPT
#undef PERMISSIVE_HOLD
```

**Comment by broken-username** [comment]
Well, I won't pronounce this solved just yet, but after a lot of test typing with no special change in the way that I do it, this seems to have worked. Is there documentation on IGNORE_MOD_TAP_INTERRUPT that I missed? I've heard of the option previously, but haven't seen much of a description anywhere.

**Comment by drashna** [comment]
https://docs.qmk.fm/#/config_options?id=behaviors-that-can-be-configured

But it's not well described.  However, this is a good description:
```
// this makes it possible to do rolling combos (zx) with keys that
// convert to other keys on hold (z becomes ctrl when you hold it,
// and when this option isn't enabled, z rapidly followed by x
// actually sends Ctrl-x. That's bad.)
```

**Comment by broken-username** [comment]
Ah, okay. That may be something to consider documenting at greater length, then - until now I thought there was no easy solution and that alphas just didn't cut it as dual-role keys. There may have been a time when that was true, but apparently not anymore! Thank you for your help.

**Comment by drashna** [comment]
IIRC, fredizzimo was going to do that, or overhaul the code.  When he gets a chance. 

But there are some other options, like `RETRO_TAPPING` that may help, too.

**Comment by schodet** [comment]
I think you need `TAPPING_FORCE_HOLD`, I have a PR which adds doc about it: #3320
