### ISSUE TITLE
Changing SS Pin for SPI Bluetooth Communication

### ISSUE THREAD

**Issue by Suzaken** [qmk/qmk_firmware#3187]
The bluetooth code that Wez made has the SPI protocol communicate using the Slave select as the B0 pin on the atmega32u4. Is there a way to change the Slave Select pin to a different I/O pin? This is the code. [https://github.com/qmk/qmk_firmware/blob/master/tmk_core/protocol/lufa/adafruit_ble.cpp](url)

**Comment by drashna** [comment]
Not sure if this would work (probably), 
Add something like this to the top:
```c
#ifndef AdafruitBleSSPin
#define AdafruitBleSSPin B0
#endif
```

And replace the call with: 
```c
    digitalWrite(AdafruitBleSSPin, PinLevelHigh);
    pinMode(AdafruitBleSSPin, PinDirectionOutput);
```

That should all it to work "normally" for the boards that use it, and should allow you to redefine the pin, if/when needed.

**Comment by Suzaken** [comment]
Thanks for the help. Tried that, I feel like I'm still missing something. I believe that this part of the code would also have to be changed for me to redefine the pin, but I'm not sure what I would change. 
[https://github.com/qmk/qmk_firmware/blob/master/quantum/pincontrol.h](url)

**Comment by drashna** [comment]
Unfortunately, that's about the extent of my expertise here.  Sorry.

**Comment by fauxpark** [comment]
@Suzaken so the thing with the SS pin is it's required to initially be logic high for the AVRs to stay in SPI master mode, regardless of whether you're actually using it - B0 is left floating in the Feather schematic. The real slave select pin is in fact `AdafruitBleCSPin`.
