### ISSUE TITLE
anyone already have keymap like this? for DZ60

### ISSUE THREAD

**Issue by Ziggomatic** [qmk/qmk_firmware#3277]
https://i.imgur.com/wOdBEOg.png

**Comment by drashna** [comment]
It's not perfect, but `LAYOUT_all` would get this, only because ... it gets everything.   However, `LAYOUT_directional` is pretty close too. 
https://config.qmk.fm/#/dz60/LAYOUT_all
https://config.qmk.fm/#/dz60/LAYOUT_directional

**Comment by Ziggomatic** [comment]
someone on geekhack gave me json and hex file! thanks you
