### ISSUE TITLE
How to turn on a LED on Ergodox EZ on Tap Dance

### ISSUE THREAD

**Issue by zzz2496** [qmk/qmk_firmware#3344]
Hi,

Here's what I want to do. I want to single tap/hold left shift to do normal shift. I want double tap left shift to capslock. For now, I've been successfully compile Tap Dance enabled firmware with @drashna's help. The single tap or hold is somewhat flakey, but it'll do. How do I turn my blue LED on so that I know it's in capslock mode?

Thanks in advance,

Damir.

Edit1: After several testing, the shift key does not instantly register - I think it's waiting for TAPPING_TERM to time out before registering, why is it doing that?

**Comment by zzz2496** [comment]
After several testing, the LEFT shift key does not instantly register - I think it's waiting for TAPPING_TERM to time out before registering, why is it doing that?

**Comment by drashna** [comment]
Does it have to be CAPS LOCK?  Would it be okay if it was a"SHIFT lock"?  

If so, One Shot keys may be a better solution for you. 
https://docs.qmk.fm/#/feature_advanced_keycodes?id=one-shot-keys

If you add the following to your config.h: 
```c
#define ONESHOT_TAP_TOGGLE 2  /* Tapping this number of times holds the key until tapped this number of times again. */
#define ONESHOT_TIMEOUT 2000  /* Time (in ms) before the one shot key is released */
```
And use `OSM(MOD_LSFT)`, tap to apply shift to the next press, hold to .... well, act as a normal shift, and double tap to lock shift "on".

**Comment by zzz2496** [comment]
@drashna Wow, you really are responsive... 
Well, it doesn't have to be capslock. The main idea is to have all the alphas to be shifted. With the shift locked, I can write many characters and need to press the shift key again to un-shift, and light a LED to indicate that it's in shift-lock mode.

Thanks,

Damir.

**Comment by drashna** [comment]
Ah, okay.  You should be able to do that with tapdance.   
On the "tap" version, you may want to check to see of the mod is active, and if it is, run `unregister_code(KC_LSFT)` rather than `register_code`.  That would let you toggle it.

As for the LED stuff... 
https://github.com/drashna/qmk_firmware/blob/60159cfb93bd53780cfa7cc5add35cde654e831f/layouts/community/ergodox/drashna/keymap.c#L296-L325

That's what I do for my ergodox.  The first one detects if shift, one shot shit, or caps lock is "on".  If so, then show a light, otherwise turn it off. 

:)

**Comment by zzz2496** [comment]
Finally my code works, with Tap Dance with LEDs and all. It does what I wanted to do, but it has a weird quirk that I can't seem to fix (everything is in my repo, https://github.com/zzz2496/qmk_firmware)

1. It needs TAPPING_TERM to time out before the shift key registered.
2. The double tap does not always turns on the SHIFT lock mode. I think, the state->count doesn't always reset to 0? And I don't know how to debug my code, unless I flash my keyboard so many times for unnecessary flashing burden on the EEPROM.

But, for now, it does what I need it to do. Hopefully I can determine why it does the quirks, and fix it.

Damir.
