### ISSUE TITLE
Hand wired Dactyl w/ Pro Micros compiles and flashes but shows up as unknown device

### ISSUE THREAD

**Issue by Krakob** [qmk/qmk_firmware#3387]
Hello! Currently building a Dactyl. As the title says, it's using Pro Micros and the firmware compiles and flashes correctly. Plugging it in on Windows 7 shows it as a bunch of devices, with one subdevice as unknown and reporting error code 43. On Linux it doesn't show up with lsusb at all. Neither take any input from it. I'm using serial for the cross communication, but I don't think that's an issue here.

My firmware code is at https://gitlab.com/Krakob/Dactyl-qmk/tree/master/keyboards/Dactyl

It's the version Crystalhand recommended when he ran the group-buy back in February. I've tried popping it into the latest version of qmk as well, but I'm getting the same results there.

Thanks in advance!

**Comment by Krakob** [comment]
For reference, how the device shows up in Windows:
![explorer_2018-07-12_23-51-02](https://user-images.githubusercontent.com/2838013/42727011-ac94377c-879e-11e8-9f92-e55c27089a1a.png)

**Comment by kdb424** [comment]
Are you flashing on Linux or Windows? If on Linux, do you have ModemManager installed? This can easily corrupt the flash.

**Comment by Krakob** [comment]
Couldn't save the micros, but luckily I had exactly four when beginning this project. Thanks so much! :)
