### ISSUE TITLE
Update docs: How to Use Github with QMK

### ISSUE THREAD

**Issue by evantravers** [qmk/qmk_firmware#3416]
I am continuing my tour of the QMK docs… and I was looking at the How to Use Github page. 

It has a good description of how to get started, but I'm worried that the non-standard terminal prompt style on the page will confuse its intended audience. 

Maybe go from

```
**[prompt you@computer]**[path ~]**[delimiter  $ ]**[command git clone https://github.com/whoeveryouare/qmk_firmware.git]
```

to

```
user@computer:~$ git clone https://github.com/whoeveryouare/qmk_firmware.git
```

https://docs.qmk.fm/#/getting_started_github

**Comment by fauxpark** [comment]
This is an artifact from the previous incarnation of the docs that used Gitbook. It had a plugin installed that would make these blocks look more like a terminal prompt, with black background and everything. Not exactly "non-standard", just badly formatted :)
