### ISSUE TITLE
JJ40 underglow LEDs 1/5 working

### ISSUE THREAD

**Issue by danicedenv** [qmk/qmk_firmware#3467]
I got myself a jj40 for my first build. I plugged in the pcb, tested every switch contact and it worked fine. The only issue was that only 1 underglow led was working. I decided to use qmk configurator to make my own layout. I flashed it onto the board and everything worked great except I still had the same issue. I decided to leave it and try later and when I plugged it in the leds were working fine, the only issue were the keys I used to setup the rgb they only worked with the one led that was on the whole time. After plugging it back in one more time it went back to only one led working. I am pretty new to this so I have 0 clue what the problem is. I could really use some help! Thanks in advance

**Comment by noroadsleft** [comment]
I know nothing personally about this issue, but #3199 is likely related.

**Comment by drashna** [comment]
I suspect that this may be working now, since all of the ps2avrGB boards have been overhauled.
