### ISSUE TITLE
Need documentation about international layouts

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#3485]
We have a lot of users who come into discord to ask about how to work with international layouts. We should write a page documenting how that works.

* Short description how letters appear when you type. switch -> scancode -> computer -> language mapping -> letter on screen
* Explain that due to historical reasons US ANSI is the "default"
* Explain how to use language specific includes in `quantum/keymap_extras`

**Comment by ThomDietrich** [comment]
Hello,
as a fresh Ergodox owner located in Germany I have similar questions and would welcome such a page. Is a *raw* pile of information present somewhere?

**Comment by skullydazed** [comment]
I think the closest we have are the includes here: https://github.com/qmk/qmk_firmware/tree/master/quantum/keymap_extras

If you're working on this, or just trying to figure out how to make it happen with your own keyboard, right now the best place to get more info is [discord](https://discord.gg/Uq7gcHh), people there have varying levels of knowledge.

**Comment by ThomDietrich** [comment]
* https://github.com/qmk/qmk_firmware/blob/master/docs/how_keyboards_work.md

* https://github.com/qmk/qmk_firmware/issues/520
* https://www.reddit.com/r/olkb/comments/4vrie0/is_there_a_way_to_make_the_plancks_layout/

**Comment by ubone** [comment]
is having a cyrillic layer even possible?

**Comment by MetalDent** [comment]
Hi, anyone working on this issue?

**Comment by sakshamtaneja21** [comment]
there are so many typos in this file

**Comment by jackhumbert** [comment]
@fauxpark is working on some docs that will help with this.

**Comment by fauxpark** [comment]
This is done as of #9194:
https://docs.qmk.fm/#/reference_keymap_extras
