### ISSUE TITLE
Minor errors documentation of tap dance

### ISSUE THREAD

**Issue by Croccifixio** [qmk/qmk_firmware#3529]
I was following __Example 4: 'Quad Function Tap-Dance'__ and came across a few minor errors in the example code and accompanying documentation.

**Comment by drashna** [comment]
I think that these were dealt with, and this issue can be closed?

**Comment by Croccifixio** [comment]
Yup, I think this issue can be closed.

**Comment by drashna** [comment]
Awesome!
