### ISSUE TITLE
Backlight flashing on XD75

### ISSUE THREAD

**Issue by ArpinFidel** [qmk/qmk_firmware#3555]
Hi, I'm new to qmk. I'm trying to add backlight functionality to my XD75 but when i enable backlight in rules.mk, the backlight just keeps flickering. Using BL_DEC eventually turns the backlight off but other keys don't seem to work. This seems really similar to a previous issue. #2226

I tried checking whether it's the same problem or not but this time the parenthesis is fine.

I got around the issue by using the keycaps_led_on and off from xd75.c but these don't allow me to change the backlight brightness. Is there some other way to have brightness control? 

update  : BL_INC and BL_DEC now work after undef ing BACKLIGHT_BREATHING. however the leds flicker and BL_TOGG still doesn't work.

update 2 : wiped eeprom. found out that flicker stops when underglow isn't set to breath. BL_TOGG can turn on backlight but not off. didn't test this before wiping.

**Comment by wanleg** [comment]
why are you using BL_? i use [RGB_ instead](https://github.com/qmk/qmk_firmware/blob/master/docs/feature_rgblight.md) and don't have any issues
here's my [layout](https://github.com/wanleg/qmk_firmware/tree/WanlegPersonal/keyboards/xd75/keymaps/wanleg) if you want to compare

**Comment by wanleg** [comment]
have you seen this [reddit post](https://www.reddit.com/r/MechanicalKeyboards/comments/7tjql1/xd75_backlighting_flickering/) already?

**Comment by ArpinFidel** [comment]
ooh thanks. i haven't actually. only searched on r/olkb lol. that one is about the same thing as issue #2226 though. it was fixed a while back.

i found another issue similar to this even on a supported pin #3566 and the flickering is apparently documented already so this should probably be closed.
