### ISSUE TITLE
YMDK np21 -> Unsupported target atmega32a 

### ISSUE THREAD

**Issue by zakanybalazs** [qmk/qmk_firmware#3559]
Support for this device is there but when running make ymdk:np21:default:dfu never flashes the device, only drops error 
```
Error: Bootloader not found. Trying again in 5s.
Unsupported target 'atmega32a'.
targets:
...
```

**Comment by drashna** [comment]
You can't use `dfu` here.  It's not supported, at all.  You MUST use the`program` target.

https://github.com/qmk/qmk_firmware/tree/master/keyboards/ymdk_np21
