### ISSUE TITLE
Bluetooth does not allow remapping of modifier keys on macOS.

### ISSUE THREAD

**Issue by Miodec** [qmk/qmk_firmware#3578]
This is a pretty weird issue. When i connect my board with usb i can remap the modifier keys as usual in the system preferences, but on bluetooth this option is not present. It also doesnt work with third party software like karabiner.

![screen shot 2018-08-06 at 00 22 43](https://user-images.githubusercontent.com/13181393/43691122-0634629e-990f-11e8-9c5c-1ae7c164e75d.png)
![screen shot 2018-08-06 at 00 23 03](https://user-images.githubusercontent.com/13181393/43691123-0651c456-990f-11e8-90f4-0a3982f33f3b.png)
![screen shot 2018-08-06 at 00 23 49](https://user-images.githubusercontent.com/13181393/43691124-066c8aac-990f-11e8-9e7d-0cb041bb44a5.png)

**Comment by Miodec** [comment]
Update: Karabiner does work, but the issue is still there for the system preferences remapping.

**Comment by StyXman** [comment]
A side question: which board are you using, that has USB and BT?

**Comment by Miodec** [comment]
Cutom board with the Feather Bluefruit as the controller

**Comment by drashna** [comment]
Do other USB boards work? 

Also, this sounds like it may be a software bug, and not a QMK issue?

**Comment by jackhumbert** [comment]
> this sounds like it may be a software bug, and not a QMK issue?

This is my understanding of it as well - if you have any other boards you can test and report back with, feel free to reopen/comment!
