### ISSUE TITLE
cospad layer_state_set error

### ISSUE THREAD

**Issue by eletoblade** [qmk/qmk_firmware#3616]
Hi,
  I am a totally new user to QMK, the C language and git hub so I apologize if this this a really basic/stupid question but: I have a cospad keyboard and I am attempting to get the under glow lighting to change based on the layer state. While I was going through the QMK documentation (link below, bottom of page) I found the layer_state_set implementation and an example of what I am trying to do but cannot seem to get it to work. I have tried multiple variations on this, with using unit32_t as suggested, as well as unit16_t (this is what my keymaps use so I figured it should be the same) and I keep getting the same error when I attempt to compile. The error I am getting is saying that the unit16_t is an unknown type. I have included screenshots of my code (in the keymap file) and error in my MSYS2 terminal for reference. I have no idea what this means or how to fix, any help would be greatly appreciated.

![image](https://user-images.githubusercontent.com/40427431/43984960-dee648d0-9cd1-11e8-9793-d53d6ef21b5c.png)

![image](https://user-images.githubusercontent.com/40427431/43984980-f22ba98a-9cd1-11e8-8c12-75271596f6a4.png)

[https://docs.qmk.fm/#/custom_quantum_functions](url)

**Comment by jackhumbert** [comment]
Looks like this is just a spelling issue `unit16_t` should be `uint16_t ` :)

**Comment by eletoblade** [comment]
![image](https://user-images.githubusercontent.com/40427431/43986055-fbbef08e-9cda-11e8-8bc9-167ac3bc25c8.png)

thanks for the help
