### ISSUE TITLE
Clean up old RGB LED defines

### ISSUE THREAD

**Issue by nooges** [qmk/qmk_firmware#3641]
List of old `#define`s that need to be cleaned up from config.h files:

- [ ] `#define ws2812_PORTREG  PORTD`
- [ ] `#define ws2812_DDRREG   DDRD`
- [ ] `#define RGBLIGHT_TIMER`

**Comment by Woovie** [comment]
Does this only affect `#define ws2812_DDRREG DDRD`? I also found these:
```#define ws2812_DDRREG   DDRB
 * #define ws2812_DDRREG   DDRF
#define ws2812_DDRREG   DDRF
 * #define ws2812_DDRREG   DDRF
#define ws2812_DDRREG   DDRF
#define ws2812_DDRREG   DDRF```

I assume yes, but checking. Thank you!

**Comment by Woovie** [comment]
Created the following bash one liner and executed it against the codebase: https://pastebin.com/raw/5qLC8GzN

Created pull request #3713
