### ISSUE TITLE
Atreus documentation links broken

### ISSUE THREAD

**Issue by pepijndevos** [qmk/qmk_firmware#3684]
A similar issue was fixed for the Ergodox (#1594), but Atreus also has some dead links. I found some related pages, but no exact match, so I'll refrain from making a PR without knowing the intended page.

> See [build environment setup](https://docs.qmk.fm/build_environment_setup.html) then the [make instructions](https://docs.qmk.fm/make_instructions.html) for more information.

**Comment by noroadsleft** [comment]
A lot of the keyboards have this issue.

I know the fix, but I'm involved elsewhere for the time being.
