### ISSUE TITLE
Space Cadet Shifts sends extraneous input with KC_GESC

### ISSUE THREAD

**Issue by edward-shen** [qmk/qmk_firmware#3701]
When typing with normal alphanumeric characters a quick shift + character sends the correct output. However, when space cadet shifts are enabled, Using either shifts for a `Shift + GESC` to access ~ outputs `~)` and `~(` when the keycombo is pressed quickly enough.

For reference, I'm using a DZ60 with pretty vanilla firmware (no special macros or anything).

Let me know if there's any additional information needed, but I think this should be reproducible in all keyboards.

**Comment by edward-shen** [comment]
Is there a possible workaround for this issue?

**Comment by drashna** [comment]
Not that I'm aware of.

**Comment by edward-shen** [comment]
It was mentioned that #5226 fixes this issue, but #5226 was replaced by #5277—@XScorpion2, can this issue by closed?

**Comment by XScorpion2** [comment]
Ya, this issue should be closed. I just tested it to make sure this doesn't occur with the latest code too and it all checks out.

**Comment by noroadsleft** [comment]
Thanks for reporting this!
