### ISSUE TITLE
is31fl3733 support: DRIVER_COUNT 1 not compiling

### ISSUE THREAD

**Issue by YousKab** [qmk/qmk_firmware#3797]
@yiancar @drashna 

makefile is only compiling when I set driver_count to 2, even though both drivers are addressed (same address since only one driver)

Btw, I coudn't get it to work.

**Comment by drashna** [comment]
Yup, talked about this in discord.

Setting `#define DRIVER_COUNT 1` causes it to error out on the 3733 version, even though it only supports one controller, ATM.

**Comment by yiancar** [comment]
Yes for now just leave it at 2. the second address you define is not used anyway. This is because atm the driver is not clever enough to know what to do. This will be fixed in the future, possibly when someone actually needs to use 2 drivers
