### ISSUE TITLE
bfo9000 avrdude out of range

### ISSUE THREAD

**Issue by AlexanderElias** [qmk/qmk_firmware#3859]
Hello the this is my first keyboard build so please forgive any newbieness. 

I am getting a error after I try to flash the firmware on a pro micro. 

I can post the error but it simply states that there is an address out of range. 

Arch Linux 14.18
bfo-9000
Pro micro

Steps:
1. Download master branch
2. Run the install script
3. Execute sudo make bfo9000:default
4. Execute sudo make bfo9000:default:avrdude

The error occurred at this point.

I appreciate the project and any help is greatly appreciated.

**Comment by nooges** [comment]
Downgrade avr-gcc from 8.2.0 to 8.1.0

**Comment by AlexanderElias** [comment]
Yup that worked. Thanks!
