### ISSUE TITLE
Autoshift doesn't work on Massdrop CTRL keyboard

### ISSUE THREAD

**Issue by swiftkoder** [qmk/qmk_firmware#3880]
This is for building keymap with autoshift enable for Massdrop's CTRL keyboard. 

When setting AUTO_SHIFT_ENABLE = yes in rule.mk, build fails with the error below.  

`Linking: .build/massdrop_ctrl_swiftkoder.elf                                                        [ERRORS]
 |
 | /usr/local/Cellar/gcc-arm-none-eabi/20171218/bin/../lib/gcc/arm-none-eabi/7.2.1/../../../../arm-none-eabi/lib/thumb/v7e-m/fpv4-sp/hard/libg.a(lib_a-sbrkr.o): In function `_sbrk_r':
 | sbrkr.c:(.text._sbrk_r+0xc): undefined reference to `_sbrk'
 | collect2: error: ld returned 1 exit status
 |
make[1]: *** [.build/massdrop_ctrl_swiftkoder.elf] Error 1
make: *** [massdrop/ctrl:swiftkoder] Error 1`

I was able to fix the compile error by commenting out line 40 of process_auto_shift.c, but after I flashed the firmware with this change to my CTRL keyboard I noticed the keys became unresponsive and not outputing anything to a text editor. Is this a hardware issue or a software issue?

**Comment by lbibass** [comment]
Sounds like a software issue.

**Comment by swiftkoder** [comment]
@lbibass Thanks for responding.  I was able to get "d" into "D" on one random occasion, but most of time nothing happens when a key is pressed for long duration.  My suspicion was that this has something to do with the timer.

**Comment by drashna** [comment]
It sounds like that this may be an issue with the timer? 

@jcowgar Maybe you have some insight? 
(the massdrop boards are ARM boards using ATSAM rather than ChibiOS)

**Comment by vomindoraan** [comment]
Looks like this is resolved by #3973.

**Comment by swiftkoder** [comment]
ConfIrmed autoshift is working with patrick's branch.  Closing this issue.
