### ISSUE TITLE
avrdude error in both qmk toolbox and ubuntu

### ISSUE THREAD

**Issue by coseyfannitutti** [qmk/qmk_firmware#3898]
I'm getting an avrdude error, "ERROR: address 0x800277 out of range at line 1184". I've tried flashing with both qmk toolbox on windows and also on a vm with ubuntu and get the same error.

**Comment by drashna** [comment]
Try reverting to AVR-GCC 8.1, as there is a change in 8.2 that cause AVRDUDE to fail.

**Comment by drashna** [comment]
This is also brought up in #3657, and you should follow that, as well.
