### ISSUE TITLE
:qmk target missing dependencies

### ISSUE THREAD

**Issue by q3w3e3** [qmk/qmk_firmware#3938]
This seems to be msys2 specific.

The `:qmk` target is missing both zip (Note: zip 3.0 has a bug in zipnote, and zip 3.1 does not exist in gnu for windows) and jq dependencies. Zip isn't installed, and jq doesn't exist for MSYS2 repo.

The workaround for now seems to be to use `:dfu-util`

**Comment by q3w3e3** [comment]
Correction, `:dfu-util` seems to be the correct method for my use case not an alternative method, the issue with `:qmk` still stands,

**Comment by drashna** [comment]
What did you do to get the right version of ZIP installed? 

And `pacman -Sy mingw64/mingw-w64-x86_64-jq` should install the correct version of jq.

**Comment by q3w3e3** [comment]
I downloaded it from https://sourceforge.net/projects/gnuwin32/files/

Both zip and bzip2 are needed, I cannot recall the exact version but it was
a single version downgrade from 3.0, I want to say it was 2.5.3(?)

I realize this is an ungraceful solution but it's all I've got.


https://stackoverflow.com/questions/38782928/how-to-add-man-and-zip-to-git-bash-installation-on-windows

May have some more/better info.

**Comment by drashna** [comment]
IIRC, it was never quite finished, and isn't supposed to be moved. 

Also, we have the `:flash` target now.
