### ISSUE TITLE
Update config.h template with new #defines

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_firmware#3947]
To save some more space in firmware, we can disable the handling for `action_get_macros` and `fn_actions`. They are depreciated so why not disable them? 

Add the following to `config.h` template 

```c
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
```

template files are located in: 

1. https://github.com/qmk/qmk_firmware/blob/master/quantum/template/avr/config.h
2. https://github.com/qmk/qmk_firmware/blob/master/quantum/template/ps2avrgb/config.h

**Comment by drashna** [comment]
Better question is: 

Since these features are depreciated, do we want to actually disable them by default, and allow them to be turned on for compatibility?

**Comment by noroadsleft** [comment]
@drashna 

> Since these features are depreciated

deprecated* :smile: 


@mechmerlin I'm okay with the spirit of these changes, but a lot of the keymaps in the repo have been ported from TMK, so we would have to go through each keymap that uses `fn_actions`/`action_get_macro` and refactor its functionality into `process_record_user`.

**Comment by jackhumbert** [comment]
This was implemented in #7211.
