### ISSUE TITLE
Auto shift does not work for non-us keys

### ISSUE THREAD

**Issue by ant-i-c-s** [qmk/qmk_firmware#4070]
**Keyboard:** ErgoDox EZ

Auto shift works fine for most keys except `KC_NONUS_BSLASH`, which repeats instead of sending `|`.

**Comment by drashna** [comment]
If you could, and you're compiling from source, could you apply this? 
```diff
diff --git a/quantum/process_keycode/process_auto_shift.c b/quantum/process_keycode/process_auto_shift.c
index 01d99445b..0d0930ee6 100644
--- a/quantum/process_keycode/process_auto_shift.c
+++ b/quantum/process_keycode/process_auto_shift.c
@@ -173,6 +173,8 @@ bool process_auto_shift(uint16_t keycode, keyrecord_t *record) {
       case KC_DOT:
       case KC_SLSH:
       case KC_GRAVE:
+      case KC_NONUS_BSLASH:
+      case KC_NONUS_HASH:
 #endif

         autoshift_flush();
```

Save this content to a file, and then use `git apply (filename)` to apply this, and see if it works. 


This may not work, though.

**Comment by ant-i-c-s** [comment]
That worked! Thank you.

**Comment by drashna** [comment]
Awesome!  I'll make a PR to merge this then.  Unless you want to :)
