### ISSUE TITLE
qmk_install.sh vs install_dependencies.sh

### ISSUE THREAD

**Issue by leifmetcalf** [qmk/qmk_firmware#4092]
The 'Complete Newb's Guide' tells you to run `qmk_install.sh`. The docs home page links to [this guide,](https://docs.qmk.fm/#/getting_started_build_tools) which tells you to use `install_dependencies.sh` instead. They both seem to do the same thing, except `install_dependencies.sh` is specialised to Linux.

How do they differ, and why should they both exist?

**Comment by SoulEst** [comment]
qmk_install.sh is a front-end. Its job is to find out which operating system you're using and then execute the appropriate script for installing the dependencies.

**Comment by leifmetcalf** [comment]
Maybe a better comparison would be `linux_install.sh` and `install_dependencies.sh` then.

**Comment by SoulEst** [comment]
From what I've read in the scripts, the linux_install.sh script is meant to get around an issue with avr-gcc 8.2. That issue may have been cleared up by now.

**Comment by drashna** [comment]
`install_dependencies.sh` is a legacy file, and could probably be removed.

The `qmk_install.sh` is the file to use, as it should support most OS's, and calls the correct installation scripts.
