### ISSUE TITLE
The Combo Feature needs some work

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_firmware#4112]
The main thing I'm concerned about is that you MUST specify the number of COMBO's being used, rather than it reading the list and determining that.

Eg, this should act more like the fn_actions or tapdance code, rather than hard coding the number of combos.

**Comment by onetom** [comment]
I would call this issue: "Determine COMBO_COUNT automatically"

**Comment by drashna** [comment]
This was done, I think.  By me.

**Comment by noahfrederick** [comment]
> This was done, I think. By me.

The [docs](https://docs.qmk.fm/#/feature_combo) still say:

> Additionally, in your `config.h`, you'll need to specify the number of combos that you'll be using, by adding `#define COMBO_COUNT 1` (replacing 1 with the number that you're using).

Is this no longer the case? I can't find the relevant change. Thanks.
