### ISSUE TITLE
Can't find a JSON default layout file to import for Massdrop ctrl keyboard

### ISSUE THREAD

**Issue by jamesalmeida** [qmk/qmk_firmware#4175]
I'm trying to use QMK Configurator to change my keyboard configuration but Im at a loss since it doesn't have a default layout to load and I can't find a JSON default layout file to import either. Anyone know how I can do this?

**Comment by just-another-jxliu** [comment]
This one? https://github.com/qmk/qmk_firmware/blob/master/keyboards/massdrop/ctrl/info.json

**Comment by noroadsleft** [comment]
@just-another-jxliu That file is for a different purpose; it's not for keymaps.

@jamesalmeida I can file a PR to the Configurator repo (it's not in qmk/qmk_firmware) that adds a default for the CTRL. Give me a bit.

**Comment by drashna** [comment]
To clarify, the default keymap in the Configurator isn't handled by QMK Firmware. It's actually files added to the Configurator repo.   So there is a bit of a disconnect there.

**Comment by jamesalmeida** [comment]
> This one? https://github.com/qmk/qmk_firmware/blob/master/keyboards/massdrop/ctrl/info.json

At first I thought this was it too but it's not the right file.

**Comment by jamesalmeida** [comment]
> @just-another-jxliu That file is for a different purpose; it's not for keymaps.
> 
> @jamesalmeida I can file a PR to the Configurator repo (it's not in qmk/qmk_firmware) that adds a default for the CTRL. Give me a bit.

Thank you!

**Comment by drashna** [comment]
@jamesalmeida Specifically, you'd need to add a layout here: https://github.com/qmk/qmk_configurator/tree/master/keymaps

Once that's done, then the "load default" button will work.

**Comment by noroadsleft** [comment]
PR is up. :arrow_up:

**Comment by noroadsleft** [comment]
PR is merged.

https://config.qmk.fm/#/massdrop/ctrl/LAYOUT

**Comment by drashna** [comment]
Awesome.

Closing this issue since it should be resolved.
