### ISSUE TITLE
reset mitosis

### ISSUE THREAD

**Issue by blawiz** [qmk/qmk_firmware#4177]
How can one 'reset' mitosis keyboard to flash it?

**Comment by drashna** [comment]
I think that the RESET keycode should work.

If not, it uses a Pro Micro for the USB adapter, correct?  If so, short the RST pin to GND twice, and it will reset it to bootloader.

**Comment by blawiz** [comment]
Oh, i found that there were two buttons on the receiver (didn't look like buttons to me), but one of them was reset :), but what is the RESET keycode?

**Comment by drashna** [comment]
Awesome.

And the reset keycode is `RESET`. :)
https://docs.qmk.fm/#/quantum_keycodes?id=qmk-keycodes

**Comment by blawiz** [comment]
X)
