### ISSUE TITLE
"Soft meta" feature

### ISSUE THREAD

**Issue by eraserhd** [qmk/qmk_firmware#4185]
I've implemented a kind of software Meta key for my ErgoDox mapping, where holding down `X` or `,` acts as though any keys pressed while they are held are preceded by tapping Escape.  This has the advantage that it works regardless of how Option keys are configured on Mac OS, meaning I can carry around my keyboard to other people's computers, and also that I can work around mapping bugs in Alacritty.

What I have is kind of hacked-together, but if there is enough interest, I'll make it a proper feature and contribute it back.

(What I have is [here](https://github.com/eraserhd/qmk_firmware/blob/master/keyboards/ergodox_ez/keymaps/eraserhd/soft_meta.h), by the way.)

**Comment by drashna** [comment]
Well, Ctrl-GUI swap was added recently, that may be a better option?

**Comment by eraserhd** [comment]
I'm no longer using this, and the link is no longer valid, so closing.
