### ISSUE TITLE
Media keys not interacting with Media programs

### ISSUE THREAD

**Issue by jwyang0213** [qmk/qmk_firmware#4229]
Hello! I am currently using Satan gh60 and I am using Windows 10.

KC_MEDIA_NEXT_TRACK | KC_MNXT | Next Track (Windows)
KC_MEDIA_PREV_TRACK | KC_MPRV | Previous Track (Windows)
KC_MEDIA_STOP | KC_MSTP | Stop Track (Windows)

I used these media keys using the aliases like KC_MSTP on my code, but it does not interact with many of the media programs, like foobar2000, Groove Music or youtube. But it seems that it works with some programs like Potplayer.

So I looked up the Autohotkey history and it shows that the registered media keys are "artificial" which I have no idea what it means. I think this has to do with this because if I register media keys with keys that were redirected by Autohotkeys it does not say artificial and it works fine.

However, it seems that the volumn keys, although they appear as "artificial", works fine. 

I've tried turning off all the autohotkey scripts but no luck there too.
EXTRAKEY_ENABLE is yes also in rules.mk file...

Thanks for your time!

**Comment by drashna** [comment]
Odd.   If you use Switch Hitter, I get this for the "play" button:
```
7:41.0108  (0xB3, BIOS 0xE000) DOWN
17:41.0229  (0xB3, BIOS 0xE000) UP -> 121ms
```

And it works properly.  It may be worth testing this out.

**Comment by drashna** [comment]
It sounds like AHK is intercepting it, and messing with it somehow.  :(

**Comment by Jungwoo0213** [comment]
As I have tried to open and close various programs, I turned out that I was not AHK.
It was actually the Google Music extension in Chrome browser.
I removed it and it works fine now!

**Comment by max-su** [comment]
Thanks so much! This helped me out a lot I had the same issue on Windows but not on Mac. 👍 also worked for me.

**Comment by Xiseous** [comment]
Reopening, W11,

KC_MEDIA_PLAY_PAUSE	KC_MPLY	Play/Pause Track

Not working using full name or alias,

Previous, Next, Volume up and down interact without issues.
