### ISSUE TITLE
Consolidate documentation

### ISSUE THREAD

**Issue by ezuk** [qmk/qmk_firmware#424]
Instead of build_guide etc., make one giant readme -- a book, a canonical source of truth.

**Comment by jackhumbert** [comment]
I started this yesterday, and added some more documentation on the functions/files. I put a header at the top of `doc/BUILD_GUIDE.md` to reflect that it's been moved to the main one.

**Comment by ezuk** [comment]
awesome!

**Comment by jackhumbert** [comment]
I think this was "finished" by moving everything to `docs/`.
