### ISSUE TITLE
Mouse speed/acceleration does not reset when rolling onto a different direction

### ISSUE THREAD

**Issue by ajh3** [qmk/qmk_firmware#4242]
What I mean by this is: hold your right mouse movement key until it achieves max speed, and then press the left mouse key BEFORE letting up on the right one. The mouse velocity immediately inverts - the cursor is suddenly moving in the opposite direction... at max speed. 

The expected behavior would be for the acceleration period to occur again when switching mouse directions, even when rolling onto a new direction instead of fully releasing the old direction before pressing the new one. (Edit: perhaps the current behavior is acceptable for 90 degree changes in direction, but not for 180 degrees.)

This is on an Ergodox EZ, default keymap (and custom keymaps, too), latest version of QMK.

**Comment by filterpaper** [comment]
#21494 and #23341 has fixed this issue.
