### ISSUE TITLE
Change EOF terminators for file keyboards/qwertyydox/rules.mk

### ISSUE THREAD

**Issue by Agilulfo** [qmk/qmk_firmware#4280]
Hi I'm having some troubles when I clone this repo.
[This file](https://github.com/qmk/qmk_firmware/blob/master/keyboards/qwertyydox/rules.mk) is showed as modified and there is no way to discard the changes.

The cause seems to be the .gitattributes file that require all the .mk files to have lf as EOF.

**Comment by drashna** [comment]
Ugh.... yeah, sorry.  Normally, that should get changed on upload, but ... sometimes it slips through. 

I've added a PR that should fix this.
