### ISSUE TITLE
No Interrobang‽

### ISSUE THREAD

**Issue by mrceephax** [qmk/qmk_firmware#4315]
Please add support

https://en.wikipedia.org/wiki/Interrobang

**Comment by coarse** [comment]
You can input an interrobang via [unicode support](https://docs.qmk.fm/#/feature_unicode)

**Comment by drashna** [comment]
To clarify, the interrobang is not in the set of characters supported by the usb HID scancodes.
That means that the only way to support it is via alternate input methods.  And specifically through unicode input.

**Comment by vomindoraan** [comment]
‽ in three easy steps:

1. Add `UNICODE_ENABLE = yes` to your `rules.mk`.
2. Call `set_unicode_input_mode` with the correct [input mode](https://docs.qmk.fm/#/feature_unicode?id=unicode-input-methods) for your OS in `matrix_init_user` in `keymap.c`. For example:
```c
void matrix_init_user(void) {
  set_unicode_input_mode(UC_LNX);
}
```
3. Put `UC(0x203D)` somewhere in your layout in `keymap.c`.

If you're keeping your layout code aligned nicely, `UC(0x203D)` will be longer than the other keycodes; in that case I suggest you `#define BANG UC(0x203D)` at the top of the file and then put `BANG` in the keymap instead.

I think this can be closed.

**Comment by mrceephax** [comment]
Thanks!
