### ISSUE TITLE
Failure to make

### ISSUE THREAD

**Issue by daltanious** [qmk/qmk_firmware#4318]
I run 
> make planck/rev5:default

and get
> Making planck/rev5 with keymap default
> /bin/sh: avr-gcc: command not found
> sh: avr-gcc: command not found
> sh: avr-gcc: command not found
> make[1]: *** [tmk_core/rules.mk:242: gccversion] Error 127
> Make finished with errors
> make: *** [Makefile:544: planck/rev5:default] Error 1

I'm thinking that I've unzipped the git file and put it in the wrong hierarchy. I've got it in C:\keebs\qmk\qmk_firmware for reference.
Also, I've followed [Chokkan's ](https://www.youtube.com/channel/UCtLJJRsmtUgCWLj_Ud9URfA) excellent videos in the past with success, but I'm stumped here.

**Comment by drashna** [comment]
avr-gcc isn't present.   You need to run `util/qmk_install.sh` from the qmk_firmware folder.

**Comment by daltanious** [comment]
Thank you. I have done this and I get
> The utils seem to already be downloaded.
The AVR toolchain is already installed.
The ARM toolchain is already installed.

I am running the make command from the same folder. 
To be fair, I have been plagued by this issue for at least a year, and I'm not a programmer, so I'm slow on the uptake.

**Comment by drashna** [comment]
run `avr-gcc --version` on the system, and report the output

**Comment by daltanious** [comment]
Geez.

> bash: avr-gcc: command not found

**Comment by drashna** [comment]
okay, what OS is this?

**Comment by daltanious** [comment]
Sorry, it's W10

**Comment by drashna** [comment]
Okay. that's what I thought.  Are you using MSYS2, or WSL/Bash for windows?

**Comment by daltanious** [comment]
Msys2 64bit

**Comment by daltanious** [comment]
In the c: folder

**Comment by daltanious** [comment]
Many thanks. I'll try this after my commute is over tonight. Cheers

**Comment by daltanious** [comment]
I don't have the gcc-etc folder. Should I run the echo in the qmk_firmware dir?

**Comment by drashna** [comment]
The correct name is `avr8-gnu-toolchain`, which you do appear to have. 

And you should be able to run that `echo` command anywhere. `~` is the "home" directory (`\MSYS2\home\(username)`). 

So yes, please do run it, and then exit MSYS and reload it.

**Comment by daltanious** [comment]
Did that to no avail. I think I'm going to do a fresh install of msys2. What is the recommended file hierarchy? I was thinking c/keebs/qmk_firmware but where should I install msys2, also in keebs?

**Comment by drashna** [comment]
in your home directory, find and open `.bashrc`.  Make sure that's calling the `activate_msys2.sh` script.  If not, then that's the problem.

**Comment by drashna** [comment]
As for reinstalling MSYS, that's up to you. But using the default location should be fine.  It has other uses. But that's up to you. 

Also, ..... I do have some remote support software, and I could see about looking at your system directly.  And see if I can get things working.

**Comment by daltanious** [comment]
Looks like my gccversion isn't up to snuff. Tried to update it with `pacman -S base-devel --needed` and selected all, but there is nothing to do.

![image](https://user-images.githubusercontent.com/32861628/48029978-e0ab9b00-e10c-11e8-8939-dd25e4cb7cd5.png)

**Comment by daltanious** [comment]
I looked into the .bashrc file. Every line is commented out, except 19 `[[ "$-" != *i* ]] && return` so it looks to me like that is the problem, as you stated above.

**Comment by drashna** [comment]
The rest of that stuff is fine, but you absolutely need `source ~/qmk_utils/activate_msys2.sh` at the end there, or somewhere there.

So definitely add that, save the file, and reopen the MSYS MINGW64 console.  Once you do that, avr-gcc should work

**Comment by daltanious** [comment]
I'm sorry I'm so dense. I'm on the verge of liking this, if I can get his to work. 
Um, I've searched for the qmk_utils folder and I can't see it. I'm on install 5 of msys2 and the qmk_firmware, so I'm in the weeds here. Should it be in the msys2 folders or the qmk_firmware folder?

**Comment by drashna** [comment]
qmk_utils should be in `C:\msys64\home\(username)\qmk_utils`.

If you have issues with that, .... I have some remote support software, and I can see about helping you get this set up and working properly more directly.

**Comment by daltanious** [comment]
I got it to work. I'm a mess. I ended up pulling an old folder out of my recycling bin and had it work in there. I did run into some trouble, where the lower keys didn't have enough underscore spaces to compile correctly. Figured it out!

**Comment by hewit110** [comment]
What lower keys are you referring to? I'm still having the same problem.
