### ISSUE TITLE
Fade not working when key pressed

### ISSUE THREAD

**Issue by Rainonmepls** [qmk/qmk_firmware#4332]
I flash the program but all of the fade effects are not working

**Comment by drashna** [comment]
What keyboard is this?

**Comment by Rainonmepls** [comment]
I am using massdrop ctrl keyboard

**Comment by drashna** [comment]
Okay, that's what I thought.  I'm tagging @patrickmt here, as he is more familiar with the Massdrop rgb matrix code than I.

**Comment by Rainonmepls** [comment]
do u have the same problem as me ?

**Comment by drashna** [comment]
I don't have a CTRL or ALT, which is why I'm not very familiar with the code for it, at all.   It's not the "RGB Matrix" code from the QMK feature, but custom stuff.

**Comment by DarkMio** [comment]
Describe the effect you are interested in and the steps you took to do it.

Do all LEDs operate normally in other modes? What do you do to enable said effect on your keyboard?

**Comment by Rainonmepls** [comment]
I wan the effects to be like this video https://www.youtube.com/watch?v=ntZn0AcSwt8
I just flash the program that was on the repo

**Comment by DarkMio** [comment]
That is not on this repository. This is part of my fork on my branch of the repository and is not part of the normal firmware.

You can checkout my repository with a branch called massdrop_mio or so and compile with ``massdrop/CTRL:darkmio`` or something like that - this should give you the scrolling fade. Otherwise, the video linked has a repository linked that has that written.

**Comment by DarkMio** [comment]
There is no firmware compiled in the video description. It is true that I do only have the scrolling effect, while @matsprehn has a fading only effect.

You likely have compiled my repo when you wanted to compile the other repository.

**Comment by Rainonmepls** [comment]
i can't seem to find your repo and I uploaded his file but he also have the scrolling fade effect
