### ISSUE TITLE
SEND_STRING style macro sends continuous input stream until keyboard is unplugged

### ISSUE THREAD

**Issue by cbailey555** [qmk/qmk_firmware#4341]
Hi. I have a macro of the following format:
```
      case EXPI3:
          SEND_STRING(
            SS_DOWN(X_LALT)
            SS_DOWN(X_K)
            SS_UP(X_LALT)
            SS_UP(X_K)
            );
```
That's supposed to execute one ALT + K combination to move focus on an I3 window. When I trigger this macro, the keyboard continuously sends inputs causing I3 to completely flip out until I unplug the keyboard.

I made a similar function with a leader key using
```
      register_code(KC_LALT);
      register_code(KC_K);
      unregister_code(KC_LALT);
      unregister_code(KC_K);
```
That works completely fine. 

In another leader key function that had both a SEND_STRING macro and a sequence of register/unregister_code calls, I a similar issue where it was repeating the final sequence of keys.

I'm using a thevankeyboards Bananasplit
QMK Toolbox 0.0.9 (1)
QMK 0.6.156

**Comment by drashna** [comment]
Try `SEND_STRING(SS_LALT("k"));`

**Comment by cbailey555** [comment]
These both reproduce the original behavior I'm afraid.

**Comment by drashna** [comment]
could you run `avr-gcc --version`and report the output?

**Comment by cbailey555** [comment]
avr-gcc (GCC) 7.3.0

**Comment by vomindoraan** [comment]
Could you provide more context surrounding the `case EXPI3` section you posted? It might be that you just forgot to add a `break` or appropriate `return`. Ideally post the entire function, or link to the file if your code is on GitHub (that would be the best way).

**Comment by cbailey555** [comment]
You nailed it. I am not smart and don't often program in C; the switch was just missing breaks to prevent it from falling all the way through after matching. Thanks for helping me out.

**Comment by vomindoraan** [comment]
You're welcome, glad I could help!
