### ISSUE TITLE
1UpKeyboards 1Up60hse Default Layout Inconsistent From QMK Configurator

### ISSUE THREAD

**Issue by loganhuskins** [qmk/qmk_firmware#4350]
The default layout in QMK for 1UpKeyboard's 1up60hse is different than the default layout generated by QMK Configurator. The layout represented in the repo is consistent with what is shipped on the board, but I prefer the layout that the Configurator generates.

I am going to add a layout that matches the Configurator, open a PR, and reference here when it's up.

**Comment by loganhuskins** [comment]
PR: https://github.com/qmk/qmk_firmware/pull/4351

**Comment by mechmerlin** [comment]
This issue was resolved in PR #4351
