### ISSUE TITLE
The currently supported 68keys board is a duplicate of the mf68

### ISSUE THREAD

**Issue by zvecr** [qmk/qmk_firmware#4391]
The currently supported 68keys board is a duplicate of the mf68. According to the docs, the [site](https://68keys.io/guide/board/) details the process of getting the mf68 gerber files printed without any modifications.

Suggestion: merge keyboard folders together, adding the existing 68keys default keymap to mf68/keymaps/68keys

**Comment by drashna** [comment]
It may be, but it's different people doing it.  

I'd feel better about leaving them as separate boards.

**Comment by drashna** [comment]
Because in this case, it may not be the same PCB.  

And in that case, we do have something like tht already with the planck, contra, fractal, and the like.

**Comment by zvecr** [comment]
From the site i linked, 
The github link points to a repo with the following commit:
https://github.com/sbstjn/tmk_keyboard/commit/ffb1d7a5250d9d6219d00902885b532983ca0e1b
Add symlink to mf68 PCB

and an image from that page:
![white mf68](https://68keys.io/images/board/diodes-pre.jpg)

I have to say, Its a shame to hear that this awesome project advocates for code duplication.

**Comment by drashna** [comment]
Ah, okay, it is the same PCB then.  In that case, yeah, don't need multiple boards.

**Comment by zvecr** [comment]
Cheers @drashna. Thanks for hearing me out on this one.
