### ISSUE TITLE
Kira 75 support 

### ISSUE THREAD

**Issue by DillonHightower** [qmk/qmk_firmware#4431]
Kira 75

There is an issue with default load out.

It does not have back lighting on or rgb under glow on by default. It is turned off.

**Comment by noroadsleft** [comment]
Should just be

```
BACKLIGHT_ENABLE = yes       # Enable keyboard backlight functionality on B7 by default
RGBLIGHT_ENABLE = yes        # Enable keyboard RGB underglow
```

in `keyboards/kira75/rules.mk`, I think. Don't have underglow on my board so not 100% sure on that.

**Comment by mechmerlin** [comment]
As noroadsleft has said, it is just a change to the `rules.mk` file. 

When I put the board into QMK, we weren't turning on all backlighting by default. I'm not opposed to doing that.
