### ISSUE TITLE
All rest notes are ignored in songs, even included songs.

### ISSUE THREAD

**Issue by mld2443** [qmk/qmk_firmware#4450]
for instance, the built in song `LP_NUMB` has a signature rest in it. The playback of this song on my Planck rev4 completely skips the rest and goes to the next note.

This might be a simple off-by-one style error, since `NOTE_REST` is defined as `0.00f`. There is one place where note frequency is part of a condition and it's in `audio.c:581` and I suspect this is the start of the problem, as it sets the `TIMER_1_PERIOD` to `0` and this has further influence in this function.

**Comment by drashna** [comment]
I think that this is a known issue, without much of a solution.
