### ISSUE TITLE
Media Track Navigation Double Press

### ISSUE THREAD

**Issue by AnthonyWharton** [qmk/qmk_firmware#4451]
When using the media next/previous track keys (`KC_MNXT`/`KC_MPRV` respectively) I experience double presses (i.e. the track is skipped twice). This happens regardless of where the key is bound, and regardless of the layer in which it is bound. 

I honestly have no idea of how to get a low level look at what is being sent to the machine, but a quick test on `xev` on Linux doesn't seem to show an unusual amount of inputs coming from the keyboard, in fact it looks remarkably normal:

```
##### PRESSING/RELEASING MEDIA PLAY/PAUSE

FocusOut event, serial 34, synthetic NO, window 0x3a00001,
    mode NotifyGrab, detail NotifyAncestor

FocusOut event, serial 34, synthetic NO, window 0x3a00001,
    mode NotifyUngrab, detail NotifyPointer

FocusIn event, serial 34, synthetic NO, window 0x3a00001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 34, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

##### PRESSING/RELEASING MEDIA PREVIOUS

FocusOut event, serial 34, synthetic NO, window 0x3a00001,
    mode NotifyGrab, detail NotifyAncestor

FocusOut event, serial 34, synthetic NO, window 0x3a00001,
    mode NotifyUngrab, detail NotifyPointer

FocusIn event, serial 34, synthetic NO, window 0x3a00001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 34, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0

##### PRESSING/RELEASING MEDIA NEXT

FocusOut event, serial 34, synthetic NO, window 0x3a00001,
    mode NotifyGrab, detail NotifyAncestor

FocusOut event, serial 34, synthetic NO, window 0x3a00001,
    mode NotifyUngrab, detail NotifyPointer

FocusIn event, serial 34, synthetic NO, window 0x3a00001,
    mode NotifyUngrab, detail NotifyAncestor

KeymapNotify event, serial 34, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
```

You can find the exact layout that I am using [here (https://github.com/qmk/qmk_firmware/blob/master/keyboards/ymd96/keymaps/AnthonyWharton/keymap.c)](https://github.com/qmk/qmk_firmware/blob/master/keyboards/ymd96/keymaps/AnthonyWharton/keymap.c).

Bit lost on this one, so any help would be appreciated!

**Comment by drashna** [comment]
I suspect that this is an issue with VUSB.  But have no idea on how to fix/resolve this. 

Though, maybe try adding `#define QMK_KEYS_PER_SCAN 4` to your keymap's `config.h` file, and see if that helps.
