### ISSUE TITLE
steno is outputting incorrect keystrokes

### ISSUE THREAD

**Issue by xsrvmy** [qmk/qmk_firmware#4506]
When I use TXBolt steno, the keystrokes that are outputted are incorrect. For example, the left T outputs a left T followed by a left W. I have already checked that this issue is not because of the keyboard itself since changing the layout does not change the incorrect output.

**Comment by drashna** [comment]
I think this is a duplicate of this: https://github.com/qmk/qmk_firmware/issues/4578

(well, this was first, but that thread has more information, and may be helpful.
