### ISSUE TITLE
[fortitude60] inconsistent default keymap comment (against implementation).

### ISSUE THREAD

**Issue by zfhrp6** [qmk/qmk_firmware#4507]
In fortitude60 keymap.c, there is inconsistent comment.
the comment says R5 2nd-left key is CTRL, but the implementation is ALT.

in Qwerty block.
comment: https://github.com/qmk/qmk_firmware/blob/a495326aed8292138577387d9124a4b980904d37/keyboards/fortitude60/keymaps/default/keymap.c#L44
implementation: https://github.com/qmk/qmk_firmware/blob/a495326aed8292138577387d9124a4b980904d37/keyboards/fortitude60/keymaps/default/keymap.c#L52

That's also in Dvorak and Colemak.

**Comment by drashna** [comment]
Good catch. 

If you open up a pull request again in the future, you can add something like "fixes #4507" in the PR description, and it will automatically close the associated issue when it's merged.  

It makes cleanup easier for us, but isn't required.
