### ISSUE TITLE
Caps-lock LED woes xd87

### ISSUE THREAD

**Issue by WarmCatUK** [qmk/qmk_firmware#4517]
I obtained an xd87 and intended on running qmk on it. Someone beat me to it but hadn't added caps-lock led support.
Caps led seems to be on pin E2.
Led flashes upon keyboard being plugged in, but led doesn't toggle with caps lock (stays off).
Initially assumed the issue was only under osx, however installed windows 10 on bootcamp and issue persists.
Here's the code in xd87 I've added:
```C
void led_init_ports(void) {
    // Set caps lock LED pin as output
    DDRE |= (1 << 2);
    // Default to off
    //PORTE &= ~(1 << 2);
}

void led_set_kb(uint8_t usb_led) {
    // put your keyboard LED indicator (ex: Caps Lock LED) toggling code here
    if (usb_led & (1 << USB_LED_CAPS_LOCK)) {
        //register_code(KC_C); //to test if this actually gets executed (it doesnt)
        PORTE &= ~(1 << 2);
    } else {
        //register_code(KC_O); //to test if this actually gets executed (it doesnt)
        PORTE |= (1 << 2);
    }
  led_set_user(usb_led);
}
```

Here is the file: https://github.com/WarmCatUK/qmk_firmware/blob/messingabout/keyboards/xd87/xd87.c

*edit* fixed code formatting

**Comment by WarmCatUK** [comment]
I can build a layout with qmkeyboard.cn which toggles the led no problem, so it must be something silly I'm missing out or doing wrong.

**Comment by fougner** [comment]
I remember having some issues with this when playing around with it. Unfortunately I have it at work so I can't try stuff out, but I can check it during the week.
@WarmCatUK IIRC all background lighting leds were connected to a MOSFET and I don't remember seeing any special handling for the capslock led, how is it connected hardware wise? Have you verified your code actually executes with e.g. a print statement and use hid_listen to check?

**Comment by WarmCatUK** [comment]
It’s connected directly to E2. I don’t think the code is executing.
I’ll look into how to using hid_listen and give that a go :-)

**Comment by fougner** [comment]
https://github.com/fougner/qmk_firmware/commits/xd87-capslock

this seems to be working for me. That's a pretty old parent though, so something might've changed in upstreams master since then

**Comment by fougner** [comment]
So I did a bisect to figure out why it doesnt work on latest master. Seems this commit broke it. https://github.com/qmk/qmk_firmware/commit/39bd760faf2666e91d6dc5b199f02fa3206c6acd

@mechmerlin anything changed in how the led functions are called?

**Comment by fougner** [comment]
Let's close this as a dupe of https://github.com/qmk/qmk_firmware/issues/4471 then. 

Seems like people agree on the faulty commit.

**Comment by WarmCatUK** [comment]
Yep good idea, can discuss further on #4471
