### ISSUE TITLE
Tap layer with Space key does't work in RETRO_TAPPING

### ISSUE THREAD

**Issue by couces** [qmk/qmk_firmware#4528]
I configured LT(1,KC_SPACE) and define RETRO_TAPPING. LT with other key worked well, but I couldn't input Space on RETRO_TAPPING.

**Comment by drashna** [comment]
What keyboard are you using? 

Also, are you defining this in your config.h, or keymap.c file?  (it needs to be in the config.h file)

**Comment by drashna** [comment]
Are you using the Ergodox EZ Configurator to generate the firmware file, or are you compiling from source? 

If you're compiling from source, make sure you've updated the config. 

Also, could you post a link to your keymap?
