### ISSUE TITLE
Tx Bolt ghosting second character on key press

### ISSUE THREAD

**Issue by sdothum** [qmk/qmk_firmware#4578]
Commit c0baf2a964b10d708281c704c0b049a1cf0f4914 on Sat Nov 18 09:38:15 2017 -0600 causes Tx Bolt mode to ghost a second character on most key presses (confirmed on Planck and Splitography keyboards). The ghosted character is always the same character from the layout matrix per key, though, is from a unique relative position to the key pressed -- that is, there is no obvious discernible pattern to the ghosted keys.

The ghosted keys are such, KEYPRESS:output

    S:s   T:tw  P:pk  H:hs  *:*p  *:*h  F:ft  P:p   L:l   T:td  D:d
    S:sh  K:kp  W:wt  R:r   *:*k  *:*w  R:rs  B:b   G:g   S:s   Z:z 
                A:ah  O:ow              E:ep  U:uk

The last working commit for Tx Bolt is 5f4c2dfd84467dc7f04e8e07c294ebfa5b4ca459T

**Comment by drashna** [comment]
Well, the simple solution in the short term would be to revert that commit, and see if it fixes it.

eg `git revert c0baf2a`

**Comment by xsrvmy** [comment]
Can confirm that version 0.6.4 does not have this issue. Hopefully this gets fixed soon.

**Comment by drashna** [comment]
@xsrvmy Could you try running the git command above on your local branch, and see if that fixes the issue?

**Comment by xsrvmy** [comment]
@drashna I reverted to a slightly earlier commit with a version number on it and it's working properly.

**Comment by drashna** [comment]
/sigh
`git revert` is not going back to a specific point in time.  It actually reverts the change that the commit made, essentially removing it. 

So the reason I asked about that command specifically, is to see if that change was the cause.  And from there, we can see if we can figure out what went wrong. 

Because otherwise, your using code that is a year out of date, and missing a lot of fixes.

**Comment by xsrvmy** [comment]
I checked out master and did the revert and it works fine.

**Comment by drashna** [comment]
Awesome.  Then it's some change to that code that is causing the issue then.

**Comment by germ** [comment]
Has there been any update on this? Will see if I can repro with a Gergo

**Comment by tschulte** [comment]
Maybe the author of that commit, @seebs, should have a look into this. This renders TX Bolt mode useless and we have to use Gemini mode.

**Comment by seebs** [comment]
Huh, interesting.

Oh, hey.

```
+static bool update_state_bolt(uint8_t key, bool press) {
+  uint8_t boltcode = pgm_read_byte(boltmap + key);
+  if (press) {
+    state[TXB_GET_GROUP(boltcode)] |= boltcode;
+    chord[TXB_GET_GROUP(boltcode)] |= boltcode;
+  } else {
+    state[TXB_GET_GROUP(boltcode)] &= ~boltcode;
+  }
```
This seems suspicious, but I can't immediately see the failure.

What's interesting to me is the difference between the two S keys. Both of those have the same entry in boltmap, in principle? So we should get boltcode = TXB_S_L, which is 0b1. TXB_GET_GROUP() should be yielding 0, so we should |= 0b1 into both chord[0] and state[0], and on release, we should & those bits out. The tw/pk cases look almost like swapping bits -- it's 0b001000 and 0b000100 being
flipped, and similarly 0b010000 and 0b000010, and s/h  would be 0b100000 and 0b000001. All specifically in the case where the top bits are 0s. Hmm.

When nothing's still pressed, we should send the chord, which means that we should have 0b1 in chord[0], so we'll send that. And... I don't see how this produces an h. h is 0b100000, and nothing should be masking it in. But weirdly, we get it apparently?

I can try to debug this, I have a keyboard that supports this functionality and I have plover. I don't see any obvious way this makes sense, though.

**Comment by seebs** [comment]
oh for !@#*!s sake

```
      switch(mode) {
        case STENO_MODE_BOLT:
          update_state_bolt(keycode - QK_STENO, IS_PRESSED(record->event));
        case STENO_MODE_GEMINI:
          update_state_gemini(keycode - QK_STENO, IS_PRESSED(record->event));
      }
```

the reason we're seeing weird glitches that relate to the bits in the raw keypress is that there's no `break;` here and thus it's falling through into the gemini case, and setting one arbitrary extra bit in one of six bytes. my bad.
to fix: add "break;" after `update_state_bolt(...)`.

**Comment by yanfali** [comment]
Fall through ftw

**Comment by tschulte** [comment]
I will prepare a pull request now.

**Comment by seebs** [comment]
thanks much, very sorry about that. that was deeply mystifying. i spent way too much time staring at the fancy bitwise logic without realizing that it was a distraction.

(There's a secondary question about the results in the `state` variable, because those won't have the top two bits of each byte set correctly, but I suspect users checking that state wouldn't care, because they know which byte to check already. I don't know.)
