### ISSUE TITLE
Audio docs point to non-existant file for midi information

### ISSUE THREAD

**Issue by jetpacktuxedo** [qmk/qmk_firmware#4619]
https://docs.qmk.fm/#/feature_audio?id=midi-functionality points to `quantum/keymap_midi.c` which is not a thing that exists.

**Comment by noroadsleft** [comment]
`quantum/keymap_midi.c` was removed in 65faab3b89245f81c50b029ca178aed175d5f330. It seems to have been refactored into `quantum/process_keycode/process_midi.c` and `quantum/process_keycode/process_midi.h`, but I'm not nearly skilled enough in C to know if that's actually the case.

**Comment by drashna** [comment]
Yup, it was refactored. 

Now.... do I add full documentation, or just update the line.

**Comment by jetpacktuxedo** [comment]
I mean, if you're up to writing full docs then I'd definitely suggest doing that, but imo updating the line would close this issue while actually documenting the midi stuff would be a separate one.
