### ISSUE TITLE
EEPROM support for Massdrop arm_atsam (CTRL & ALT)

### ISSUE THREAD

**Issue by helluvamatt** [qmk/qmk_firmware#4625]
Per [the datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/60001507C.pdf) for ATSAMD51J18A the MCU has a [SmartEEPROM function](http://ww1.microchip.com/downloads/en/DeviceDoc/60001507C.pdf#_OPENTOPIC_TOC_PROCESSING_d115e202581) that allows up to 64K of EEPROM storage.

I am working on implementing this in `tmk_core/common/arm_atsam/eeprom.c` as that file is already set up to handle eeprom simulation in memory and it should be fairly simple to configure SmartEEPROM.

**Comment by drashna** [comment]
Well, check out the STM stuff too.  I think that has some of the same limitations/issues that ATSAM has, so it would be a good place to look.

**Comment by tprk77** [comment]
I've been watching this ticket, can I offer to help in some way?

**Comment by drashna** [comment]
There is a PR that adds persistent storage.  So it maybe worth checking that out.

**Comment by daltona** [comment]
Well I'm sorry I missed this issue, but my implementation is actually implementing SmartEEPROM support, with a fallback to original functionality if SmartEEPROM is not enabled on the chip.
Enabling SmartEEPROM can be done with a change that I've made to mdloader, referenced in #6068 
So for sure I believe it exactly solves this issue.

**Comment by zvecr** [comment]
Fixed with 6068.
