### ISSUE TITLE
Documentation: macOS Screen Brightness

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_firmware#4750]
As reported in https://www.reddit.com/r/MechanicalKeyboards/comments/ab4yls/qmk_config_for_mac_screen_brightness_up_down/

QMK docs should make reference to the fact that on macOS, 

```
KC_SLCK - Screen Brightness up
KC_PAUS - Screen Brightness down
```

**Comment by sai2791** [comment]
This need to be checked on my laptop, these are the wrong way around.

KC_SLCK seems to be Screen Brightness Down
KC_PAUS seems to be Screen Brightness Up

**Comment by fauxpark** [comment]
IMHO `KC_BRIU` and `KC_BRID` should be used over Scroll Lock/Pause as they work on (at least) macOS and Windows and are more obviously named, but I guess it wouldn't hurt to make note of these.

**Comment by treetrum** [comment]
FWIW — KC_PAUS and KC_SLCK worked for me to control the brightness of the Apple Studio Display.
