### ISSUE TITLE
Switching between left and "right" shift doesn't keep the shift modifier enabled

### ISSUE THREAD

**Issue by rayburgemeestre** [qmk/qmk_firmware#4785]
Didn't file this as a bug because it could be I'm not reading the docs correctly.

I have this as my left shift: `KC_LSFT` and `SFT_T(KC_ENT)` as my "right" shift.
It's really super convenient.

The problem is that I tend to switch back and forth between left- and right shift when trying to type something IN ALL CAPS. 

An example would be typing WATERLOO.
I tend to use the right-shift (`SFT_T(KC_ENT)`) for WATER, then I switch to left-shift (`KC_LSFT`) for the LOO type (on a qwerty layout). It's more convenient for my fingers and I do it automatically. However when I do that, I will get WATERloo, because `KC_LSFT` doesn't seem to take over the role of enabling caps that I initiated with the `SFT_T(KC_ENT)`. Also vice versa it's the same (left shift -> right shift). 

Hope it makes sense, would really appreciate a solution / workaround for this it would make the entire thing perfect for me :)

My keymap is a bit messy, but I'll include it since it might be helpful: https://github.com/rayburgemeestre/qmk_firmware/blob/master/keyboards/jj40/keymaps/default/keymap.c#L36

**Comment by shmcgrath** [comment]
Try swapping to the RSFT_T(EC_ENT) instead of SFT_T(KC_ENT). I don't know if it will have an impact, but right now, you are calling left-shift twice

**Comment by rayburgemeestre** [comment]
Wow, thanks a lot! Really! Just tried your suggestion and _finally_ your suggestion fixed my issue. Now I can unlearn some of the muscle memory I developed working around it :)

Glad that there is no problem with QMK but indeed with my configuration (as I expected)
Thanks again!
