### ISSUE TITLE
Macros send random characters

### ISSUE THREAD

**Issue by luandy64** [qmk/qmk_firmware#4801]
I'd like someone to replicate my issue and prove my solution works. Then we can change the docs accordingly.

### Problem: 
Following the docs to define a macro, I write the following code:
```
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case MY_MACRO:
            if (record->event.pressed){
                SEND_STRING("Hello World");
            }
        break;
    }
    return true;
}
```

When I go to use `MY_MACRO`, I get "Hello World" and some other character at the end (Multiple tests have given me multiple things, like a `+` or `:` or `|`).

### Solution:
```
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case MY_MACRO:
            if (record->event.pressed){
                SEND_STRING("Hello World");
            }
        return false;
        break;
    }
    return true;
}
```

Now the macro works as intended.

I question whether we need both the `return false;` and the `break`. I didn't look into and I am not confident in my C skills to make a confident statement about this. But I have `return false; break;` in my keymap right now and it's working.

**Comment by vomindoraan** [comment]
Could you link to where exactly in the docs you found this? The `return false;` is indeed required. The `break;` isn't as the `return` statement already serves to break the switch.

**Comment by luandy64** [comment]
[Here's the link](https://docs.qmk.fm/#/feature_macros?id=the-new-way-send_string-amp-process_record_user)

**Comment by vomindoraan** [comment]
While the tutorial is technically correct and `return false` isn't required since the macro keycode is `>= SAFE_RANGE`, it'd still be nice to have it there. In your case, how did you define the `MY_MACRO` keycode?

**Comment by luandy64** [comment]
Just in an `enum` with a bunch of other things.
```
enum custom_keycodes {
    QWERTY = SAFE_RANGE,
    ...
    MY_MACRO
};
```

Is this the proper way of doing it?

**Comment by vomindoraan** [comment]
It is, but then it shouldn't have caused any issues. Could you share the whole enum?

**Comment by luandy64** [comment]
```
enum preonic_keycodes {
  QWERTY = SAFE_RANGE,
  LOWER,
  RAISE,
  TMUX_LD = LCTL(KC_RBRC),
  TMUX_SC, // TMUX Scroll
  TMUX_LO, // TMUX LogOut
};
```
where `MY_MACRO` is `TMUX_LO`

**Comment by luandy64** [comment]
Thanks for all of your help @vomindoraan!
