### ISSUE TITLE
Diverge3 broken by #4419

### ISSUE THREAD

**Issue by mcmadhatter** [qmk/qmk_firmware#4816]
The soft serial stuff introduced in pull requst #4419 has stopped the diverge 3 from working fully,Diverge 3 config.h will need a slight rework to remove the soft serial and make it I2C based again.

**Comment by mtei** [comment]
You can try adding the following options:

```
diff --git a/keyboards/diverge3/config.h b/keyboards/diverge3/config.h
index 464dc835f..29e2edfba 100644
--- a/keyboards/diverge3/config.h
+++ b/keyboards/diverge3/config.h
@@ -59,6 +59,7 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 /* serial.c configuration for split keyboard */
 #define SOFT_SERIAL_PIN D0
+#define SELECT_SOFT_SERIAL_SPEED 3 /* 1:default, 2, 3, 4, 5 */
 
 /* define if matrix has ghost (lacks anti-ghosting diodes) */
 //#define MATRIX_HAS_GHOST
```

**Comment by mcmadhatter** [comment]
It should not be using serial , I think just changing over to use #define  USE_I2C instead should be enough but I haven’t had time to try it out as a fix yet.

**Comment by mcmadhatter** [comment]
setting the speed to 2 seems to work ok.

**Comment by drashna** [comment]
@mcmadhatter Are you using the 8MHz version of the Pro Micro?  If so, that may be the issue. 

And just curious, did 2 or 1 work, at all?  Or only 3 (and up)?

**Comment by mcmadhatter** [comment]
16mhz version,  2 worked fine for me so I stuck with that.
