### ISSUE TITLE
Feature request/implementation: LED pattern responsive to key input

### ISSUE THREAD

**Issue by valen214** [qmk/qmk_firmware#4846]
## Feature Request Type

- [x] New behavior
- [x] Core Functionality
- [ ] Add-on hardware support (e.g. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing Feature(s)

## Description 
[related (pull request)](https://github.com/qmk/qmk_firmware/pull/4340)
[source project](https://github.com/valen214/Massdrop-Ctrl-Keyboard-Ripple-LED/blob/master/keyboards/massdrop/ctrl/keymaps/custom/keymap.c)

This issue focuses on **Implementing LED effect by modifying `keymap.c` only**.
Effect showcase is available in [video](https://www.youtube.com/watch?v=W3U1SDztx1I) linked in source project (more patterns are added since then)

### Ideas
1) This feature is quite complete in the source project, which is however forked from [Massdrop's base](https://github.com/Massdrop/qmk_firmware), thus not compatible with this mother qmk project (they have additional feature like `led_instructions`). I am working on porting it to qmk (several methods are possible, more below), which is the main point of this issue.
2) I failed to get `<rgblight.h>` working, it is why I try to use `led_map->rgb` (in qmk) or `led_instruction_t led_instructions[]` (in Massdrop) instead.
3) "Why so stubborn to only use `keymap.c`?": I thought it would be less intrusive to other part of the project. It is welcome to be offered any better solutions.

### What I am working on currently
**Porting from source project to be compatible to this base project** (as mentioned)
several ways are proposed (tested):
1) setting `led_per_run = 1` and modify led rgb values in `keymap.c: matrix_scan_user()` (in each and every invocation)
    - potential problem: performance, (might, although unlikely, not working on other occasion)
    - The reason setting `led_per_run = 1` is because modifying rgb in `matrix_scan_user()` causes racing with `arm_atsam/led_matrix.c: led_matrix_run()`, which makes some led's rgb is modified again in `led_matrix_run()` after `matrix_scan_user()` if `led_per_run` is `15 (default value)`.
2) set `led_lighting_mode  = LED_MODE_KEYS_ONLY` and modify `led_cur->scan`
    - in `tmk_core/protocol/arm_atsam/led_matrix.c: led_matrix_run(): line 311` doing so would skip certain led, so the overriding and racing problem as mentioned above can be avoided.
    - problem: `Fn + Z` toggle led mode would not behave normally.
3) modify `led_matrix_run()` by modifying `tmk_core/protocol/arm_atsam/led_matrix.c`, or overriding such function in `keymap.c` (which is possible because `led_matrix_run()` has `__attribute__((weak))` reference)
    - open up many possibilities, able to cover the problems of above methods.
    - problem: need to submit pull request / merge branch

**Comment by drashna** [comment]
I believe that #4856 should have closed this issue.   

I'm closing it now. Reopen if i'm incorrect.
