### ISSUE TITLE
Add support for .clang-format file

### ISSUE THREAD

**Issue by drashna** [qmk/qmk_firmware#4867]
In theory, we can add a `.clang-format` file to the repo, so that code can be automatically formatted __correctly__ based on the QMK Contributor guidelines.

## Feature Request Type

- [ ] Core Functionality
- [ ] Add-on hardware support (e.g. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing Feature(s)
- [X] New behavior

**Comment by pelrun** [comment]
Funnily enough I already have one... :grinning:

**Comment by Lenbok** [comment]
This was fixed by #4880
