### ISSUE TITLE
Ergodox EZ with WS2812B incorrect colors

### ISSUE THREAD

**Issue by LukeeeeBennett** [qmk/qmk_firmware#4951]
I built an ergodox and added a WS2812B strip.

I am having some issues with the LEDs being the wrong color.

I have modified the ergodox_ez default_osx keymap.

`config.h`

```
#undef RGB_DI_PIN
#undef RGBLED_NUM
#define RGB_DI_PIN D5
#define RGBLED_NUM 8
#define RGBLIGHT_ANIMATIONS
```

`Makefile`

```
RGBLIGHT_ENABLE = yes
```

`rgblight_setrgb_orange` results in: https://i.imgur.com/Q5jMVbU.jpg
`rgblight_setrgb_white` results in: https://i.imgur.com/xB7nrYt.jpg

When I put it into an animation using an RGB keycode, every animation looks the same and is just the one colour per pixel fading in and out, rather than the hue changing as well.

I've also loaded the teensy without qmk, using an arduino neopixel example to confirm the strip works.

Any help is hugely appreciated and thank you for your time! ❤️

**Comment by drashna** [comment]
Well, it should be `rules.mk`, not `makefile`, unless you're using a very old version. 

Additionally, it sounds like the mode may not be set correctly.  But if you're using "setrgb", that shouldn't matter. 

It may be an issue with how the ergodox ez firmware sets up the rgb lights, and you may need to undefine `RGBW_BB_TWI` and `RGBW`

**Comment by drashna** [comment]
Was this still an issue?

**Comment by LukeeeeBennett** [comment]
Thanks for the info @drashna, I'll try to poke around some more tonight.

I was thinking of looking to your [rgb_layer keymap](https://github.com/qmk/qmk_firmware/tree/master/keyboards/ergodox_ez/keymaps/rgb_layer) for more info aswell.

**Comment by LukeeeeBennett** [comment]
I copied your rgb_layer keymap and set `RGB_DI_PIN` to `D5`. The colours still incorrect/weird.

**Comment by drashna** [comment]
Did you try undefining the other values? 
Also, have you tried wiping the eeprom? (`EEP_RST` keycode)
And did you set the mode?

**Comment by drashna** [comment]
Figured out the issue, actually.

The EZ is designed with RGBW lights in mind, and has a define to enable that behavior.  This sends different data than "just" RGB LEDs. 

You need to add `#undef RGBW` in your config.h file to get proper colors sent.
