### ISSUE TITLE
Layer Mod (LM) doesn't work properly with Layer Tap (LT)

### ISSUE THREAD

**Issue by maxshaffer** [qmk/qmk_firmware#5023]
I want to use the key sequence d-f as Left Shift. I've implemented this functionality in the following way.

1. I use the 'd' key on my base layer to access layer 2 with the Layer Tap function, LT(2, KC_D) 
2. I use the 'f' key on layer 2 to return to the base layer and apply Left Shift with Layer Mod, LM(0, MOD_LSFT)

The following sequence should result in the '+' symbol, but instead the '=' symbol is sent. Layer switching appears to work correctly, but the Left Shift modifier is not applied.
1. Press and hold the 'd' key
2. Press and hold the 'f' key
3. Tap the '=' key

**System Information**
 - Keyboard:  Filco Majestouch 2, Bpiphany/Pegasushoof controller
 - Operating System: MacOSX Mojave 10.14.1
 - avr-gcc version: 7.3.0
 - arm gcc version: 7.3.1 20180622
 - QMK Firmware version: 0.6.240
 - Any keyboard related software installed? No

**Additional context**

**Comment by noroadsleft** [comment]
Can you post your `keymap.c` file? I think I have an idea what's going on, but I'd need to see the keymap to be sure.

**Comment by maxshaffer** [comment]
Thanks @noroadsleft! Here's my keymap.c (renamed to .txt because Github complains about .c files).
[keymap.txt](https://github.com/qmk/qmk_firmware/files/2818694/keymap.txt)

**Comment by noroadsleft** [comment]
After maybe an hour trying to trace this, I just realized/remembered a few things:

1. Your `MOD_RSFT` key is actually on the R key and *not* the F key on Layer 2.
2. `LM(layer, mod)` only works for layers 0-15, and the left modifiers.
So `LM(0, MOD_RSFT)` passes the first requirement but fails on the second.
[Reference](https://docs.qmk.fm/#/feature_advanced_keycodes?id=switching-and-toggling-layers)
3. `LT(layer, kc)` only supports [basic keycodes](https://docs.qmk.fm/#/keycodes_basic). Any specified modifiers are ignored. I don't recall the technical reason for this.
[Reference](https://docs.qmk.fm/#/feature_advanced_keycodes?id=caveats)

Doing a `LM(0, MOD_LSFT)` + `KC_EQL` *might* work, but I'm not 100% sure.

**Comment by maxshaffer** [comment]
Bah! You're totally right. Sorry to waste your time. Also thanks! :)

**Comment by noroadsleft** [comment]
> Bah! You're totally right. Sorry to waste your time. Also thanks! :)

I actually kind of wasted my own time by not thinking to check the docs first. :rofl: 

Was fun to chase down though. Hope you get it sorted!
