### ISSUE TITLE
Support for B.87 TKL

### ISSUE THREAD

**Issue by mikebell** [qmk/qmk_firmware#5056]
Hi,

I saw that the B.Face was supported so I was wondering whether it's possible to support the B.87 as well. I'd love to be able to run QMK on my B.87 so I can flash it from Linux rather than windows.

## Feature Request Type

- [ ] Core Functionality
- [ ] RGB Backlight
- [ ] Key Blacklight

**Comment by drashna** [comment]
@mechmerlin ?

**Comment by mechmerlin** [comment]
Sure! Is there a pcb available @mikebell

**Comment by mikebell** [comment]
I have one here, but I don't have a spare one. They're also no longer commercially available.

**Comment by equalunique** [comment]
@mechmerlin you can try with mine. Is it ok to sort the logistics over reddit? I'm u/equalunique
