### ISSUE TITLE
Add configuration for NYM96

### ISSUE THREAD

**Issue by cancakmur** [qmk/qmk_firmware#5103]

**Comment by mechmerlin** [comment]
@cancakmur can you elaborate on what you mean here? What type of configuration?

**Comment by cancakmur** [comment]
I meant a layout for NYM96 on the QMK Configurator but i guess Melody96 works for it. Sorry for the confusion.

**Comment by mechmerlin** [comment]
Ahh ok I see what you mean now. The Melody96 is the same board as the NYM96.
