### ISSUE TITLE
KBD75 Rev2 board - Caps lock LED code not working?

### ISSUE THREAD

**Issue by necropsyuk** [qmk/qmk_firmware#5118]
I have used both Rev1 and Rev2 builds on my KBD75 rev2 (USB-C) board. The caps lock LED is not functional. 

This is the code that appears in both the rev1.c and rev2.c files

```
void led_set_kb(uint8_t usb_led) {
	// put your keyboard LED indicator (ex: Caps Lock LED) toggling code here
  if (IS_LED_ON(usb_led, USB_LED_CAPS_LOCK)) {
    writePinHigh(B2);
  } else {
    writePinLow(B2);
  }

	led_set_user(usb_led);
}
```

I know the LED itself is functional as whatever build was on the PCB out the box from kbdfans was working well.

Is it possible that the pin is different? If so then how do I figure out which pin code relates to which key?

**Comment by fauxpark** [comment]
According to [this drawing](https://cdn.shopify.com/s/files/1/1473/3902/files/Q75.pdf?9073386096780420683) B2 is correct (it's the second pin to the right of the "U1" text).

The circuit:
![led](https://user-images.githubusercontent.com/4781841/52757796-104a3780-305a-11e9-8692-6e5db07ea8f8.png)

It seems like the pin should actually be pulled *low* to turn the LED on. But you should be seeing the LED light up when Caps Lock is off instead of "not functional".

**Comment by necropsyuk** [comment]
> According to [this drawing](https://cdn.shopify.com/s/files/1/1473/3902/files/Q75.pdf?9073386096780420683) B2 is correct (it's the second pin to the right of the "U1" text).
> 
> The circuit:
> ![led](https://user-images.githubusercontent.com/4781841/52757796-104a3780-305a-11e9-8692-6e5db07ea8f8.png)
> 
> It seems like the pin should actually be pulled _low_ to turn the LED on. But you should be seeing the LED light up when Caps Lock is off instead of "not functional".

Unfortunately it's off at all times. I did try swapping the commands in the if statement to pull to low, else high. Still nothing. 

Interestingly, when I comment out this code, the LED still does not light, even though other LEDs do. I'm at a loss.

**Comment by drashna** [comment]
How is the pin being set? 

Try adding the following to the rev2.c file: 
```c
void matrix_init_kb(void) {
  setPinOutput(B2);
  matrix_init_user();
}
```

**Comment by necropsyuk** [comment]
> How is the pin being set?
> 
> Try adding the following to the rev2.c file:
> 
> ```c
> void matrix_init_kb(void) {
>   setPinOutput(B2);
>   matrix_init_user();
> }
> ```

Yes! It worked. Legend. Thanks @drashna 

Final working code in rev2.c for anyone else as follows:

```
#include "rev2.h"

void matrix_init_kb(void) {
  setPinOutput(B2);
  matrix_init_user();
}

void led_set_kb(uint8_t usb_led) {
	// put your keyboard LED indicator (ex: Caps Lock LED) toggling code here
  if (IS_LED_ON(usb_led, USB_LED_CAPS_LOCK)) {
    writePinLow(B2);
  } else {
    writePinHigh(B2);
  }

	led_set_user(usb_led);
}
```

**Comment by drashna** [comment]
Awesome! 

Well, if you want, open a PR that fixes this (ideally, in its own branch).  For both the rev1 and rev2, since both seem to have this issue. 

If not, I'm sure that myself or somebody else can.

**Comment by necropsyuk** [comment]
> Awesome!
> 
> Well, if you want, open a PR that fixes this (ideally, in its own branch). For both the rev1 and rev2, since both seem to have this issue.
> 
> If not, I'm sure that myself or somebody else can.

Thanks for doing it, this is my first time using Github. Nice to know my issue might help others though.

**Comment by CUTTY22** [comment]
Hi i have a question. i am new and i am having the same problem with my caps lock led not working on my kbd67 rev2 once i flashed it using qmk. how do i access or where to i go to find the rev2.c file so i can copy and paste that code up above to get the caps lock led to work. thank you very much.

**Comment by necropsyuk** [comment]
> Hi i have a question. i am new and i am having the same problem with my caps lock led not working on my kbd67 rev2 once i flashed it using qmk. how do i access or where to i go to find the rev2.c file so i can copy and paste that code up above to get the caps lock led to work. thank you very much.

https://github.com/qmk/qmk_firmware/tree/master/keyboards/kbdfans/kbd67/rev2

Here you go. Not sure if it's been updated, but you can amend it as per my above changes.

**Comment by CUTTY22** [comment]
thank you. sorry about another question. i found the code line but do i have to install like a build tool or something to amend it. and do i flash it to the keyboard. sorry again this is my first time dealing with this. 
    On Monday, January 13, 2020, 03:40:15 PM EST, necropsyuk <notifications@github.com> wrote:  
 
 

Hi i have a question. i am new and i am having the same problem with my caps lock led not working on my kbd67 rev2 once i flashed it using qmk. how do i access or where to i go to find the rev2.c file so i can copy and paste that code up above to get the caps lock led to work. thank you very much.


https://github.com/qmk/qmk_firmware/tree/master/keyboards/kbdfans/kbd67/rev2

Here you go. Not sure if it's been updated, but you can amend it as per my above changes.

**Comment by necropsyuk** [comment]
Yes you need to build it. Check out the documentation.

https://docs.qmk.fm/#/

**Comment by CUTTY22** [comment]
ok thank you once again ill give it a look. have a great day
    On Monday, January 13, 2020, 08:11:20 PM EST, necropsyuk <notifications@github.com> wrote:  
 
 
Yes you need to build it. Check out the documentation.

https://docs.qmk.fm/#/
