### ISSUE TITLE
Switch keyboard between multiple simultaneously connected devices/computers

### ISSUE THREAD

**Issue by equalunique** [qmk/qmk_firmware#5185]
## The Need

Some people work with multiple computers every day, and some of those computers are "locked-down" so that Synergy or some other software-based keyboard/mouse switching software cannot run, and bringing a $250+ keyboard/mouse switch (KM) to the office is out of the question. The ability to connect multiple devices to the same keyboard would eliminate the need for an expensive and cumbersome separate hardware/software keyboard switcher. While this exists to an extent in QMK with bluetooth support, it's limited to switching between one bluetooth device and one USB connection (via the `OUT_AUTO`, `OUT_USB`, `OUT_BT `keycodes).

## Feature As Solution?

For boards sporting two halves with USB-capable microcontrollers on either side, it would be fantastic if one half could connect to one computer and the other half connect to another computer, then connect both halves and have the keyboard as a whole be able to switch seamlessly between either computer.

I understand that the circuitry of contemporary split boards is not designed to support this, but if such a board were to be engineered, I hope it would run QMK. Are others interested in this? Do we have any thoughts on the feasibility of adding this to QMK? What types of changes would be necessary, and in what order? I'm interested in general discussion of this feature - hopefully this is an appropriate venue.

## Other Thoughts

I don't know much about circuitry of QMK-capable boards, but I haven't seen any easy to find parts for adding extra USB ports to a Teensy, ProMicro, Elite-C, Proton-C, or any other easy-to-source QMK-capable microcontroller board. If it were possible to just add a bunch of USB ports to any QMK-capable board, i.e. not requiring a "split" style board, then that would be great too. From the circuitry stand-point, I don't know where to start.

With QMK bluetooth support, there's been a tiny amount of discussion of switching between a number of bluetooth devices/computers, but it's not implemented AFAIK. This would fulfill this need for some users, but not ones who work in places that disallow bluetooth.

**Comment by equalunique** [comment]
* I have A LOT to learn about QMK.

Current docs for Let's Split show how to configure the board to use either half as master: https://github.com/qmk/qmk_firmware/tree/master/keyboards/lets_split#setting-ee_hands-to-use-either-hands-as-master

Current docs for ErgoDox Infinity also show how to set either half as master: https://github.com/qmk/qmk_firmware/tree/master/keyboards/lets_split#setting-ee_hands-to-use-either-hands-as-master

Provided the circuitry were capable of connecting both halves simultaneously, QMK would then have to be able to control which half is "master" on-the-fly.

**Comment by equalunique** [comment]
This project seems like an inspirational resource. It connects the USB hosts together via I2C, just like how the Let's Split (& quite a few of it's derivatives) communicate between halves: https://hackaday.io/project/2872-driverless-mouse-and-keyboard-sharing

**Comment by m42martin** [comment]
Bump
