### ISSUE TITLE
Gitbook page is missing.

### ISSUE THREAD

**Issue by s-luna** [qmk/qmk_firmware#5240]
'Gitbook' in ['readme.md'](https://github.com/qmk/qmk_firmware/blame/15a73f4f64a3b2b109e63cf1eeb37c9875c3d870/readme.md#L16) is 404 not found for me.
https://www.gitbook.com/book/qmk/firmware/details
The referenced document looks disappeared.
Is the document alive?

**Comment by noroadsleft** [comment]
Should link to either https://beta.docs.qmk.fm/ or https://docs.qmk.fm/.
