### ISSUE TITLE
Case printing question

### ISSUE THREAD

**Issue by antonpaisov** [qmk/qmk_firmware#5275]
Sorry about polluting the issues, but I don't know how else to ask :)

I wonder how was this case printed? ![](https://camo.githubusercontent.com/25351dcbe4a241eb27c6bd69201bdce18f2ec088/68747470733a2f2f692e696d6775722e636f6d2f377930566279642e6a7067)
I'm building a dactyl-manuform and I really love this look, would love to build a similar looking one!

**Comment by drashna** [comment]
It looks like it's translucent filament with rgb LEDs inside of the case.
