### ISSUE TITLE
Reusing FAUXCLICKY_ENABLE

### ISSUE THREAD

**Issue by roguepullrequest** [qmk/qmk_firmware#5293]
Want to have ´COIN_SONG´ from ´songlist.h´  play on each a-zA-Z. Wondering if FAUXCLICKY_ENABLE could be reworked to include COINCLICK_ENABLE?

Does FAUXCLICKY_ENABLE interfere with AUDIO?

**Comment by drashna** [comment]
Yes, Fauxclicky is mutually exclusive with Audio.

However, there is a subfeature for Audio that does the same thing. 
https://docs.qmk.fm/#/feature_audio?id=audio-click

Alternatively, if you want to implement the coin sound, you can just add this to your keymap: 
```c
float clicky_sound[][2] = SONG(COIN_SOUND);
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
#ifdef AUDIO_ENABLE
  if (record->event.pressed) { PLAY_SONG( clicky_sound ); }
#endif 

  return true;
}
```

This will play the coin sound every time you press a key.
