### ISSUE TITLE
Cleanup: Remove extraneous includes from non-user keymaps

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#5349]
A lot of default keymaps have extraneous includes, some examples include:

```c
#include "config_common.h"
```

```c
#include "../../config.h`
```

To promote clean code we should remove these lines from all default keymaps and any keymap that is not owned by a user.

While changing these files we can also replace these old-style include guards with `#pragma once`:

```c
#ifndef CONFIG_USER_H
#define CONFIG_USER_H
[...] /* rest of config.h here */
#endif
```

**Comment by drashna** [comment]
I decided to go through, and do this.  As well as clean up the includes in the default keymap.c, as well as the `_______` and `XXXXXX` defines.
