### ISSUE TITLE
Cant compile hex for my dz60

### ISSUE THREAD

**Issue by Aggeloz** [qmk/qmk_firmware#5352]
Every time i try to compile msys2 gives me an error that says : 

Linking: .build/dz60_Aggelos.elf                                                                    [ERRORS]
 |
 | .build/obj_dz60_Aggelos/quantum/keymap_common.o: In function `keymap_key_to_keycode':
 | C:\Users\Aggelos\Desktop\qmk_firmware/quantum/keymap_common.c:212: undefined reference to `keymaps'
 | C:\Users\Aggelos\Desktop\qmk_firmware/quantum/keymap_common.c:212: undefined reference to `keymaps'
 | collect2.exe: error: ld returned 1 exit status
make[1]: *** [tmk_core/rules.mk:292: .build/dz60_Aggelos.elf] Error 1
Make finished with errors
make: *** [Makefile:551: dz60:Aggelos] Error 1

**Comment by mechmerlin** [comment]
could you give us more info as to what command you are using to compile?

**Comment by Aggeloz** [comment]
Omg im sorry. I fixed it by remaking my own layout and forgot to close my issue.
