### ISSUE TITLE
PS2_MOUSE_ENABLE ridiculously slows down matrix scan rate

### ISSUE THREAD

**Issue by tomykaira** [qmk/qmk_firmware#5357]
## Describe the Bug

PS2_MOUSE_ENABLE with PS2_USE_INT ridiculously slows down other procedures such as matrix scan.
With rough testing, it seems like matrix scan counts per second decreased to about 1/10.

This is because `ps2_host_send()` in `ps2_interrupt.c` uses lots of `delay()`.
Inserting `return` to the first line of `ps2_host_send()` solves the problem, but then PS2 mouse does not work, of course.

## System Information

 - Keyboard:  my own hand made keyboard with X19 trackball
 - Operating system: macOS
 - AVR GCC version: 8.2.0
 - QMK Firmware version: Fork from `tag: 0.6.302`
 - Any keyboard related software installed? : no

## Additional Context

As far as my knowledge goes, the only way to solve the problem is to rewrite `ps2_host_send()` using timer interrupt instead of `delay()`s.
I will try it, but it seems hard.

**Comment by alex-ong** [comment]
Timer interrupt may not be necessary - we could potentially use a time-delta method and call ps2_host_send() every scan?
