### ISSUE TITLE
Remove build option firmware size impacts from rules.mk

### ISSUE THREAD

**Issue by fauxpark** [qmk/qmk_firmware#5488]
For example:

```make
...
BOOTMAGIC_ENABLE = no    # Virtual DIP switch configuration(+1000)
MOUSEKEY_ENABLE = yes    # Mouse keys(+4700)
EXTRAKEY_ENABLE = yes    # Audio control and System control(+450)
...
```

These numbers are misleading, because they are outdated and as @drashna mentioned here: https://github.com/qmk/qmk_firmware/pull/5485#issuecomment-476420194, dependent on the compiler version. It seems there is not much point having them around since they will simply never be accurate.

But... these are in *every* rules.mk, so I won't bother making a PR for this, even though I strongly feel these kinds of changes should be done sooner rather than later as QMK grows in popularity, complexity and size.

**Comment by drashna** [comment]
@jackhumbert @skullydazed 

Personally, I'm in favor of this.  They're not accurate, and I don't think we should keep them in the repo.

**Comment by noroadsleft** [comment]
Strongly in favor.

**Comment by roguepullrequest** [comment]
Would this z

**Comment by fauxpark** [comment]
> Would this z

Probably not.
