### ISSUE TITLE
Windows, Ergodox, KC_SLEP

### ISSUE THREAD

**Issue by hia3** [qmk/qmk_firmware#560]
Looks like after [this](https://github.com/jackhumbert/qmk_firmware/commit/d48a4cf1eb80600fb3e8eb859e5b77c954a18137) commit KC_SLEP stopped working on Windows.

**Comment by ezuk** [comment]
Hi @hia3! Would you mind providing some more detail? Which version of Windows, maybe your keymap or repo? Or if you have positive proof that this is the issue, a PR with a possible fix?

**Comment by hia3** [comment]
Sure. I'm building with Ubuntu (VirtualBox):

mkdir repro && cd repro/
git clone https://github.com/jackhumbert/qmk_firmware.git
cd qmk_firmware/keyboards/ergodox_ez/
make keymap=ordinary

And test on Windows 10: press and hold "[Media Tab](https://github.com/jackhumbert/qmk_firmware/blob/master/keyboards/ergodox_ez/keymaps/ordinary/keymap.c#L46)" button (3rd led will turn on). Then press [Sleep](https://github.com/jackhumbert/qmk_firmware/blob/master/keyboards/ergodox_ez/keymaps/ordinary/keymap.c#L132) button - nothing will happen.

Changing all 0x0081 back to 0x0001 in tmk_core/protocol/lufa/descriptor.c helps.

Btw, regardless of this commit I've never been able to wake up the PC with ErgoDox EZ (even though waking up with another keyboard works just fine).

**Comment by ezuk** [comment]
@jackhumbert what do you think? Seems like a good isolation of a bug imho. Also, can people wake up Windows machines with the Planck? Trying to understand if this is keyboard specific.

**Comment by jackhumbert** [comment]
It looks like #963 addressed this - @hia3, if this isn't the case, please reopen this!
