### ISSUE TITLE
dz60rgb LED stays on while in sleep/suspend

### ISSUE THREAD

**Issue by Sada-Mio** [qmk/qmk_firmware#5705]
## Describe the Bug

RGB LED lights stays ON when computer goes into sleep/suspend mode. Tried on multiple desktop PC & Macbook

## System Information

 - Keyboard:  
   - Revision (if applicable):  v1
 - Operating system: Windows 10 & MacOS 10.14.3
 - AVR GCC version:  https://config.qmk.fm/#/dztech/dz60rgb/LAYOUT

 - ARM GCC version: https://config.qmk.fm/#/dztech/dz60rgb/LAYOUT

 - QMK Firmware version: https://config.qmk.fm/#/dztech/dz60rgb/LAYOUT

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context

While in sleep mode the LED RGB animation effect is slower & less fluid.

**Comment by drashna** [comment]
It's not probably sleeping, right now. 

However, it will take some code change to the dz60rgb to implement properly.

**Comment by moyi4681** [comment]
@drashna thanks, already fixed.

**Comment by drashna** [comment]
Awesome.

I'm closing this, as it appears to be resolved.  If not, please re-open.
