### ISSUE TITLE
Multiple random keypresses after KC_LEAD freezes keyboard.

### ISSUE THREAD

**Issue by jpetermans** [qmk/qmk_firmware#5762]
I'm not sure I'd characterize this as a bug or just misuse of the LEADER feature. If I hit KC_LEAD then mash several keys quickly my keyboard completely freezes. I realize this isn't the intent of the LEADER feature, but it's not an implausible scenario.

I have a layer that locks my keyboard so anyone (like say a 2 year old) can mash on the keyboard without registering keypresses. It's unlocked with KC_LEAD ...  I've found an easy way to avoid the freeze issue, but didn't know if this is an expected behavior that just should be avoided.

## System Information
Massdrop ALT on Windows
QMK release 0.6.341

**Comment by jpetermans** [comment]
Maybe an overflow of `leader_sequence[leader_sequence_size]` in `process_leader.c` if too many keypresses register before LEADER_TIMEOUT? I have very little c++ to know a protection for this but that seems like a plausible reason for the crash.

**Comment by shinmai** [comment]
Have this same issue. From testing, it seems around 11-12 keypresses will freeze the board. Tested a dozen or so times by just hitting KC_LEAD followed by hitting one key on the board an increasing number of times.
Tested on a rev 6.1 Planck and a rev 3 Preonic.

**Comment by shinmai** [comment]
Well, I seem to be posting horrible hacky workarounds to QMK issues all over the place tonight.
Adding
```
if(leader_sequence_size > 5) {
  leader_time = timer_read() - LEADER_TIMEOUT;
  return false;
}
```
after [`leader_sequence_size++;`](https://github.com/qmk/qmk_firmware/blob/bb1b44132514fc30de7de77f2c6a80b8c7ba0416/quantum/process_keycode/process_leader.c#L62) in `qmk_firmware/quantum/process_keycode/process_leader.c` will fail the leader after 6 keypresses (by running out the timer, because that was the fastest way I could think up to do it without venturing into how exactly the leader stuff is implemented :D), and keeps the board from locking up.

**Comment by drashna** [comment]
Yup, that would be the best way, since that's what the actual documentation uses. 

Also, there's the problem:

```c
uint16_t leader_sequence[5] = {0, 0, 0, 0, 0};
```

That's already at 5, so it causes an overflow, I think.

**Comment by drashna** [comment]
Actually, if you could, try changing this line:
https://github.com/qmk/qmk_firmware/blob/master/quantum/process_keycode/process_leader.c#L61

```c
        if (leader_sequence_size < 5) {
          leader_sequence[leader_sequence_size] = keycode;
        } else {
          leading = false;
          leader_end();
        }
```

**Comment by jpetermans** [comment]
Makes sense to me.

**Comment by drashna** [comment]
well, it's adding a keycode to index 6, on an array that only has 5 entries.  So ... yeah.  

I don't use leader keys, but if you could test this fix, (and just it), and let me know.
