### ISSUE TITLE
Split Backspace support for Noxary 268.2

### ISSUE THREAD

**Issue by packman86** [qmk/qmk_firmware#5769]
There is only one layout option for the Noxary 268. Would be nice to have the additional layouts available for that PCB.

**Comment by fauxpark** [comment]
Seems like the `LAYOUT` macro already supports split backspace - it has the same number of keys on the top row as the 268's `LAYOUT_all`. According to the layout image in [this thread](https://typehype.net/threads/noxary-268-2.215/), the number of keys on the bottom row is also correct (max 9), and it apparently is ANSI only. So perhaps there is just the one layout needed.
