### ISSUE TITLE
Space Cadet shift starts with extra Shift up and down, and frequently double-taps

### ISSUE THREAD

**Issue by petergaultney** [qmk/qmk_firmware#5780]
## Describe the Bug

At my last compilation in January, Space Cadet Shift worked perfectly. The event output from my keyboard for a single Space Cadet shift tap looked like this:

<img width="194" alt="Screenshot 2019-05-04 09 49 06" src="https://user-images.githubusercontent.com/549720/57180945-6194e680-6e53-11e9-905d-85937ec2fc21.png">

Now event output for a single keystroke (my tapping term is still 200) looks like this:
<img width="339" alt="Screenshot 2019-05-04 09 54 01 short" src="https://user-images.githubusercontent.com/549720/57180972-a15bce00-6e53-11e9-837d-f49bb8010547.png">

Note the extra Shift down/up before even starting the combination, and note that it then repeats itself twice despite there being only a single tap.

## System Information

 - Keyboard:  Ergodox EZ
   - Revision (if applicable):  
 - Operating system: Mac 10.14
 - AVR GCC version: 4.9.2
 - ARM GCC version: (unknown, using Ergodox configurator and compiler)

 - QMK Firmware version: 0.6.325
 - Any keyboard related software installed? 
   - [*] Karabiner - I have disabled all Space Cadet-related things in Karabiner

**Comment by XScorpion2** [comment]
Hmm, ya, I can add a check if the tap & hold mods are the same to skip the extra up and down in this case. The double tap might be due to debounce, perf has been increased quite a bit and @drashna was saying he needed to increase debounce time because of this.

**Comment by XScorpion2** [comment]
Here ya go: https://github.com/qmk/qmk_firmware/pull/5781

**Comment by skorokithakis** [comment]
@petergaultney Which application did you use to generate those keystroke logs?

**Comment by petergaultney** [comment]
Karabiner Elements on Mac. https://pqrs.org/osx/karabiner/

**Comment by skorokithakis** [comment]
Thank you.
