### ISSUE TITLE
Space Cadet has incorrect naming of configuration

### ISSUE THREAD

**Issue by transitracer** [qmk/qmk_firmware#5793]
`LAPO_KEYS` is associated with `KC_LAPO`, but for `KC_RAPC` the define is named `RAPO_KEYS`

Seems like just a simple typo, but should probably be corrected anyway to decrease confusion.

Since there are existing configurations presumably using `RAPO_KEYS`, including mine, it should probably be kept so the configs don't break, but possibly warn upon compilation so that it can eventually be removed (if this is possible in C to do with a #define, I'm not a C programmer)

**Comment by XScorpion2** [comment]
Fixed in https://github.com/qmk/qmk_firmware/pull/5781
