### ISSUE TITLE
Backlight and underglow LEDs stay on

### ISSUE THREAD

**Issue by thepinkturtle** [qmk/qmk_firmware#5833]
With underglow and backlight, the LEDs on the slave side won't turn completely off. The LEDs on the slave side will dim to a certain point and then stay on and won't get any lower light output.

## Describe the Bug
When the keyboard has underglow and backlight the backlight LEDs on the slave side don't turn off and won't dim completely. The LEDs will dim to a certain point and then stop, while the master side LEDs will keep getting lower.

## System Information

 - Levinson:  
   - Revision 2  
 - Operating system:
 - Ubuntu 14

 - Will update everything below soon
 - AVR GCC version: avr-gcc (GCC) 5.4.0

 - ARM GCC version: arm-none-eabi-gcc (15:6.3.1+svn253039-1build1) 6.3.1 20170620

 - QMK Firmware version: 0.6.376

**Comment by Lenbok** [comment]
What version of the code are you running? #3886 was merged just 3 days ago which may fix what you are seeing, so please check.

**Comment by thepinkturtle** [comment]
Alright, I'll try it tonight. Hopefully, it fixes it. 😊

**Comment by thepinkturtle** [comment]
im using the latest qmk_firmware, i just did a pull today.

**Comment by thepinkturtle** [comment]
For the record this was never solved

**Comment by drashna** [comment]
Try adding: 
```c
void suspend_power_down_user(void) {
    rgblight_disable_noeeprom();
    backlight_disable();
}

void suspend_wakeup_init_user(void) {
    rgblight_enable_noeeprom();
    backlight_enable();
}
```

This will hard code to turn on... but ... may be a good test.

**Comment by TD22057** [comment]
Still a problem.
