### ISSUE TITLE
Niu Mini uses dfu bootloader, the suggested command is wrong

### ISSUE THREAD

**Issue by ivomac** [qmk/qmk_firmware#5835]
[Here](https://github.com/qmk/qmk_firmware/tree/master/keyboards/niu_mini) it is suggested to flash the Niu Mini with
  
`make niu_mini:default:avrdude`

but it should say

`make niu_mini:default:dfu`

**Comment by newtonapple** [comment]
I have the niu_mini as well and I can confirm it should be dfu and not avrdude.  I can send a PR if you want.

**Comment by ivomac** [comment]
Sure, I didn't look into how to do that yet. Thanks

**Comment by drashna** [comment]
@ivomac You should be able to "edit" the readme fine in the repo.  that should allow you to create a branch in your repo for it, and to open a PR to fix it.

**Comment by hadibus** [comment]
@ivomac I ran into the same issue when trying to flash my niu_mini. Hope you don't mind me doing a PR.
