### ISSUE TITLE
pop layer

### ISSUE THREAD

**Issue by pvinis** [qmk/qmk_firmware#585]
so i was thinking i might need this:
- press a key, and `TG(SYSCTL)` happens.
- on `SYSCTL` keymap, i want to have a few keys that do something, like volume up or something.
- all other keys, i want them to pop the `SYSCTL` layer.

is there a way to do that now, except for putting all other keys in that layer to `TG(SYSCTL)`?

i thought i could add a new `KC_POP`, that would pop the layer you are on. would that make sense?

**Comment by ezuk** [comment]
this sounds like one-shot layer keys. Check out [this part of the readme](https://github.com/jackhumbert/qmk_firmware#switching-and-toggling-layers) - `OSL` specifically. Sounds like what you're looking to do?

**Comment by pvinis** [comment]
no.. when im in the `SYSCTL` layer, i want to be able to press vol up and down as many times as i want. and only when im done, i can press the same `toggle` button i used to go in that layer, to go out of it.
but i would like to press any other key to go out of it.

**Comment by pvinis** [comment]
now that i think about it, we could even have a `KC_POP` that pops the layer, and a `KC_POPANDSEND` that pops the layer, and also does whatever the key in the layer below would do.
so in my example, i go to layer `SYSCTL`, put the volume to max, then if i have `KC_POP` on a the `Y` key, for example, i press `Y` and go to `BASE` again. then i can type `YEA!`. in this case, i tap on `Y` twice.
if the `Y` button on the `SYSCTL` layer is `KC_POPANDSEND`, then after i max out the volume, i tap `Y` and i immediately fall back to `BASE`, and also a `Y` appears on the screen, so i can keep writing by just tapping `EA`.

how does that sound?

**Comment by algernon** [comment]
Untried idea: use `OSL`, but make the volume up/down/etc keys macros, which reset the one-shot state, and re-install `SYSCTL` as a one-shot layer. Pressing any other key pops the layer, but pressing the layer keys, the layer is re-instated, and remains in effect.

Other than this, some `process_record_user` things may do what you want... or perhaps you could use that, instead of macros.

Mind you, I haven't tried, no idea if this'd even work.

**Comment by pvinis** [comment]
hm, i will try like that and report back. but it feels a bit more weird.. especially if i have more than a few buttons (which i will).

i might try the way i proposed and see how it works etc.

**Comment by iFreilicht** [comment]
How were you results? Could you implement everything inside the keymap?

**Comment by pvinis** [comment]
havent finished it yet. i need to do it in a weekend. i will update when its done.

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @pvinis please reopen this or open a new issue.
