### ISSUE TITLE
Issue Building or Flashing on Cospad

### ISSUE THREAD

**Issue by OneWithNothing** [qmk/qmk_firmware#5956]
Hi there. I have tried various permutations when it comes to flashing my Cospad. I created the config file online and downloaded a .hex, I went in and edited it myself with Sublime Text and tried it that way to no avail. I tried using the QMK Toolbox and command line. The result of all of these combinations is a seemingly bricked cospad that doesn't recognize any input whatsoever. I was sure to read over the guides many times. What could I be doing wrong? Thanks.

**Comment by drashna** [comment]
Could you fill out this info? 

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:


Also, are you 100% that you actually have a COSPAD, and not something that just happens to be similar?  

if it's not exactly the same, then the pin and matrix configuration will be wrong, and not work properly.
