### ISSUE TITLE
more keys

### ISSUE THREAD

**Issue by letarg0** [qmk/qmk_firmware#6054]
is possible add more keys for example https://klawiatura.wordpress.com/
remember 2 rotor too

**Comment by drashna** [comment]
I'm not exactly sure what you're asking here. 

Though, QMK Firmware is limited by the USB HID specs.  So  if those keys are not supported, then we can't support them.   Also, the OS itself handles the mapping of the keys.  So, if the OS doesn't understand them.... same issue. 

Also, some of this may be done by adding modifiers to the keycodes (altgr for instance), or can be done using Unicode input.   

In fact, some of the caveats I mentioned above are covered there too. 
https://docs.qmk.fm/#/feature_unicode
