### ISSUE TITLE
add support for IS31FL3741

### ISSUE THREAD

**Issue by miraclehoshi** [qmk/qmk_firmware#6101]
## Feature Request Type

- [ ] Core functionality
- [x] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

QMK uses the RGB matrix and supports IS31FL3731, 3733, 3736, and 3737.

But those four ICs support less than 100 keys of RGB.

The IS31FL3741 from the same company supports 117 RGB LEDs.

This means that you can add RGB to a single IC on a 104- to 108-key keyboard

Can you add support for IS31FL3741?

I usually use a full size keyboard.

Using multiple ICs complicates the design.

**Comment by drashna** [comment]
Well, we have a number of the ISSI chips already supported.   It should be a simple matter of taking one of them, and porting the code over for the 3741.

**Comment by miraclehoshi** [comment]
> Well, we have a number of the ISSI chips already supported. It should be a simple matter of taking one of them, and porting the code over for the 3741.

I think so too, but I am very poor in programming knowledge. Also, even if I make it, it's not official support.

**Comment by yiancar** [comment]
IF someone creates a PCB with that chip we can talk about it:)

**Comment by miraclehoshi** [comment]
> IF someone creates a PCB with that chip we can talk about it:)

I tried to design a PCB using IS31FL3741.
But I found out a few hours ago that QMK didn't support it.

So I wrote issue. If QMK officially support for IS31SL3741, I must use this.

**Comment by yiancar** [comment]
You can give it a go and we can work with it together:)

**Comment by Wilba6582** [comment]
I'll build a breakout PCB, confirm datasheet.

**Comment by GitWellBack** [comment]
I'm happy to supply existing code for this - but it will be a few weeks before I'm allowed/in position.

**Comment by yiancar** [comment]
Quite happily this driver doesnt even have a sync pin so even less complexity!

**Comment by e11i0t23** [comment]
@GitWellBack is there any update on this?

**Comment by 4pplet** [comment]
Any progress on the IS31FL3741?

**Comment by melgeek001365** [comment]
> we can



> IF someone creates a PCB with that chip we can talk about it:)

Hello. We have used the ISSI3741 for many board already. it simple and better than 3733 and 3731.
