### ISSUE TITLE
questions of documents by^问题少年^ 

### ISSUE THREAD

**Issue by ymzcdg** [qmk/qmk_firmware#6107]
”The presce of this fienle means that the folder is a keyboard target and can be used in `make` commands. “  in hardware_keyboard_guidelines.md
“presce” and "fienle" may not English words.What are they mean?
Thanks!

**Comment by noroadsleft** [comment]
I think you accidentally created a typo in your file. This sentence is correct on QMK's current master.

https://github.com/qmk/qmk_firmware/blame/master/docs/hardware_keyboard_guidelines.md#L66:

```md
The presence of this file means that the folder is a keyboard target and can be used in `make` commands. This is where you setup the build environment for your keyboard and configure the default set of features.
```
