### ISSUE TITLE
Symbol keys switch in Iso osx

### ISSUE THREAD

**Issue by aykot** [qmk/qmk_firmware#6152]
## Describe the Bug

As soon as I press º key, system recognizes > and they are both switched until I reset the keyboard. At first I thought it was a problem with my first build ( and adafruit blufeather) but I have the same problem now with a pcb ymd96. Tested in Mojave, Yosemite and high Sierra. Same output

## System Information

 - Keyboard:  
   - Revision (if applicable):  ymd96
 - Operating system: osx Mojave
 - AVR GCC version: 9.1.0

 - ARM GCC version: 7.3.1

 - QMK Firmware version:0.6.398

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

## Additional Context
Present at least since qmk gh60-0.1

**Comment by fauxpark** [comment]
If you go to the Keyboard preferences -> Input Sources, does the graphic there show an ISO layout?

**Comment by aykot** [comment]
yes @fauxpark , and when I press the º button, it switches the keyboard map shown in that picture

**Comment by fauxpark** [comment]
Which input source are you using?

**Comment by aykot** [comment]
I´ve tried both Spanish and Spanish - ISO and both have the same problem

**Comment by fauxpark** [comment]
Could you show a picture?

**Comment by fauxpark** [comment]
Please also post the keymap you're using on the YMD96.

**Comment by aykot** [comment]
[video.zip](https://github.com/qmk/qmk_firmware/files/3302558/video.zip)

[me96.json.zip](https://github.com/qmk/qmk_firmware/files/3302560/me96.json.zip)

**Comment by fauxpark** [comment]
Hm, it looks like you've generated that .json file using kbfirmware, which is not recommended as it's not an official tool and very out of date. That might be (part of) the issue. Please have a look at the [QMK Configurator](https://config.qmk.fm) instead.

**Comment by aykot** [comment]
I have the same problem with /ymd96/keymaps/AnthonyWharton keymap, which is generated with qmk, and with my other keymap in a complete different build

**Comment by fauxpark** [comment]
Oh, I think I see now. What you want to do is make sure the layout has changed to the ANSI one (as you showed in the video), then click the `Change keyboard type...` button in the Keyboard preferences and set it up as an ISO layout.

**Comment by aykot** [comment]
I think you are right and the problem goes in that direction, but Mac doesn't recognices qmk keyboard as an unknown keyboard, so there is no "change keyboard type" and defaults it to ANSI, without possibility to change it, even when deleting the corresponding plist. Is there any part in qmk where I can specify that it is ISO instead of ANSI?

**Comment by fauxpark** [comment]
It's entirely on the OS side, QMK can't do anything about it. Try running the following:

```
sudo open /System/Library/CoreServices/KeyboardSetupAssistant.app/Contents/MacOS/KeyboardSetupAssistant
```

**Comment by aykot** [comment]
ok, found the problem and fixed it.
Osx recognizes the keyboard as ANSI by default, but if you delete /Library/Preferences/com.apple.keyboardtype.plist and then restart the system, it prompts with a window where you can select keyboard type.
Now my system recognizes it as follows:

<img width="788" alt="Captura de pantalla 2019-06-18 a las 19 37 24" src="https://user-images.githubusercontent.com/12032199/59706317-80cbb580-9200-11e9-868d-1d93ee50deb5.png"> 

Thank you @fauxpark
