### ISSUE TITLE
I am getting that error unknown type name 'MidiDevice' any help ?

### ISSUE THREAD

**Issue by Romyo167** [qmk/qmk_firmware#6166]
Compiling: ./tmk_core/common/avr/suspend.c                                                         In file included from ./tmk_core/common/avr/suspend.c:14:0:
./tmk_core/protocol/lufa/lufa.h:72:3: error: unknown type name 'MidiDevice'
   MidiDevice midi_device;
   ^
 [ERRORS]
 |
 |
 |
make[1]: *** [tmk_core/rules.mk:355: .build/obj_kb_default/common/avr/suspend.o] Error 1
Make finished with errors
make: *** [Makefile:501: kb] Error 1

**Comment by fauxpark** [comment]
`obj_kb_default`, and the fact that line 14 of suspend.c is currently empty in QMK master, suggests to me that you've used kbfirmware to generate your keyboard files (`kb` is the default keyboard name it uses).

I would advise against this as the version of QMK it uses is horribly out of date now (over 2 years old I believe), and the site itself is not officially supported.

Instead you can use the [QMK Configurator](https://config.qmk.fm) to make a keymap for an existing keyboard, or set yourself up to compile from QMK master, starting here: https://docs.qmk.fm/#/newbs.
