### ISSUE TITLE
Align language-specific keymaps with zsa/qmk_firmware

### ISSUE THREAD

**Issue by cortex** [qmk/qmk_firmware#6187]
The QMK fork at https://github.com/zsa/qmk_firmware/ have started to merge a set of changes that separates Swedish keyboard symbols from Nordic ones under the prefix SE_XX:

https://github.com/zsa/qmk_firmware/pull/80

I believe the purpose of this is to help them build better support for Swedish and other international keyboards into their configurator. 

As a Swedish keyboard user, this set of symbol names makes much more sense than what is currently in keymap_swedish.h (which is prefixed with NO) and is also more complete. In addition, adding this would make keymaps created in the Oryx keyboard configurator that use this feature compile.

I noticed this PR https://github.com/qmk/qmk_firmware/pull/2121 that adds a less complete version of this under the SV_XX prefix. https://github.com/qmk/qmk_firmware/issues/513 

I am not sure which one of these makes the most sense, (SE is the country and SV is the language), but it would be very good if we could make sure it is aligned with what is going on in zsa.

**Comment by drashna** [comment]
Yup, planning on doing that today/tomorrow, actually
