### ISSUE TITLE
Reading state of modifier keys during macro

### ISSUE THREAD

**Issue by r24y** [qmk/qmk_firmware#619]
I'm overriding `action_get_macro` in my layout so I can have customized keys (e.g. a key that produces `@` normally or `^` when Shift is pressed).

I have the following working and installed on my keyboard; I just don't know what to put for `SOMECONDITION`.

``` c
const macro_t *action_get_macro(keyrecord_t *record, uint8_t id, uint8_t opt)
{
  switch(id) {
    case _RY_ASPD:
      if (record->event.pressed) {
        register_code(KC_LSFT);
        if (SOMECONDITION) {
          register_code(KC_6);
          unregister_code(KC_6);
        } else {
          register_code(KC_2);
          unregister_code(KC_2);
        }
        unregister_code(KC_LSFT);
      }
  }
  return MACRO_NONE;
}
```

I think this is just a simple documentation issue and I'd be happy to create a PR once this gets resolved!

**Comment by iFreilicht** [comment]
You can use the `keyboard_report` function and `MOD_BIT` macro like so:

`keyboard_report->mods & (MOD_BIT(KC_LSFT))`

This will be 0 if LShift isn't pressed and some other number if it is pressed. If you care about both shifts, it get's a little more complicated, but I'm sure you can figure that out yourself.

Would be nice if you could integrate that into the documentation, it's really hard to find stuff like this, you basically have to see what other users have done.

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @r24y please reopen this or open a new issue.
