### ISSUE TITLE
[Bootmagic] swap control and gui

### ISSUE THREAD

**Issue by xiluo58** [qmk/qmk_firmware#6273]
I want to be able to use bootmagic to swap control and gui key

## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

I use a keyboard on both Windows and Mac OS. Many shortcuts that are ctrl + something are cmd(gui) + something on Mac. I wish I can use bootmagic to swap ctrl and gui so the shortcuts are at same position.

**Comment by fauxpark** [comment]
Looks like someone's way ahead of you 😉

**Comment by xiluo58** [comment]
Thanks. Closing this duplicated issue.
