### ISSUE TITLE
Compile Error: keymap_br_abnt2.h includes keymap_common.h

### ISSUE THREAD

**Issue by the0demiurge** [qmk/qmk_firmware#6325]
quantum/keymap_extras/keymap_br_abnt2.h:20:10: fatal error: keymap_common.h: No such file or directory

https://github.com/qmk/qmk_firmware/blob/421125211741993ba874068dadf4ab371d4d13de/quantum/keymap_extras/keymap_br_abnt2.h#L20

change that line from keymap_common.h to keymap.h fixed the problem, so hope to make this change in this repo.

**Comment by drashna** [comment]
Yup, this is a known issue, that is fixed in the breaking changes/future branch, already.

**Comment by the0demiurge** [comment]
Okay, thanks 4 your hard-working :)
