### ISSUE TITLE
Macro strings

### ISSUE THREAD

**Issue by capaldo** [qmk/qmk_firmware#6407]
Is it possible to assign a sequence of keys to trigger a macro. For example `\bc` to send the string "because"?

**Comment by noroadsleft** [comment]
I believe [Leader Key](https://docs.qmk.fm/#/feature_leader_key) is the feature you want.

**Comment by danielo515** [comment]
Leader key as @noroadsleft suggested is exactly what you want. I was about to open an issue to request an improvement for it.
I think you are already familiar with the concept of leader key since your example starts with  `\`, which is usually the leader key on vi.

**Comment by capaldo** [comment]
> Leader key as @noroadsleft suggested is exactly what you want. I was about to open an issue to request an improvement for it.
> I think you are already familiar with the concept of leader key since your example starts with `\`, which is usually the leader key on vi.

It does. Thank you for both your help. Much appreciated.

**Comment by danielo515** [comment]
So maybe close the issue?

**Comment by capaldo** [comment]
Sorry about that forgot to close it.
