### ISSUE TITLE
KC_GRV & KC_NUBS reversed on macOS

### ISSUE THREAD

**Issue by MrJuliuss** [qmk/qmk_firmware#6437]
# KC_GRV & KC_NUBS reversed on macOS

## Describe the Bug

Hi !
I have a problem with `KC_NUBS` & `KC_GRV`, on my layout. They seem to be reversed on macOS. I test the pcb on Windows 10, and all is OK. I will test on Ubuntu tomorrow.

Regards,

Julien

## System Information

 - Keyboard:  dz60
   - Revision:  Rev3
 - Operating system: macOS 10.14.6
 - AVR GCC version: 8.3.0
 - ARM GCC version: 7.3.1 20180622
 - QMK Firmware version: 0.6.439

**Comment by fauxpark** [comment]
You probably need to set the correct keyboard type in macOS. In the Keyboard preferences on the first tab should be a button labelled "Change Keyboard Type...". Click that and follow the instructions, and it should fix the incorrect layout.

**Comment by MrJuliuss** [comment]
Hi, indeed my keyboard was recognized as an ansi layout. It's now ISO and it works :)

Thanks !

**Comment by metawops** [comment]
I'm having the same issue (with another keyboard but QMK firmware)  but in macOS Big Sur I can't find any "Change Keyboard Type ..." button in the Keyboard System Preferences ... Any hint/help?
