### ISSUE TITLE
Support for Cypress PSoC 1 (8bit MCU) architecture

### ISSUE THREAD

**Issue by madivad** [qmk/qmk_firmware#6536]
*I am about to get my first devices capable of using QMK, I haven't used it before. But I decided I wanted to check out a macro keyboard I have and what would be the possibility of putting QMK on it. I read somewhere it may have been an AVR inside, but it turns out it is not. I considered pulling the chip out and trying to interface with the existing PCB, but in looking up the chip, it's quite a good piece of kit, and hence I wanted to start a discussion on the viability of adding support for this architecture*

I have a macro keyboard containing a Cypress CY8C24794 chip summarised as follows:

![info](https://i.imgur.com/BhOXIlj.jpg )

It looks pretty good with 50 IO pins (a 25x25 matrix could yield 625 buttons!), and included USB. The keyboard I have has every key directly wired to the chip (great for NKRO). It runs up to 25MHz and has I2C and USB. It has it's own [IDE (Unfortunately, it windows based only)](https://www.cypress.com/products/psoc-designer), but claims the tool chain includes a 

>a free C compiler with no size restrictions or time limits.

Unfortunately, I don't use or have windows but I was curious, given it has its own compiler, what are the difficulties in supporting another architecture? Is it at all even possible?

There are extensive resources and sample codes etc, but I am out of my depth even considering what should be done to even think about it. I have no idea where to start. 

There are plenty of resources available under:

https://www.cypress.com/documentation/application-notes/an2014-basics-psoc-1-programming
and
https://www.cypress.com/design-guides/cy3210-psoceval1-psocr-1-evaluation-kit-guide

I have just discovered my device itself doesn't have a XRES pin but can still be programmed via power cycling when a certain key is pressed and is documented from page 11 on this document: https://www.cypress.com/file/42201/download

But the question is essentially, what would it take to get QMK to compile on this architecture?

**Comment by drashna** [comment]
Well, it sounds like it's not supported by LUFA, ChibiOS or ATSAM.  If that's the case, then it makes it hard to implement.  And without the proper toolchain to compile ....
