### ISSUE TITLE
LEDs for layers not showing on Redox

### ISSUE THREAD

**Issue by pixelbreaker** [qmk/qmk_firmware#6602]
Since creating my own custom layout for my Redox wireless, the layer status indicator LEDs have completely stopped working, has anyone else come across this issue?

**Comment by noroadsleft** [comment]
@mattdibi Any ideas?

**Comment by pixelbreaker** [comment]
I've figured this out, don't worry. I was using the QMK configurator to compile, but now I download the keymaps into my own layout for the redox_w and match the layer indexes in the `matrix_scan_user` switch statement.

It's a shame it doesn't work out of the box with the QMK configurator though 😢

**Comment by noroadsleft** [comment]
Yeah, QMK Configurator doesn't quite have any support for advanced features like indicator LEDs or custom macros. Its API would need changes for that to happen. It's on our wish list, but no timeline as of yet.
