### ISSUE TITLE
rgb matrix and underglow 

### ISSUE THREAD

**Issue by boykhocnhe** [qmk/qmk_firmware#6604]
i have success in rgb matrix with ws2812 led
can i use other pin to drive ws2812 underglow

**Comment by drashna** [comment]
Unfortunately, no, I don't think you can.  I think there are too many collisions in the code right now, to allow that.

**Comment by Lenbok** [comment]
I think way to go may be to link the two into a single chain, and use different effects for per key vs underglow LEDs, ala #5851

**Comment by drashna** [comment]
Yup.
