### ISSUE TITLE
.hex instead of .bin?

### ISSUE THREAD

**Issue by zezoca1** [qmk/qmk_firmware#6634]
![Screenshot_1](https://user-images.githubusercontent.com/52155906/63974208-4ace6b80-caa4-11e9-9a6b-92a5c9e15520.png)

I was flashing my keyboard (dz60rgb) and when I open the softeare and tried to flash it said "! Only firmware files in .bin format can be flashed with dfu-util!" but everywhere I go download my firmwares it always downloads as hex files. Is there a way around this? Thanks.

**Comment by zvecr** [comment]
The firmware for a dz60rgb is located here <https://github.com/qmk/qmk_firmware/tree/master/keyboards/dztech/dz60rgb>, and precompiled here <https://qmk.fm/compiled/dztech_dz60rgb_default.bin>. The file you were trying to flash is for the regular AVR based dz60 which is why you were having issues.

**Comment by yanfali** [comment]
@zezoca1 this doesn't really seem like a bug, please close the issue if it's resolved. tl;dr your keyboard is ARM based not AVR so it doesn't use HEX files, it uses BIN.
