### ISSUE TITLE
Not recognized by Windows 10 on boot. 

### ISSUE THREAD

**Issue by ShizzyGuo** [qmk/qmk_firmware#6658]
This just recently started happening after the latest Windows 10 update. I have to un plug and re plug my Niu Mini in order to use it whenever I put my pc to sleep or after shutdown/restart. Any one else having this issue? Potential Fix? I compile using the web QMK configurator and flash with the QMK Toolbox

**Comment by johann-koebbe** [comment]
I don't have that particular problem, but one of my layers doesn't work on Windows 10 (fully up to date). I've been looking for information, but haven't found any yet. I came here to possibly post an issue. And I did the same, compiled using the online configurator, and flashed with QMK Toolbox 0.0.12.

**Comment by yanfali** [comment]
@johann-koebbe please don't hijack other people's issues. If you're having layer problems I would just try the discord and people can help you troubleshoot.

**Comment by johann-koebbe** [comment]
@yanfali I wasn't inteding to hijack the issue. I just wanted to add to the conversation about potential problems on Windows. For my own problems, I did create an issue in what I think is the appropriate place. Sorry for the confusion. Just trying to help. :disappointed:

**Comment by yanfali** [comment]
@johann-koebbe I've already commented on your issue. Feel free to close your issue once you've tested it. Thanks

**Comment by drashna** [comment]
@ShizzyGuo That's very odd.   IIRC, the NIU Mini is using an ATmega32u4 chip, and I don't see this behavior with any other board I'm using. 

If you could, try adding:
```
#define NO_USB_STARTUP_CHECK
```

And see if this helps.

**Comment by AaronJCA** [comment]
I am getting the same issue with my NIU Mini. On startup and on waking, the keyboard must be unpluged and pluged back in to work. I haven't tried the #define NO_USB_STARTUP_CHECK suggestion... though I'm not sure how to implement it.
