### ISSUE TITLE
A letter from the 3rd row + space registers a key from the 5th row

### ISSUE THREAD

**Issue by riccardocalligaro** [qmk/qmk_firmware#6692]
Hi, I have this issue with my new dz60rgb hot-swap, when I press a letter from the 3rd row + space it triggers also a key from the 5th row.
https://imgur.com/a/9Yb4I7c here I'm pressing only r + space but it registers also the ' t ' 

this happens when I type fast 

- dz60rgb and windows 10, already flashed default firmware.

kbdfans, where I bought  thet PCB, told me that this is a software issue and not PCB

**Comment by drashna** [comment]
That sounds like it might have a missing diode?  Or otherwise may be a hardware issue.  But I'm not 100% sure about that.
