### ISSUE TITLE
dz60rgb hot swap randomly starts clicking 6 y h and delete keys.

### ISSUE THREAD

**Issue by zezoca1** [qmk/qmk_firmware#6703]
Hi, just built my first mechanical keyboard and I have a pretty big issue. Randomly my keyboard starts spamming 6 y h and delete keys for no reason and it drives me nuts. Did someone had this problem or know how to solve it? Thanks in advance. (Maybe it is my shitty cable but I doubt it.).

**Comment by yanfali** [comment]
looks like you have a bad column. Since it's hot swap, try removing the switches and see if you can make it spam. This is probably a hardware problem, not a QMK issue.
