### ISSUE TITLE
IS31FL3731 the suspended mode does not use the shutdown pin. Right?

### ISSUE THREAD

**Issue by HMarxen** [qmk/qmk_firmware#6720]
Hi,
I am designing my first more complex board and I am going to use an IS31FL3731. The documentation mentions the suspended mode. I just wanted to make extra sure this means the software shutdown not the hardware shutdown on pin 3 right? Also, just to be sure, the interrupt output on pin 4 is also not used right? Maybe the wording in the documentation needs to be a bit clearer for other noobs like me.^^

**Comment by HMarxen** [comment]
So, I’ve looked up all boards in the keyboards folder which mention either “IS31FL3731” or “RGB matrix” and none of them are open hardware. The Ergodox EZ also isn’t open source. 
I’ve found a schematic for the OLKB planck:
https://github.com/olkb/olkb_parts/blob/master/planck/light/light-schematic-rev1.pdf
But the plank schematic seems sketchy. The SDB pin is unconnected, but if the pin isn’t pulled high the IC would go into hardware shutdown. 

So, my original question stays.^^ Does QMK make use of the interrupt output “INTB” and hardware shutdown ”SDB”? If not, I would connect SDB to VCC and leave INTB unconnected. I am running short on MCU pins, so it would be good to know.

**Comment by fauxpark** [comment]
Neither of the 3731 drivers (there are two of them for some reason) know anything about the SDB or INTB pins - all they do is communicate with the chip over I2C. It is probably the same story for the other ISSI drivers. So, yes, I think pulling SDB to VCC (with a resistor) and leaving INTB floating would be the right thing to do here.

**Comment by HMarxen** [comment]
OK, thank you very much for the help. :)

**Comment by drashna** [comment]
IIRC, there are schematics for the ergodox ez.  have you tried contacting them about it? 

Also, it sounds like this may be resolved?  If so, could we close this issue
