### ISSUE TITLE
QMK Configurator site is missing multiple KBD75v2 layouts

### ISSUE THREAD

**Issue by davidwed** [qmk/qmk_firmware#6735]
There is only one layout for the KBD75v2 "LAYOUT_numpad".

Since the KBD75 rev1 and KBD75 rev2 are the same except for the Numpad, you only have to extend the KBD75 rev1 layouts.

**Comment by yanfali** [comment]
Hi, submit a pull request against qmk_firmware on the info.json. the configurator just reads that info from there. Thanks.

**Comment by noroadsleft** [comment]
I vaguely remember looking into this a while back; I think it *may* require changes to the header files also.

**Comment by noroadsleft** [comment]
@davidwed Just confirmed this in QMK Configurator; it's fixed. You should be good to go.

**Comment by davidwed** [comment]
Thx

**Comment by noroadsleft** [comment]
You're welcome.
