### ISSUE TITLE
QMK Download Error 

### ISSUE THREAD

**Issue by DarrioG** [qmk/qmk_firmware#6784]
I am in the process of downloading QMK using the instructions on this website: https://docs.qmk.fm/#/newbs_getting_started

I encounter this error when carrying out out the first step of "Set Up QMK" on the website above.

![QMK ERROR](https://user-images.githubusercontent.com/55628757/65374949-566a1800-dc87-11e9-89af-7d2f064bd95c.png)

What can I do to solve this issue? 
Thanks in advance!

_________________________________________________________________________
$ git clone --recurse-submodules https://github.com/qmk/qmk_firmware.git
Cloning into 'qmk_firmware'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF

**Comment by drashna** [comment]
I think this is related to the issue that you're experiencing: 
https://github.com/msys2/MSYS2-packages/issues/735

**Comment by mrpbennett** [comment]
fixed the issue over SSH with adding the following to my ssh config file

```  hostname ssh.github.com
  port 443```
