### ISSUE TITLE
Keyboard randomly locks up while PC is sleeping.

### ISSUE THREAD

**Issue by fOmey** [qmk/qmk_firmware#6822]
## Bug Description

I use RGBLIGHT_SLEEP. I've noticed if the RGB lights turn back on while the PC is sleeping (usually overnight).. I know the keyboard is stuck in this "frozen" state.

If I look under devices & printers the keyboard is labeled as: "Unknown USB Device (Device Descriptor Request Failed)". Only fix being removing the USB & re-plugging it in.

Everything was working fine up until what seems like a recent upstream sync, but looking at the commits I can't notice anything that would cause this? Coincidence perhaps? 

I have my is keyboard connected right directly into the back of my PC, no hubs are being used.

Any ideas how I can debug further? The lock ups seem to be very intermittent, I'm struggling to come up with anything.. can't seem to reproduce them either.

## System Information

 - Keyboard:  KDB75 REV2 board
 - Operating system: Windows 10
 - AVR GCC version: avr-gcc.exe (AVR_8_bit_GNU_Toolchain_3.6.1_1752) 5.4.0

 - QMK Firmware version: 0.7.26
   - [X] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**EDIT:**

The issue still persists, I've noticed if I wake the PC up with the mouse however.. the keyboard doesn't _always_ lock up into the "Unknown USB Device (Device Descriptor Request Failed)" state. At least when this happens I can avoid having to remove the USB cable to restart the keyboard...

**Comment by drashna** [comment]
That's really odd.  Given the controller and everything, that's ... not typical. 

My guess would be faulty hardware. Be it the USB port, the USB cable, or a short on the PCB.

**Comment by fOmey** [comment]
It is a strange issue, a very intermittent one also. It only happens every few days?

If it was a short of some kind, I'd imagine it would happen a lot more frequently.. I would be able to reproduce it, seems to be very set/specific circumstances that cause this problem to happen.

It's as if the keyboard is detecting a false wake up signal, trying to initialize and breaking when its not receiving the expected result.. that's my guess.

I don't believe this to be related to RGB sleep at all.. I think it's just a side effect of the issue I described above that they're turned back on.

Faulty hardware? That's a stretch, but I guess I'll order a new USB and test..

**Comment by fOmey** [comment]
Purchased a brand new USB cable shortly after my last message, everything seemed fine up until 2 minutes ago when the issue returned.

God dam it, really thought it had fixed it for a second! 

Argh, i'm going to dismantle the board and inspect the PCB.. give it another really good isopropyl clean in hopes a miracle happens and the issue disappears.

**Comment by fOmey** [comment]
Well it's been 4 days and the issue has not reappeared since swapped the USB C cable out.

I've attached some images of the cable I was having issues with for record just in case someone finds themselves in a similar situation in the future.. it was a generic braided USB C cable I sourced off eBay:

![s-l500 (1)](https://user-images.githubusercontent.com/5051561/66364401-4bc4b800-e9d5-11e9-82d7-a021b87791b7.jpg)
![s-l500](https://user-images.githubusercontent.com/5051561/66364402-4bc4b800-e9d5-11e9-9e8c-4b915c0e7214.jpg)
