### ISSUE TITLE
qmk compile could be context sensitive about keyboard directory

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_firmware#6824]
Idea is: you are in `keyboards/keebio/iris/rev3` and you type `qmk compile` if no defaults are set it detects the directory you are in and compiles that with the default keymap. If you have a default keymap set in your global config it attempts to compile your personal keymap if it exists.

This would make the qmk compile context sensitive to where it is being run from to source parameters for keyboard and keymap.

## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Think of these as fall back sources for parameters when there are none supplied by the defaults or the cli.

**Comment by skullydazed** [comment]
I think a good argument could be made for CWD overriding configuration. It would be consistent with how the global CLI operates- configuration can specify the default `qmk_firmware` location but your current directory will override that configuration.

**Comment by cfbender** [comment]
I'd love to take this one for hacktoberfest if that's alright! I think I should be able to do it, thought it will be some of the first python I've written for a bit. If you'd prefer someone more experienced I'd understand!

**Comment by ThiagoWhispher** [comment]
This would be very interesting for users who use it, leaving the complexity to QMK.

**Comment by vaibhavbisht06** [comment]
Is there any way I can add images to this guide

**Comment by sakshamtaneja21** [comment]
for this ill open a pr and then can check @admin

**Comment by DavidYangDev** [comment]
@vaibhavbisht06  Where would you want to add images? just confused because I'm not really great at this either

**Comment by rishav142k** [comment]
Is anyone working on this issue because I would like to take it.
