### ISSUE TITLE
MIDI device can't be recognized on win10

### ISSUE THREAD

**Issue by hsgw** [qmk/qmk_firmware#6846]
## Describe the Bug
MIDI device can't be recognized correctly on windows10 64bit.
I revert commit before changing lib/lufa to submodule, it works.

## Additional Context
There is no probrem on OSX, ubuntu, and win7.

**Comment by drashna** [comment]
If that's the case, one of the files in `tmk_core/protocol/usb_descriptors.c` wasn't probably changed when LUFA was changed over to a submodule.

**Comment by LouWii** [comment]
@hsgw Have you tried that fix: https://github.com/qmk/qmk_firmware/pull/7258 ? It's been merged in.

**Comment by drashna** [comment]
@hsgw have you had a chance to update the repo and test to see if this is still an issue?

**Comment by tzarc** [comment]
Hasn't been updated in 2.5 years, going to assume this is no longer an issue.
