### ISSUE TITLE
Dc-2014 Print Screen button

### ISSUE THREAD

**Issue by SneakyRobb** [qmk/qmk_firmware#6866]
Hi,

I am having an issue where my print screen button on the DC-2014 keyboard.

It seems to give the code 37 which is Pad_asterisk when I press print screen. 

Could you add this additional layout where that key is changed to the layout options for 

keyboard "converter_xt_usb?"

I think my file might not be properly formated or correct though. I added a new file. I think I accidentally pasted over the shift key.

*I found this tmk documentation outlining what is happening as well.
https://github.com/tmk/tmk_keyboard/issues/552

Thanks,
Robb

[converter_xt_usb_dc2014b.txt](https://github.com/qmk/qmk_configurator/files/3677317/converter_xt_usb_dc2014b.txt)

**Comment by noroadsleft** [comment]
@SneakyRobb I think I might be starting to wrap my head around this.

Because Print Screen and Pad Asterisk are on the same key on your keyboard, you want the key to send Print Screen when Num Lock is disable, but Pad Asterisk when Num Lock is enabled, is that correct?

**Comment by SneakyRobb** [comment]
@noroadsleft 

I understand this, it really confused me. It is not the biggest issue, it is just a minor thing. I think I understand it now.  Really its just to change the layout on the main QMK thing a bit. 

Basically on the XT keyboard the Asterisk and PrintScreen were the same key. 

For whatever reason, in TMK, the asterisk key was put down on the XT layout, as "Print Screen."

But the key is asterisk first, you had to press shift, to print screen. 

So now in QMK, if I open the configurator, to the keyboard "converter/xt_usb"
and layout "LAYOUT_xt"
here:
https://config.qmk.fm/#/converter/xt_usb/LAYOUT_xt

The key under enter is shown as Print Screen. If I use the configurator to map this key, it wont work. Because that key is Numpad-Asterisk. ''

That is basically it.

**Comment by noroadsleft** [comment]
So it's always Numpad Asterisk no matter what is assigned there? I'm still confused.
