### ISSUE TITLE
Convert new_keyboard.sh to a python command

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#6872]
## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

Similar to #6066, we should convert new_keyboard.sh to a qmk command.

Some thoughts on implementation:

* The cleanest way to handle the templates is probably by using `.format()` string formatting. 
* Like new_keymap the user should be able to supply answers on the command line. Any information not provided should be prompted for.
* This is an instance where most (all?) CLI flags should be `arg_only=True`.

**Comment by HBBisenieks** [comment]
Is the intention that this be, essentially, a drop-in replacement for the current .sh version with the addition of CLI flags that supersede the interactive prompts?

**Comment by skullydazed** [comment]
As a start, yes. I think there will be room to iterate and improve on it once that is done, and I'd welcome most of those improvements as part of the initial PR. For example, support for arm keyboards.

**Comment by HBBisenieks** [comment]
I'm making a branch on my fork to get the ball rolling on this, and I'll open a PR when it's at least feature-complete with the .sh version.

**Comment by stjohnjohnson** [comment]
@HBBisenieks sorry!

**Comment by HBBisenieks** [comment]
Hey no worries! Your implementation looks way better than mine was looking in the planning stages.

**Comment by ThiagoWhispher** [comment]
Hi @skullydazed, what is the advantage of replacing .sh with a python command? Better debugging?

**Comment by lf-** [comment]
@ThiagoWhispher I'm going to go for maintainability, consistency in output/behaviour, reliability, and moving all the shell stuff to the qmk utility.

**Comment by stjohnjohnson** [comment]
I like the idea of centralizing all these commands into a single CLI.  Combine that with the Docker container and you have a single command with no dependencies (besides Docker) for all operations.

**Comment by ThiagoWhispher** [comment]
@lf- now I understand how advantageous this is.
@stjohnjohnson I working with Docker, and strongly recommend, very practical to work.

**Comment by helios1101** [comment]
Are these docker images hosted on Docker Hub too? Just wanted to start my journey in containers as it would be my first experience with dockers contribution.

**Comment by stjohnjohnson** [comment]
@helios1101 https://hub.docker.com/r/qmkfm/qmk_firmware for example

**Comment by sakshamtaneja21** [comment]
for this please tell me what exact changes you needed

**Comment by DavidYangDev** [comment]
Looking at the other comments, at first I was confused about the purpose of it now, but I rethought about it and it's usage is quite widespread. Is there a PR that tackles this?

**Comment by DavidYangDev** [comment]
Just wondering, is there a pr that has handles/is handing this request?
