### ISSUE TITLE
CLI command to convert KLE to JSON

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#6880]
## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

Currently you have to use the API (by way of a single use web page) to convert KLE to info.json. We should have a CLI command to do this as well.

A good starting point would be the API code that already does this. The API entrypoint for the converter is here: https://github.com/qmk/qmk_api/blob/master/web.py#L209

**Comment by cfbender** [comment]
Working on this now!

**Comment by helios1101** [comment]
Just a suggestion, while I was exploring, as a beginner I personally felt that it would be great if the virtual environment would be made in the beginning so that the requirements don't hamper the rest of the environment.

**Comment by skullydazed** [comment]
@helios1101 We have talked about doing that in the past (in fact if you install the qmk cli using homebrew it uses a virtualenv) but for right now are not doing so. Users can setup their own virtualenv if they feel it is important.

That said, we're out of scope for the current issue. If you'd like to discuss this further please create a new issue for the topic.

**Comment by vaibhavbisht06** [comment]
Can any repo maintainer help me to understand the 2 flie of project
