### ISSUE TITLE
How to get keymaps to show up on the QMK configurator

### ISSUE THREAD

**Issue by blu006** [qmk/qmk_firmware#6891]
Hello,

I'm wondering if there is a way to get keymaps to show up by default on the QMK configurator.  Mainly, I want to set a default keymap for the handwired/tritium_numpad keyboard's ortho_6x4 layout.

Could this have something to do with the /layouts folder in the repo?

Thanks,
Brandon

**Comment by yanfali** [comment]
@blu006 this is unfortunately a hard problem, parsing arbitrary C with macros is a non-trivial task. @skullydazed is working on a JSON driven version of QMK that will make this much easier in the future and a lot of these keymaps could then be converted and would be accessible from configurator. But at this time it's not very easy to do consistently.

**Comment by blu006** [comment]
Is there a way to do it manually for now?  I'm more than willing to hand-translate my own keymaps until the automated JSON-driven QMK comes out.

**Comment by yanfali** [comment]
kind of, you can simply use the configurator to copy the keymap you like and export a JSON file. The new format will be the same for the upcoming change.

**Comment by blu006** [comment]
So saving the configuration and then uploading it to the /layouts folder in the repo would make it show up in the configurator eventually?

**Comment by yanfali** [comment]
we don't currently support multiple keymaps per keyboard in the configurator at this time. You would need to store it locally. Eventually when everything is JSON driven it would be trivial to add that feature.

For now you'll just need to have a copy locally.

**Comment by blu006** [comment]
Thanks for answering my questions.  I guess I'll close this PR until then
;)

**Comment by danielo515** [comment]
If you use an ergodox I built a tool that allows you visualize your layout on a kind-of visual configurator: https://danielorodriguez.com/ergodox-configurator
