### ISSUE TITLE
CLI command to list keyboards

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#6911]
## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

We should have a new command, `qmk list-keyboards`, that lists all the available keyboards. A good first step would be to simply run `make list-keyboards` and let it print to stdout.

It may be more performant to look at what make is doing and replicate the logic in python. If so we should do that so that `make list-keyboards` can call `qmk list-keyboards` instead of the current method.

**Comment by danmcclain** [comment]
I'll take a quick pass at this today

**Comment by raghavdhingra** [comment]
Looks good
