### ISSUE TITLE
Windows subsystem for Linux in documentation

### ISSUE THREAD

**Issue by Gimly** [qmk/qmk_firmware#6913]
The documentation on Windows explains how to setup the build environment on Windows using MSYS2, which is nice but might be a bit complicated for new users. Wouldn't it make more sense to use the Windows subsystem for Linux (WSL) for this?

WSL is a real Linux that runs in Windows, so it should behave exactly like a Linux and has the advantage to be "built-in" the system since Windows 10.

**Comment by alexweininger** [comment]
As a WSL user I would love to see this.

**Comment by fauxpark** [comment]
I believe we do support WSL: https://docs.qmk.fm/#/getting_started_build_tools?id=toolchain-setup
This documentation was probably written at a time when WSL was not able to access USB devices for flashing, so MSYS2 was the recommended method instead.

**Comment by noroadsleft** [comment]
Note that WSL is only available for Windows 10; Windows 8/8.1 users will need to use the MSYS2 method.

**Comment by ThiagoWhispher** [comment]
It's a good idea, even with some details of Windows restrictions, it would still be another feature in favor of new users.

**Comment by noroadsleft** [comment]
> It's a good idea, even with some details of Windows restrictions, it would still be another feature in favor of new users.

I agree. Just wanted it documented that the MSYS instructions need to remain if/when WSL instructions are added. :+1:

**Comment by drashna** [comment]
Additionally, WSL does not allow you to flash the firmware for any of the bootloaders.   Additionally, last I checked, the 18.04 version of ubuntu for WSL still has broken packages for ARM GCC.   

Between these two issues, MSYS is a better solution, sadly.

**Comment by sakshamtaneja21** [comment]
also can add this documentation to github and push over the website

**Comment by drashna** [comment]
Closing this. 

Unfortunately, I don't think that WSL is in a state where it will be better than MSYS, in terms of usability. At least, not for everyone.
