### ISSUE TITLE
QMK Translations Hub

### ISSUE THREAD

**Issue by noroadsleft** [qmk/qmk_firmware#6924]
In an effort to reduce the likelihood of multiple people translating the same thing twice, here are the PRs that have worked or are working on translations. **We encourage you to open a pull request as soon as you have the first page/file translated, and work together with others that may be interested in translating or reviewing.** Be sure to put the name of the language you're translating to in the title to help with visibility.

**Please don't comment here about specific translations - do that on the relevant PR.**

## QMK Firmware Documentation ([docs.qmk.fm](https://docs.qmk.fm/))

- Repository: [qmk/qmk_firmware](https://github.com/qmk/qmk_firmware/)
- Directory: https://github.com/qmk/qmk_firmware/tree/master/docs

### Brazilian Portuguese

- README: [#7016](https://github.com/qmk/qmk_firmware/pull/7016) by @igorhideki 

### French

- **MERGED** Spelling corrections: [#7171](https://github.com/qmk/qmk_firmware/pull/7171) by @Ph0tonic
- FAQ: [#6995](https://github.com/qmk/qmk_firmware/pull/6995) by @Gimly and @4sStylZ
- **MERGED** Breaking Changes: [#6966](https://github.com/qmk/qmk_firmware/pull/6966) by @Gimly 
- **MERGED** QMK Basics: [#6925](https://github.com/qmk/qmk_firmware/pull/6925) by @Gimly 
- **MERGED** Complete Newbs Guide: [#6901](https://github.com/qmk/qmk_firmware/pull/6901) by @Gimly and @4sStylZ

### German

- README and Newbs Guide: [#6909](https://github.com/qmk/qmk_firmware/pull/6909) by @kuchosauronad0, @Maxr1998 and @geisterfurz007
- **MERGED** "CLI" documentation: [#7178] by @flechnical and @kuchosauronad0

### Hebrew

- **MERGED** [#7001](https://github.com/qmk/qmk_firmware/pull/7001) by @GuyKh (reviewed by @ezuk)

### Hindi

- README and Summary: [#6962](https://github.com/qmk/qmk_firmware/pull/6962) by @arimanyus
- ARM Debugging and CLI docs: [#7069](https://github.com/qmk/qmk_firmware/pull/7069) by @aloks98

### Russian

- **MERGED** Complete Newbs Guide: [#6967](https://github.com/qmk/qmk_firmware/pull/6967) by @StrikerRUS and @nabokovas

### Spanish

- README and Newbs Guide: [#7068](https://github.com/qmk/qmk_firmware/pull/7068) by @namelivia and @kbravh
- Hardware: documentation [#7161](https://github.com/qmk/qmk_firmware/pull/7068) by @michizhou

### Thai

- README: [#7032](https://github.com/qmk/qmk_firmware/pull/7032/files) by @narze

----

## QMK Configurator ([config.qmk.fm](https://config.qmk.fm/))

- Repository: [qmk/qmk_configurator](https://github.com/qmk/qmk_configurator/)
- Directory: https://github.com/qmk/qmk_configurator/tree/master/src/i18n

### Brazilian Portuguese

- **MERGED** [#540](https://github.com/qmk/qmk_configurator/pull/540) by @Andre-rsfc, @fcoury and @Gondolindrim
- **MERGED** [#525](https://github.com/qmk/qmk_configurator/pull/525) by @ThiagoWhispher, @Gondolindrim and @fcoury

### Chinese

- **NEEDS REVIEWERS** [#520](https://github.com/qmk/qmk_configurator/pull/520) by @mechmerlin

### French

- **MERGED** [#558](https://github.com/qmk/qmk_configurator/pull/558) by @Ph0tonic 
- **MERGED** [#325](https://github.com/qmk/qmk_configurator/pull/325) by @gab-a
- Additional Contributions by @zekth

### German

- **MERGED** [#513](https://github.com/qmk/qmk_configurator/pull/513) by @Vexatos
- **MERGED** [#365](https://github.com/qmk/qmk_configurator/pull/365) by @heieisch (original translator)

### Greek

- **MERGED** [#556](https://github.com/qmk/qmk_configurator/pull/545) by @GreekGeorge and @yiancar

### Hindi and Marathi

- [#547](https://github.com/qmk/qmk_configurator/pull/547) by @bantya

### Italian

- **MERGED** [#557](https://github.com/qmk/qmk_configurator/pull/557) by @michizhou and @sahalsaad

### Japanese

- **MERGED** [#543](https://github.com/qmk/qmk_configurator/pull/543) by @shelaf, @ai03-2725 and @mtei

### Malaysian (Bahasa Malaysia)

- **MERGED** [#546](https://github.com/qmk/qmk_configurator/pull/546) by @sahalsaad

### Philippine Tagalog

- [#541](https://github.com/qmk/qmk_configurator/pull/541) by @Nievac

### Polish

- **MERGED** [#531](https://github.com/qmk/qmk_configurator/pull/531) by @wojciechgabrys and @kbudaj

### Russian

- Part 2 **MERGED** [#528](https://github.com/qmk/qmk_configurator/pull/528) by @nabokovas and @StrikerRUS
- Part 1 **MERGED** [#519](https://github.com/qmk/qmk_configurator/pull/519) by @StrikerRUS and @nabokovas

### Spanish

- **MERGED** [#516](https://github.com/qmk/qmk_configurator/pull/516) by @kbravh and @namelivia
- **MERGED** [#559](https://github.com/qmk/qmk_configurator/pull/559) by @johnny243

----

## QMK Firmware website ([qmk.fm](https://qmk.fm/))

- Repository: [qmk/qmk.fm](https://github.com/qmk/qmk.fm/)
- Directory: https://github.com/qmk/qmk.fm/tree/gh-pages/_i18n
- Instructions: https://github.com/qmk/qmk.fm/blob/gh-pages/readme.md

### Brazilian Portuguese

- **MERGED** [#62](https://github.com/qmk/qmk.fm/pull/62) by @ThiagoWhispher

### Chinese

- **MERGED** Chinese translation strings: [#70](https://github.com/qmk/qmk.fm/pull/70) by @michizhou and @mechmerlin 

### French

- **MERGED** Initial Translation [#66](https://github.com/qmk/qmk.fm/pull/66) by @MattMattV, @Darkpingouin, @zekth and @Ph0tonic
- **MERGED** Patch [#88](https://github.com/qmk/qmk.fm/pull/66) by @Darkpingouin, @zekth, and @Ph0tonic

### Russian

- **MERGED** [#61](https://github.com/qmk/qmk.fm/pull/61) by @StrikerRUS, @nabokovas and @lex111

### German

- **MERGED** Main Page [#60](https://github.com/qmk/qmk.fm/pull/60) by @Vexatos and @kuchosauronad0
- **MERGED** 404 Page [#79](https://github.com/qmk/qmk.fm/pull/79) by @flechnical and @kuchosauronad0
- **MERGED** Code of Conduct [#81](https://github.com/qmk/qmk.fm/pull/81) by @john2ksonn and @kuchosauronad0
- German translation for powered, support, proton-c and the categories directory: [#82](https://github.com/qmk/qmk.fm/pull/82) by @kuchosauronad0
- **MERGED** License Page: [#84](https://github.com/qmk/qmk.fm/pull/84) by @john2ksonn and @kuchosauronad0
- **MERGED** Converter, Flasher, Powered, Support and Toolbox pages: [#85](https://github.com/qmk/qmk.fm/pull/85) by @john2ksonn and @kuchosauronad0 
- **MERGED** German Sidebar Links: [#86](https://github.com/qmk/qmk.fm/pull/86) by @john2ksonn

### Greek

- [#71](https://github.com/qmk/qmk.fm/pull/71) by @MIP2000, @drashna and @kuchosauronad0

### Hindi

- [#76](https://github.com/qmk/qmk.fm/pull/76) by @MetalDent

### Italian

- [#77](https://github.com/qmk/qmk.fm/pull/77) by @michizhou

### Malayalam

- [#74](https://github.com/qmk/qmk.fm/pull/74) by @sagarvd01 

### Marathi

- [#87](https://github.com/qmk/qmk.fm/pull/87) by @parammittal16

### Spanish

- Spanish translations: [#67](https://github.com/qmk/qmk.fm/pull/67) by @kbravh and @kuchosauronad0
- ~~Spanish translation for keyboards.md: [#69](https://github.com/qmk/qmk.fm/pull/69) by @michizhou~~ **closed as `wontfix`**: infrastructure doesn't support proposed changes

**Comment by kbravh** [comment]
I'm currently working on Spanish translations for the [qmk/qmk_firmware](https://github.com/qmk/qmk_firmware/) documentation.

**Comment by Gimly** [comment]
@noroadsleft you can add the PR #6925 for the French translation, it adds the translation for the QMK Basics chapter

**Comment by ThiagoWhispher** [comment]
@noroadsleft is it possible to add new languages ​​besides those mentioned above? I wanted to work on translating my native language (pt-BR)

**Comment by kichloo** [comment]
I have made the Hindi translation of the same.

**Comment by kichloo** [comment]
Here is the link of Hindi translation of CODE_OF_CONDUCT.md in Hindi
https://github.com/qmk/qmk_firmware/pull/6939

**Comment by Kolkies** [comment]
I will look into translating the configurator!

**Comment by ThiagoWhispher** [comment]
@noroadsleft I worked on the translation in the qmk/qmk_configurator repository for pt-BR available at https://github.com/qmk/qmk_configurator/pull/525

**Comment by jackhumbert** [comment]
Sorry to the folks that commented - this was just meant to be a resource, not a discussion page. You can mention this issue in your PR (via `#6924`) and we'll get it added to the list :)

**Comment by zvecr** [comment]
Closing as most translations have been removed due to being extremely stale, and this mostly covering hacktoberfest activities.
