### ISSUE TITLE
update readme - fix documentation section

### ISSUE THREAD

**Issue by Parikshit-Hooda** [qmk/qmk_firmware#6937]
The documentation section has 'See the official documentation on docs.qmk.fm' entirely used as link text. The link text should be only 'docs.qmk.fm'

I want to take this up as part of hacktoberfest.

**Comment by parammittal16** [comment]
on it

**Comment by Aditya2603** [comment]
So, how you supposed to do that?

**Comment by Aditya2603** [comment]
@Parikshit-Hooda

**Comment by Parikshit-Hooda** [comment]
As I have mentioned above, the link text should only be docs.qmk.fm .

**Comment by jackhumbert** [comment]
I'm not entirely clear on what you're suggesting, but feel free to just open a PR - no need to make a separate issue for it beforehand.
