### ISSUE TITLE
order matters: OSL + OSM ignores OSL; OSM + OSL works as expected

### ISSUE THREAD

**Issue by plantarum** [qmk/qmk_firmware#6943]
I am using OSL and OSM. I have a key set to OSM(MOD_LGU), and another set to OSL(_RS), where _RS is defined as a separate layer. If I want to modify a key from _RS, I can tap the OSM key, then tap the OSL key, and finally the regular key on _RS. This works as expected. 

However, if I reverse the order, and tap OSL, then OSM, and then the regular key, the keypress that is sent is the key from the original layer with the modifier applied, NOT the key from the _RS layer.

If this is expected behaviour, I can train myself to respect the required order. However, it would be nice to be able to hit the modifiers in either order. Is this possible?

I'm using an Atreus keyboard, and my config file is here: 

https://github.com/plantarum/qmk_firmware/blob/master/keyboards/atreus/keymaps/algernon/keymap.c

I'm running Debian Linux
avrdude version 6.3-20171130
avr-gcc (GCC) 5.4.0
QMK 0.5.173

I use KC_TRNS on the _RS layer to ensure that the OSM and OSL keys have the same definition on each layer, as you can see in my config.

Thank you for your time, and for all the work you have done on this software and the documentation! I did check the manual, but if this issue is explained there I apologize, as I've overlooked it.

**Comment by precondition** [comment]
One-Shot layer turns off the layer after the next key is pressed but pure modifier keys (`KC_LCTL`, etc.) are ignored in the code so I believe OSMs should get ignored too.

Patch to ignore OSMs and fix your issue:
```diff
diff --git a/quantum/action.c b/quantum/action.c
index 6b2e9104e0..68e6cee85a 100644
--- a/quantum/action.c
+++ b/quantum/action.c
@@ -319,7 +319,8 @@ void process_action(keyrecord_t *record, action_t action) {
 #ifndef NO_ACTION_ONESHOT
     bool do_release_oneshot = false;
     // notice we only clear the one shot layer if the pressed key is not a modifier.
-    if (is_oneshot_layer_active() && event.pressed && (action.kind.id == ACT_USAGE || !IS_MOD(action.key.code))
+    if (is_oneshot_layer_active() && event.pressed && (action.kind.id == ACT_USAGE || 
+                !(IS_MOD(action.key.code) || (action.kind.id & ACT_MODS_TAP && (action.layer_tap.code == MODS_ONESHOT || action.layer_tap.code == MODS_TAP_TOGGLE))))
 #    ifdef SWAP_HANDS_ENABLE
         && !(action.kind.id == ACT_SWAP_HANDS && action.swap.code == OP_SH_ONESHOT)
 #    endif
```
