### ISSUE TITLE
TAPPING_TERM counting the second key hold time is unintuitive

### ISSUE THREAD

**Issue by xster** [qmk/qmk_firmware#6953]
TAPPING_TERM and variations like PERMISSIVE_HOLD IGNORE_MOD_TAP_INTERRUPT seem to facilitate things for making more things register as holds, but I'd argue the default TAPPING_TERM is already over-inclusive in one case for "slow" typists:

Assume a TAPPING_TERM of 200ms

t=0ms - press down LCTL_T(KC_A)
t=20ms - press down KC_B
t=40ms - LCTL_T(KC_A) up
t=220ms - KC_B up

Even though the mod key LCTL_T was held down very briefly, it still gets registered as a hold since the second key was held down for longer. 

For slow typists who'd like to keep the TAPPING_TERM at the threshold of their natural typing speed, this doubles the odds of a false positive and I'm also not sure what the general valid use case this behavior is meant to support.

**Comment by xster** [comment]
Actually playing around with this a bit more, it seems like this is explicitly meant to be fixed by IGNORE_MOD_TAP_INTERRUPT but I would have never realized it from reading the doc. 

I didn't read through the source and I'm only testing this empirically but it seems like the IGNORE_MOD_TAP_INTERRUPT behavior is almost the reverse of how the doc describes it. i.e. defining it makes hold triggers less likely rather than more likely. 

Tentatively sending https://github.com/qmk/qmk_firmware/pull/6955 to verify my understanding.

**Comment by xster** [comment]
Looking through the codebase, it seems like there's a lot of other duplicate 'solutions' to this same problem in their own config.h https://github.com/qmk/qmk_firmware/blob/a1a7a84831230515bac68c9fe2c93cd90c02acb8/keyboards/georgi/config.h#L59 https://github.com/qmk/qmk_firmware/blob/4be1dfcee48daeb77e966b08ad9ca51e02253acf/users/manna-harbour_miryoku/config.h#L6 https://github.com/qmk/qmk_firmware/blob/cc8744548108b1c1f820fb411ac3bf313aca1f5f/keyboards/jd45/keymaps/blakedietz/config.h#L5

where they also felt the need to 'redocument' what this flag does. 

Arguably the behavior with `IGNORE_MOD_TAP_INTERRUPT` should be the default behavior. As mentioned above, I can't imagine a valid proper use case for it. But I can imagine how big of a breaking change it would be changing the default.

**Comment by rpbaptist** [comment]
I just want to weigh in on this, because I also think the description is very confusing. Each time I had to revisit these options I had to re-read the docs and only the provided examples allowed me to understand it. It took a lot of testing with `TAPPING_TERM`, `PERMISSIVE_HOLD` and `IGNORE_MOD_TAP_INTERRUPT`to get a situation where the keyboard behaved to my liking.

In fact, I was convinced that I needed `PERMISSIVE_HOLD` and not `IGNORE_MOD_TAP_INTERRUPT` to solve the issues I had until trial and error proved otherwise.

**Comment by xster** [comment]
Another potential piece of supporting data, someone at ergodox-ez probably thought the default behavior (IGNORE_MOD_TAP_INTERRUPT undefined) is confusing and flipped it. 

<img width="791" alt="Screen Shot 2019-10-07 at 4 29 18 PM" src="https://user-images.githubusercontent.com/156888/66362890-3e59f000-e939-11e9-908d-96e2a762ba71.png">

**Comment by noroadsleft** [comment]
@drashna Could you weigh in on this?

**Comment by xster** [comment]
Would like to get #6955 reviewed if anyone has the time. I think it adds more clarification.
