### ISSUE TITLE
What does "KC_MSEL" mean?

### ISSUE THREAD

**Issue by SeanJM** [qmk/qmk_firmware#698]
Hi, I am currently working on a front end for this tool and I want to design an icon for "KC_MSEL", for that to be clear, I would like to know what it means.

Proof of front end: https://twitter.com/SeanJMacIsaac/status/764432999983243264

**Comment by jackhumbert** [comment]
[Media Select](https://github.com/jackhumbert/qmk_firmware/blob/master/tmk_core/common/keycode.h#L147) :) what it actually does, I'm not sure, but it likely varies per system.

**Comment by SeanJM** [comment]
That is odd, I know it's 'Media Select'. I see you are as stumped as I am good sir. 💃

**Comment by fredizzimo** [comment]
@tmk and @shelaf did some very nice investigation [here](https://github.com/tmk/tmk_keyboard/issues/332). 

So apparently it opens the media player in Windows 10 and does nothing on other platforms.

**Comment by SeanJM** [comment]
Thank you!

Sean

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @SeanJM please reopen this or open a new issue.
