### ISSUE TITLE
Website: Gitbook link dead and unclear reference to “suggest an edit”

### ISSUE THREAD

**Issue by DLFW** [qmk/qmk_firmware#7054]
The link to the Gitbook documentation (https://qmk-1.gitbook.io/firmware) on the https://qmk.fm/ front page gives a HTTP 404 response. The link should be updated or removed.

The front page also mentions that changes can be requested by “suggest an edit” links on “any” page, but I cannot find them anywhere.

**Comment by fauxpark** [comment]
Fixed by the above PR.
