### ISSUE TITLE
Language links are invalid

### ISSUE THREAD

**Issue by MetalDent** [qmk/qmk_firmware#7102]
On clicking on any of the languages in [this](https://github.com/MetalDent/qmk_firmware/blob/master/docs/_langs.md) it says that "Page not found"

**Comment by fauxpark** [comment]
That file is used only for Docsify, you can see it in use on the actual docs site: https://docs.qmk.fm/

Although, the French link still does not work, but this is a known issue, and will be fixed at some point (hopefully soon): https://github.com/qmk/qmk_firmware/issues/7002
