### ISSUE TITLE
Compatible bluetooth module

### ISSUE THREAD

**Issue by skeltr** [qmk/qmk_firmware#7115]
I want to have bluetooth on my keyboard based on a AT90USB1286.
But I don't know which modules are compatible with QMK and with my IC.
I don't want a feather except if it is a feather with an AT90USB1286.
Thank you in advance and sorry for my bad english.

**Comment by fauxpark** [comment]
The RN-42 module is USB128 compatible as of quite recently. There is also the Adafruit BLE SPI Friend, which is just the Bluetooth module from the Feather, without the MCU: https://www.adafruit.com/product/2633

**Comment by skeltr** [comment]
Only those 2 are qmk compatible ?
