### ISSUE TITLE
Adafruit Bluefruit LE SPI Friend Pins

### ISSUE THREAD

**Issue by skeltr** [qmk/qmk_firmware#7130]
I would build a bluetooth keyboard with a AT90USB1286 and for the bluetooth a Adafruit Bluefruit LE SPI Friend (https://www.adafruit.com/product/2633)
But the problem is that i don't know which pins of the module must be connected to which pins of the microcontroller.
Thank you in advance and sorry for my bad english.

**Comment by noroadsleft** [comment]
Sorry for the non-response. Did you figure this out?

**Comment by skeltr** [comment]
Someone say me that : B1 = SCLK, B2 = MOSI, and B3 = MISO
But can I connect the others pins of the bluefruit to any pins of the at90usb1286 ?
And which pins of the bluefruit are essential and which are not.

**Comment by fauxpark** [comment]
You can easily confirm this using the datasheet: http://ww1.microchip.com/downloads/en/devicedoc/doc7593.pdf

On page 3, it says that the SPI pins for the AT90USB64/128 are indeed B1-3.

**Comment by skeltr** [comment]
And the others pins (cs, irq, dfu, rst), where i have to connect them ?

**Comment by fauxpark** [comment]
According to the docs: https://docs.qmk.fm/#/feature_bluetooth?id=adafruit-ble-spi-friend
B4, E6 and D4 respectively - the DFU pin is for putting the Bluetooth module itself into DFU mode, it's not necessary to connect it to anything unless you're trying to update the firmware, which it can do over the air anyway.

**Comment by skeltr** [comment]
Can I change the pins of the cs, irq, rst ?
