### ISSUE TITLE
Backlight LEDs setyup is not working on Mitosis

### ISSUE THREAD

**Issue by LEdiodes** [qmk/qmk_firmware#7179]
I cannot seem to get the backlight LEDs working on the Mitosis wireless split keyboard

BACKLIGHT_ENABLE = yes is in my rules.mk

BL_TOGG is set as a key on my board.

Any help would be appreciated

**Comment by fauxpark** [comment]
I don't think it supports backlighting, due to how it's set up with the nRF modules. At least, I can't see anything here: https://github.com/reversebias/mitosis

**Comment by pmstyle123** [comment]
I am agree with @fauxpark  It's not support backlighting
