### ISSUE TITLE
KBD8X_MK2 missing ISO layouts in QMK Configurator

### ISSUE THREAD

**Issue by robertholz** [qmk/qmk_firmware#7229]
The QMK configurator is missing the ISO_65 and ISO_70 layouts, these are in gmk_firmware repo but are not avalable on the QMK Configurator site

**Comment by yanfali** [comment]
Someone needs to step up and provide the KLE's and add them to the info.json

**Comment by noroadsleft** [comment]
> Someone needs to step up and provide the KLE's and add them to the info.json

... and also verify the switch matrix for them.
