### ISSUE TITLE
Code Crash

### ISSUE THREAD

**Issue by Anant016** [qmk/qmk_firmware#7247]
Not running Code, after I forked and cloned, the code is not running in my env

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by noroadsleft** [comment]
What code is it that's not running? Is it a keyboard you've flashed with QMK that isn't working? Can you not compile firmware?

There's not enough context here to determine anything.
