### ISSUE TITLE
make: No rule to make target, even when in correct directory?

### ISSUE THREAD

**Issue by ArmsAlpha** [qmk/qmk_firmware#7307]
## Describe the Bug
When running the make command it always comes back saying "No rule to make target '(target)'. Stop. This happens no matter what command I use, even with make commands which are confirmed to work normally. I'm in the correct directory and I believe the commands are valid - I'm practically copy-pasting them. I'm using MSYS2 and I followed the beginner setup guide exactly. I've tried reinstalling everything but it doesn't change anything. https://i.imgur.com/iqFvUEM.png

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system: Windows 10
 - AVR GCC version: avr-gcc.exe (AVR_8_bit_GNU_Toolchain_3.6.1_1752) 5.4.0

 - ARM GCC version: arm-none-eabi-gcc.exe (GNU Tools for ARM Embedded Processors 6-2017-q2-update) 6.3.1 20170620 (release) [ARM/embedded-6-branch revision 249437]

 - QMK Firmware version: 0.7.64

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by fauxpark** [comment]
The keyboard in your image is actually located under the `kingly_keys/` directory, so the make command should be:

```
make kingly_keys/romac_plus:default
```

**Comment by ArmsAlpha** [comment]
Wow that worked! Most stuff I found online for fixes specifically said _not_ to do that so it's strange that it works. Either way, thanks a bunch! I was going insane trying to figure it out.

**Comment by fauxpark** [comment]
Well, our build system is heavily customised specifically for QMK's use case, so a lot of the advice about make commands probably wouldn't apply here.
