### ISSUE TITLE
[Bug] Defaulting to "RGB_BACKLIGHT = yes" for the non-RGB Planck Rev6 breaks keypresses

### ISSUE THREAD

**Issue by justin-sleep** [qmk/qmk_firmware#7315]
Commit cec391df70197a63b12a69c0e08927ecb156e341 breaks keypresses for me on my non-RGB Planck Rev6 (tested with the default keymap). Setting `RGBLIGHT_ENABLE = no` in the rules.mk file for the keymap makes keypresses register again.

**Comment by zvecr** [comment]
Should be fixed by #7330, can you try updating please.

**Comment by justin-sleep** [comment]
After flashing the latest master (6614622) it's working again without the line in `rules.mk`. Thanks!

**Comment by zvecr** [comment]
Perfect, thanks for testing!
