### ISSUE TITLE
[Bug] Can't use ProMicro pin 5 for RGB LEDs

### ISSUE THREAD

**Issue by acid2000** [qmk/qmk_firmware#7324]
I have a WS2812B strip I've attached to PIN 5 of my Pro Micro. I've set RGB_DI_PIN to C6 which I think is the correct pin.
I get a compiler warning:
error: ‘C6’ undeclared (first use in this function)

I've using this as a reference:
qmk_firmware/keyboards/handwired/splittest/promicro/config.h
. 
## Describe the Bug

error: ‘C6’ undeclared (first use in this function)

What #define do I need to make?

**Comment by fauxpark** [comment]
I think some more context is needed here. Would you be able to post your code?

**Comment by acid2000** [comment]
I’m using master with the default key map. Just compile the XT usb converter.

**Comment by fauxpark** [comment]
Ah, I see now. the keyboard's config.h is missing the config_common.h include, but adding that produces a new error, which seems to be about a collision with `E0` in the custom matrix (even though on the 32U4, this pin does not exist; the pindef stuff is not that smart). Prefixing the state enum members with `XT_STATE_` makes it compile, at least. I'll write up a PR in a sec.

Thanks for reporting!

**Comment by acid2000** [comment]
I worry that the bigger problem might be that I’m using the XT codebase which is interrupt based. This might be throwing out the timing. I’ll test your PR anyway
