### ISSUE TITLE
[Bug] Broken link in docs/other_eclipse.md 

### ISSUE THREAD

**Issue by mtei** [qmk/qmk_firmware#7408]
## Describe the Bug

In the `docs/other_eclipse.md`:

```markdown
# Prerequisites
## Build Environment
Before starting, you must have followed the [Getting Started](README.md#getting-started) section corresponding to your system. In particular, you must have been able to build the firmware with [the `make` command](../#the-make-command).
```

There is two link seemd broken:
 * `README.md#getting-started`
 * `../#the-make-command`

## System Information

 - QMK Firmware version: 0.7.79

**Comment by mtei** [comment]
Does anyone know what the right link is?

**Comment by fauxpark** [comment]
I think this sentence should just be reworded to point at the newbs guide instead.

**Comment by noroadsleft** [comment]
I agree with @fauxpark – just rework it to point at https://docs.qmk.fm/#/newbs_getting_started.

**Comment by mtei** [comment]
Correction completed. 👍
