### ISSUE TITLE
[Bug] MT() not working as expected

### ISSUE THREAD

**Issue by stevexyz** [qmk/qmk_firmware#7415]
The “jj28” ([`jj40/stevexyz`](https://github.com/qmk/qmk_firmware/tree/master/keyboards/jj40/keymaps/stevexyz)) is one of the keymaps that put the framework to the limits, but on this I’ve found a strange behavior that in my opinion can be considered to be a bug (for sure is not as the keyboard is expected to react and so I would like to find a solution), and I would expect to work the same in other keyboards too.

To enter in detail,  this is the setup:
 * Space key configured as `MT(MOD_RSFT, KC_SPC)`
 * “A” key (can be any other key) configured simply as `KC_A`

With this configuration if you press and release `space` key, and later on you press `space` and before releasing it (and within a short period) you press again `A` and release both, the result expected is “ A” (space and capital A).

And this is what is happening if you let time pass between the first `space` and the one that is used as modifier for `A`.

The problem appears if the second `space` is being pressed (quickly) just after the release of the first one; the result is then an unexpected “  a“ (space and space and not capitalized "a", meaning the second `space` worked as an `additional key` released instead as the intended `shift modifier`)…

**Comment by bcat** [comment]
I've never understood _why_, but this is expected default behavior. You can set `TAPPING_FORCE_HOLD` to change this (but you lose the ability to repeat the tap code, and I think this also breaks tap dance somehow).

**Comment by stevexyz** [comment]
@bcat yes, you are completely right!!

I don't need tapping toggles, but unfortunately for how it is designed the keyboard now I've lost the possibility to autorepeat keys... But thinking of it seems to me there is no option and this is a limitation that I should live with.

Thank you!
