### ISSUE TITLE
ChibiOS Upgrade Issues

### ISSUE THREAD

**Issue by tzarc** [qmk/qmk_firmware#7452]
Got the ChibiOS upgrade to v19.1.3 working for onekey Proton C and Blue Pill.

There was mention on Discord about issues found during previous upgrade attempts -- this issue is a placeholder for discussion and verification purposes.

**Comment by zored** [comment]
@tzarc do you have an example of this upgrade?

**Comment by tzarc** [comment]
Yep, PR #7597.
There are prebuilt binaries of the default keymaps in a link on the description.

**Comment by zored** [comment]
Sounds cool! But got 403 [here](https://qmk.tzarc.io/chibios-upgrade/planck_ez_default.bin).

**Comment by tzarc** [comment]
Closing as we've just been using #7597 for discussion anyway.
