### ISSUE TITLE
[Bug] Encoder support causing spamming on Iris Rev. 3 & 4

### ISSUE THREAD

**Issue by yanfali** [qmk/qmk_firmware#7487]
@XScorpion2 patch 0f0c73f14a8ffb83a79b51582c0e7465c2411749 on the 15th is causing spamming on the right side of an Iris v3 with default keymap on Page UP and Page Down keycodes. This is an unpopulated PCB. The PCB has no encoder on the right side, only the left side. Seems like the code is making some assumptions about the presence of an encoder.

## Describe the Bug
Before 0f0c73f14a8ffb83a79b51582c0e7465c2411749 everything is fine, after that patch the spamming occurs.

To reproduce:

 - flash commit before - no spam
 - flash commit 0f0c73f14a8ffb83a79b51582c0e7465c2411749 - spam

## System Information

 - Keyboard:  Iris
   - Revision (if applicable):  rev 3
 - Operating system: MacOS Mojave
 - AVR GCC version: 8.3.0

 - ARM GCC version: N/A

 - QMK Firmware version: N/A

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by yanfali** [comment]
Confirmed independently by @nooges

**Comment by yanfali** [comment]
@XScorpion2 since you wrote this patch, do you want to take a stab at diagnosing what's going on? Thanks

**Comment by XScorpion2** [comment]
When you say spamming, is it spamming in one direction? or alternating? or what?

**Comment by nooges** [comment]
I'm getting just PGDN spammed on my board.

**Comment by yanfali** [comment]
yep, if you put it in into https://config.qmk.fm/#test you will see the PGDN key being repeatedly sent. This is just right right half when plugged in. Also happens when you plug in both halves and have trrs between them.

**Comment by nooges** [comment]
Possibly related: https://www.reddit.com/r/olkb/comments/e0enua/flashing_iris_rev_4

**Comment by nooges** [comment]
Okay, getting the same PGDN spamming on Iris Rev. 4 right PCB as well, no spamming with left half.

**Comment by yanfali** [comment]
Should we revert this patch?

**Comment by XScorpion2** [comment]
Probably should revert it. Another users Sol r1 also is showing this issue. I cannot repro this locally so it's taking some time to fix.

**Comment by yanfali** [comment]
interesting, while reverting this, I got into a conflict

**<<<<<<< HEAD
static uint8_t encoder_state[NUMBER_OF_ENCODERS]  = {0};
static int8_t  encoder_pulses[NUMBER_OF_ENCODERS] = {0};
=======
static uint8_t encoder_state[NUMBER_OF_ENCODERS] = {0};
>>>>>>> parent of 0f0c73f14... Updated slave encoder sync to reduce dropped pulses (#7325)**

changing the data type might explain what happened here

**Comment by yanfali** [comment]
I switched it to uint but no change

**Comment by XScorpion2** [comment]
Don't switch thos types. Those are required for the delta calculation to work correctly.

**Comment by yanfali** [comment]
> Don't switch those types. Those are required for the delta calculation to work correctly.

Can you send a PR to revert this temporarily while you fix it? I tried to do it automatically but now it's too deeply embedded

**Comment by XScorpion2** [comment]
Will do

**Comment by XScorpion2** [comment]
@yanfali https://github.com/qmk/qmk_firmware/pull/7498

**Comment by yanfali** [comment]
https://github.com/qmk/qmk_firmware/issues/7055 is being re-opened because we had to revert that fix. Closing this for now.
