### ISSUE TITLE
[Bug] #7195 breaks RGB on crkbd slave

### ISSUE THREAD

**Issue by manna-harbour** [qmk/qmk_firmware#7492]
## Describe the Bug

Prior to #7195 commit b94f6cb116f1628f6d14ff3b1365bcbae6792dea, RGB works on the crkbd slave side with both RGBLIGHT and RGB_MATRIX.  From this commit onwards the slave no longer responds to RGB. All other functions work normally.

## System Information

 - Keyboard:  crkbd with pro-micros
 - AVR GCC version: 4.9.2

 - QMK Firmware version: 0.7.78

## Additional Context

See also https://github.com/qmk/qmk_firmware/pull/7195#issuecomment-555503175

**Comment by zvecr** [comment]
Fixed by #7404.
