### ISSUE TITLE
can't compile Chibios I2CV1 driver under stm32f4 through QMK configurator

### ISSUE THREAD

**Issue by yulei** [qmk/qmk_firmware#7524]
While I compile the keyboard (matrix/noah), the following error occurs:
![image](https://user-images.githubusercontent.com/720475/69924702-b0892400-14e7-11ea-94d7-75c511a6c144.png)

But the latest qmk  compiled successfully under my local machine, and I can't find " qEvt(0x0000);" on the lib/chibios/os/hal/ports/STM32/LLD/I2Cv1/hal_i2c_lld.c. I also checked chibios 17, 18 and 19, but they all did not contains such codes.

The cannonkeys/ortho48 also use the I2CV1, and it compiled successfully through the qmk configurator.

**Comment by yanfali** [comment]
https://github.com/qmk/qmk_configurator/issues/655

**Comment by yanfali** [comment]
Something's weird. This is either a regression or it's not fixed.

**Comment by zvecr** [comment]
![image](https://user-images.githubusercontent.com/16520359/75084328-64161900-5517-11ea-9322-be822b72f4d5.png)

Seems fine now so im going to close this, feel free to reopen if you still see the issue.
