### ISSUE TITLE
Custom Keyboard Help

### ISSUE THREAD

**Issue by jojothepyro** [qmk/qmk_firmware#7578]
I am creating my own custom keyboard using a Teensy 3.2 and was hoping to use your project for the programming the controller. First off is that possible? Second what existing keyboard might be a good example to use as a starting off point? I don't have any LEDs so something without that would be awesome. 

Thanks in advance.
Chris

**Comment by noroadsleft** [comment]
@jojothepyro,

https://github.com/qmk/qmk_firmware/tree/master/keyboards/handwired/onekey/teensy_32

would probably be the best place to start.
