### ISSUE TITLE
Timer Interrupt in QMK with Teensy2.0++

### ISSUE THREAD

**Issue by leon-titan** [qmk/qmk_firmware#7632]
Hi guys, I'm making my own keyboard with QMK on Teensy 2.0++, and I want to use the teensy's timer interrupt (should shorter than 1 microsecond) to do my own stuff. How can I do that in QMK's source code like my keymap.c?

**Comment by drashna** [comment]
I'm guessing that you're talking about the hardware timers? 

If so, it may be worth looking at the audio implementation, as that uses the hardware timers (as does the backlight feature).  It may be a good place to start.
