### ISSUE TITLE
Make can't find some keyboards [Bug] 

### ISSUE THREAD

**Issue by levitanong** [qmk/qmk_firmware#7789]
When I try to `make dztech/dz65rgb:default`, I get:

```
QMK Firmware 0.7.106
make: *** No rule to make target 'dztech/dz65rgb:default'. Stop.
|
|  QMK's make format recently changed to use folder locations and colons:
|     make project_folder:keymap[:target]
|  Examples:
|     make planck/rev4:default:dfu
|     make planck:default
|
```
Even the second example: `make planck:default` yields the same error.

So far, I've tried most of the dztech keyboard:keymaps, and it's the same.

**Comment by fauxpark** [comment]
There are two versions of these dztech boards - `dztech/dz65rgb/v1` etc. use an Arm MCU (STM32F303), and `v2` are AVR (ATmega32U4). They've been refactored recently so you have to know which version you have, and append the correct one to the make command.

**Comment by levitanong** [comment]
That worked, thank you! Perhaps the readme should be updated then :) https://github.com/qmk/qmk_firmware/blob/master/keyboards/dztech/dz65rgb/readme.md

**Comment by fauxpark** [comment]
Good point! I've added it to https://github.com/qmk/qmk_firmware/pull/7664 😃
