### ISSUE TITLE
Bluetooth (Adafruit Ez-Key) Not Working on Planck Rev 4

### ISSUE THREAD

**Issue by throwyourboatsgently** [qmk/qmk_firmware#7844]
I have a Planck Rev 4 which I assembled for Bluetooth use with an Adafruit Ez-Key back in 2017. Back in 2017 I had Bluetooth functionality working with the default keymap and firmware from that time. The keyboard sat on a shelf unused until now because I finally got around to building a case for it. I flashed the most recent firmware and now Bluetooth will pair, but not transmit any keypresses. Everything else works. Unfortunately, I have no idea what version firmware I was running before the upgrade, so rolling back would need to be done in guess and check form. 

I have tried `BLUETOOTH_ENABLE = yes` in rules.mk, which results in Bluetooth seeming to pair correctly, but no keypresses being transmitted.

I have also tried:
`BLUETOOTH_ENABLE = no`
`BLUETOOTH = AdafruitEzKey`

The above results in my backlight only working when the usb cable is plugged in, and a strange clicking noise comes from the keyboard when not plugged in. Bluetooth still pairs, and keypresses don't work. 

Finally, I tried:
`BLUETOOTH_ENABLE = yes`
`BLUETOOTH = AdafruitEzKey`

The results here are the same as the first scenario, Bluetooth pairs, keypresses don't transmit, backlight works as expected, no strange noises.

Any help would be greatly appreciated.

**Comment by latincompass** [comment]
sir,just use the old version QMK,and  complile it  once more
