### ISSUE TITLE
[Feature Request] Add change detection to qmk cformat

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#7884]
Currently `qmk cformat` without any additional arguments runs clang-format against everything. To make it easier and faster to use we should support detecting changes and run only against those files which have been edited.

## Feature Request Type

- [X] Core functionality
- [X] Alteration (enhancement/optimization) of existing feature(s)

## Description

When the user supplies a list of filenames (by running `qmk cformat <file1> <file2> <...> <fileN>`) the behavior should be unchanged.

When the user runs `qmk cformat -a` the command should behave exactly as running `qmk cformat` does today, by running `clang-format` against all core files.

When the user runs `qmk cformat` without any arguments we should use the output of `git diff --name-only origin/master <core directories>` to find the files to format. We should provide a new optional option `--base-branch` (`-b`) to specify a branch other than `origin/master`.

**Comment by skullydazed** [comment]
The behavior is still a WIP. I've written these down as a starting point but if there's an argument for doing it differently please suggest changes. For example, I'm not entirely fond of the name `--master-branch` but I'm wary of the implications of having `user.branch` overriding behavior here.

**Comment by noroadsleft** [comment]
I'd suggest `--base-branch` instead of `--master-branch`, because `base branch` is GitHub's term for the target of a pull request. The default branch of a repo isn't always going to be named `master`. `-b` alias still works IMO though.

**Comment by skullydazed** [comment]
I like that name a lot better.
