### ISSUE TITLE
NK65 Indicator LEDs flash briefly but do not stay lit

### ISSUE THREAD

**Issue by dukrous** [qmk/qmk_firmware#7899]
Since the refactor (https://github.com/qmk/qmk_firmware/pull/7862) was done, NK65 Indicator LEDs now briefly flash and then stay dark whereas before they would stay lit.

If I revert the NK65 code to before the refactor the indicators stay lit, so this appears to be the direct and only cause.

**Comment by zvecr** [comment]
@yiancar can you take a look into this please.

**Comment by yiancar** [comment]
Hello,
Could you please update after https://github.com/qmk/qmk_firmware/pull/7895 ?
Also before you flash, please use the escape method (bootmagic light) to get in the bootloader.

If you have flashed a .bin with before https://github.com/qmk/qmk_firmware/pull/7862 then:
Unplug USB, press hold esc, plug usb, wait 5 seconds, release esc flash:)

**Comment by dukrous** [comment]
Hey,

I did have a .bin before #7862 so I followed the steps. Wiping with a new build produced the same issue. If I revert back to the known good .bin then everything is happy.

**Comment by yiancar** [comment]
Hm thats very weird if you can add me on discord yiancar#1180 so we can do some more debug that would be great :)

**Comment by dukrous** [comment]
Request sent.

**Comment by yiancar** [comment]
Note that this is only happening in LED_OFF, LED_SINGLE_COLOR, LED_DOUBLE_COLOR
