### ISSUE TITLE
How to get TT(Layer) to work - Nyquist Rev 3

### ISSUE THREAD

**Issue by pmc222** [qmk/qmk_firmware#7962]
The toggle function of TT(layer) is not working for me. I can only get it to respond like MO(layer). I've tried adjusting #define TAPPING_TOGGLE to 2 and then 1, with no change. Keymap.c screenshot below. How do I get this to work?

![Nyquist Keymap Github](https://user-images.githubusercontent.com/43119193/72864015-9e826100-3ca0-11ea-9fbf-5047a2f9c302.png)

**Comment by zvecr** [comment]
`#define TAPPING_TOGGLE 2` needs to go in a `config.h`.

Something like `keyboards/keebio/nyquist/keymaps/pmc222/config.h`, which contains:
```c
#pragma once 

#define TAPPING_TOGGLE 2
```

**Comment by pmc222** [comment]
Oh wow, silly mistake. Thank you so much! That fixed the issue.
