### ISSUE TITLE
print 'NUM CAPS SCRL C' and dont't work (ergodox infinity)

### ISSUE THREAD

**Issue by vikke** [qmk/qmk_firmware#7999]
i have problme at ergodox infinity default keymap.

use by usb cable to each keyboard(parallel), it works.
but cascade keyboard, it does'nt work. downstream's ergodox infinity LCD print 'NUM CAPS SCRL C'.

how to do it.

**Comment by frodeanonsen** [comment]
I have a very similar issue with same keyboard, but custom keymap. When I connect through a USB hub, I get the 'NUM CAPS SCRL C', and rows and columns of 'BBBB'. When I connect directly to computer it works, and prints rows/cols of '0000'.

**Comment by drashna** [comment]
Just a heads up, only the part connected directly to the computer will get the "lock" status.
