### ISSUE TITLE
"Comma key + Spacebar" for Russian layout

### ISSUE THREAD

**Issue by ant1k** [qmk/qmk_firmware#800]
Hello, community!

My name is Alex. I'm using Ergodox-EZ, and I would like to ask for your help.

I'll try to describe briefly the problem I have.

In Russian language, if you see comma, in 99% it comes with spacebar after it, so it's obvious to create such automatization "comma + spacebar" in one key press. 
But in Russian layout to create comma key I need to press **Shift+/**. 
Automatization, described above, will help also not to use hard-to-reach-out-Shift-key.

To press "comma + spacebar" in Russian I need to press 4 keys in a row: 
1) Shift (down); 
2) /  (Slash key, or vkBF, or sc035)
3) Spacebar;
4) Shift (up)
(3 and 4 can be interchanged). 

So I want to do such combination in one keypress. 

I ask you to help me to create code for Ergodox software with this combination.

Right now I've created my own layout, and there is \* key for left thumb (you can see it in the link below). This key I would like to use like a "Russian comma + spacebar".
For English layout the same will be - "? (question mark) + Spacebar".

I attached link to my layout:
http://configure.ergodox-ez.com/keyboard_layouts/dmqgwq

Or you can download *.hex file here:
https://drive.google.com/open?id=0B4m2Ft73Sw0yekVWS01obTNfWk0

Appreciate any help with this!
Ready to answer your questions.

**Comment by PureSpider** [comment]
This should easily be possible with a macro: https://github.com/jackhumbert/qmk_firmware#macro-shortcuts-send-a-whole-string-when-pressing-just-one-key

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @ant1k please reopen this or open a new issue.
