### ISSUE TITLE
planck/ez build failed - Makefile ARCH option cannot be blank

### ISSUE THREAD

**Issue by muukii** [qmk/qmk_firmware#8017]
I'm trying to create my settings with qmk_firmware.
Before I used Oryx visual configurator.

And I faced following build error from make command.
Does anyone have ways to solve this problem?

```
$ make planck/ez:muukii
QMK Firmware 0.7.120
Making planck/ez with keymap muukii

lib/lufa/LUFA/Build/LUFA/lufa-sources.mk:32: *** Makefile ARCH option cannot be blank.  Stop.
/bin/sh: .//.build/error_occurred: No such file or directory
make: *** [planck/ez:muukii] Error 1
```

This issue seems related
https://github.com/qmk/qmk_firmware/issues/2086

**Comment by drashna** [comment]
run `make git-submodule`. 

Otherwise, I can't reproduce this.

**Comment by muukii** [comment]
@drashna 
Thanks!
Actually, I tried this command. But it's still stuck.

but, I can forward the next step, I changed the other tag from mater branch.
