### ISSUE TITLE
Creating a dead/diacritica key

### ISSUE THREAD

**Issue by MarkuBu** [qmk/qmk_firmware#8069]
Hi,
I want to create a new minimalistic keyboard for a german layout called PUQ. Originally it uses a diacritica key to type the german characters ä, ö, ü and ß.

http://adnw.de/index.php?n=Main.OptimierungF%c3%bcrDieGeradeTastaturMitDaumen-Shift

First you type the base character like the a and then you hit the diacritica key and get the ä. If you type the A and the diacritica key you get the Ä and so on. But this is done in the driver on the PC. I want to be able to use my keyboard on any PC without the need for a driver. 

How can I create a similar behavior with QMK? 

Regards
Markus

**Comment by drashna** [comment]
It sounds like a lot of that is handled by the OS's layout.

However, some of this can be done with the unicode feature. 
https://docs.qmk.fm/#/feature_unicode

**Comment by MarkuBu** [comment]
yes. I think most of this is done in the os driver. I have to learn more about QMK, thanks.

currently I solved it with an OSL
