### ISSUE TITLE
Combo breaks autoshift

### ISSUE THREAD

**Issue by AnonJohn** [qmk/qmk_firmware#8136]
When autoshift is enabled, it ceases to work for any keys used in a combo. Using process_combo_event. Having only some keys autoshifted is tough! Is there a workaround? Thanks.

**Comment by arturbecker** [comment]
Hi, if anyone reads this, [PR 8591](https://github.com/qmk/qmk_firmware/pull/8591) includes functionality to enable combos+autoshift
