### ISSUE TITLE
data.exe stopped working

### ISSUE THREAD

**Issue by insertnamethere** [qmk/qmk_firmware#816]
Ran the setup twice on a Windows 10 PC and a Windows 7 PC with the same result. Some error about data.exe stopped working. I can't even generate the Win_Check log cause i get the same issue

**Comment by fredizzimo** [comment]
I guess the issue is the same as #782 and #709. And discussed in more detail in #791. 

I will try to see if I can add more checks to the make command in itself. I also think that the install script might need some fixup. But that will happen earliest this weekend.

**Comment by fredizzimo** [comment]
I'm closing this, since there's already other similar issues reported. Also if you are using Windows 10, you can now follow [these instructions](https://docs.qmk.fm/Build-Environment-Setup.html#windows-10).
