### ISSUE TITLE
doc issue of zh-cn translate

### ISSUE THREAD

**Issue by ymzcdg** [qmk/qmk_firmware#8202]
https://github.com/qmk/qmk_firmware/blame/master/docs/getting_started_introduction.md#L7
I don't know if ‘keyboard’ folder exists

**Comment by noroadsleft** [comment]
Ahh, good spot.

The `keyboards` directory was originally named `keyboard`. It should read `keyboards`.

https://github.com/qmk/qmk_firmware/pull/432

**Comment by ymzcdg** [comment]
> 
> 
> Ahh, good spot.
> 
> The `keyboards` directory was originally named `keyboard`. It should read `keyboards`.
> 
> #432

Thanks.
Fix this in https://github.com/qmk/qmk_firmware/pull/8185
Please merge.

**Comment by ymzcdg** [comment]
https://github.com/qmk/qmk_firmware/blame/master/docs/understanding_qmk.md#L133
How can I understand the word"cluecard"?I can't find this word in my dictionary.

**Comment by noroadsleft** [comment]
> 1.https://github.com/qmk/qmk_firmware/blame/master/docs/understanding_qmk.md#L133
> How can I understand the word"cluecard"?I can't find this word in my dictioary.

`cluecard` is an old device by skullydazed, and refers to [clueboard/card](https://github.com/qmk/qmk_firmware/tree/dc79792ab463f614e3aba979dace7d9625b340bf/keyboards/clueboard/card). `cluecard` should probably be capitalized here (`Cluecard`).

> 2.https://github.com/qmk/qmk_firmware/blame/master/docs/understanding_qmk.md#L131
> is the"process"a noun or a verb？

Verb.

**Comment by ymzcdg** [comment]
> 
> 
> > 1.https://github.com/qmk/qmk_firmware/blame/master/docs/understanding_qmk.md#L133
> > How can I understand the word"cluecard"?I can't find this word in my dictioary.
> 
> `cluecard` is an old device by skullydazed, and refers to [clueboard/card](https://github.com/qmk/qmk_firmware/tree/dc79792ab463f614e3aba979dace7d9625b340bf/keyboards/clueboard/card). `cluecard` should probably be capitalized here (`Cluecard`).
> 
> > 2.https://github.com/qmk/qmk_firmware/blame/master/docs/understanding_qmk.md#L131
> > is the"process"a noun or a verb？
> 
> Verb.

If I use Cluecard, I will find keyboard/keymap level functions. Is that right?

**Comment by noroadsleft** [comment]
> If I use Cluecard, I will find keyboard/keymap level functions. Is that right?

Yes. It's used as a sample implementation.
