### ISSUE TITLE
redox wireless, D4 on receiver

### ISSUE THREAD

**Issue by danielo515** [qmk/qmk_firmware#8203]
Hello,
I noticed that the redox wireless has a fourth led on the receiver labeled D4.
However, only three of the leds seems to be controllable from the firmware. Is there any reason for this?
Is it possible to control the fourth led ? It will be a real advantage!

**Comment by noroadsleft** [comment]
@mattdibi Could you please advise?

**Comment by mattdibi** [comment]
Hi,
actually yes it's perfectly usable. [Here](https://github.com/mattdibi/redox-keyboard/issues/24#issuecomment-500109781) I put a few references on how to use it. It's been some time since I wanted to put the 4th led code but never find the time to actually work on it, I'm sorry.

**Comment by danielo515** [comment]
Thanks for the link, I'll take a look at it. What do you mean by the old api? How is this led different from the other three?

**Comment by mattdibi** [comment]
> What do you mean by the old api?

Now there's a [higher level API](https://docs.qmk.fm/#/custom_quantum_functions?id=led-control) to control LEDs but is more readable and easier to use.

> How is this led different from the other three?

It is not. It's exactly the same and should be used the same way.

**Comment by danielo515** [comment]
But is there code to use D4 right now? Like the existing defs to turn on the blue led, magenta color and such?

**Comment by mattdibi** [comment]
> But is there code to use D4 right now? Like the existing defs to turn on the blue led, magenta color and such?

No, there isn't. You need to add the changes I implemented [here](https://github.com/mattdibi/qmk_firmware/commit/e0d24216bcaaed86a148730b6cb74b97d3685f1d) and add your own logic.

Hope this helps.
