### ISSUE TITLE
Pressing Function Keys when another key was held stops registering the keypress.

### ISSUE THREAD

**Issue by jonathantumulak** [qmk/qmk_firmware#823]
Hello!

I have a question regarding this issue. On my TADA68, when press + hold a key (eg. W key), then pressing a function key (FN0 etc., MO()), it stops registering the keypress of the held key.
Does this behavior happen to other keyboards?

**Comment by IBNobody** [comment]
This is the default behavior. It happens because some of the keys trigger a keypress clear event in order to block stuck keys.

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @jonathantumulak please reopen this or open a new issue.
