### ISSUE TITLE
[Feature Request] RAW HID and Console on V-USB

### ISSUE THREAD

**Issue by yiancar** [qmk/qmk_firmware#8320]
Looking at VUSB which is the bases of all the atmega32a and 328p mcus the above 2 features are missing.
Console is especially vital for debugging.
With the help of @fauxpark we have concluded that we need more than the 2 endpoints V-USB shows in all its examples.

This is because 1 endpoint is used to the keyboard HID and the second endpoint for extrakeys and mouse.

A further endpoint would be needed for Console and another for RAW HID.

Any ideas or experiences how to implement this are welcome.

## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

**Comment by hsgw** [comment]
Good timing! I implemented this feature on plaid and keycapsss/plaid_pad.   

https://github.com/hsgw/qmk_firmware/tree/VUSB_HIDRAW

I try to choose mouse/extrakeys or hid_raw for now.

I had done to recognize it as a composite device from OS and send data from the device to the host.    
I succeed to send data from the host to the device on plaid_pad. but I fail it on plaid and tartan.

I think that usb polling rate is not enough to keep correct USB connection, because keyboard_task() and matrix_scan() takes time.

**Comment by hsgw** [comment]
I looked up a bit more this issue, I found strange behavior.

On plaid, interrupt transfer from host uses EP3 and fail, but it uses EP1 on plaid_pad and success.
I think both keyboards use same config and code 🤔

**Comment by yiancar** [comment]
Ill give it a look later tonight
:) even tho I think a lot of people would want extrakeys as a minimum

**Comment by hsgw** [comment]
> extrakeys support
I will try same method as KEYBOARD_SHARED_EP.

**Comment by yiancar** [comment]
I have added you on discord, Have a few questions:)

**Comment by hsgw** [comment]
I read VUSB codes on QMK again, and I realized the following issues.

- "Boot keyboard" and "Boot mouse" is not implemented on VUSB
    - need to handle USBRQ_HID_(SET/GET)_PROTOCOL in vusb.c.
      but I can use plaid in bios
- "Boot mouse" is not implemented on LUFA
    - on ChibiOS, boot keyboard and mouse is implemented

And 
- Adding ep4 to VUSB is possible.
    - from discussion with @yiancar

Therefore, I will try implemented following method.

- EP1 is keyboard 
- EP3 is shared by mouse/extrakey/hid_raw
- EP4 is reserved for console

First, I will make a PR to add hid_raw feature soon.

If you have any suggestion, please advise me!

**Comment by yiancar** [comment]
Small update as well:
Looks like we have managed to get 32byte reports in and out! I will be testing this with VIA and see how it goes.

From a brief look on adding EP4 (and a very helpful email from the authors of V-USB) it looks like it can be done. However it will mean spinning our own version of the library, something that might harm future code maintenance.

Due to the above, I think that @hsgw proposal is a very reasonable compromise.
As boot keyboard was not there anyway, add an option to share EP1 with mouse/extrakeys. This opens up the route to hid_raw. If there is further time and will we can try opening up EP4.

**Comment by fauxpark** [comment]
> However it will mean spinning our own version of the library, something that might harm future code maintenance.

That's why I'd like to get #8321 in before any of this work is done; we can then fork the V-USB repo to qmk/v-usb and apply our modifications there while still being able to pull down any updates from upstream.

**Comment by yiancar** [comment]
Any idea when that will be done? We can keep testing in the meantime

**Comment by fauxpark** [comment]
It's ready to go, just needs more eyes on it. Will also need https://github.com/qmk/qmk_compiler/pull/62 merged & deployed at the same time so as to not break Configurator.

**Comment by hsgw** [comment]
## Tested keyboard
- plaid
- keycapsss/plaid_pad
- tartan

## Test
1. send 32bytes data from device to host.
2. send 32bytes data from host to device.

## Device
I made test keymap for plaid, plaid_pad and tartan.
https://github.com/hsgw/qmk_firmware/tree/vusb_raw_hid_test

### Device settings
- Disable mouse and extrakey
- Set `RAW_ENABLE = yes`
- `usbconfig.h' in your keyboard 
```
#define USB_CFG_IMPLEMENT_FN_WRITE      1
```
 
## Host
My small script with webhid on chrome.
https://hsgw.github.io/webhid_qmk/

And hidpytoy is useful too. 
Please set send and receive data length to **32**.
https://github.com/todbot/hidpytoy

**Comment by yiancar** [comment]
This has been done and can be closed
