### ISSUE TITLE
[Documentation] Need document on selecting and installing the correct avr-gcc version

### ISSUE THREAD

**Issue by skullydazed** [qmk/qmk_firmware#8344]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior
- [x] Documentation

## Description

As described in #8338 we should have a page describing why avr-gcc 8.x is required and why 9.x is problematic. It should then be followed with instructions for downgrading in different environments.

**Comment by christopherjanzen** [comment]
I just got hung up on this issue the other day after accidentally updating avr-gcc via Homebrew. Providing instructions for fixing that could be as simple `brew unlink avr-gcc` then `brew link avr-gcc@8`
