### ISSUE TITLE
Can atmega32a drivers ws2812 by bitbang?

### ISSUE THREAD

**Issue by tinggua** [qmk/qmk_firmware#8375]
Hello, I have made a keybord with atmega32a. It has the rgb underglow, and i connected ws2812s with mcu's io pin directly(just like many atmega32u4).But now i find the ws2812s can not work. So is 32a not supported bitbang driver the ws2812?
Thank you for your answer .

**Comment by mtei** [comment]
I feel it is clock speed matter.

https://github.com/qmk/qmk_firmware/blob/2b66acf04a82bc571ac5f545be7c43af722d6704/drivers/avr/ws2812.c#L93-L101

**Comment by yulei** [comment]
ps2avr used an attiny to drive ws2812, so you need to buy this from author of ps2avr or write your own driver on attiny to translate i2c commands from atmega32a to ws2812 signal sequence. If your made the keyboard by yourself, why not just using atmega32u4?

**Comment by yiancar** [comment]
yes they can, they work just fine and I have tried this.
I think this issue can be closed

**Comment by zvecr** [comment]
From #8598, I had to modify the existing AVR implementation. 32a partially shares the same register config so i cant see how the existing code would work without the same changes.

**Comment by yiancar** [comment]
is this about entering the bootloader?

**Comment by zvecr** [comment]
Verified working on <https://www.rgbkb.net/products/pan-keyboard-diy-kit> by Legonut.
