### ISSUE TITLE
Please add more information to read.me

### ISSUE THREAD

**Issue by Zik42** [qmk/qmk_firmware#8379]
Please add info how to go boot mode on v1 \ v2, I dont know...

**Comment by Erovia** [comment]
Would you please be so kind to elaborate a little bit on this?
QMK currently supports nearly a thousand keyboards, sooo, we will not be able to help you if you provide zero information.

**Comment by Zik42** [comment]
Sorry, It was bad issue, booting via dztech/dz60rgb_ansci/v1 - needed press reset button \ hold esc while plug back.
