### ISSUE TITLE
OSL and key with modifier not working as intended

### ISSUE THREAD

**Issue by npoirey** [qmk/qmk_firmware#838]
Hello,

I have a weird behavior when using OSL and tring to press a key with a modifier (shift or anything)

How to reproduce :
- set a base layer defining OSL(1) on one key in layer 0
- on layer 1, have a key without modifier, like KC_EQL (case 1)
- on layer 1, have a key with a modifier, like ALTG(KC_2) for <²> (case 2)
- keep OSL(1) pressed and type the key of case 1, <=> is produced as intended
- keep OSL(1) pressed and type the key of case 2, <²> is produced as intended
- type OSL(1), then type the key of case 1, <=> is produced as intended
- type OSL(1), they type the key of case 2, **nothing is produced**

When looking at an event tester, i can see that the last case only produce the modifiers, in my exemple it looks like that: 
![image](https://cloud.githubusercontent.com/assets/6019178/19616936/b904eac4-9821-11e6-958a-8bac2c0a8496.png)

when the OSL is kept down, the following is produced :
![image](https://cloud.githubusercontent.com/assets/6019178/19616939/d5a2618e-9821-11e6-9021-56e5d493b8d3.png)

edit:
in my keymap the key is defined like this : ALTG(KC_2)
This behavior is reproduced with S(kc) and any quick definition with shift, like KC_AMPR

**Comment by npoirey** [comment]
Got a workaround, not thebest solution but at least it works almost as intended 👍 

		/**
		 deactivate layer on keypress if it was locked
		**/
		static macro_t *_one_shot(keyrecord_t *record, uint16_t code, uint16_t controlled, uint16_t shifted, uint16_t altgred ){
		  if (record->event.pressed) {
		    if( layer_locked ){
		      layer_locked = 0;
		      layer_off(1);
		    }
		    if(controlled) register_code(KC_LCTL);
		    if(shifted) register_code(KC_LSHIFT);
		    if(altgred) register_code(KC_RALT);
		    register_code (code);

		    unregister_code(KC_LCTL);
		    unregister_code(KC_LSHIFT);
		    unregister_code(KC_RALT);
		    unregister_code (code);
		    clear_keyboard();
		  } else {
		  }
		  return MACRO_NONE;
		}

		/**
		 deactivate layer on keypress if it was locked
		**/
		static macro_t *one_shot(keyrecord_t *record, uint8_t code, uint8_t shifted, uint8_t altgred ){
		  return _one_shot(record, code, 0, shifted, altgred);
		}

and in action_get_macro

    case OSL1: //activate layer 1, if typed (<150 ms), stay active until another key is pressed
          if (record->event.pressed) {
            layer_on(1);
            key_timer2 = timer_read(); // if the key is being pressed, we start the timer.
          } else {
            if (timer_elapsed(key_timer2) < 150 && layer_locked != 1) {
              layer_locked = 1;
            } else {
              layer_locked = 0;
              layer_off(1);
            }
          }
        break;
     case M_EXP1 : one_shot(record, KC_1,    1, 1); break; // ¹

the downside is that i have to define a macro for every key on layer 1, otherwise it won't turn off.

I'm not blocked anymore so you can close this ticket if you want.

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @npoirey please reopen this or open a new issue.
