### ISSUE TITLE
Can't find PM port

### ISSUE THREAD

**Issue by adcampbell** [qmk/qmk_firmware#8384]
I don't know if this is better off posted in a pro micro forum or not, so my apologies if this is the wrong place.

I have a pro micro on a redox. I initially used the cli to flash the default redox to the board, and got a success message. None of the keys worked, so I edited the hex file and tried again. This time, the COM port would not show up when I reset the board. Instead, the board shows up as a "USB Composite Device". No program (cli, qmk toolbox, avrdudess) can find it to flash it. I tried uninstalling the drivers, redoing it on linux, and various other things, and cannot get the PM to be reached. Is there a way to clear it and start over? It's an atmega32u4 if that wasn't clear. I tried searching and couldn't find this particular issue anywhere. Thank you for your time.

**Comment by Erovia** [comment]
Hi!
What do you mean by 

> edited the hex file and tried again

Could you please describe what and how you did this?

**Comment by adcampbell** [comment]
Sorry, I meant that I edited the keymap and created a new hex file - so not the default redox one.

**Comment by Erovia** [comment]
What happens if you reset it? How is it identified in the `lsusb` output?
It should be something like `2341:0036 Arduino SA Arduino Leonardo`

**Comment by adcampbell** [comment]
I'm using virtualbox to run linux in a vm. I have to attach a usb item. When I attach it and run lsusb the output is "Bus 001 Device 005: ID feed:0000". If I reset it virtualbox drops the attachment. 

I'm using a GUI application called USBDeview by nirsoft to see it using windows. Please see attached picture. "The Redox Keyboard" at the bottom seems to be this microcontroller. 
![redox_usb](https://user-images.githubusercontent.com/15174896/77007995-4d56bc80-6933-11ea-9397-04097684ce24.png)

**Comment by fauxpark** [comment]
That device is the actual keyboard; what you want is the bootloader device which will enumerate with a different VID and PID when you short RST and GND. Pro Micro bootloaders will only stay in bootloader mode for only about 8 seconds so you'll want to set up the VirtualBox passthrough beforehand.

**Comment by adcampbell** [comment]
I set it up but it just disappears from lsusb output when i reset it.

**Comment by fauxpark** [comment]
What does your passthrough device look like? Note that when you reset, it will show up as a completely different device, so if you've set it up to look for the FEED:0000 device, that won't work. For example:
![image](https://user-images.githubusercontent.com/4781841/77022500-dfb39a80-69dd-11ea-8f23-f9f998ff2142.png)

**Comment by adcampbell** [comment]
![feed](https://user-images.githubusercontent.com/15174896/77031606-16eb6280-6970-11ea-83dd-ade002129b03.jpg)

**Comment by fauxpark** [comment]
It should turn up in Device Manager, under Ports.
![image](https://user-images.githubusercontent.com/4781841/77031923-1ba72980-69f7-11ea-893b-bbcb86e485d1.png)

**Comment by Erovia** [comment]
The problem is that once you reset the PM, it will show up as a new device on the host which is not yet passed through to the vm. But the PM only stays in bootloader mode for a few secs, so by the time you pass it through, it already booted into firmware.

Imho, you'll have an easier time if you flash it on either Windows or boot into a Linux liveusb.

**Comment by adcampbell** [comment]
@Erovia I flashed it on windows the first time, running qmk on linux was just my attempt to fix my issue. Though now I know it won't work easily on my linux vm.

@fauxpark The crux of my issue is that it will never show up under ports when resetting. No program or CLI has been able to find it.

**Comment by adcampbell** [comment]
At this point I just believe it to be a faulty PM. I gave up and ordered a few new ones and had zero issues with them when following the same steps. Closing
