### ISSUE TITLE
"How to use Github" link in getting started docs is dead. Where should it be pointing at?

### ISSUE THREAD

**Issue by christopherjanzen** [qmk/qmk_firmware#8402]
The page in question: [Setting up your QMK Environment](https://docs.qmk.fm/#/newbs_getting_started?id=set-up-qmk)
Dead link: [how to use Github](https://docs.qmk.fm/#/getting_started_github)

I'm happy to correct the link but I'm not sure where it's supposed to point to. I'm guessing [Git Best Practices](https://docs.qmk.fm/#/newbs_git_best_practices)?

**Comment by noroadsleft** [comment]
I think we meant to move that doc's contents somewhere else, but the file was deleted without the content getting saved elsewhere.

For now, we've restored the deleted file, though it may be updated or deleted again (with a replacement, this time!) in the coming days.

Thanks for reporting!

https://github.com/qmk/qmk_firmware/commit/904610718332d4526248221edc91be76f012c0e0
