### ISSUE TITLE
Auto-Shifted Macros

### ISSUE THREAD

**Issue by ThePreviousOne** [qmk/qmk_firmware#8551]
I followed the instructions on #7840 to get custom shift keys, but how could I get it to work with Auto Shift?

``` 
switch (keycode) {
		case C_1 ... C_X:
			if (record->event.pressed) {
        uint8_t mod_state = get_mods() & MOD_MASK_SHIFT;
				//uint16_t shifting_timer = timer_read();
        clear_mods();
        if(mod_state) {
					tap_code16(alt_keymap[1][keycode - C_1]);
        } else {
					tap_code16(alt_keymap[0][keycode - C_1]);
        }
        set_mods(mod_state);
      }
      break;
```
I tried changing the `if` to 
```if (modstate | timer_elapsed(shifting_timer) > AUTO_SHIFT_TIMEOUT)```

but that didn't work. I also tried adding

```
if (timer_elapsed(shifting_timer) > AUTO_SHIFT_TIMEOUT) {
    tap_code16(alt_keymap[1][keycode - C_1]);
}
```
to the `else` statement, which also didn't work.

I'm still a beginner with QMK and don't know what else to try

**Comment by IsaacElenbaas** [comment]
You can clone from [here](https://github.com/IsaacElenbaas/qmk_firmware/tree/as_custom_shifts) if #8127 still isn't merged. See [here](https://github.com/qmk/qmk_firmware/pull/8127/files?short_path=4bf35e8#diff-4bf35e820a51ecaf4693669762ae1efa) for usage.
