### ISSUE TITLE
chaining OSM

### ISSUE THREAD

**Issue by chrde** [qmk/qmk_firmware#856]
I would like to chain modifiers (shift, alt, ctrl) without keeping them pressed, e.g:
 ctrl+ shift + a  -> 3 key strokes, no need to hold ctrl or shift key

I've tried with OSM/OSL but it doesn't do the trick, since the first modifier fires off the moment the second key (modifier) is pressed. Is there an easy way to achieve this?

**Comment by algernon** [comment]
There is no easy way at the moment, you'd have to dive into `tmk_core/common/action.c`, and within it, into `process_action`, the parts for the `ACT_LMODS_TAP`/`ACT_RMODS_TAP` cases.

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @chrde please reopen this or open a new issue.
