### ISSUE TITLE
Allow split keyboards on chips without USB like 328p

### ISSUE THREAD

**Issue by triron-pixel** [qmk/qmk_firmware#8592]
Trying to make a split keyboard with a 328p chip. And the software does not compile due to the fact that split_util.c use USB registers. So make this patch for undef USB stuff.

[0001-split-for-chip-without-usb.patch.txt](https://github.com/qmk/qmk_firmware/files/4397818/0001-split-for-chip-without-usb.patch.txt)

**Comment by chubylive** [comment]
I am trying to do something similar. I think there is more usb stuff that needs to either taken out or defined out.

**Comment by zvecr** [comment]
@chubylive lufa isnt used on a 328p (or 32a) so thats the wrong rabbit hole.

I've raised #8594 but it still has transport requirements.
* serial is currently 32u4 only
* i2c compiles but is untested

**Comment by yiancar** [comment]
i2c should work I use it for other things

**Comment by zvecr** [comment]
@yiancar In this context, its i2c_slave that would potentially cause issues, and to my knowledge that is currently untested.

**Comment by yiancar** [comment]
I have tested i2c_slave as well. mostly the AVR library takes cares of the abstraction here for most 8bit controllers

**Comment by zvecr** [comment]
Good to know!. But given the solution as a whole doesn't compile, i'm still going to stand by my "i2c transport code is untested" stance.

**Comment by yiancar** [comment]
yep I have no clue about the rest just that you can send with our libraries something from one 328p master to a slave
