### ISSUE TITLE
[Bug] Console Descriptor shoud be one way

### ISSUE THREAD

**Issue by yiancar** [qmk/qmk_firmware#8593]
## Describe the Bug

Looking at the console descriptor it has both an input and output section.
This is probably because of the rawhid code from PJRC. In my understanding we use console as a one way communication tool. From the keyboard TO the host. If this is true, and if qmk-toolbox is only listening, I suggest we modify the descriptors to show that only output exists.

In a quick look it looks like console code does not handle any input anyway, please correct me if I am wrong

## System Information

 - Keyboard:  
   - Revision (if applicable):  
 - Operating system:
 - AVR GCC version: 

 - ARM GCC version: 

 - QMK Firmware version:

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [ ] Karabiner
   - [ ] Other:

**Comment by yiancar** [comment]
Ok initial check:
https://github.com/yiancar/qmk_firmware/commit/4ecea11aaf7e4457cabef0f9a806e364caa4a64c

Chibios:
Removed the output hid descriptor, removed the input handling. All good.
Trying to remove the endpoint is not as straight forward.

Removing `CONSOLE_IN_EPNUM` starts to cause issue as in usb_main.c the macro QMK_USB_DRIVER_CONFIG need the epnum. Furthermore `out_ep_config` is always in the macro. Any ideas how to exclude it without making everything ugly?

**Comment by drashna** [comment]
This was fixed in 22304.
