### ISSUE TITLE
Canceling shifted key with shift

### ISSUE THREAD

**Issue by jcoleman** [qmk/qmk_firmware#861]
If I define a key as `KC_UNDS` (which is really `LSFT(KC_MINS)`) I, as expected, get an underscore when typing it. But when I also hold down the shift key, I don't get a minus.

Is there a way to make the key just invert so that shifting types the minus and a regular keypress types the underscore?

**Comment by algernon** [comment]
There is a not-so-simple workaround. You use `LSFT(KC_MINS)` as per usual.

But, in `process_record_user`, you do two things:

- If the key being pressed is `Shift`, you set a flag indicating so (and clear it upon release).
- If the key being pressed is `LSFT(KC_MINS)`, then you check the flag we tinkered with above.
  - If the flag is set, that means that your `KC_UNDS` and `Shift` keys are pressed at the same time. In this case, you temporarily unregister `Shift`, register `KC_MINS`, re-register `Shift`, and return.
  - If the flag is not set, proceed as usual.

This should get you the desired behaviour.

The code would look something like [this](https://gist.github.com/algernon/2f1dcd217277c8872842329582649118). The code is not perfect, it fails if both shifts are pressed along with `KC_UNDS`. Correcting that is left as an exercise for the reader.

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @jcoleman please reopen this or open a new issue.
