### ISSUE TITLE
USB2USB(Hasu) - Using keycode to enter bootloader

### ISSUE THREAD

**Issue by duoshock** [qmk/qmk_firmware#8611]
Is there a way to enter bootloader without using the physical switch on the converter?
I've tried reset keycode + bootmagic (space+b) that's didn't work.

Is it possible at all?

**Comment by vomindoraan** [comment]
Both Bootmagic and Command are disabled by default on this converter. Try adding `COMMAND_ENABLE = true` to your `rules.mk` and resetting using LShift+LShift+B.

**Comment by duoshock** [comment]
> Both Bootmagic and Command are disabled by default on this converter. Try adding `COMMAND_ENABLE = true` to your `rules.mk` and resetting using LShift+LShift+B.

Thanks for reply. I just tried it, with 'COMMAND_ENABLE = true' and 'BOOTMAGIC_ENABLE = yes', it reset the keyboard, but it won't stay in the bootloader for flashing,

Is there a way I can trigger the commend with simple keycode in layer? i.e. Fn2+Esc = enter bootloader.

**Comment by duoshock** [comment]
I've also tried 'RESET' keycode, it's doing the same as above. :(

**Comment by vomindoraan** [comment]
My bad, it should be `COMMAND_ENABLE = yes`, not `COMMAND_ENABLE = true`. But if the board stays in bootloader mode after being reset, it may be a quirk of the converter after all. Some ARM boards behave the same way and don't jump into the bootloader properly unless the physical reset switch is used.

**Comment by duoshock** [comment]
That's a shame. I was thinking of making a custom usb2usb for Norbaforce. that will be very inconvenient to unscrew the backplate to flash.

Thanks for your help :)

**Comment by vomindoraan** [comment]
Could you open QMK Toolbox and tell me what happens and what shows up in the console when you press LShift+RShift+B to reset the board while it's plugged in?

One final thing you could try is disabling Command, setting `BOOTMAGIC_ENABLE = lite` and adding the following to your `config.h`:
```c
// Location of the Esc key in the matrix (row 2, col 9)
#define BOOTMAGIC_LITE_ROW    2
#define BOOTMAGIC_LITE_COLUMN 9
```
Then compile and flash the board. Once you've done this, unplug the board and hold Esc while plugging it back in. If all goes well, it should go into bootloader mode and stay there.

**Comment by duoshock** [comment]
Not sure did I do it right, It didn't recognise the converter with the default setting until I added 'CONSOLE_ENABLE   = yes'.
Once it recognised, I pressed LShift+RShift+B, then it printed 'Jumping to bootloader...', and no further message after that.
Windows detected there's a usb disconnected and reconnected within about a second, then the keyboard work as normal.

See screen cap here
![O3w8i0d](https://user-images.githubusercontent.com/33636898/77951604-3c5a6380-72c2-11ea-8b2b-5231fa99c935.png)

After changed it to 'BOOTMAGIC_ENABLE = lite' and added theose 2 lines of code to keymaps\default\config.h
it's still doing the same - disconnected and connected soon after, didn't stay in bootloader.

**Comment by zvecr** [comment]
Project seems to default to the caterina bootloader, which might not be correct in this instance. Tried `BOOTLOADER = atmel-dfu` in rules.mk?

**Comment by duoshock** [comment]
> Project seems to default to the caterina bootloader, which might not be correct in this instance. Tried `BOOTLOADER = atmel-dfu` in rules.mk?

That's it! It works!
LShift+RShift+B works as intended.
Bootmagic to bootloader (space+B) works as well!

Thank you so much guys!

**Comment by zvecr** [comment]
Raised #8613
