### ISSUE TITLE
Linux udev rules for flashing Pro Micro with qmk cli

### ISSUE THREAD

**Issue by NickyTope** [qmk/qmk_firmware#8655]
Hey, I have just succesfully flashed my Pro Micro based keyboard after much trial and error and would like to suggest an addition to the following page: https://github.com/qmk/qmk_firmware/blob/master/docs/faq_build.md 

In addition to the udev rules listed, I needed one for flashing..

```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2341", MODE:="0666"
```

I added this rule to 52-tmk-keyboard.rules but it probably warrants having it's own file..

I found the device id needed by resetting the pro micro and immediately running `lsusb`

after this was added I could then flash with qmk cli, hoping this helps someone else as for all my searching I could only see people using `sudo make ...` as a solution

**Comment by Erovia** [comment]
Thanks for the suggestions, I was just working on it.
My suggestion would (and will) be to add this rule to **etc/udev/rules.d/55-caterina.rules:**
```
SUBSYSTEMS=="usb", ATTRS{idVendor}=="2341", ATTRS{idProduct}=="0036", TAG+="uaccess", RUN{builtin}+="uaccess"
```
This will add an ACL to the device for your user instead of making it world-writable.

**Comment by NickyTope** [comment]
Looks great, thanks!

**Comment by Erovia** [comment]
The docs have been updated.
