### ISSUE TITLE
docs/coding_conventions_c.md VS clang-format

### ISSUE THREAD

**Issue by mtei** [qmk/qmk_firmware#8664]
In docs/coding_conventions_c.md it says the following:

https://github.com/qmk/qmk_firmware/blob/59188bf29d10cdf0500811a68f611ab6a724494f/docs/coding_conventions_c.md#L23

However, the .clang-format is set up as follows:
https://github.com/qmk/qmk_firmware/blob/59188bf29d10cdf0500811a68f611ab6a724494f/.clang-format#L15

If you follow docs/coding_conventions_c.md, the .clang-format setting should look like this:
```
IndentPPDirectives: BeforeHash 
```

And I prefer the provision in docs/coding_conventions_c.md.

**Comment by vomindoraan** [comment]
Would it make sense to update the coding conventions to match `.clang-format`, for the time being? This may help prevent further confusion until we are ready to fully transition to `BeforeHash`.

**Comment by fauxpark** [comment]
Yeah, a bit of explanation on the current situation is probably called for.
