### ISSUE TITLE
More than 3 mousekeys speed options

### ISSUE THREAD

**Issue by Flutterlice** [qmk/qmk_firmware#8868]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [X] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

I use mousekeys daily to reduce required movement of my right hand between mouse and keyboard for occasional need in mouse cursor, switching speed settings 10 times a minute for gradual precision / speed trade off. 

But personally i find existing 3 speed settings very limiting for comfortable mouse cursor movement that is on par with using mouse itself. Adding just 2 more (or even better - somehow not hard limiting number of speed settings at all) would benefit my established workflow greatly.

**Comment by nathanvercaemert** [comment]
I can work on this! Quick question for confirmation, though: do 'c' and 'w' respectively refer to cursor and wheel in mousekey.c?
