### ISSUE TITLE
Hasu USB2USB with AT90USB1286 firmware won't compile

### ISSUE THREAD

**Issue by duoshock** [qmk/qmk_firmware#9027]
I'm thinking of making a usb2usb with AT90USB1286, which allow me to have all the functions I need. Also, bigger EEPROM that allows me to have more than 1 layer with VIA enabled!

I tried to compile the firmware with 'MCU = AT90USB1286' in rule.mk and it won't compile, with error 'Please define board in avrpins.h' (see sceenshot)

Any pointers?

![image](https://user-images.githubusercontent.com/33636898/81088328-b8b01a00-8ef2-11ea-9243-a34403524e88.png)

**Comment by fauxpark** [comment]
The MCU name must be lowercase for AVRs.

**Comment by duoshock** [comment]
> The MCU name must be lowercase for AVRs.

tried it. same error. :(

**Comment by fauxpark** [comment]
Ah, you'll also need to add `#define CORE_TEENSY` in your config.h.

**Comment by duoshock** [comment]
It works! thank you so much!
