### ISSUE TITLE
USB report IDs in "report.h"

### ISSUE THREAD

**Issue by PeterMortensen** [qmk/qmk_firmware#9028]
By inspection, with no other context from here: Are the report IDs in "/tmk_core/common/report.h" correct?

    enum hid_report_ids {
        REPORT_ID_KEYBOARD = 1,
        REPORT_ID_MOUSE,
        REPORT_ID_SYSTEM,
        REPORT_ID_CONSUMER,
        REPORT_ID_NKRO
    };

I would expect something like:

    enum hid_report_ids {
        REPORT_ID_KEYBOARD  = 2,
        REPORT_ID_MOUSE     = 1,
        REPORT_ID_SYSTEM    = 5,
        REPORT_ID_CONSUMER, = 4
        REPORT_ID_NKRO      = 8
    };

Source: *[Arduino HID Project](https://github.com/NicoHood/HID/blob/master/src/HID-Settings.h)*

**Comment by fauxpark** [comment]
The report ID is just a unique ID to differentiate reports where they share the same endpoint. They can be pretty much whatever you want.

From the [HID Device Class Specification, Section 5.6](https://usb.org/sites/default/files/documents/hid1_11.pdf#page=27):
> However, some devices may have multiple report structures on a single endpoint, each representing only a few data fields. For example, a keyboard with an integrated pointing device could independently report “key press” data and “pointing” data over the same endpoint. Report ID items are used to indicate which data fields are represented in each report structure. A Report ID item tag assigns a 1-byte identification prefix to each report transfer. If no Report ID item tags are present in the Report descriptor, it can be assumed that only one Input, Output, and Feature report structure exists and together they represent all of the device’s data.
