### ISSUE TITLE
[Feature Request] Dual function keys only triggered by other keyboard half

### ISSUE THREAD

**Issue by Ofenhed** [qmk/qmk_firmware#9040]
## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

It would be nice with a second type of the dual function key (LT layer buttons and personally more important dual function modifier keys). This new key would only be triggered if it's pressed in combination with a key on the other keyboard half.

To the user, this could present as _Strict Layer Toggle (SLT)_ and _Strict Dual-function keys_ in the interface, where these keys have this new behavior.

### Example

Let `Z` and `/` be the _Strict Dual-function Ctrl key_ in the following scenarios:

- `Z`+`C` will always become `zc` (independent of timing rules)
- `/`+`C` will be `^c` (depending on timing rules)
- `Z`+(`P` then `C`) will be `^p^c` (as Ctrl was activated by P and not released before C was pressed)

I think this would limit the amount of mistakes that dual function keys bring.

**Comment by manna-harbour** [comment]
Here's a partial implementation: [Bilateral Combinations](https://github.com/manna-harbour/qmk_firmware/blob/bilateral-combinations/docs/tap_hold.md#bilateral-combinations).
