### ISSUE TITLE
No mention of putting into bootloader mode when jumping to linux flashing instructions.

### ISSUE THREAD

**Issue by mcp292** [qmk/qmk_firmware#9074]
When following [this step](https://docs.qmk.fm/#/newbs_flashing?id=flashing-your-keyboard) and jumping to the Linux section, there is no mention of putting the keyboard into bootloader mode. It is counter intuitive to go back up and read for it in the section we were told to skip.

**Comment by fauxpark** [comment]
I've made a PR to improve the flow of this page, see above :)

**Comment by mcp292** [comment]
That's awesome! Your quick, what a great community. Bunch of happy typists!
