### ISSUE TITLE
Specify qmk home folder not documented in qmk setup.

### ISSUE THREAD

**Issue by mcp292** [qmk/qmk_firmware#9075]
The ability to specify a new home location with `qmk setup -H <location>` is not documented. A blue note box right under [`qmk setup`](https://docs.qmk.fm/#/newbs_getting_started?id=set-up-qmk) would be very helpful.

**Comment by DweebsUnited** [comment]
Thank you for finding this! There is no documentation on how to change the home folder, so I completely agree it would be nice to put this in the documentation somewhere.

I would also appreciate it if the location of the QMK config file (that specifies your home directory) was included in the documentation... 

I will see how difficult it is to create a pull request to rectify these.
