### ISSUE TITLE
[Bug] Calling lcd_clrsrc() from keyboard.c raises error

### ISSUE THREAD

**Issue by RichardMiruGeorge** [qmk/qmk_firmware#9085]
Trying to interface my LCD with QMK, im following the instructions provided in https://github.com/qmk/qmk_firmware/blob/master/docs/feature_hd44780.md

with HD44780_ENABLE = yes in the rules.mk raises following issue:
The following lines in my keyboard.c:

void matrix_init_kb(void) {
    // put your keyboard start-up code here
    // runs once when the firmware starts up

    matrix_init_user();
    lcd_clrsrc();
//    lcd_init(LCD_DISP_ON_CURSOR_BLINK);
}

cause the error:
-----------------------------------------------------
qmk_firmware$ make kb:default
QMK Firmware 0.8.153
Making kb with keymap default

avr-gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Size before:
   text	   data	    bss	    dec	    hex	filename
      0	  22382	      0	  22382	   576e	.build/kb_default.hex

Compiling: keyboards/kb/kb.c                                                                       keyboards/kb/kb.c: In function ‘matrix_init_kb’:
keyboards/kb/kb.c:10:5: error: implicit declaration of function ‘lcd_clrsrc’ [-Werror=implicit-function-declaration]
     lcd_clrsrc();
     ^
cc1: all warnings being treated as errors
 [ERRORS]
 | 
 | 
 | 
tmk_core/rules.mk:383: recipe for target '.build/obj_kb_default/keyboards/kb/kb.o' failed
make[1]: *** [.build/obj_kb_default/keyboards/kb/kb.o] Error 1
Make finished with errors
Makefile:560: recipe for target 'kb:default' failed
make: *** [kb:default] Error 1

**Comment by fauxpark** [comment]
Looks like the documentation is wrong, the function name is actually `lcd_clrscr()`. If that still doesn't work, try adding `#include "hd44780.h"` at the top of the keyboard.c.

**Comment by RichardMiruGeorge** [comment]
ok now i feel silly - that works! - thanks for doing the typo spotting for me.
For posterity: #include "hd44780.h" is unnecessary as its included in  tmk_core/common/keyboard.c when the appropriate enable is set in rules.mk
