### ISSUE TITLE
Building qmk firmware with custom compiler and linker flags

### ISSUE THREAD

**Issue by heshananupama** [qmk/qmk_firmware#9120]
Hi. 
For my research work I needed to build firmware with different compiler flags. For examples I need to build the same firmware with different optimization levels and different debug levels. How could I change these settings and then invoke `qmk compile` command? Is there a place or file that I could change these compiler flags? I tried going through the MakeFIle and it looks much complex and I could not find out a place to change the compiler and linker flag options. Is there any other file I could change these settings. Thank you very much for the help

**Comment by elfmimi** [comment]
QMK is complex but relatively well organized.

You can find the variable related to optimization level here.
https://github.com/qmk/qmk_firmware/blob/38d2c8cedf9f9f43b5ba372ffd38ccc7cc96be15/tmk_core/rules.mk#L49

And here is another one related to link-time-optimization, or lto  if you like.
https://github.com/qmk/qmk_firmware/blob/38d2c8cedf9f9f43b5ba372ffd38ccc7cc96be15/tmk_core/common.mk#L156

In a use case like you described, I guess it is better to use make command directly.
for eample `make planck/rev6:default OPT=2 LINK_TIME_OPTIMIZATION_ENABLE=yes`

and you can confirm what was the actual compiler flags used by looking into the following files.
.build/obj_planck_rev6_default/cflags.txt
.build/obj_planck_rev6_default/cxxflags.txt
.build/obj_planck_rev6_default/asflags.txt
.build/obj_planck_rev6_default/ldflags.txt

**Comment by heshananupama** [comment]
Thank you very much!
