### ISSUE TITLE
[Feature Request] Cowork with STM32CubeIDE

### ISSUE THREAD

**Issue by YunyushuLiu** [qmk/qmk_firmware#9189]
## Feature Request Type

- [ ] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description
Since STM32 is widly used, it would be nice if we can generate code which can be used by STM32CubeIDE to do add-on function's development.

**Comment by camrbuss** [comment]
With QMK using ChibiOS, the configuration that CubeMX and the Cube IDE is done in chconf.h and mcuconf.h 

I would be more interested in having a documented process for Arm Cortex Debugging which is enabled in STM32CubeIDE. I think the best path forward on this would be to use already existing VS Code extensions.
