### ISSUE TITLE
Dynamic macros do not replay repeat characters on crkbd

### ISSUE THREAD

**Issue by rpbaptist** [qmk/qmk_firmware#9219]
## Describe the Bug

On the Corne keyboard (crkbd) dynamic macros do not function properly. An example:

1. I record and type any repeating character: "door"
2. I stop the macro and replay it. Output will be "dor"

It happens for all strokes on either master or slave side, be it letters, special characters or arrow keys. In this scenario the "o" does not double as another key in any way.

I tested this with my own keymap (rpbaptist), as well as with another keymap. (dsanchezseco)

I also tried setting USB_POLLING_INTERVAL_MS on 1, 10 or 20. The result is the same.

## System Information

 - Keyboard: crkbd 
   - Revision:  1
 - Operating system: Ubuntu 19.04
 - AVR GCC version: 5.4.0

 - ARM GCC version: arm-none-eabi-gcc (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

 - QMK Firmware version: 0.8.186

 - Any keyboard related software installed?
   - None

## Additional Context

sigprof in the QMK help discord helped troubleshooting. (The USB_POLLING_INTERVAL_MS config suggestin came from him.) He managed to get the dynamic macros (with keyrepeats) to work with id80 keyboard on Linux.

Could be related to split keyboard code?

**Comment by keyboard-magpie** [comment]
Closing for now as should be remedied by the split transport overhauls of the last year or so.
