### ISSUE TITLE
ATMEGA32A ISSUE

### ISSUE THREAD

**Issue by therealstoia** [qmk/qmk_firmware#9317]
Hi guys. I am triyng to flash a gh60 minila (atmega32a) that has software issues.

I am using a pro micro as an isp and it seems to work fine, but when i use qmk to flash the firmware this message is shown to me:

"avr part atmega32a not found."

even if the flash is shown as complete

idk how to solve that...

**Comment by therealstoia** [comment]
I managed to flash the firmware by coding in cmd, but after I flashed the keymap hex file with bootloader, keyboard didn't work properly.

It doesn't type at all, but program recognised the lcrtl pression when I flash😰

**Comment by fauxpark** [comment]
Could you post a screenshot of this error?

I don't know what a "GH60 minila" is, but maybe you're referring to the [YD60](https://www.aliexpress.com/item/32799437588.html)? The sellers on Aliexpress aren't the best with naming.

**Comment by therealstoia** [comment]
Hi bro. I got no screenshots, bc there is no advise of errors. 

I flashed the file, than when I type the kB doesn't work.
I got no error shown by windows, but if I try to download the keymap that I flashed, bootmapper doesn't recognize the keyboard as plugged.

**Comment by therealstoia** [comment]
Here you are the link of the article
[https://a.aliexpress.com/_dVsZ9j4]()

**Comment by fauxpark** [comment]
That is a YMDK Bface: https://github.com/qmk/qmk_firmware/tree/master/keyboards/ymdk/bface/

**Comment by therealstoia** [comment]
YEAH it is. Now Idk how to go on. I flashed the bootload software using the cmd, i flashed the keymap hex file using bootloader holding left ctrl while plugging. If i did not hold it, then the keyboard is not recognized.

You gave me some code to flash, but idk how to use it.. may i download visual studio code? How it works? thanks

**Comment by therealstoia** [comment]
actually i am pretty sure i flashed it correctly, but it still doesn't work

**Comment by fauxpark** [comment]
It would be really helpful if you could provide some screenshots. I'm not sure what you mean by flashing the "bootload software".

The link I posted is simply showing that the keyboard name in QMK is `ymdk/bface`, so that is the one you want to select in the Configurator.

**Comment by therealstoia** [comment]
Ok. I'll link a video.

Resuming: I use this guide [](https://beta.docs.qmk.fm/using-qmk/guides/keyboard-building/isp_flashing_guide) to flash the bootloader file with an isp in cmd.

I used the software the seller recommended to use since bootloadhid.exe does't run on my pc (error 33) and i couldn't fix it.[](https://drive.google.com/file/d/1tK2jK3pWR7nLH4nmj429yniL5HXjYAn1/view?usp=sharing)

**Comment by therealstoia** [comment]
i was isp flashing because windows didn't recognize the pcb. I wanted to use qmk, but the chip is an Atmega32a and qmk toolbox didn't work

**Comment by fauxpark** [comment]
You need to provide more information, "qmk toolbox didn't work" is not all that helpful on its own. A screenshot of the Toolbox "not working" would be nice.

**Comment by therealstoia** [comment]
I was wrong bacause i used the wrong way to flash it i guess.

I have been trying using msys2, and now i have to flash te file into the keyboard. This is the issue.[
![image](https://user-images.githubusercontent.com/66514842/83981564-7037b200-a91f-11ea-9f6c-2a021fbff2b3.png)
](url)

**Comment by spidey3** [comment]
You should be able to flash by doing `qmk flash -kb ymdk/bface -km default`...

**Comment by therealstoia** [comment]
I'll try when I go back home from work, thanks.

However I have a doubt: how can I reset the kB? jumping jb holes is ok? Bc I tried yesterday before sleeping, but no message of "device found" appeared

**Comment by therealstoia** [comment]
IT DOES WORK! Thank you both guys.

**Comment by fauxpark** [comment]
@therealstoia can this be closed?

**Comment by therealstoia** [comment]
> @therealstoia can this be closed?

Yeah
