### ISSUE TITLE
Wrong Mod Tap link in documentation for One Shot Keys

### ISSUE THREAD

**Issue by mcp292** [qmk/qmk_firmware#9321]
On [this page](https://docs.qmk.fm/#/one_shot_keys) in this sentence:
>OSM(mod) - Momentarily hold down mod. You must use the MOD_* keycodes as shown in [Mod Tap](), not the KC_* codes.

Mod Tap links to: https://docs.qmk.fm/#/one_shot_keys?id=mod-tap 
instead of: https://docs.qmk.fm/#/mod_tap

**Comment by rmwphd** [comment]
Looks like you're right. Want to submit a PR?

**Comment by mcp292** [comment]
I would but it might be a while until I can get to it.

**Comment by noroadsleft** [comment]
Fixed by #9380.
