### ISSUE TITLE
Potential GPL violation in atsam port and massdrop keyboards

### ISSUE THREAD

**Issue by xyzz** [qmk/qmk_firmware#9327]
Hello,

I've noticed that several files in atsam port include the following disclaimer:

```
* 4. This software may only be redistributed and used in connection with an
*    Atmel microcontroller product.
```

Specifically, the list of files that include this is:

- tmk_core/protocol/arm_atsam/usb/udi_hid_kbd_conf.h
- tmk_core/protocol/arm_atsam/usb/udi.h
- tmk_core/protocol/arm_atsam/usb/usb_protocol_hid.h
- tmk_core/protocol/arm_atsam/usb/usb_protocol.h
- tmk_core/protocol/arm_atsam/usb/ui.c
- tmk_core/protocol/arm_atsam/usb/conf_usb.h
- tmk_core/protocol/arm_atsam/usb/usb_device_udd.c
- tmk_core/protocol/arm_atsam/usb/udc_desc.h
- tmk_core/protocol/arm_atsam/usb/usb.h
- tmk_core/protocol/arm_atsam/usb/udc.h
- tmk_core/protocol/arm_atsam/usb/usb_main.h
- tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.h
- tmk_core/protocol/arm_atsam/usb/udd.h
- tmk_core/protocol/arm_atsam/usb/usb_protocol_cdc.h
- tmk_core/protocol/arm_atsam/usb/udi_hid_kbd_desc.c
- tmk_core/protocol/arm_atsam/usb/udi_hid_kbd.c
- tmk_core/protocol/arm_atsam/usb/status_codes.h
- tmk_core/protocol/arm_atsam/usb/udi_cdc.h
- tmk_core/protocol/arm_atsam/usb/compiler.h
- tmk_core/protocol/arm_atsam/usb/usb_atmel.h
- tmk_core/protocol/arm_atsam/usb/udi_hid.h
- tmk_core/protocol/arm_atsam/usb/udc.c
- tmk_core/protocol/arm_atsam/usb/udi_cdc.c
- tmk_core/protocol/arm_atsam/usb/udi_hid.c
- tmk_core/protocol/arm_atsam/usb/udi_cdc_conf.h
- tmk_core/protocol/arm_atsam/usb/ui.h
- tmk_core/protocol/arm_atsam/usb/usb.c
- lib/arm_atsam/packs/atmel/SAMD51_DFP/1.0.70/include/instance/can0.h
- lib/arm_atsam/packs/atmel/SAMD51_DFP/1.0.70/include/instance/can1.h
- lib/arm_atsam/packs/atmel/SAMD51_DFP/1.0.70/include/component/can.h
- lib/arm_atsam/packs/atmel/SAMD51_DFP/1.0.70/include/instance/pukcc.h

I believe this clause is incompatible with the GPL license QMK is under. GPL states:

```
  6. Each time you redistribute the Program (or any work based on the
Program), the recipient automatically receives a license from the
original licensor to copy, distribute or modify the Program subject to
these terms and conditions.  You may not impose any further
restrictions on the recipients' exercise of the rights granted herein.
You are not responsible for enforcing compliance by third parties to
this License.
```

Therefore, I suggest that the atsam port and massdrop keyboards are removed from QMK.

**Comment by mewa** [comment]
@xyzz @skullydazed @jackhumbert  I think these libraries are valid to include under the "system library" exception.
