### ISSUE TITLE
[Bug] TAP_CODE_DELAY not honored by MT

### ISSUE THREAD

**Issue by Strayer** [qmk/qmk_firmware#9418]
It seems TAP_CODE_DELAY is not honored by `MT`, e.g. `MT(MOD_RSFT, KC_ENT)` does not have a delay when tapping the switch while `LT(_HYPER, KC_ESC)` does.

## System Information

 - Keyboard:  ErgoDash
   - Revision (if applicable): 1.2 
 - Operating system: macOS Catalina/Windows 10
 - AVR GCC version: avr-gcc (Homebrew AVR GCC 8.4.0) 8.4.0

 - ARM GCC version: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

 - QMK Firmware version: 0.9.7

 - Any keyboard related software installed? 
   - [ ] AutoHotKey
   - [x] Karabiner
   - [ ] Other:

**Comment by fauxpark** [comment]
Easy fix:
`LT()`
![image](https://user-images.githubusercontent.com/4781841/84601951-49512100-aec7-11ea-91d9-b2f4905e3d88.png)
`MT()`
![image](https://user-images.githubusercontent.com/4781841/84601962-61c13b80-aec7-11ea-82bf-a985a1fb1fe1.png)
