### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by Yatreyu** [qmk/qmk_firmware#9473]
The unicode FAQ is unclear. Because new nomenclature is added it is unclear at times whether the new terms are used in the keymap and that is a complete or partial solution. I.e. https://docs.qmk.fm/#/feature_unicode?id=basic-unicode makes it sound like you use  UC(0x45B) to enter ћ in your keymap as a one step solution, or by defining PLANCK and using X(PLANCK) in the keymap.

But later at https://docs.qmk.fm/#/feature_unicode?id=input-modes it sounds like you need a registry entry or separate software to enable.

Cheers,

**Comment by spidey3** [comment]
Isn't this addressed in the introductory section at the very top of https://docs.qmk.fm/#/feature_unicode?id=input-modes 
 (https://github.com/qmk/qmk_firmware/blob/master/docs/feature_unicode.md#L5)?
