### ISSUE TITLE
Using ILI9341 with uGFX

### ISSUE THREAD

**Issue by HalFrgrd** [qmk/qmk_firmware#9509]
Hi,

I have an ILI9341 (using SPI) that I want to use with my pro micro running QMK. I think I'd like to use uGFX but I can't figure out how. Could someone provide some guidance please?

Thank you

**Comment by tzarc** [comment]
@HalFrgrd we're actually working towards the removal of uGFX over time, as the licensing of the library is incompatible with the distribution of binaries that include it.

Fear not, I've actually been working on an ILI9341 driver specifically for QMK -- just need some time to finalise it: ![QMK + ILI9341](https://cdn.discordapp.com/attachments/440870965728116754/724884799143280650/image0.jpg)

**Comment by HalFrgrd** [comment]
Thank you, looking forward to it!
