### ISSUE TITLE
Alu84 = KBD75. Request to get rid of Alu84 and put it as a note in KBD75

### ISSUE THREAD

**Issue by mechmerlin** [qmk/qmk_firmware#9639]
The Alu84 and the KBD75 share the exact same pin out and the exact same switch matrix. 

Pin Out: 
KBD75: https://github.com/qmk/qmk_firmware/blob/master/keyboards/kbdfans/kbd75/config.h
Alu84: https://github.com/qmk/qmk_firmware/blob/master/keyboards/alu84/config.h

Switch Matrix:
KBD75: https://github.com/qmk/qmk_firmware/blob/master/keyboards/kbdfans/kbd75/rev2/rev2.h
Alu84: https://github.com/qmk/qmk_firmware/blob/master/keyboards/alu84/alu84.h

In order to get rid of code repetition I would be in favor of getting rid of the Alu84 and just adding it as a note in the KBD75 readme.

**Comment by fauxpark** [comment]
It does appear to be the exact same PCB. Compare:

ALU84 from [this MM post](https://www.reddit.com/r/mechmarket/comments/64ripq/usoh_h_unbuilt_alu84_75_board_gmk_carbon_w_paypal/)
https://imgur.com/a/UGer0

KBD75 (rev1? rev2 seems to be white and less notch-y)
https://geekhack.org/index.php?topic=87829.0
