### ISSUE TITLE
[Feature Request]  Support Direct Macbook Pro Plugin

### ISSUE THREAD

**Issue by UebelAndre** [qmk/qmk_firmware#9717]
## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [x] New behavior

## Description

I would like to be able to use the keyboard by plugging it directly into my Macbook Pro. Is it possible through firmware to make the keyboard usable if I directly plug it in via the USB-C port? (Using a MacBook Pro 2019)

**Comment by MxBlu** [comment]
That's a hardware issue, not a software one.

**Comment by UebelAndre** [comment]
@MxBlu Is there a place I should post this request instead?

**Comment by MxBlu** [comment]
The vendor of whatever hardware you own that you want to run QMK on, USB C to C requires a bit of extra circuitry on the PCB.

**Comment by UebelAndre** [comment]
Hey, sorry for the delay. Turns out this works 😄 I was using a faulty cable (the charging cable my mac came with + an adapter). Also sorry for the bother 😄
