### ISSUE TITLE
anyway to get this around

### ISSUE THREAD

**Issue by SuJiKiNen** [qmk/qmk_firmware#978]
I want a key to ahieve this
single tap is OSM(MOD_LSFT)
double tap is toggle layer
I try this
TAP_DANCE_DOUBLE(OSM(MOD_LSFT,TG(LAYER_NAME),but faied

**Comment by mneme** [comment]
Have you tried setting up a tap-dance function for it instead?

Something in the style of:
```
// Tapdance
enum {
  TD_OS = 0
};

keymap...(
  KC_TRNS, TD(TD_OS), KC_TRNS
)

qk_tap_dance_action_t tap_dance_actions[] = {
 [TD_OS] = ACTION_TAP_DANCE_FN (dance_onshot)
};


void dance_onshot()(qk_tap_dance_state_t *state, void *user_data) {
  switch (state->count) {
    case 1: // =>
      set_oneshot_mods (MOD_LSFT);
      break;
    case 2:
      layer_on (LAYER_NAME);
}

qk_tap_dance_action_t tap_dance_actions[] = {
 [TD_OS] = ACTION_TAP_DANCE_FN (dance_onshot)
};
```

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @SuJiKiNen please reopen this or open a new issue.
