### ISSUE TITLE
RGB underglow effects

### ISSUE THREAD

**Issue by VinnyCordeiro** [qmk/qmk_firmware#979]
I read [this article](http://hackaday.com/2016/12/12/more-blinky-more-better-the-ws2812fx-library/) some days ago, but only today I remembered to come here to show it. It is an [open source (MIT License) library for Arduino (Nano, Uno, Micro tested) and ESP8266 containing 45 visual effects for the WS2812 RGB LED](https://github.com/kitesurfer1404/WS2812FX#ws2812fx---more-blinken-for-your-leds), the most commonly used for RGB underglow in custom keyboards.

Would it be possible to add at least some of these effects on QMK?

**Comment by jackhumbert** [comment]
I think we support a lot of these right now - it probably be pretty easy to port ones you're interested in! Thanks for sharing, though! I wasn't aware of this :)
