### ISSUE TITLE
[Bug] Massdrop Ctrl wont compile if COMMAND enabled

### ISSUE THREAD

**Issue by jpmorris** [qmk/qmk_firmware#9840]
## Describe the Bug

With `COMMAND_ENABLE = yes` in rules.mk.  I get the following error:

```
Linking: .build/massdrop_ctrl_jmorris.elf                                                           [ERRORS]
 | 
 | /usr/lib/gcc/arm-none-eabi/10.1.0/../../../../arm-none-eabi/bin/ld: .build/obj_massdrop_ctrl_jmorris/common/command.o: in function `command_common':
 | /home/jmorris/qmk_firmware/tmk_core/common/command.c:502: undefined reference to `keyboard_idle'
 | collect2: error: ld returned 1 exit status
 | 
make[1]: *** [tmk_core/rules.mk:306: .build/massdrop_ctrl_jmorris.elf] Error 1

``` 
As a workaround I've had to comment out:

```
//    print_val_hex8(keyboard_protocol);
//    print_val_hex8(keyboard_idle);

```
In tmk_core/common/command.c

## System Information

 - Keyboard:  Massdrop CTRL
   - Revision (if applicable):  
 - Operating system: Linux (Arch)
 - AVR GCC version: 10.1.0

 - ARM GCC version: 10.1.0

 - QMK Firmware version: 0.9.46

 - Any keyboard related software installed? None

**Comment by zvecr** [comment]
Closing as this is correctly handled in the recent RIOT work, and there is little motivation to update the legacy code.
