### ISSUE TITLE
OSL(2) does not work

### ISSUE THREAD

**Issue by adius** [qmk/qmk_firmware#986]
I have following layout: http://configure.ergodox-ez.com/keyboard_layouts/qjdnog

The `OSL(2)` on the left side works, but the one the right side doesn't.
It's always getting stuck...

Any ideas?

**Comment by blindman78** [comment]
i think its no possible to use same key for 2 layer you rewrite bind key if you use same key active layer

**Comment by adius** [comment]
Ah ... you're right. That fixed it. Thanks!
... but is this the intended behavior?
Shouldn't it work like I built it too? 

It should at least warn me that this is no valid layout!

**Comment by blindman78** [comment]
np ,i don't know sorry i'm not Developer but i try fix it

**Comment by skullydazed** [comment]
I'm closing this to clean up our open issues, but if you still have questions @adius please reopen this or open a new issue.
