### ISSUE TITLE
Split keyboard - Adrafruit with Bluetooth in left and pro micro right

### ISSUE THREAD

**Issue by skarone** [qmk/qmk_firmware#9873]
Hi,
I would like to know if the Bluetooth option would work in a split keyboard with an adrafruit ble on the left side and a pro micro on the right?

Cheers and amazing work!

**Comment by fauxpark** [comment]
Probably only if the Bluefruit half is the master, as that half is the one doing all the processing - the slave half essentially just sends over the matrix state.
