### ISSUE TITLE
[Bug] MO: Key release order makes a key stuck

### ISSUE THREAD

**Issue by oldrich-s** [qmk/qmk_firmware#9925]
I have a main layer where I define `MO(_FN)`. In the `_FN` layer, I define `KC_AUDIO_VOL_UP`.

When I

1. press and hold FN key
2. press and hold vol up key
3. release FN key
4. release vol up key

the volume continues to increase until it reaches the maximum volume.

Is it a bug?

Commit that shows my changes:

https://github.com/oldrich-s/qmk_firmware/commit/558551ba56597a2a9892e98f175bfffee0559d29

**Comment by drashna** [comment]
I think this should be fixed now.
