### ISSUE TITLE
Using clang instead of gcc

### ISSUE THREAD

**Issue by heshananupama** [qmk/qmk_firmware#9928]
I am currently using arm-none-eabi-gcc toolchain to compile the QmK firmware (firmware related to arm architecture instead of avr) my question is whether I could use llvm toolchain instead of GCC. If possible, how could we do it?

**Comment by drashna** [comment]
there are some settings for the makefile that you can specify a different compiler.  However, the biggest issue/hurdle is that a lot of the code may not compile outright on clang.

**Comment by nektro** [comment]
old does in fact not mean resolved

**Comment by tzarc** [comment]
> old doesn't mean resolved

We have to pick our battles -- adding support for clang is best left to someone in the community. Perhaps that's you?

**Comment by nektro** [comment]
perhaps, I was trying to get stale bot to reopen the issue so folks know the task is available

**Comment by tzarc** [comment]
Guess we'll see if it goes stale again, then.

**Comment by tzarc** [comment]
Short-circuiting stalebot. Closing. If someone's keen to get clang working, they'll do so.
